### DISCUSSION TITLE
Secure Connection Failed of local Nextcloud Instance behind an Reverse Proxy

### DISCUSSION THREAD

**Discussion by BR14Nx** [nextcloud/all-in-one#1033] [Questions] [answered]
* [This](https://help.nextcloud.com/t/aio-this-site-can-t-provide-a-secure-connection/128478) forum entry could not help me further.
* I followed the [Local Instance](https://github.com/nextcloud/all-in-one/blob/main/local-instance.md) Guide.
* The Caddy Reverse Proxy is running on the same host.
* I setup a local DNS A override for the nextcloud domain: `aionextcloud.mydomain.com` with the following IP (used OPNSense)
* Let's say my host has the IP: `10.10.0.123`
* So I set the Caddyfile like this:
```
https://aionextcloud.mydomain.com:443 {
    reverse_proxy localhost:11000 
}
```

Here I am already confused which entries of the Caddyfile are necessary. In [1. The recommended way](https://github.com/nextcloud/all-in-one/blob/main/local-instance.md#1-the-recommended-way) it is described under point 2 that only port 80 is necessary for the ACME challenge. So do I have to setup the Caddyfile like [this](https://github.com/nextcloud/all-in-one/blob/main/reverse-proxy.md#caddy-with-acme-dns-challenge) after all? But what would be the difference to [2. Use the ACME DNS-challenge](https://github.com/nextcloud/all-in-one/blob/main/local-instance.md#2-use-the-acme-dns-challenge) then? Furthermore they say to only open port 80. The port of which instance and how do I do that? Probably not in the docker-compose file, because that's the aio-mastercontainer and the documentation says to only use port 8080:8080 if the instance is behind an reverse proxy, right?

* I used the following docker-compose file:
```
version: "3.8"

volumes:
  nextcloud_aio_mastercontainer:
    name: nextcloud_aio_mastercontainer # This line is not allowed to be changed

services:
  nextcloud:
    image: nextcloud/all-in-one:latest # Must be changed to 'nextcloud/all-in-one:latest-arm64' when used with an arm64 CPU
    restart: always
    container_name: nextcloud-aio-mastercontainer # This line is not allowed to be changed
    volumes:
      - nextcloud_aio_mastercontainer:/mnt/docker-aio-config # This line is not allowed to be changed
      - /var/run/docker.sock:/var/run/docker.sock:ro # May be changed on macOS, Windows or docker rootless. See the applicable documentation
      - /var/aionextcloud/config/nxtcld:/var/www/html/config
    ports:
    #  - 80:80 # Can be removed when running behind a reverse proxy. See https://github.com/nextcloud/all-in-one/blob/main/reverse-proxy.md
      - 8080:8080
    #  - 8443:8443 # Can be removed when running behind a reverse proxy. See https://github.com/nextcloud/all-in-one/blob/main/reverse-proxy.md
    environment: # Is needed when using any of the options below
     - SKIP_DOMAIN_VALIDATION=true
     - APACHE_PORT=11000 # Is needed when running behind a reverse proxy. See https://github.com/nextcloud/all-in-one/blob/main/reverse-proxy.md
     - APACHE_IP_BINDING=127.0.0.1 # Should be set when running behind a reverse proxy that is running on the same host. See https://github.com/nextcloud/all-in-one/blob/main/reverse-proxy.md
    # - TALK_PORT=3478 # This allows to adjust the port that the talk container is using.
     - NEXTCLOUD_DATADIR=/var/aionextcloud/data/nxtcld/ # Allows to set the host directory for Nextcloud's datadir. See https://github.com/nextcloud/all-in-one#how-to-change-the-default-location-of-nextclouds-datadir
    # - NEXTCLOUD_MOUNT=/var/ # Allows the Nextcloud container to access the chosen directory on the host. See https://github.com/nextcloud/all-in-one#how-to-allow-the-nextcloud-container-to-access-directories-on-the-host
    # - DOCKER_SOCKET_PATH=/var/run/docker.sock # Needs to be specified if the docker socket on the host is not located in the default '/var/run/docker.sock'. Otherwise mastercontainer updates will fail.
    # - DISABLE_BACKUP_SECTION=true # Setting this to true allows to hide the backup section in the AIO interface.
    depends_on:
     - caddy
     
  # # You can find further examples here: https://github.com/nextcloud/all-in-one/discussions/588
  caddy:
    image: caddy:alpine
    restart: always
    container_name: caddy
    volumes:
      - /var/aionextcloud/Caddyfile:/etc/caddy/Caddyfile
      - /var/aionextcloud/certs:/certs
      - /var/aionextcloud/config:/config
      - /var/aionextcloud/data:/data
      - /var/aionextcloud/sites:/srv
    network_mode: "host"

```
* All containers are running fine after the setup, but Caddy is now giving me the following errors:

```
"trying to solve challenge","identifier":"aionextcloud.mydomain.com","challenge_type":"http-01","ca":"https://acme.zerossl.com/v2/DV90"}
"could not get certificate from issuer","identifier":"aionextcloud.mydomain.com","issuer":"acme.zerossl.com-v2-DV90","error":"[aionextcloud.mydomain.com] solving challenges: [aionextcloud.mydomain.com] authorization took too long (order=https://acme.zerossl.com/v2/DV90/order/5t9LKHp7dekaAvZRk5J64g) (ca=https://acme.zerossl.com/v2/DV90)"}
"will retry","error":"[aionextcloud.mydomain.com] Obtain: [aionextcloud.mydomain.com] solving challenges: [aionextcloud.mydomain.com] authorization took too long (order=https://acme.zerossl.com/v2/DV90/order/5t9LKHp7dekaAvZRk5J64g) (ca=https://acme.zerossl.com/v2/DV90)","attempt":1,"retrying_in":60,"elapsed":335.825699052,"max_duration":2592000}
"trying to solve challenge","identifier":"aionextcloud.mydomain.com","challenge_type":"tls-alpn-01","ca":"https://acme-staging-v02.api.letsencrypt.org/directory"}
"challenge failed","identifier":"aionextcloud.mydomain.com","challenge_type":"tls-alpn-01","problem":{"type":"urn:ietf:params:acme:error:dns","title":"","detail":"DNS problem: NXDOMAIN looking up A for aionextcloud.mydomain.com - check that a DNS record exists for this domain; DNS problem: NXDOMAIN looking up AAAA for aionextcloud.mydomain.com - check that a DNS record exists for this domain","instance":"","subproblems":[]}}
```
I was also wondering if the internal IP-address of the Proxy should/can be a different one then the one from my host (so no localhost, but an IP and I change the DNS entry accordingly to the new address)?
