### DISCUSSION TITLE
Cant access AIO Interface with Traefik2

### DISCUSSION THREAD

**Discussion by D3nn7** [nextcloud/all-in-one#1166] [Questions] [answered]
### Steps to reproduce
1. create docker-compose in portainer
2. add traefik2 tags to container
3. start the container
4. try to access ip:8080

### Expected behavior
Accessing AIO Interface

### Actual behavior
Get Browser response: `NET::ERR_CERT_INVALID`.

### Host OS
Debain Buster

#### Other valuable info

<details><summary>Docker-compose info</summary>

```
version: "3.8"

volumes:
  nextcloud_aio_mastercontainer:
    name: nextcloud_aio_mastercontainer

services:
  nextcloud:
    image: nextcloud/all-in-one:latest
    restart: always
    expose:
          - "11000"
    container_name: nextcloud-aio-mastercontainer
    networks:
      - proxy
    volumes:
      - nextcloud_aio_mastercontainer:/mnt/docker-aio-config
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 8088:8080
    environment: 
      - APACHE_IP_BINDING=0.0.0.0
      - APACHE_PORT=11000
    labels:
    # activate treafik
    - "traefik.enable=true"
    
    # set to proxy network
    - "traefik.docker.network=proxy"

    # create cloud middlewares (caldav) and regex
    - "traefik.http.middlewares.NEXTCLOUD-caldav.redirectregex.permanent=true"
    - "traefik.http.middlewares.NEXTCLOUD-caldav.redirectregex.regex=^https://(.*)/.well-known/(card|cal)dav"
    - "traefik.http.middlewares.NEXTCLOUD-caldav.redirectregex.replacement=https://$${1}/remote.php/dav/"

    # redirect middleware from http to https
    - "traefik.http.middlewares.NEXTCLOUD-https.redirectscheme.scheme=https"

    # create http router
    - "traefik.http.routers.NEXTCLOUD-http.entrypoints=web"
    - "traefik.http.routers.NEXTCLOUD-http.rule=Host(`cloud.instance.com`)"
    - "traefik.http.routers.NEXTCLOUD-http.middlewares=NEXTCLOUD-https"

    # create https router
    - "traefik.http.routers.NEXTCLOUD.entrypoints=websecure"
    - "traefik.http.routers.NEXTCLOUD.rule=Host(`cloud.instance.com`)"
    - "traefik.http.routers.NEXTCLOUD.middlewares=cactuscloud,NEXTCLOUD-caldav"
    - "traefik.http.routers.NEXTCLOUD.tls=true"
    - "traefik.http.routers.NEXTCLOUD.tls.certresolver=default"

    # create HSTS middleware
    - "traefik.http.middlewares.NEXTCLOUD.headers.stsSeconds=155520011"
    - "traefik.http.middlewares.NEXTCLOUD.headers.stsIncludeSubdomains=true"
    - "traefik.http.middlewares.NEXTCLOUD.headers.stsPreload=true"
    - "traefik.http.middlewares.NEXTCLOUD.headers.contentTypeNosniff=true"
    - "traefik.http.middlewares.NEXTCLOUD.headers.browserXSSFilter=true"

networks:
  proxy:
    external: true
```

</details>
