### DISCUSSION TITLE
Nextcloud Talk container fails to start on a fresh install (NextCloud 24.0.5, AIO v2.0.3)

### DISCUSSION THREAD

**Discussion by Gunzinger** [nextcloud/all-in-one#1238] [Questions] [answered]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Install Nextcloud-AIO via a docker-compose.yml approach on a fresh Ubuntu 22.04 host

### Expected behavior 
Everything gets running fine and will be online

### Actual behavior 
The Nextcloud Talk container fails to start and the whole instance can only be started as long as the Nextcloud Talk addon is disabled in the AIO interface.

### Host OS 
Ubuntu 22.04 LTS
Docker version 20.10.18, build b40c2f6

#### Nextcloud AIO version 
Nextcloud AIO v2.0.3
NextCloud 24.0.5

#### Current channel 
latest (x86-64)

#### Other valuable info 
Reverse-proxied via nginx, HTTPS certificates obtained via certbot.
Docker installed via official tutorial (not obtained through Ubuntus repositories, but Dockers repositories)

Everything runs fine with the Talk addon disabled.

docker-compose.yml
```
version: "3.8"

volumes:
  nextcloud_aio_mastercontainer:
    name: nextcloud_aio_mastercontainer

services:
  nextcloud:
    image: nextcloud/all-in-one:latest
    restart: always
    container_name: nextcloud-aio-mastercontainer
    volumes:
      - nextcloud_aio_mastercontainer:/mnt/docker-aio-config
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 8080:8080 # management passthrough
      - 3478:3478 # nextcloud talk passthrough
    environment: # Is needed when using any of the options below
      - APACHE_PORT=11000
      - APACHE_IP_BINDING=127.0.0.1 # reverse proxy config
      # - TALK_PORT=3478 # This allows to adjust the port that the talk container is using.
      - NEXTCLOUD_DATADIR=/nextcloud_data
      - NEXTCLOUD_UPLOAD_LIMIT=50G
      - NEXTCLOUD_MAX_TIME=43200
```

Log:
```
[Sat Oct 08 19:39:58.167530 2022] [php:notice] [pid 35793] [client 127.0.0.1:42802] Slim Application Error\nType: GuzzleHttp\\Exception\\ServerException\nCode: 500\nMessage: Server error: `POST http://localhost/v1.41/containers/nextcloud-aio-talk/start` resulted in a `500 Internal Server Error` response:\n{&quot;message&quot;:&quot;driver failed programming external connectivity on endpoint nextcloud-aio-talk (2daff54bf0fa029befe675d71476 (truncated...)\n\nFile: /var/www/docker-aio/php/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php\nLine: 113\nTrace: #0 /var/www/docker-aio/php/vendor/guzzlehttp/guzzle/src/Middleware.php(69): [...]
```
