### DISCUSSION TITLE
'nextcloud-aio-nextcloud' container fails to connect to database

### DISCUSSION THREAD

**Discussion by lockness-Ko** [nextcloud/all-in-one#1247] [Questions] [answered]
### Steps to reproduce
1. Fresh install of nextcloud AIO. Here's my docker-compose file:
```
version: "3"

services:
  nextcloud:
    image: nextcloud/all-in-one:latest-arm64
    restart: unless-stopped
    container_name: nextcloud-aio-mastercontainer
    volumes:
      - /srv/data/nextcloud_aio_mastercontainer:/mnt/docker-aio-config
      - /srv/data/data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 80:80
      - 8080:8080
      - 8443:8443
    privileged: true
```
2. Login and start containers
2. Wait until all containers are green (except Apache and Nextcloud):
![image](https://user-images.githubusercontent.com/42625905/195007267-b9bd1576-42f0-41ad-ab42-be3891fec420.png)
3. Nextcloud or Apache container never starts.

Apache container is doing the correct behavior (it's waiting for Nextcloud) but it fails trying to connect to the postgres db. I've not used postgres before and I'm not sure how I'd be able to reset the password so I have not poked and prodded to try and fix the error.

### Expected behavior 
Nextcloud AIO should setup and start normally

### Actual behavior 
It (nextcloud-aio-nextcloud) fails with:
![image](https://user-images.githubusercontent.com/42625905/195007448-3967e39f-911a-4a85-a8a9-450dacf172f4.png)

### Host OS 
Raspberry PI Os 64-bit lite
Linux front 5.15.61-v8+ #1579 SMP PREEMPT Fri Aug 26 11:16:44 BST 2022 aarch64 GNU/Linux
```
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

#### Nextcloud AIO version 
Nextcloud AIO v2.0.3
