### DISCUSSION TITLE
Domaincheck and Collabora not starting

### DISCUSSION THREAD

**Discussion by loeffelpan** [nextcloud/all-in-one#1608] [Questions] [answered]
Hey,

I'm new to nextcloud all-in-one migrating from native installation on my Ubuntu server.
I endet up with this `compose.yaml`.
```
version: '3.8'

volumes:
  nextcloud_aio_mastercontainer:
    name: nextcloud_aio_mastercontainer

services:
  nextcloud:
    image: nextcloud/all-in-one:latest
    restart: always
    container_name: nextcloud-aio-mastercontainer
    volumes:
      - nextcloud_aio_mastercontainer:/mnt/docker-aio-config
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 8080:8080
    environment:
      - APACHE_PORT=11000
      - APACHE_IP_BINDING=127.0.0.1
      - NEXTCLOUD_DATADIR=/opt/ncdata
      - NEXTCLOUD_MOUNT=/mnt
      - NEXTCLOUD_STARTUP_APPS=files calendar contacts
```

AIO-Interface comes up as expected. Accessable via Caddy running as reverse proxy in a docker container with `network: host` and this Caddyfile.
```
https://kbw3.duckdns.org {
        reverse_proxy localhost:11000
}

https://kbw3.duckdns.org:8443 {
        reverse_proxy https://localhost:8080 {
                transport http {
                        tls_insecure_skip_verify
                }
        }
}
```

But the domaincheck-container exits with this error.
```
sudo docker logs nextcloud-aio-domaincheck
2022-12-26 21:13:36: (network.c.387) socket: Address family not supported by protocol
```

I don't get where the error is.
Any help?
