### DISCUSSION TITLE
Using a TCP socket proxy instead of the socket file

### DISCUSSION THREAD

**Discussion by tacticz** [nextcloud/all-in-one#1712] [Questions] [answered]
Hello,

I would like to have the `nextcloud/all-in-one` container access the docker daemon through a TCP connection and not using the `/var/run/docker.sock` socket file.

Using `docker compose`, I already have a `tecnativa/docker-socket-proxy` up and running along with a `traefik` and a `portainer/portainer-ce` container. In the `compose.yml`, the Traefik instance can be configured to use the TCP socket proxy by using the following `command` line:

```yml
services:
  traefik:
    container_name: traefik
    image: "traefik:v2.5"
    restart: always
    depends_on:
      - socket-proxy
    networks:
      - socket
      - backend
      - gateway
    ...
    command:
      ...
      - "--providers.docker.endpoint=tcp://socket-proxy:2375"
    ...
  
  socket-proxy:
    container_name: socket-proxy
    image: tecnativa/docker-socket-proxy
    restart: always
    environment:
      ...
    networks:
      - socket
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
```

Portainer can be launched without the `docker.sock` bind mount, and later configured to use a TCP socket connection, which works.

Unfortunately, I'm unable to figure out how to substitute the bind-mount of `- /var/run/docker.sock:/var/run/docker.sock:ro` for the `nextcloud/all-in-one` container to have it use the TCP connection instead.

Any help would be welcome.
Thank you.
