### DISCUSSION TITLE
Error updating mastercontainer on Docker Desktop macOS

### DISCUSSION THREAD

**Discussion by gerardkieffer** [nextcloud/all-in-one#1801] [Questions] [answered]
Hello,

I'm running AIO v4.0.1 and trying to update the mastercontainer.
My docker-compose file contains the following changes because of macOS:

```
services:
  nextcloud:
(...)
    volumes:
      - nextcloud_aio_mastercontainer:/mnt/docker-aio-config # This line is not allowed to be changed
      - /var/run/docker.sock.raw:/var/run/docker.sock:ro # May be changed on macOS, Windows or docker rootless. See the applicable documentation. If adjusting, don't forget to also set 'DOCKER_SOCKET_PATH'!
(...)
    environment: 
(...)
      - DOCKER_SOCKET_PATH=/var/run/docker.sock.raw # Needs to be specified if the docker socket on the host is not located in the default '/var/run/docker.sock'. Otherwise mastercontainer updates will fail.
```

Despite specifiying the correct DOCKER_SOCKET_PATH, mastercontainer updates fail and I can see the following info in the logs:

```
(...)
time="2023-01-18T15:34:53Z" level=debug msg="FIXME: Got an status-code for which error does not match any expected type!!!" error="Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?" module=api status_code=-1
time="2023-01-18T15:34:53Z" level=error msg="Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x9f1182]
(...)
```

Any thoughts on how to get the update working?
