### DISCUSSION TITLE
Collabora doesn't work out-of-the-box

### DISCUSSION THREAD

**Discussion by shalak** [nextcloud/all-in-one#1863] [Questions] [answered]
### Steps to reproduce
1. I installed AIO using following docker-compose:
```yaml
services:
  caddy:
    image: caddy:alpine
    restart: unless-stopped
    container_name: caddy
    volumes:
      - /srv/fast/caddy/Caddyfile:/etc/caddy/Caddyfile
      - /srv/fast/caddy/certs:/certs
      - /srv/fast/caddy/config:/config
      - /srv/fast/caddy/data:/data
      - /srv/fast/caddy/sites:/srv
      - /mnt/ssl:/mnt/ssl
    network_mode: "host"

  nextcloud:
    image: nextcloud/all-in-one:latest
    restart: unless-stopped
    container_name: nextcloud-aio-mastercontainer
    ports:
      - "8080:8080"
    environment:
      - APACHE_PORT=11000
      - NEXTCLOUD_DATADIR=/srv/fast/ncdata
      - NEXTCLOUD_MEMORY_LIMIT=2048M
    volumes:
      - nextcloud_aio_mastercontainer:/mnt/docker-aio-config
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:
      - caddy

volumes:
  nextcloud_aio_mastercontainer:
```

Caddyfile used:
```
{
    auto_https disable_certs
}

https://hostname.mydomain.com:443 {
    reverse_proxy localhost:11000
    tls /mnt/ssl/fullchain.pem /mnt/ssl/privkey.pem
}

https://hostname-aio.mydomain.com:443 {
    reverse_proxy https://localhost:8080 {
        transport http {
            tls_insecure_skip_verify
        }
    }
    tls /mnt/ssl/fullchain.pem /mnt/ssl/privkey.pem
}
```

### Expected behavior 
- Nextcloud Office works
### Actual behavior 
- Nextcloud Office doesn't work:
<img width="1190" alt="image" src="https://user-images.githubusercontent.com/1536554/215345730-6b6ca130-17dd-4dd5-b1e5-700405733ac1.png">
When I click "save", there's an underlying POST to https://hostname.mydomain.com/index.php/apps/richdocuments/ajax/admin.php that gets a 500

### Host OS 
Ubuntu 22.04.1 LTS

#### Nextcloud AIO version 

Nextcloud AIO v4.2.0

#### Current channel 

latest

#### Other valuable info 

Logs from nextcloud-aio-collabora container:
```
Server: COOLWSD HTTP Server 22.05.9.2
Upgrade: websocket
Connection: Upgrade
Sec-WebSocket-Accept: eaLv7u87BZO43/BSZyWbmYoGB5E=
| net/WebSocketHandler.hpp:935
wsd-00001-00029 2023-01-29 18:31:26.703314 +0100 [ prisoner_poll ] TRC  #22: Wrote 201 bytes of 201 buffered data| net/Socket.hpp:1445
wsd-00001-00029 2023-01-29 18:31:26.703346 +0100 [ prisoner_poll ] INF  ChildProcess ctor [32].| wsd/COOLWSD.hpp:59
wsd-00001-00029 2023-01-29 18:31:26.703369 +0100 [ prisoner_poll ] TRC  #22: Resetting thread affinity while in transit (was 0x7f4aec545700)| net/Socket.hpp:330
wsd-00001-00029 2023-01-29 18:31:26.703391 +0100 [ prisoner_poll ] TRC  Calling addNewChild in disposition's move thing to add to NewChildren| wsd/COOLWSD.cpp:3388
wsd-00001-00029 2023-01-29 18:31:26.703408 +0100 [ prisoner_poll ] TRC  Adding a new child 32 to NewChildren| wsd/COOLWSD.cpp:542
frk-00030-00030 2023-01-29 18:31:26.703376 +0100 [ forkit ] WRN  The systemplate directory [/opt/cool/systemplate] is read-only, and at least [/opt/cool/systemplate//etc/hosts] is out-of-date. Will have to copy sysTemplate to jails. To restore optimal performance, make sure the files in [/opt/cool/systemplate/etc] are up-to-date.| common/JailUtil.cpp:437wsd-00001-00029 2023-01-29 18:31:26.703425 +0100 [ prisoner_poll ] INF  Have 1 spare child after adding [32]. Notifying.| wsd/COOLWSD.cpp:548

wsd-00001-00029 2023-01-29 18:31:26.703642 +0100 [ prisoner_poll ] TRC  #22: Removing socket (at 2 of 3) from prisoner_poll| net/Socket.cpp:469
wsd-00001-00029 2023-01-29 18:31:26.703672 +0100 [ prisoner_poll ] TRC  #20: setupPollFds getPollEvents: 0x1| net/Socket.hpp:860
wsd-00001-00029 2023-01-29 18:31:26.703691 +0100 [ prisoner_poll ] TRC  #21: setupPollFds getPollEvents: 0x1| net/Socket.hpp:860
wsd-00001-00029 2023-01-29 18:31:26.703709 +0100 [ prisoner_poll ] TRC  ppoll start, timeoutMicroS: 5000000 size 2| net/Socket.cpp:337
wsd-00001-00001 2023-01-29 18:31:26.703683 +0100 [ coolwsd ] TRC  Have 1 new children.| wsd/COOLWSD.cpp:5390
wsd-00001-00001 2023-01-29 18:31:26.703761 +0100 [ coolwsd ] INF  WSD initialization complete: setting log-level to [warning] as configured.| wsd/COOLWSD.cpp:5406
Ready to accept connections on port 9980.

wsd-00001-00036 2023-01-29 18:31:26.864262 +0100 [ remotefontconfig_poll ] ERR  Remote config server has response status code: 502| wsd/COOLWSD.cpp:1163
wsd-00001-00029 2023-01-29 18:31:27.399390 +0100 [ prisoner_poll ] WRN  Attempted ping on non-upgraded websocket! #28| net/WebSocketHandler.hpp:573
wsd-00001-00036 2023-01-29 18:32:27.065913 +0100 [ remotefontconfig_poll ] ERR  Remote config server has response status code: 502| wsd/COOLWSD.cpp:1163
wsd-00001-00034 2023-01-29 18:34:49.467410 +0100 [ websrv_poll ] ERR  Looks like SSL/TLS traffic on plain http port| wsd/COOLWSD.cpp:3575
wsd-00001-00034 2023-01-29 18:34:52.939152 +0100 [ websrv_poll ] ERR  Looks like SSL/TLS traffic on plain http port| wsd/COOLWSD.cpp:3575
```
There's are related logs in `/settings/admin/logging`:

```
[richdocuments] Error: GuzzleHttp\Exception\ConnectException: cURL error 6: Could not resolve host: hostname.mydomain.com (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://hostname.mydomain.com/hosting/capabilities at <<closure>>
[spreed] Error: GuzzleHttp\Exception\ConnectException: cURL error 6: Could not resolve host: hostname.mydomain.com (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://hostname.mydomain.com/standalone-signaling/api/v1/room/jzj3nz4n at <<closure>>
```

Very important note is that this nextcloud instance **is not exposed** to the internet. I have a static DNS entry on my router that points to this server IP.

I tried changing the `URL (and Port) of Collabora Online-server` to `https://nextcloud-aio-collabora:9980`, that did not help, but the log entry changed:
```
[richdocuments] Error: GuzzleHttp\Exception\ConnectException: cURL error 35: error:1408F10B:SSL routines:ssl3_get_record:wrong version number (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://nextcloud-aio-collabora:9980/hosting/capabilities at <<closure>>
```
