### DISCUSSION TITLE
nextcloud aio dont start when change datadir in docker compose and still go to /mnt/mcdata

### DISCUSSION THREAD

**Discussion by myB0B** [nextcloud/all-in-one#1873] [Questions] [answered]
HOST: 
Windows Server 2016 HYPER-V 
VM:
debian 11 RAM 6Go SSD 50Go with HestiaCP Nginx Proxy (working well)

NEXTCLOUD DATADIR:
CIFS Mount from Windows Share : /media/cloud/
access rights : www-data:root

Portainer.io docker compose:
```
version: "3.8"

volumes:
  nextcloud_aio_mastercontainer:
    name: nextcloud_aio_mastercontainer

services:
  nextcloud:
    image: nextcloud/all-in-one:latest
    restart: always
    container_name: nextcloud-aio-mastercontainer
    volumes:
      - nextcloud_aio_mastercontainer:/mnt/docker-aio-config
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 7080:8080
    environment: 
      - APACHE_PORT=11000 
      - APACHE_IP_BINDING=0.0.0.0
      - DISABLE_BACKUP_SECTION=true
      - NEXTCLOUD_DATADIR=/media/cloud/
      - NEXTCLOUD_MOUNT=/media/ 
      - NEXTCLOUD_UPLOAD_LIMIT=10G 
      - NEXTCLOUD_MAX_TIME=3600
      - NEXTCLOUD_MEMORY_LIMIT=2048M 
      - NEXTCLOUD_ADDITIONAL_APKS=imagemagick 
      - NEXTCLOUD_ADDITIONAL_PHP_EXTENSIONS=imagick 
      - TALK_PORT=3478 
      - SKIP_DOMAIN_VALIDATION=true
 ```

RESULT: 
next-cloud-aio-nextcloud don't start and log show:
```
-------------------------------
 2023-01-31 09:50:02.849169+01
(1 row)
+ '[' -f /dev-dri-group-was-added ']'
++ find /dev -maxdepth 1 -mindepth 1 -name dri
+ '[' -n '' ']'
+ set +x
Configuring Redis as session handler...
Setting php max children...
find: /mnt/ncdata/: Permission denied
Appdata is not present. Did you maybe change the datadir after aio was first started?
See https://github.com/nextcloud/all-in-one#how-to-change-the-default-location-of-nextclouds-datadir
In the datadir was found:
ls: cannot open directory '/mnt/ncdata/': Permission denied
```

i create a symbolic link to /media/cloud /mnt/ncdata with good rights but no change
