### DISCUSSION TITLE
Allow custom UID/GID

### DISCUSSION THREAD

**Discussion by wbinek** [nextcloud/all-in-one#1974] [Ideas] [answered]
Lately the option to use custom UID/GID was added to nextcloud docker image (https://github.com/nextcloud/docker/pull/1812). Is it possible to change the user in AIO image as well? It would be helpful when accessing local storage (currently the user UID is fixed as 33 and I can not make it work properly with QNAP server acting as a docker host).

**Comment by szaimen** [comment]
> I can not make it work properly with QNAP server acting as a docker host

why?

**Reply by webysther** [reply]
On QNAP and Synology the default user and group is already set, all minor UID and GID number is already used, so to chown UID:GID of nextcloud sometimes can be conflicted with already service using this number, like happens in Synology/QNAP, for instance, I have +40 portainer stacks (compose files) on my Synology box and I only have hard time to configure that don't support change this value, this is a reason that [LinuxServer images](https://docs.linuxserver.io/general/understanding-puid-and-pgid) become huge popular among self-host, they offer a S6 like AIO for [lots of services](https://fleet.linuxserver.io/) and make seamsly to integrate, sounds like this repo, right? I think that is important to consider this to make this repository more wide adopted for self-hosted with already shares.

**Reply by webysther** [reply]
![image](https://github.com/nextcloud/all-in-one/assets/750007/23b5a0f6-45c4-4189-acf0-1e861464f8cc)

**Reply by webysther** [reply]
```yml
---
version: "2.1"
services:
  nextcloud:
    image: lscr.io/linuxserver/nextcloud:latest
    container_name: nextcloud
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /path/to/appdata:/config
      - /path/to/data:/data
    ports:
      - 443:443
    restart: unless-stopped
```
