### DISCUSSION TITLE
Franken-Success with Windows Docker Desktop and Compose

### DISCUSSION THREAD

**Discussion by FlattusBlastus** [nextcloud/all-in-one#2038] [Questions] [answered]
Today I got docker compose running but its not magic.
1. Create your ncdata and ncbackup folders on a drive. I chose my D: drive.
2. Run:
docker volume create ^
--driver local ^
--name nextcloud_aio_nextcloud_datadir ^
-o device="/d/ncdata" ^
-o type="none" ^
-o o="bind"

docker volume create ^
--driver local ^
--name nextcloud_aio_backupdir ^
-o device="/d/ncbackup" ^
-o type="none" ^
-o o="bind"

3. docker compose up -d
begin docker-compose.yml

```
version: '3.9'

volumes:
  nextcloud_aio_mastercontainer:
    name: nextcloud_aio_mastercontainer

services:
  nextcloud:
    image: nextcloud/all-in-one:beta
    restart: unless-stopped
    container_name: nextcloud-aio-mastercontainer
    volumes:
      - nextcloud_aio_mastercontainer:/mnt/docker-aio-config
      - //var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 8080:8080
    environment:
      - APACHE_PORT=11000
      - SKIP_DOMAIN_VALIDATION=true
      - NEXTCLOUD_DATADIR=nextcloud_aio_nextcloud_datadir
      - NEXTCLOUD_ADDITIONAL_APKS=imagemagick aria2 yt-dlp ocrmypdf tesseract-ocr-data-deu sane-utils netpbm
```

May it be useful to someone!

I tried some other things:

This created folders but nothing went in them:
      - /d/ncbackup:/mnt/backup
      - /d/ncdata:/var/lib/docker/volumes/nextcloud_aio_nextcloud_data/_data
This sent an error:
      - /d/ncbackup:nextcloud_aio_backupdir 
      - /d/ncdata:nextcloud_aio_nextcloud_datadir
This should have worked but nothing went in the folders:
      - nextcloud_aio_backupdir:/d/ncbackup
      - nextcloud_aio_nextcloud_datadir:/d/ncdata

**Comment by FlattusBlastus** [comment]
Not working: -No files in ncdata or ncbackup

```
version: '3.9'

volumes:
  nextcloud_aio_mastercontainer:
    name: nextcloud_aio_mastercontainer
  nextcloud_aio_backupdir:
    name: nextcloud_aio_backupdir
  nextcloud_aio_nextcloud_datadir:
    name: nextcloud_aio_nextcloud_datadir

services:
  nextcloud:
    image: nextcloud/all-in-one:beta
    restart: unless-stopped
    container_name: nextcloud-aio-mastercontainer
    volumes:
      - nextcloud_aio_mastercontainer:/mnt/docker-aio-config
      - nextcloud_aio_backupdir:/d/ncbackup
      - nextcloud_aio_nextcloud_datadir:/d/ncdata
      - //var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 8080:8080
    environment:
      - APACHE_PORT=11000
      - SKIP_DOMAIN_VALIDATION=true
      - NEXTCLOUD_ADDITIONAL_APKS=imagemagick aria2 yt-dlp ocrmypdf tesseract-ocr-data-deu sane-utils netpbm
```
