### DISCUSSION TITLE
How to fix sudden dns resolution issues after the AIO update to v4.4.1 or higher.

### DISCUSSION THREAD

**Discussion by szaimen** [nextcloud/all-in-one#2065] [Wiki]
## Problem
For AIO instances that have been initially created between March 9th 2022 and March 24th 2022, upgrading to v4.4.1 or higher might suddenly disable the dns resolution for the AIO containers. This is due to `Internal: true` settings that was falsely applied to the nextcloud-aio network during that time. Now with the update to v4.4.1 we remove the default bridge network which leads to the containers suddenly not being able to do dns resolution anymore.

## Fix
In order to fix this, you need to do the following:
1. stop all containers with `sudo docker stop $(sudo docker ps --format {{.Names}} | grep '^nextcloud-aio')`
2. Make sure that the mastercontainer is stopped: `sudo docker stop nextcloud-aio-mastercontainer`
3. Make sure to remove the nextcloud-aio network from the mastercontainer with `sudo docker network disconnect nextcloud-aio nextcloud-aio-mastercontainer`
4. remove the nextcloud-aio network with `sudo docker network rm nextcloud-aio`
5. Add the default bridge network back with `sudo docker network connect bridge nextcloud-aio-mastercontainer`
6. Start the mastercontainer again `sudo docker start nextcloud-aio-mastercontainer`
7. Open the AIO interface and start your containers again.

**Comment by Croydon** [comment]
From my nextcloud container logs: 

> Server error: `GET https://<domain>/hosting/discovery` resulted in a `502 Bad Gateway` response

Is this this problem?

Is it safe to remove the network or is this potential deconstructive?

**Reply by Zoey2936** [reply]
can you please run: `sudo docker network inspect nextcloud-aio | grep Internal`

**Reply by Croydon** [reply]
The command gave me `Internal: true`, so I followed the commands above and everything seems to be fine again.

Thank you!

**Comment by johnnyq** [comment]
This fixed my issue on all 3 instances Thanks @szaimen

**Comment by JieNiucmcc** [comment]
Hi,

want to ask does AIO need to be run in a network envrioment?
can I deploy AIO offline? 

I'm in my test enviroment, there's no public network access, and keeps getting this DNS error,
so I assume AIO need to be run in an enviroment that can access https://nextcloud.com?

**Reply by szaimen** [reply]
See https://github.com/nextcloud/all-in-one#can-i-run-aio-offline-or-in-an-airgapped-system

**Reply by JieNiucmcc** [reply]
thank you!

**Comment by brccabral** [comment]
I was only able to solve DNS issue after I set DNS to be the subnet Gateway  

`docker-compose.yml`
```
version: "3"

volumes:
  nextcloud_aio_mastercontainer:
    name: "nextcloud_aio_mastercontainer"

services:
  nextcloud-aio:
    container_name: nextcloud-aio-mastercontainer
    image: nextcloud/all-in-one:latest
    restart: unless-stopped
    ports:
      - "8080:8080"
    networks:
      nextcloud-aio:
        ipv4_address: 172.24.0.2
    dns:
      - 172.24.0.1
    volumes:
      - nextcloud_aio_mastercontainer:/mnt/docker-aio-config
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      APACHE_PORT: 11000
      APACHE_IP_BINDING: '127.0.0.1'
      NEXTCLOUD_MEMORY_LIMIT: 2048M

networks:
  nextcloud-aio:
    name: nextcloud-aio
    ipam:
      driver: default
      config:
        - subnet: 172.24.0.0/16
          gateway: 172.24.0.1
```
