### DISCUSSION TITLE
nextcloud/all-in-one image as part of docker-compose with caddy.

### DISCUSSION THREAD

**Discussion by shalak** [nextcloud/all-in-one#2075] [Questions] [answered]
I initially started my nextcloud using following `docker-compose.yaml`:

```yaml
 services:
   caddy:
     image: caddy:alpine
     restart: unless-stopped
     container_name: caddy
     volumes:
       - /srv/fast/caddy/Caddyfile:/etc/caddy/Caddyfile
     network_mode: "host"

   nextcloud:
     image: nextcloud/all-in-one:latest
     restart: unless-stopped
     container_name: nextcloud-aio-mastercontainer
     ports:
       - "8080:8080"
     environment:
       - APACHE_PORT=11000
       - NEXTCLOUD_DATADIR=/srv/fast/ncdata
       - NEXTCLOUD_MEMORY_LIMIT=2048M
     volumes:
       - nextcloud_aio_mastercontainer:/mnt/docker-aio-config
       - /var/run/docker.sock:/var/run/docker.sock:ro
     depends_on:
       - caddy

 volumes:
   nextcloud_aio_mastercontainer:
```

From what I see, after initial `docker-compose up` the mastercontainer takes over the docker and spins up all necessary containers.

Now - the question I have is: can I safely use this docker-compose to restart whole stack (or even re-create), to update Caddy or add more services to this compose?

Or will it break the mastercontainer auto-magic?
