### DISCUSSION TITLE
Unable to start collabora container

### DISCUSSION THREAD

**Discussion by jlmanohar** [nextcloud/all-in-one#2170] [Questions] [answered]
Hi, I have deployed AIO following the portainer compose file and also disabled secomp for collabora, but i get a fatal error while it starts, and ten it restarts, this continues and doesnt stop.
Attached the entire log below, but here is a snippet
```
wsd-00001-00001 2023-03-19 21:44:44.470598 +0530 [ coolwsd ] INF  Creating jail path (if missing): /opt/cool/child-roots//tmp/incoming| common/JailUtil.cpp:229
Failed to initialize COOLWSD: File access error: Invalid argument: /opt/cool/child-roots
wsd-00001-00001 2023-03-19 21:44:44.471883 +0530 [ coolwsd ] FTL  Failed to initialize COOLWSD: File access error: Invalid argument: /opt/cool/child-roots| wsd/COOLWSD.hpp:505
File access error: Invalid argument: /opt/cool/child-roots
cp: cannot create regular file '/opt/cool/systemplate/etc/resolv.conf': Permission denied
cp: cannot create regular file '/opt/cool/systemplate/etc/hosts': Permission denied
```
My docker compose file
```
version: "3.8"

volumes:
  nextcloud_aio_mastercontainer:
    name: nextcloud_aio_mastercontainer # This line is not allowed to be changed

services:
  nextcloud:
    image: nextcloud/all-in-one:latest
    restart: always
    container_name: nextcloud-aio-mastercontainer # This line is not allowed to be changed
    volumes:
      - nextcloud_aio_mastercontainer:/mnt/docker-aio-config # This line is not allowed to be changed
      - /var/run/docker.sock:/var/run/docker.sock:ro # May be changed on macOS, Windows or docker rootless. See the applicable documentation. If adjusting, don't forget to also set 'DOCKER_SOCKET_PATH'!
    ports:
      #- 80:80 # Can be removed when running behind a web server or reverse proxy (like Apache, Nginx and else). See https://github.com/nextcloud/all-in-one/blob/main/reverse-proxy.md
      - 8080:8080
      #- 8443:8443 # Can be removed when running behind a web server or reverse proxy (like Apache, Nginx and else). See https://github.com/nextcloud/all-in-one/blob/main/reverse-proxy.md
    environment: # Is needed when using any of the options below
      - SKIP_DOMAIN_VALIDATION=true
      - APACHE_PORT=11000 # Is needed when running behind a web server or reverse proxy (like Apache, Nginx and else). See https://github.com/nextcloud/all-in-one/blob/main/reverse-proxy.md
      # - APACHE_IP_BINDING=127.0.0.1 # Should be set when running behind a web server or reverse proxy (like Apache, Nginx and else) that is running on the same host. See https://github.com/nextcloud/all-in-one/blob/main/reverse-proxy.md
      - COLLABORA_SECCOMP_DISABLED=false 
```
[collabora_log.txt](https://github.com/nextcloud/all-in-one/files/11011650/collabora_log.txt)

**Comment by szaimen** [comment]
Hi, this reminds me of https://github.com/CollaboraOnline/online/issues/2800.

**Reply by jlmanohar** [reply]
From what I saw in the thread it's still an open issue, the container needs mknod or privileged access right? i will try creating that manually, will check to see if that fixes the issue

**Reply by szaimen** [reply]
Mknod would be possible to add by us, privileged not.

**Reply by jlmanohar** [reply]
Didnt work :( , i added MKNOD and privilaged and started it manually, still the same error 

Logs : [_nextcloud-aio-collabora_logs(2).txt](https://github.com/nextcloud/all-in-one/files/11019452/_nextcloud-aio-collabora_logs.2.txt)
```
File access error: Invalid argument: /opt/cool/child-roots
cp: cannot create regular file '/opt/cool/systemplate/etc/resolv.con
f': Permission denied
cp: cannot create regular file '/opt/cool/systemplate/etc/hosts': Permission denied
Generating RSA private key, 2048 bit long modulus (2 primes)
.................................................+++++
..+++++
e is 65537 (0x010001)
Generating RSA private key, 2048 bit long modulus (2 primes)
................................................................+++++
..............................................................+++++
e is 65537 (0x010001)
```

Compose:
```
version: "3.8"
networks:
  nextcloud-aio:
    external: true
volumes:
  nextcloud_aio_collabora_fonts:
    name: nextcloud_aio_collabora_fonts
    external: true
  
services:
  nextcloud-aio-collabora:
    container_name: nextcloud-aio-collabora
    image: nextcloud/aio-collabora:latest
    cap_add:
      - MKNOD
    privileged: true
    expose:
      - "9980"
    environment:
      - aliasgroup1=https://cloud.....(my domain):443
      - extra_params=--o:ssl.enable=false --o:ssl.termination=true --o:mount_jail_tree=false --o:logging.level=warning --o:remote_font_config.url=https://cloud....(my domain)/apps/richdocuments/settings/fonts.json
      #- dictionaries=${COLLABORA_DICTIONARIES}
      - TZ=Asia/Calcutta
      - server_name= cloud...... (my domain)
    volumes:
      - nextcloud_aio_collabora_fonts:/opt/cool/systemplate/tmpfonts:rw
    restart: unless-stopped
    networks:
      - nextcloud-aio
```
