### DISCUSSION TITLE
AIO Not Reachable with Traefik2

### DISCUSSION THREAD

**Discussion by jumblies** [nextcloud/all-in-one#2205] [Questions] [answered]
### Steps to reproduce
1. Create nextcloud.yaml dynamic configuration from [AIO reverse proxy instructions. ](https://github.com/nextcloud/all-in-one/blob/main/reverse-proxy.md)
2. Create docker-compose with AIO image
3. Comment out ports not needed for reverse proxy
4. Ensure traefik is finding dynamic config.
5. Start AIO container using docker compose below. 
6. Try to access container. 

AIO Docker Compose
```
version: "3.7"

volumes:
  nextcloud_aio_mastercontainer:
    name: nextcloud_aio_mastercontainer # This line is not allowed to be changed

services:
  nextcloud:
    image: nextcloud/all-in-one:latest
    restart: always
    container_name: nextcloud-aio-mastercontainer # This line is not allowed to be changed
    volumes:
      - nextcloud_aio_mastercontainer:/mnt/docker-aio-config # This line is not allowed to be changed
      - /var/run/docker.sock:/var/run/docker.sock:ro # May be changed on macOS, Windows or docker rootless. See the applicable documentation. If adjusting, don't forget to also set 'DOCKER_SOCKET_PATH'!
    ports:
      # - 16000:80 # Can be removed when running behind a web server or reverse proxy (like Apache, Nginx and else). See https://github.com/nextcloud/all-in-one/blob/main/reverse-proxy.md
      - 16001:8080
      # - 16002:8443 # Can be removed when running behind a web server or reverse proxy (like Apache, Nginx and else). See https://github.com/nextcloud/all-in-one/blob/main/reverse-proxy.md
    environment: # Is needed when using any of the options below
      - APACHE_PORT=11000 # Is needed when running behind a web server or reverse proxy (like Apache, Nginx and else). See https://github.com/nextcloud/all-in-one/blob/main/reverse-proxy.md
      - APACHE_IP_BINDING=10.10.10.102 # Should be set when running behind a web server or reverse proxy (like Apache, Nginx and else) that is running on the same host. See https://github.com/nextcloud/all-in-one/blob/main/reverse-proxy.md
      # - COLLABORA_SECCOMP_DISABLED=false # Setting this to true allows to disable Collabora's Seccomp feature. See https://github.com/nextcloud/all-in-one#how-to-disable-collaboras-seccomp-feature
      # - DOCKER_SOCKET_PATH=/var/run/docker.sock # Needs to be specified if the docker socket on the host is not located in the default '/var/run/docker.sock'. Otherwise mastercontainer updates will fail. For macos it needs to be '/var/run/docker.sock'
      # - DISABLE_BACKUP_SECTION=false # Setting this to true allows to hide the backup section in the AIO interface.
      # - NEXTCLOUD_DATADIR=/mnt/ncdata # Allows to set the host directory for Nextcloud's datadir. See https://github.com/nextcloud/all-in-one#how-to-change-the-default-location-of-nextclouds-datadir
      # - NEXTCLOUD_MOUNT=/mnt/ # Allows the Nextcloud container to access the chosen directory on the host. See https://github.com/nextcloud/all-in-one#how-to-allow-the-nextcloud-container-to-access-directories-on-the-host
      # - NEXTCLOUD_UPLOAD_LIMIT=10G # Can be adjusted if you need more. See https://github.com/nextcloud/all-in-one#how-to-adjust-the-upload-limit-for-nextcloud
      # - NEXTCLOUD_MAX_TIME=3600 # Can be adjusted if you need more. See https://github.com/nextcloud/all-in-one#how-to-adjust-the-max-execution-time-for-nextcloud
      # - NEXTCLOUD_MEMORY_LIMIT=512M # Can be adjusted if you need more. See https://github.com/nextcloud/all-in-one#how-to-adjust-the-php-memory-limit-for-nextcloud
      # - NEXTCLOUD_TRUSTED_CACERTS_DIR=/path/to/my/cacerts # CA certificates in this directory will be trusted by the OS of the nexcloud container (Useful e.g. for LDAPS) See See https://github.com/nextcloud/all-in-one#how-to-trust-user-defiend-certification-authorities-ca
      # - NEXTCLOUD_STARTUP_APPS=deck twofactor_totp tasks calendar contacts # Allows to modify the Nextcloud apps that are installed on starting AIO the first time. See https://github.com/nextcloud/all-in-one#how-to-change-the-nextcloud-apps-that-are-installed-on-the-first-startup
      - NEXTCLOUD_STARTUP_APPS=calendar # Allows to modify the Nextcloud apps that are installed on starting AIO the first time. See https://github.com/nextcloud/all-in-one#how-to-change-the-nextcloud-apps-that-are-installed-on-the-first-startup
      # - NEXTCLOUD_ADDITIONAL_APKS=imagemagick # This allows to add additional packages to the Nextcloud container permanently. Default is imagemagick but can be overwritten by modifying this value. See https://github.com/nextcloud/all-in-one#how-to-add-os-packages-permanently-to-the-nextcloud-container
      # - NEXTCLOUD_ADDITIONAL_PHP_EXTENSIONS=imagick # This allows to add additional php extensions to the Nextcloud container permanently. Default is imagick but can be overwritten by modifying this value. See https://github.com/nextcloud/all-in-one#how-to-add-php-extensions-permanently-to-the-nextcloud-container
      # - NEXTCLOUD_ENABLE_DRI_DEVICE=true # This allows to enable the /dev/dri device in the Nextcloud container which is needed for hardware-transcoding. See https://github.com/nextcloud/all-in-one#how-to-enable-hardware-transcoding-for-nextcloud
      # - TALK_PORT=3478 # This allows to adjust the port that the talk container is using.
```

Dynamic config
```
http:
    routers:
        nextcloud:
            rule: "Host(`nextcloud.lamkerad.com`)"
            entrypoints:
                - "websecure"
            service: nextcloud
            middlewares:
                - nextcloud-chain
            tls:
                certresolver: "myresolver"

    services:
        nextcloud:
            loadBalancer:
                servers:
                    - url: "http://10.10.10.102:11000" # Use the host's IP address if Traefik runs outside the host network

    middlewares:
        nextcloud-secure-headers:
            headers:
                hostsProxyHeaders:
                    - "X-Forwarded-Host"
                referrerPolicy: "same-origin"

        https-redirect:
            redirectscheme:
                scheme: https 

        nextcloud-chain:
            chain:
                middlewares:
                    # - ... (e.g. rate limiting middleware)
                    - https-redirect
                    - nextcloud-secure-headers
    
```

### Expected behavior 
Should receive Nextcloud setup instruction page. 

### Actual behavior 
Bad Gateway

### Host OS 
Ubuntu Server

#### Nextcloud AIO version 
Latest - No version given on startup (?oversight)
```
 docker-compose up
Starting nextcloud-aio-mastercontainer ... done
Attaching to nextcloud-aio-mastercontainer
nextcloud-aio-mastercontainer | WARNING: No swap limit support
nextcloud-aio-mastercontainer | Initial startup of Nextcloud All In One complete                                                                                                              !
nextcloud-aio-mastercontainer | You should be able to open the Nextcloud AIO Int                                                                                                              erface now on port 8080 of this server!
nextcloud-aio-mastercontainer | E.g. https://internal.ip.of.this.server:8080
nextcloud-aio-mastercontainer |
nextcloud-aio-mastercontainer | If your server has port 80 and 8443 open and you                                                                                                               point a domain to your server, you can get a valid certificate automatically by                                                                                                               opening the Nextcloud AIO Interface via:
nextcloud-aio-mastercontainer | https://your-domain-that-points-to-this-server.t                                                                                                              ld:8443
nextcloud-aio-mastercontainer | {"level":"info","ts":1679696124.175554,"msg":"us                                                                                                              ing provided configuration","config_file":"/Caddyfile","config_adapter":""}
nextcloud-aio-mastercontainer | [24-Mar-2023 22:15:24] NOTICE: fpm is running, p                                                                                                              id 96
nextcloud-aio-mastercontainer | [24-Mar-2023 22:15:24] NOTICE: ready to handle c                                                                                                              onnections
nextcloud-aio-mastercontainer | {"level":"info","ts":1679696124.178525,"msg":"fa                                                                                                              iled to sufficiently increase receive buffer size (was: 208 kiB, wanted: 2048 ki                                                                                                              B, got: 416 kiB). See https://github.com/quic-go/quic-go/wiki/UDP-Receive-Buffer                                                                                                              -Size for details."}
```

#### Current channel 
Cannot reach AIO interface to determine channel

#### Other valuable info 

![image](https://user-images.githubusercontent.com/24206271/227653840-6dd3fde2-daf9-495c-95c1-cf3c6ff241d1.png)

Following Troubleshooting instructions on AIO Reverse Proxy Page
```
docker exec -it traefikv2 /bin/sh
/ # nc -z 10.10.10.102 11000; echo $?
0
```

Although running on same machine, AIO in unreachable if localhost used. Same result with 127.0.0.1

```
/ # nc -z localhost 11000; echo $?
1
```
Traefik Static Config

```

      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--entrypoints.websecure.address=:443"
```

Traefik Log when Trying to access
```
https://github.com/nextcloud/all-in-one/blob/main/reverse-proxy.md
```
