### DISCUSSION TITLE
apache : pcfg_openfile: unable to check htaccess

### DISCUSSION THREAD

**Discussion by IOTech17** [nextcloud/all-in-one#2278] [Questions] [answered]
Hi,

I am trying to deploy NextCloud AIO, using portainer

The host OS is Fedora Core OS.

The whole setup process went well, but then I cannot access the nextcloud UI

I get this error : 

![image](https://user-images.githubusercontent.com/68947790/230022274-f8f2dc9f-2d63-475f-93b1-6f3c2fe06b51.png)

Then looking in the Apache container I can see these error : 

`[Wed Apr 05 10:04:10.089964 2023] [core:crit] [pid 141:tid 140355360688952] (13)Permission denied: [client 127.0.0.1:54316] AH00529: /var/www/html/.htaccess pcfg_openfile: unable to check htaccess file, ensure it is readable and that '/var/www/html/' is executable

docker-compose

```
version: "3.8"

volumes:
  nextcloud_aio_mastercontainer:
    name: nextcloud_aio_mastercontainer

services:
  nextcloud:
    image: nextcloud/all-in-one:latest
    restart: always
    privileged: true
    container_name: nextcloud-aio-mastercontainer
    volumes:
      - nextcloud_aio_mastercontainer:/mnt/docker-aio-config
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 8080:8080
    environment:
      - PHP_MEMORY_LIMIT=2048M
      - PHP_UPLOAD_LIMIT=20G
      - APACHE_PORT=11000
      - APACHE_IP_BINDING=0.0.0.0
      - SKIP_DOMAIN_VALIDATION=true
```
