### DISCUSSION TITLE
Can't Get SSL cert

### DISCUSSION THREAD

**Discussion by mrfluffy-dev** [nextcloud/all-in-one#2281] [Questions] [answered]
### Steps to reproduce
1. Allow ports 443/TCP, 3478, 8080/TCP, 80/TCP, 8443/TCP using ufw 
![image](https://user-images.githubusercontent.com/53239525/230079741-84782d81-3007-4f2d-b54d-ba8b0a8e63c0.png)
2. Port forward all these ports on my router.
![image](https://user-images.githubusercontent.com/53239525/230080286-c2cc46ab-30d2-4751-96d9-f81a90b193f1.png)
3. Install docker the recommended way `curl -fsSL https://get.docker.com | sudo sh`
4. run the Docker start script 
```
sudo docker run \
--sig-proxy=false \
--name nextcloud-aio-mastercontainer \
--restart always \
--publish 80:80 \
--publish 8080:8080 \
--publish 8443:8443 \
--volume nextcloud_aio_mastercontainer:/mnt/docker-aio-config \
--volume /var/run/docker.sock:/var/run/docker.sock:ro \
nextcloud/all-in-one:latest
```
5. Go to my Domain on port :8443 and get the password 
6. Enter the password
7. Submit my domain `cloud.mrfluffy.xyz` 
8. Get error that port 443 is not reachable 

### Expected behavior
I should get a SSL cert and go to the next step.

### Actual behavior 
I get Error That Port 443 is not accessible 

### Host OS 
Ubuntu 22.04.2 LTS x86_64

#### Nextcloud AIO version 
Nextcloud AIO v4.7.0

#### Current channel 
Latest

#### Other valuable info
I did an install with the Snap and I was able to get a SSL cert meaning I an pretty sure my ports are good.
I tried `-e SKIP_DOMAIN_VALIDATION=true` And that allowed me to go to the `/containers` page but when I start them I cant get in to my cloud coz I don't have a SSL cert.

**Comment by szaimen** [comment]
Hi, see https://github.com/nextcloud/all-in-one/discussions/2105

**Reply by mrfluffy-dev** [reply]
The Log states that It might be a firewall problem Ill Remove the AAAA DNS record and see if that helps. Ill get back the DNS records are done updating. Thanks for the quick reply.

**Reply by mrfluffy-dev** [reply]
Ok update When I get to the password screen I get new output 
```
{"level":"error","ts":1680708179.008856,"logger":"tls.obtain","msg":"will retry","error":"[86.41.182.58] Obtain: subject does not qualify for a public certificate: 86.41.182.58","attempt":2,"retrying_in":120,"elapsed":60.00266332,"max_duration":2592000}
```

If I refresh the page and re enter the AIO password I go to the next page where it asks for the domain and once again it states that my port 443 might be closed.

![image](https://user-images.githubusercontent.com/53239525/230130706-468219c3-102e-4a4a-a0d3-c11a60a4c7d7.png)

![image](https://user-images.githubusercontent.com/53239525/230130853-954cecf8-cbf3-42c3-bf60-f7717017bd81.png)


:man_shrugging:

**Comment by szaimen** [comment]
> asks for the domain and once again it states that my port 443 might be closed

I thought you skipped the domain validation for your domain already? What have been the logs of the apache container after doing so and starting things up?

**Comment by mrfluffy-dev** [comment, marked as answer]
Well I got it running after quite the struggle. 
`docker-compose.yml` containing 
```
services:
  caddy:
    image: caddy:alpine
    restart: unless-stopped
    container_name: caddy
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./certs:/certs
      - ./config:/config
      - ./data:/data
      - ./sites:/srv
    network_mode: "host"

  nextcloud:
    image: nextcloud/all-in-one:latest
    restart: unless-stopped
    container_name: nextcloud-aio-mastercontainer
    ports:
      - "8080:8080"
    environment:
      - APACHE_PORT=11000
      - APACHE_IP_BINDING=127.0.0.1
      - SKIP_DOMAIN_VALIDATION=true
    volumes:
      - nextcloud_aio_mastercontainer:/mnt/docker-aio-config
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:
      - caddy


volumes:
  nextcloud_aio_mastercontainer:
    name: nextcloud_aio_mastercontainer
```
and I made a file in HOME called `Caddyfile`
and added 
```
https://cloud.mrfluffy.xyz:443 {
    header Strict-Transport-Security max-age=31536000;
    reverse_proxy localhost:11000
}
```

I can `sudo docker compose up` and it finally worked. thanks for the responds. but it was quite the rabbit hole I needed to go through to get it running.
