### DISCUSSION TITLE
nextcloud php memory and upload limit value not passed to container

### DISCUSSION THREAD

**Discussion by IOTech17** [nextcloud/all-in-one#2298] [Questions] [answered]
Hi,

Using the env variable to increase PHP_MEMORY_LIMIT and PHP_UPLOAD_LIMIT did not worked

version: "3.8"

volumes:
  nextcloud_aio_mastercontainer:
    name: nextcloud_aio_mastercontainer

```
services:
  nextcloud:
    image: nextcloud/all-in-one:latest
    restart: always
    privileged: true
    container_name: nextcloud-aio-mastercontainer
    volumes:
      - nextcloud_aio_mastercontainer:/mnt/docker-aio-config
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 8080:8080
    environment:
      - PHP_MEMORY_LIMIT=2048M
      - PHP_UPLOAD_LIMIT=20G
      - APACHE_PORT=11000
      - APACHE_IP_BINDING=0.0.0.0
      - SKIP_DOMAIN_VALIDATION=true

```
I had to go in the docker and manually change them in in nextcloud.ini file, now, it is correctly reflecting the right value and nextcloud is work better.

![image](https://user-images.githubusercontent.com/68947790/230589256-0c59acf1-11c9-4051-9170-e402a6422872.png)
