### DISCUSSION TITLE
Running AIO behind a reverse proxy without network_mode:host in caddy

### DISCUSSION THREAD

**Discussion by raffael0** [nextcloud/all-in-one#2364] [Questions] [answered]
Hi,
I've successfully installed AIO with docker-compose and I'm running it behind caddy.

While it does work, I have some issues with the `network_mode:"host"` setting on the caddy container. 
I'd like to run other applications behind caddy in docker and I'd now have to expose the ports to access them in the caddy.

Is there a way to use AIO without the host network mode? Maybe by adding caddy to the nextcloud-aio network?
I've read ([here](https://github.com/nextcloud/all-in-one/blob/main/reverse-proxy.md#caddy-recommended))that I can use an IP address instead of localhost in the caddy config when I can't use host mode, but I don't know how I can apply that here.

Thank you for your help!
<details><summary>Configs</summary>
<p>

docker-compose:
``` 
version: "3.9"

services:
  caddy:
    image: caddy:latest
    restart: unless-stopped
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./site:/srv
      - caddy_data:/data
      - caddy_config:/config
    network_mode: "host"

  nextcloud:
    image: nextcloud/all-in-one:latest
    restart: unless-stopped
    container_name: nextcloud-aio-mastercontainer
    #ports:
    #  - "8080:8080"
    environment:
      - APACHE_PORT=11000
      - APACHE_IP_BINDING=127.0.0.1
      - SKIP_DOMAIN_VALIDATION=true
    volumes:
      - nextcloud_aio_mastercontainer:/mnt/docker-aio-config
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:
      - caddy
    
      
volumes:
  caddy_data:
  caddy_config:
  nextcloud_aio_mastercontainer:
    name: nextcloud_aio_mastercontainer # This line is not allowed to be changed
```
caddy:
```
cloud.XXXX {
	@nextcloud host cloud.XXXX
	handle @nextcloud {
		reverse_proxy localhost:11000
	}
}
```
</p>
</details>
