### DISCUSSION TITLE
Choosing subnet IP range for all NextcloudAIO containers

### DISCUSSION THREAD

**Discussion by EgonHeuson** [nextcloud/all-in-one#2521] [Questions] [answered]
Hello all! :-) I hope you're doing very well!
I checked in the discussion but couldn't find a similar one. Maybe I missed it 😥
I wondered if there was a way to config NextcloudAIO using environment variable in the docker-config, or other method to select the range of the subnet I want Docker to use when it creates the different containers for Nextcloud? By default, it chooses an IP range in 172.yy.xx.xx/24, but quite often the "yy" value is in a range which collides with some other services I have already running in the network. It would be super great if I could fix the subnet and gateway. Usually I add this type of config to my docker-compose file:
```
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
    name: network_name
    ipam:
     config:
       - subnet: aa.bb.cc.dd/24
         gateway: aa.bb.cc.dd
```

Do you think this might be feasible? Thanks a lot in advance! :-D
