### DISCUSSION TITLE
Using linuxservers swag as a proxy?

### DISCUSSION THREAD

**Discussion by EkkiHelgi** [nextcloud/all-in-one#2560] [Questions] [answered]
Hello!

A bit of a newbie here. I'm looking for help setting the container up using the swag container from linuxserver. I'm getting stuck on setting the domain in the setup phase. I'm getting the error:

`Domain does not point to this server or the reverse proxy is not configured correctly. See the mastercontainer logs for more details. ('sudo docker logs -f nextcloud-aio-mastercontainer')`

and when I go to the domain I just get a 502 Bad Gateway error.  My port forwarding is all in order since I have other containers in the same compose file that work just fine.

Any help would be appreciated. 

`docker-compose.yaml`
```
  ---
  version: '3' 
  
  networks:
    default:
      external:
        name: proxynet
  
  volumes:
    nextcloud_aio_mastercontainer:
      name: nextcloud_aio_mastercontainer
  
  services:
    swag:
      image: ghcr.io/linuxserver/swag
      container_name: swag
      cap_add:
        - NET_ADMIN
      environment:
        - PUID=1000
        - PGID=1000
        - TZ=${TIME_ZONE}
        - URL=${SWAG_URL}
        - SUBDOMAINS=${SWAG_SUBDOMAINS}
        - VALIDATION=${SWAG_VALIDATION}
        - DOCKER_MODS=linuxserver/mods:swag-dashboard
      volumes:
        - ./swag:/config
      ports:
        - '443:443'
        # required if VALIDATION=http above, if you aren't using DuckDNS
        - '80:80'
        - '81:81'
      restart: unless-stopped

    # and many other containers

    nextcloud:
      image: nextcloud/all-in-one:latest
      container_name: nextcloud-aio-mastercontainer
      environment:
        - APACHE_PORT=11000
      volumes:
        - nextcloud_aio_mastercontainer:/mnt/docker-aio-config
        - /var/run/docker.sock:/var/run/docker.sock:ro
      ports:
        - '8080:8080'
      restart: 'always'
```

`nextcloud.subdomain.conf`
```
server {
    listen 443 ssl;
    listen [::]:443 ssl;

    server_name cloud.*;

    include /config/nginx/ssl.conf;

    client_max_body_size 0;

    location / { 
        include /config/nginx/proxy.conf;
        include /config/nginx/resolver.conf;
        set $upstream_app nextcloud-aio-mastercontainer;
        set $upstream_port 11000;
        set $upstream_proto https;
        proxy_pass $upstream_proto://$upstream_app:$upstream_port;

        # Uncomment X-Frame-Options directive in ssl.conf to pass security checks.
        proxy_hide_header X-Frame-Options;
        proxy_max_temp_file_size 2048m;
    }   
}
```
