### DISCUSSION TITLE
Beta 6.0.0 with Compose and DB/Data migration from old instance

### DISCUSSION THREAD

**Discussion by kaulex99** [nextcloud/all-in-one#2634] [Questions] [answered]
I tried to migrate my existing NC 26 to Nextcloud AIO including the Data as well as the Database following the steps in [Migration guide](https://github.com/nextcloud/all-in-one/blob/main/migration.md). The nc data should remain on the host system as it is important from an external storage located in `/storage/data`. I added this in the docker-compose.yml file as a datadircetory. 

```yml

version: "3.8"

volumes:
  nextcloud_aio_mastercontainer:
    name: nextcloud_aio_mastercontainer # This line is not allowed to be changed as otherwise the built-in backup solution w>

services:
  nextcloud:
    image: nextcloud/all-in-one:beta
    restart: always
    container_name: nextcloud-aio-mastercontainer # This line is not allowed to be changed as otherwise AIO will not work co>
    volumes:
      - nextcloud_aio_mastercontainer:/mnt/docker-aio-config # This line is not allowed to be changed as otherwise the built>
      - /var/run/docker.sock:/var/run/docker.sock:ro # May be changed on macOS, Windows or docker rootless. See the applicab>
    ports:
      - 80:80 # Can be removed when running behind a web server or reverse proxy (like Apache, Nginx and else). See https://>
      - 8080:8080
      - 8443:8443 # Can be removed when running behind a web server or reverse proxy (like Apache, Nginx and else). See http>
    environment: # Is needed when using any of the options below
      - NEXTCLOUD_DATADIR=/storage/data 
      - NEXTCLOUD_MOUNT=/storage/
```

Nevertheless, after following the steps until step 7. works great. I got Nextcloud AIO running but when applying steps 7-13 the data from the database dump is not loaded into the DB and I always have a clean NC AIO without my previous data. 

Any ideas?
