### DISCUSSION TITLE
Allow configuring location of nextcloud installation and database

### DISCUSSION THREAD

**Discussion by k4my4b** [nextcloud/all-in-one#2656] [Ideas] [answered]
I would really appreciate it if I can configure the default location of nextcloud_aio_nextcloud and nextcloud_aio_database just like we can with NEXTCLOUD_DATADIR for nextcloud_aio_nextcloud_data. 
This would primarily, at least in my case, help with ditching borgbackup and relying on the snapshotting feature of btrfs.
currently my drive is being snapshotted automatically anyways because I have other containers there too but with nc-aio I have to keep borgbackup running as well which is chewing through storage and redundant.
I tried defining these volumes in the `docker-compose.yml` but it seems like nc-aio overrides these volumes anyways. 
```
volumes:
  nextcloud_aio_mastercontainer:
    name: nextcloud_aio_mastercontainer
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /mnt/nextcloud-aio
  nextcloud_aio_nextcloud:
    name: nextcloud_aio_nextcloud
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /mnt/nc
  nextcloud_aio_nextcloud_data:
    name: nextcloud_aio_nextcloud_data
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /mnt/ncdata
  nextcloud_aio_database:
    name: nextcloud_aio_database
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /mnt/ncdatabase
...
```
