### DISCUSSION TITLE
No default phone region set - is there an environmental variable for this?

### DISCUSSION THREAD

**Discussion by nn0de** [nextcloud/all-in-one#2720] [Questions] [answered]
So I had set up an instance on AIO a few months ago and I resolved this issue with what i believe was an environmental variable but i recently reset up a new instance but my docker-compose file did not contain this environmental variable. I am struggling to figure out a variable to fix this issue. Now I know that there is a documented way to fix this issue by editing the config.php file but I would really like to do an enviro variable. 

Is this possible or am I just remembering this fix incorrectly? I am rather new to all of this and I am confident I didn't edit the config.php because I literally just learned where it was actually located ahahaha.

```
volumes:
  nextcloud_aio_mastercontainer:
    name: nextcloud_aio_mastercontainer

services:
  nextcloud:
    image: nextcloud/all-in-one:latest
    container_name: nextcloud-aio-mastercontainer
    network_mode: "bridge"
    volumes:
      - nextcloud_aio_mastercontainer:/mnt/docker-aio-config
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 8880:8080
    environment:
      - APACHE_PORT=11000
      - APACHE_IP_BINDING=192.168.0.109
      - NEXTCLOUD_MOUNT=/usb1/Nextcloud
    restart: unless-stopped
```
