### DISCUSSION TITLE
Watchtower not purging old images of containers managed by the master container.

### DISCUSSION THREAD

**Discussion by nn0de** [nextcloud/all-in-one#2790] [Questions] [answered]
So as my title suggests I am having issues with Watchtower not removing the old unused images from the containers managed by the master container. I am posting this here as this seems to be more of an issue on AIO's side and not Watchtowers. Watchtower updates the master container and removes the old image of the master container when updated but does not remove all the other unused images from the containers managed by the master container. Is there something in my compose file that I need to add to allow Watchtower to clear these images? I find it very annoying having to go in and purge unused images as I am a neat freak when it comes to Docker. I hate having data taken up by unused items.

I am not using the watchtower container provided during login, I am using my own. Compose files will be posted below.

NEXTCLOUD AIO COMPOSE
```
volumes:
  nextcloud_aio_mastercontainer:
    name: nextcloud_aio_mastercontainer

services:
  nextcloud:
    image: nextcloud/all-in-one:latest
    container_name: nextcloud-aio-mastercontainer
    network_mode: "bridge"
    volumes:
      - nextcloud_aio_mastercontainer:/mnt/docker-aio-config
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 8880:8080
    environment:
      - APACHE_PORT=11000
      - APACHE_IP_BINDING=192.x.x.x
      - NEXTCLOUD_MOUNT=/usb1/Nextcloud
    restart: unless-stopped
```

WATCHTOWER COMPOSE

```
version: "3"
services:
  watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower
    network_mode: bridge
    environment:
      - TZ=Australia/Melbourne
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_INCLUDE_RESTARTING=true
      - WATCHTOWER_POLL_INTERVAL=43200
#      - WATCHTOWER_HTTP_API_METRICS=true
#      - WATCHTOWER_HTTP_API_TOKEN=xxxxxxxxxxxx
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8367:8080
    restart: unless-stopped
```
