### DISCUSSION TITLE
nextcloud aio + nginx proxy manager collabora doesn't work - black screen, no error message

### DISCUSSION THREAD

**Discussion by glandya** [nextcloud/all-in-one#2792] [Questions] [answered]
Hi, i just installed nextcloud aio on my server with nginx proxy manager  but nextcloud office doesn't work, i'm on Nextcloud AIO v6.1.1. I think the problem is because i don't configure the websocket on nginx proxy manager but i don't find how to.
If anyone has an solution please ping me.

**Comment by Zoey2936** [comment]
can you please send the screenshots of your npm config?

**Reply by glandya** [reply]
this ?
```yaml
version: '3.8'
services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      # These ports are in format <host-port>:<container-port>
      - '80:80' # Public HTTP Port
      - '443:443' # Public HTTPS Port
      - '81:81' # Admin Web Port
      # Add any other Stream port you want to expose
      # - '21:21' # FTP
    environment:
      # Mysql/Maria connection parameters:
      DB_MYSQL_HOST: "db"
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: "npm"
      DB_MYSQL_PASSWORD: "npm"
      DB_MYSQL_NAME: "npm"
      # Uncomment this if IPv6 is not enabled on your host
      # DISABLE_IPV6: 'true'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    depends_on:
      - db

  db:
    image: 'jc21/mariadb-aria:latest'
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 'npm'
      MYSQL_DATABASE: 'npm'
      MYSQL_USER: 'npm'
      MYSQL_PASSWORD: 'npm'
    volumes:
      - ./mysql:/var/lib/mysql
```
