### DISCUSSION TITLE
bad gateway after setting up reverse proxy with nginx

### DISCUSSION THREAD

**Discussion by youpie** [nextcloud/all-in-one#2831] [Questions] [answered]
hi,

I tried to set-up a reverse-proxy using nginx using the tutorial [here](https://github.com/nextcloud/all-in-one/discussions/588#discussioncomment-2811152). I have now set up everything correctly i believe, however i keep getting `502: bad gateway` whenever i visit the nextcloud server. 

my `./nginx/conf.d/default.conf` looks as follows:
```
server {
    listen	 80;
    server_name  localhost;
    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
    }
}

server {
    listen	443 ssl;
    server_name server.name;
    location / {
        proxy_pass http://192.168.1.2:11000;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        client_max_body_size 0;

        # Websocket
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $connection_upgrade;
    }
    ssl_certificate /etc/letsencrypt/live/server.name/fullchain.pem; # managed by certbot on host machine
    ssl_certificate_key /etc/letsencrypt/live/server.name/privkey.pem;
}
```

and i my `docker-compose.yml` looks as follows:
```
version: "3"
services:
  nextcloud:
    container_name: nextcloud-aio-mastercontainer
    image: nextcloud/all-in-one:latest
    restart: always
    ports:
      - 8080:8080
    environment:
      - APACHE_PORT=11000
    volumes:
      - nextcloud_aio_mastercontainer:/mnt/docker-aio-config
      - /var/run/docker.sock:/var/run/docker.sock:ro
  nginx:
    container_name: nginx
    image: nginx:1.21.6
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx:/etc/nginx
      - /etc/letsencrypt:/etc/letsencrypt

volumes:
  nextcloud_aio_mastercontainer:
    name: nextcloud_aio_mastercontainer

```
the error nginx gives me is:
`1d086500b156_nginx | 2023/06/20 22:22:58 [error] 30#30: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.1.1, server:server.name, request: "GET / HTTP/1.1", upstream: "http://192.168.1.2:11000/", host: "server.name"`

when i don't use the reverse proxy it works fine but i would really like to use it, the port is also open if i check it on websites.
many thanks!
