### DISCUSSION TITLE
Slim Application Error

### DISCUSSION THREAD

**Discussion by cedrikletarte** [nextcloud/all-in-one#2898] [Questions] [answered]
Hi, 

I want to create a nexcloud docker container, but I can pass the login page. When I go to enter the password, it's loading and after that a white page appear.

![image](https://github.com/nextcloud/all-in-one/assets/81364847/8e2210c9-8985-4d39-986f-104a67a9d906)

I'm on a ubuntu server and i don't want to use a reverse-proxy for the moment. Here's my docker-compose file.

```
  nextcloud:
    image: nextcloud/all-in-one:latest
    restart: always
    container_name: nextcloud-aio-mastercontainer # This line is not allowed to be changed as otherwise AIO will not work correctly
    volumes:
      - nextcloud_aio_mastercontainer:/mnt/docker-aio-config
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 3434:80 
      - 3535:8080
      - 8443:8443

  nextcloud_aio_mastercontainer:
    name: nextcloud_aio_mastercontainer
```

Thank's for your help.
