### DISCUSSION TITLE
Cannot create a backup

### DISCUSSION THREAD

**Discussion by spectromas** [nextcloud/all-in-one#3012] [Questions] [answered]
I am receiving the following log after trying to create a backup: 

```
configuration.json not present. Cannot perform the backup!
/start.sh: line 42: /nextcloud_aio_volumes/nextcloud_aio_mastercontainer/data/backup_archives.list: No such file or directory
chmod: /nextcloud_aio_volumes/nextcloud_aio_mastercontainer/data/backup_archives.list: No such file or directory

```

I saw in some other issues discussions that the docker compose was requested so this is mine: 

```
volumes:
  nextcloud_aio_mastercontainer:
    name: nextcloud_aio_mastercontainer
    external: true

services:
  nextcloud:
    image: nextcloud/all-in-one:latest
    restart: always
    container_name: nextcloud-aio-mastercontainer
    environment:
      - APACHE_PORT=11000
      - APACHE_IP_BINDING=127.0.0.1
      - NEXTCLOUD_DATADIR=/mnt/photos/ncdata
      - NEXTCLOUD_TRUSTED_DOMAINS=mydomain.com
      - SKIP_DOMAIN_VALIDATION=true
      - NEXTCLOUD_MOUNT=/mnt/photos
      - NEXTCLOUD_ADDITIONAL_APKS=nodejs-current gcompat imagemagick
    volumes:
      - /mnt/photos/nextcloud_aio_mastercontainer:/mnt/docker-aio-config
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 8080:8080
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

```

I am trying to back up to either `/mnt/photos/nextcloud_backup` or `/mnt/backup/nextcloud_backup`
