### DISCUSSION TITLE
pgAdmin

### DISCUSSION THREAD

**Discussion by joezimjs** [nextcloud/all-in-one#3061] [Ideas] [answered]
I need to use the pgAdmin Docker setup to connect to the DB to do some direct edits, but I don't really understand how to do what the Readme says:

> For the container to connect to the `aio-database`, you need to connect the container to the docker network `nextcloud-aio` and use `nextcloud-aio-database` as database host, `oc_nextcloud` as database username and the password that you get when running `sudo docker exec nextcloud-aio-nextcloud grep dbpassword config/config.php` as the password.

How do I "connect the container to the docker network `nextcloud-aio` and use `nextcloud-aio-database` as database host"?

I assume I just use "nextcloud-aio-database" as the host in the connection setup like this:

![image](https://github.com/nextcloud/all-in-one/assets/1313898/211380f8-10db-4c75-9887-2f49587f3a3f)

But that isn't working and I assume it's because I didn't "connect the container to the docker network `nextcloud-aio`", but I really don't know how to do that.

**Comment by joezimjs** [comment]
Figured it out. Just add `--network nextcloud-aio` as an argument to the docker command to start up the pgadmin container

**Reply by vladbejenaru** [reply]
adding also how this is done via docker-compose:
```
  pgadmin4:
    image: dpage/pgadmin4:latest
    container_name: pgadmin4
    restart: unless-stopped
    environment:
       - PGADMIN_DEFAULT_EMAIL=user@domain.tld # your email for login here
       - PGADMIN_DEFAULT_PASSWORD=SuperSecret # your login password here
    ports:
       - 5080:80 # your favourite port here instead of 5080
    networks:
       - nextcloud-aio
```

additionally since the `nextcloud-aio` is not explicitly defined in docker compose this should be added at the end of the docker-compose file:
```
networks:
  nextcloud-aio:
    driver: bridge
    name: nextcloud-aio
    external: true
```

I would also like to underline that the marked answer is not correct as PgAdmin4 is not documented as a community container for Nextcloud-AIO. Lost a bit of time until I have understood this...

Update: since docker will append the name of the folder to the name of the network I have added the name and the external parameters to the network to ensure that pgadmin4 is connecting to the nextcloud-aio network. Details here: https://docs.docker.com/reference/compose-file/networks/
