### DISCUSSION TITLE
Docker compose up return "no such service: nextcloud-aio-xxx"

### DISCUSSION THREAD

**Discussion by GuillaumeHullin** [nextcloud/all-in-one#3085] [Questions] [answered]
I use the manual install of AIO and I have a weird issue since yesterday (when I updated my instance).

Here is my usual command
`docker compose --profile collabora --profile talk --profile imaginary --profile fulltextsearch up --detach --always-recreate-deps`

But now it returns an error: `no such service: nextcloud-aio-onlyoffice`

If I try to run with no additional profile: 
`docker compose up --detach --always-recreate-deps`
I get: `no such service: nextcloud-aio-talk`

When I look in my compose file I see:
```yaml
services:
  nextcloud-aio-apache:
    depends_on:
      - nextcloud-aio-onlyoffice
```

If I run `docker compose config`, the nextcloud-aio-onlyoffice service is not listed... because I did not select the profile? 
(sorry if I don't use the right terminology... I'm not super experienced with Docker).

I have restored backups of my previous compose and env file... and now I have a the same error (when it was running fine before). So it **seems** that the issue might not be there... could it be an update of Docker which require that any service referenced in the config must be existing? if so... then what is the point of profiles?

**Comment by foxhoundv** [comment]
@GuillaumeHullin You might have a look at https://github.com/nextcloud/all-in-one/discussions/2461#discussion-5151714
It was removed/disabled from the configuration file and won't show up in the AIO interface or setup for that matter.

I would remove it from the depends_on section and after enabling onlyoffice, restart once you add it back itno the depends_on section if you want to keep it in there.

**Reply by GuillaumeHullin** [reply]
@foxhoundv Thanks for your reply.
I do not use OnlyOffice, I'm using Collabora.
II do not have a mastercontainer because I do the manual-install.
If I remove the reference in the depends_on section, I now get the error: `no such service: nextcloud-aio-clamav`... any other idea :) ?

**Comment by Zoey2936** [comment]
seems to be a bug in docker-compose v2.20.x, just install docker-compose v2.19.1:
`curl -L https://github.com/docker/compose/releases/download/v2.19.1/docker-compose-$(uname -s | tr [:upper:] [:lower:])-$(uname -m) -o /usr/local/bin/docker-compose && chmod +x /usr/local/bin/docker-compose` and use `docker-compose` instead of `docker compose` for your commands

**Reply by GuillaumeHullin** [reply]
Thanks @Zoey2936, docker-compose v2.18.1 worked out to start my Nextcloud AIO (while v2.19.1 gave a similar error).

However it seems to not be a bug in docker-compose but in the yaml.

When I read the doc about `depends_on`
https://docs.docker.com/compose/compose-file/05-services/#depends_on

> required: when false Compose only warns you when the dependency service isn’t started or available. **If not defined the default value of required is true.**

So from my understanding... we need to see how to restructure the docker-compose.yaml in order to work with Docker Compose newer version which enforce this dependency.

More data: 
https://github.com/docker/compose/issues/10804
https://github.com/docker/compose/issues/9795

**Reply by GuillaumeHullin** [reply]
Modify the depends_on of the yaml in this way works:
```yaml
services:

  nextcloud-aio-apache:
    depends_on:
      nextcloud-aio-onlyoffice:
        condition: service_started
        required: false
      nextcloud-aio-collabora:
        condition: service_started
        required: false
      nextcloud-aio-talk:
        condition: service_started
        required: false
      nextcloud-aio-nextcloud:
        condition: service_started
        required: false
      nextcloud-aio-notify-push:
        condition: service_started
        required: false

  nextcloud-aio-nextcloud:
    depends_on:
      nextcloud-aio-database:
        condition: service_started
        required: false
      nextcloud-aio-redis:
        condition: service_started
        required: false
      nextcloud-aio-clamav:
        condition: service_started
        required: false
      nextcloud-aio-fulltextsearch:
        condition: service_started
        required: false
      nextcloud-aio-talk-recording:
        condition: service_started
        required: false
      nextcloud-aio-imaginary:
        condition: service_started
        required: false
```
