### DISCUSSION TITLE
The Login is blocked since Nextcloud is running

### DISCUSSION THREAD

**Discussion by Landrin201** [nextcloud/all-in-one#3127] [Questions] [answered]
I swear, I have had everything go wrong trying to get this to work.  I FINALLY got to where I could actually try to set up nextcloud, but now whenever I navigate to my nextcloud URL I get the following:

![Screenshot 2023-08-09 at 09-44-20 AIO](https://github.com/nextcloud/all-in-one/assets/14348611/1906a85c-05e4-4fe7-b8b2-844026ccd82c)

I have no idea how to fix this. I'm so lost. I've found multiple threads that all got resolved without saying anything even remotely helpful. It doesn't matter what I try to navigate to in nextcloud, I always get redirected to that error. 

I've quadruple checked that my NGINX settings are EXACTLY what the guide shows. I'm at a loss, how do I get this to work? IDK what to even ask, because the information I'm getting from the AIO is entirely useless.

Here's my docker compose:

```
version: "3.8"
services:
  nextcloud:
    image: nextcloud/all-in-one:latest
    restart: always
    container_name: nextcloud-aio-mastercontainer # This line is not allowed to be changed as otherwise AIO will not work correctly
    volumes:
      - nextcloud_aio_mastercontainer:/mnt/docker-aio-config # This line is not allowed to be changed as otherwise the built-in backup solution will not work
      - /var/run/docker.sock:/var/run/docker.sock:ro # May be changed on macOS, Windows or docker rootless. See the applicable documentation. If adjusting, don't forget to also set 'WATCHTOWER_DOCKER_SOCKET_PATH'!
    ports:
      #- 38984:80 # Can be removed when running behind a web server or reverse proxy (like Apache, Nginx, Cloudflare Tunnel and else). See https://github.com/nextcloud/all-in-one/blob/main/reverse-proxy.md
      - 38984:8080
      #- 38984:8443 # Can be removed when running behind a web server or reverse proxy (like Apache, Nginx, Cloudflare Tunnel and else). See https://github.com/nextcloud/all-in-one/blob/main/reverse-proxy.md
    environment: # Is needed when using any of the options below
      - APACHE_PORT=11000 # Is needed when running behind a web server or reverse proxy (like Apache, Nginx, Cloudflare Tunnel and else). See https://github.com/nextcloud/all-in-one/blob/main/reverse-proxy.md
      - APACHE_IP_BINDING=0.0.0.0 # Should be set when running behind a web server or reverse proxy (like Apache, Nginx, Cloudflare Tunnel and else) that is running on the same host. See https://github.com/nextcloud/all-in-one/blob/main/reverse-proxy.md
      - NEXTCLOUD_DATADIR=/storage/nextcloud/data # Allows to set the host directory for Nextcloud's datadir. ⚠️⚠️⚠️ Warning: do not set or adjust this value after the initial Nextcloud installation is done! See https://github.com/nextcloud/all-in-one#how-to-change-the-default-location-of-nextclouds-datadir
      - WATCHTOWER_DOCKER_SOCKET_PATH=/var/run/docker.sock # Needs to be specified if the docker socket on the host is not located in the default '/var/run/docker.sock'. Otherwise mastercontainer updates will fail. For macos it needs to be '/var/run/docker.sock'
      - SKIP_DOMAIN_VALIDATION=true

volumes:
  nextcloud_aio_mastercontainer:
    name: nextcloud_aio_mastercontainer # This line is not allowed to be changed as otherwise the built-in backup solution will not work
```
