### DISCUSSION TITLE
Incorporate Authentik into Nextcloud

### DISCUSSION THREAD

**Discussion by FlattusBlastus** [nextcloud/all-in-one#3218] [Ideas] [answered]
authentik-docker-compose.yml
```
version: "3.8"
networks:
  nextcloud-aio:
    name: nextcloud-aio
    external: true
    driver: bridge
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: fd12:3456:789a:2::/64 # IPv6 subnet to use
services:
  server:
    image: ghcr.io/goauthentik/server:latest
    restart: unless-stopped
    container_name: authentik-server
    command: server
    environment:
      AUTHENTIK_REDIS__HOST: nextcloud-aio-redis
      AUTHENTIK_REDIS__PASSWORD: [get it from inspecting nextcloud-aio-redis]
      AUTHENTIK_POSTGRESQL__HOST: nextcloud-aio-database
      AUTHENTIK_POSTGRESQL__USER: nextcloud
      AUTHENTIK_POSTGRESQL__NAME: nextcloud_database
      AUTHENTIK_POSTGRESQL__PASSWORD: [get it from inspecting nextcloud-aio-database]
      AUTHENTIK_SECRET_KEY: [make a 50 to 64 character key of your own]
    volumes:
      - /c/dockerdata/authentik:/media
      - /c/dockerdata/authentik/templates:/templates
    ports:
      - 9000:9000
      - 9443:9443
    networks:
      - nextcloud-aio
    labels:
      - com.centurylinklabs.watchtower.enable=true
  worker:
    image: ghcr.io/goauthentik/server:latest
    restart: unless-stopped
    container_name: authentik-worker
    command: worker
    environment:
      AUTHENTIK_REDIS__HOST: nextcloud-aio-redis
      AUTHENTIK_REDIS__PASSWORD: [get it from inspecting nextcloud-aio-redis]
      AUTHENTIK_POSTGRESQL__HOST: nextcloud-aio-database
      AUTHENTIK_POSTGRESQL__USER: nextcloud
      AUTHENTIK_POSTGRESQL__NAME: nextcloud_database
      AUTHENTIK_POSTGRESQL__PASSWORD: [get it from inspecting nextcloud-aio-database]
      AUTHENTIK_SECRET_KEY: [make a 50 to 64 character key of your own]
    user: root
    volumes:
      - //var/run/docker.sock:/var/run/docker.sock
      - /c/dockerdata/authentik:/media
      - /c/dockerdata/authentik/certs:/certs
      - /c/dockerdata/authentik/templates:/templates
    networks:
      - nextcloud-aio
    labels:
      - com.centurylinklabs.watchtower.enable=true
```
