### DISCUSSION TITLE
My impressions using manual install and AIO in general so far

### DISCUSSION THREAD

**Discussion by webysther** [nextcloud/all-in-one#3228] [Ideas] [answered]
Hi, I like to share my configuration and impressions about using the manual install to have a better experience to my use case.

## My use case
- Simple files access, removed lots of apps
- Integration with open project and onlyoffice
- 2 users, family usage
- NAS box
- I use a naming pattern to all my docker compose projects, containers and strict use of network
- I already have watchtower and the fixed label to disable makes me sad
- I use ofelia + mysqldump/pgdump as a backup which works for years for me
- To deploy I use a stack lifecycle create by me on n8n with portainer api

## My learn
- To reproduce the install you need to skip the GUI and use more the `occ`
- The hardening version with manual install collid with forced approach of AIO which cause problems:
  - The AIO app always reinstall
  - The AIO reinstall some apps
  - The apps supported by ENV override STARTUP_APPS
  - Don't have a [hooks like _nexcloud docker make life terrible](https://github.com/nextcloud/docker#auto-configuration-via-hook-folders)

### docker compose
```yml
version: "3.9"

services:
  nextcloud:
    image: nextcloud/aio-apache:latest
    container_name: app-cloud-webserver
    env_file: ../nextcloud/.env
    expose:
      - "${APACHE_PORT}:${APACHE_PORT}/tcp"
      - "${APACHE_PORT}:${APACHE_PORT}/udp"
    volumes:
      - www:/var/www/html:ro
      - webserver:/mnt/data:rw
    networks:
      nextcloud:
      nextcloud-backend:
    read_only: true
    tmpfs:
      - /var/log/supervisord
      - /var/run/supervisord
      - /usr/local/apache2/logs
      - /tmp
      - /home/www-data
    depends_on:
      cloud:
        condition: service_healthy
    healthcheck:
      start_period: 600s
    restart: unless-stopped

  cloud:
    image: nextcloud/aio-nextcloud:latest
    container_name: app-cloud
    env_file: ../nextcloud/.env
    expose:
      - 9000
    networks:
      nextcloud-backend:
    volumes:
      - www:/var/www/html
      - data:/data
      - cloud:/media/cloud
    tmpfs:
      - /tmp:exec
      - /usr/local/share/ca-certificates
    devices:
      - /dev/dri:/dev/dri
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy
      imaginary:
        condition: service_healthy
    healthcheck:
      start_period: 600s
    restart: unless-stopped

  postgres:
    image: nextcloud/aio-postgresql:latest
    container_name: db-postgres-nextcloud
    env_file: ../nextcloud/.env
    expose:
      - 5432
    volumes:
      - db:/var/lib/postgresql/data
      - backup:/bkp
    stop_grace_period: 1800s
    read_only: true
    networks:
      nextcloud-backend:
    tmpfs:
      - /var/run/postgresql
    healthcheck:
      test: [
        "CMD-SHELL", 
        "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'"
      ]
      start_period: 300s
      interval: 60s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  redis:
    image: nextcloud/aio-redis:latest
    container_name: db-redis-nextcloud
    env_file: ../nextcloud/.env
    volumes:
      - cache:/data
    networks:
      nextcloud-backend:
    read_only: true
    expose:
      - 6379
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      start_period: 300s
      interval: 60s
      timeout: 3s
    restart: unless-stopped

  push:
    image: nextcloud/aio-notify-push:latest
    container_name: app-cloud-push
    env_file: ../nextcloud/.env
    volumes:
      - www:/nextcloud:ro
    networks:
      nextcloud-backend:
    read_only: true
    expose:
      - 7867
    depends_on:
      cloud:
        condition: service_healthy
    healthcheck:
      start_period: 600s
    restart: unless-stopped

  imaginary:
    image: nextcloud/aio-imaginary:latest
    container_name: app-cloud-image
    env_file: ../nextcloud/.env
    cap_add:
      - SYS_NICE
    networks:
      nextcloud-backend:
    read_only: true
    tmpfs:
      - /tmp
    devices:
      - /dev/dri:/dev/dri
    expose:
      - 9000
    healthcheck:
      start_period: 600s
    restart: unless-stopped

  elasticsearch:
    image: nextcloud/aio-fulltextsearch:latest
    container_name: app-cloud-search
    env_file: ../nextcloud/.env
    volumes:
      - search:/usr/share/elasticsearch/data
    expose:
      - 9200
    networks:
      nextcloud-backend:
    healthcheck:
      start_period: 600s
    restart: unless-stopped

volumes:
  data:
    name: "$STACK-data"
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=x.x.x.x,rw,rsize=32768,wsize=32768,tcp,timeo=14,nfsvers=4"
      device: ":$STORAGE/$STACK/data"

  cloud:
    name: "$STACK-cloud"
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=x.x.x.x,rw,rsize=32768,wsize=32768,tcp,timeo=14,nfsvers=4"
      device: ":$VOLUME/cloud"

  www:
    name: "$STACK-www"
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=x.x.x.x,rw,rsize=32768,wsize=32768,tcp,timeo=14,nfsvers=4"
      device: ":$STORAGE/$STACK/www"

  webserver:
    name: "$STACK-webserver"
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=x.x.x.x,rw,rsize=32768,wsize=32768,tcp,timeo=14,nfsvers=4"
      device: ":$STORAGE/$STACK/webserver"

  search:
    name: "$STACK-search"
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=x.x.x.x,rw,rsize=32768,wsize=32768,tcp,timeo=14,nfsvers=4"
      device: ":$STORAGE/$STACK/search"

  cache:
    name: "$STACK-cache"
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=x.x.x.x,rw,rsize=32768,wsize=32768,tcp,timeo=14,nfsvers=4"
      device: ":$STORAGE/$STACK/cache"

  db:
    name: "$STACK-db"
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=x.x.x.x,rw,rsize=32768,wsize=32768,tcp,timeo=14,nfsvers=4"
      device: ":$STORAGE/$STACK/db"

  backup:
    name: "$STACK-backup"
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=x.x.x.x,rw,rsize=32768,wsize=32768,tcp,timeo=14,nfsvers=4"
      device: ":$BACKUP/$STACK"

networks:
  nextcloud:
    name: nextcloud
  nextcloud-backend:
    name: nextcloud-backend
```

### My dotenv

This is more easy to work than the example, the section based on which app use
```env
# https://github.com/nextcloud/all-in-one/blob/main/manual-install/sample.conf

STACK=nextcloud

TZ=Europe/Rome
TIMEZONE=Europe/Rome

STORAGE=/volume1/docker
BACKUP=/volume1/backup/database
VOLUME=/volume1

# apache

APACHE_IP_BINDING=0.0.0.0
APACHE_MAX_SIZE=107374182400
APACHE_MAX_TIME=3600
APACHE_PORT=80

# app

NC_DOMAIN=cloud.example.com

ADMIN_USER=admin
ADMIN_PASSWORD=

SIGNALING_SECRET=

NEXTCLOUD_HOST=cloud
NEXTCLOUD_DATA_DIR=/data
NEXTCLOUD_MOUNT=/mnt

CLAMAV_ENABLED='no'
COLLABORA_ENABLED='no'
TALK_ENABLED='no'
UPDATE_NEXTCLOUD_APPS='no'
INSTALL_LATEST_MAJOR='no'

ONLYOFFICE_ENABLED='yes'
FULLTEXTSEARCH_ENABLED='yes'
IMAGINARY_ENABLED='yes'

ONLYOFFICE_HOST=office.example.com
ONLYOFFICE_SECRET=

PHP_UPLOAD_LIMIT=100G
PHP_MEMORY_LIMIT=2048M
PHP_MAX_TIME=3600

STARTUP_APPS=twofactor_totp notes onlyoffice
ADDITIONAL_APKS=imagemagick
ADDITIONAL_PHP_EXTENSIONS=imagick

# redis

REDIS_HOST=redis
REDIS_HOST_PASSWORD=

# database

PGTZ=Europe/Rome
POSTGRES_HOST=postgres
POSTGRES_PASSWORD=
POSTGRES_DB=nextcloud_database
POSTGRES_USER=nextcloud

# imaginary

IMAGINARY_HOST=imaginary

# fulltextsearch

FULLTEXTSEARCH_HOST=elasticsearch
ES_JAVA_OPTS=-Xms512M -Xmx512M
bootstrap.memory_lock=true
cluster.name=nextcloud-aio
discovery.type=single-node
logger.org.elasticsearch.discovery=WARN
http.port=9200
xpack.license.self_generated.type=basic
xpack.security.enabled=false

# push

NOTIFY_PUSH_HOST=push
```

### Customizations after install
```sh
# system
docker exec --user www-data -it app-cloud php occ config:system:set default_phone_region --value="IT"
docker exec --user www-data -it app-cloud php occ config:system:set default_language --value="en"
docker exec --user www-data -it app-cloud php occ config:system:set force_language --value="en"

# app
docker exec --user www-data -it app-cloud php occ config:app:set onlyoffice DocumentServerUrl --value="https://office.example.com/"

docker exec --user www-data -it app-cloud php occ app:disable \
    dashboard federation files_sharing firstrunwizard circles \
    logreader serverinfo nextcloud-aio nextcloud_announcements \
    photos sharebymail support survey_client user_status weather_status
    
docker exec --user www-data -it app-cloud php occ app:remove nextcloud-aio
```

## My ideias
- We really need a PID/GID solution, without this make life really hard.
- The [QA about using external storage](https://github.com/nextcloud/all-in-one/discussions/2978) don't work for me, you need to change permission so forcing the user to enable SMB/CIFS (which is a security concern) don't works for me
- Forcing myself to learn 3 different implementations of nextcloud was terrible, worst experience ever:
  - [LSIO version](https://hub.docker.com/r/linuxserver/nextcloud) support PID/GID but only works on 443
  - nextcloud supports FPM but not PID/GID and samples don't include integrations
  - AIO don't support PID/GID, great sample, no support for FPM
- I really like the ideia of AIO start using as a base the nextcloud/docker
- Start using the ideia of extensibility of S6 related containers like LSIO use, this help users like me to run a bash script to custom the container
- Support the [great ideia of MODS](https://mods.linuxserver.io/?mod=nextcloud) that add new features on-the-fly without no further changes, as a example, this is my code server using heavilly this ideia (the pipe logic can be used to install new apps in nextcloud):

```yml
version: '3.9'

services:
  code-server:
    image: lscr.io/linuxserver/code-server:4.16.1
    container_name: app-code
    cpuset: '1,2'
    networks:
      code-server:
    env_file: ../code-server/.env
    environment:
      DOCKER_MODS: >
        linuxserver/mods:universal-docker|
        linuxserver/mods:universal-git|
        linuxserver/mods:universal-package-install|
        linuxserver/mods:code-server-nodejs|
        linuxserver/mods:code-server-php8|
        linuxserver/mods:code-server-python3|
        linuxserver/mods:code-server-zsh
      INSTALL_PACKAGES: >
        apt-transport-https|
        software-properties-common|
        gnupg-agent|
        python-is-python3|
        build-essential
      VSCODE_EXTENSION_IDS: >
        genieai.chatgpt-vscode|
        ms-azuretools.vscode-docker|
        mikestead.dotenv|
        hediet.vscode-drawio|
        rogalmic.bash-debug|
        pinage404.bash-extension-pack
      INSTALL_PIP_PACKAGES: >
        pip|
        wheel|
        pipx|
        httpie
    volumes:
      # docker
      - "/var/run/docker.sock:/var/run/docker.sock"
      # docker compose
      - "$STORAGE/../portainer/data/compose:/data/compose:ro"
      # data
      - "$STORAGE/config/lab:/config"
      - "$STORAGE/code:/config/code"
      - "$STORAGE/workspace:/config/workspace"
      - "$LOG:/config/logs"
    expose:
      - 8443
    healthcheck:
      test: curl --fail http://localhost:8443 || exit 1
      interval: 300s
      retries: 5
      start_period: 600s
      timeout: 10s
    restart: unless-stopped

networks:
  code-server:
    name: code-server
```

## A perfect solution by my point of view

I think a AIO stands for all-in-one for container itself, is strange to me a solution trying to manage container to me, like onlyoffice and lots of solutions, AIO stands for one container with all-inclusive.

I think all configuration need to be at least in two ways, one containers with all deps and services with custom location already configured and with support a MOD this are not covered here because LSIO is a prime. Another way is the docker compose with all pieces, like manual install, but without create every image to stay in sync, just use the ideia to have multiple sample projects and cover the use cases.

```yml
version: "3.9"

services:

  # push/webserver/app here
  nextcloud:
    image: nextcloud/aio-nextcloud:27-fpm
    container_name: app-cloud
    environment:
      TZ: Europe/Rome
      PUID: 1026
      PGID: 101
      DOCKER_MODS: >
        nextcloud/mods:postgresql|
        nextcloud/mods:redis|
        nextcloud/mods:imaginary|
        nextcloud/mods:elasticseach
      INSTALL_APPS: >
        # list apps to install
        # can be ued to show all default apps
      DISABLE_APPS: >
        dashboard|
        federation|
        files_sharing|
        firstrunwizard
      INSTALL_PACKAGES: >
        imagemagick
      INSTALL_PHP_PACKAGES: >
        imagick
    expose:
      - 80
    networks:
      nextcloud:
      nextcloud-backend:
    volumes:
      - config:/config
      - data:/data
    devices:
      - /dev/dri:/dev/dri
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy
      imaginary:
        condition: service_healthy
    healthcheck:
      start_period: 600s
    restart: unless-stopped

  postgres:
    image: postgresql:15
    container_name: db-postgres-nextcloud
    environment: # skipped
    expose:
      - 5432
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      nextcloud-backend:
    tmpfs:
      - /var/run/postgresql
    healthcheck:
      test: [
        "CMD-SHELL", 
        "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'"
      ]
      start_period: 300s
      interval: 60s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  redis:
    image: redis:7
    container_name: db-redis-nextcloud
    environment: # skipped
    volumes:
      - cache:/data
    networks:
      nextcloud-backend:
    expose:
      - 6379
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      start_period: 300s
      interval: 60s
      timeout: 3s
    restart: unless-stopped

  imaginary:
    image: h2non/imaginary:1
    container_name: app-cloud-image
    environment: # skipped
    networks:
      nextcloud-backend:
    expose:
      - 9000
    restart: unless-stopped

  elasticsearch:
    image: elasticsearch:8.8.1
    container_name: app-cloud-search
    environment: # skipped
    volumes:
      - search:/usr/share/elasticsearch/data
    expose:
      - 9200
    networks:
      nextcloud-backend:
    restart: unless-stopped

    # add watchtower here

    # add ofelia for cron here

    # add any service here

volumes:
  data:
    name: "$STACK-data"
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=192.168.1.39,rw,rsize=32768,wsize=32768,tcp,timeo=14,nfsvers=4"
      device: ":$STORAGE/$STACK/data"

  config:
    name: "$STACK-config"
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=192.168.1.39,rw,rsize=32768,wsize=32768,tcp,timeo=14,nfsvers=4"
      device: ":$VOLUME/$STACK/config"

  search:
    name: "$STACK-search"
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=192.168.1.39,rw,rsize=32768,wsize=32768,tcp,timeo=14,nfsvers=4"
      device: ":$STORAGE/$STACK/search"

  cache:
    name: "$STACK-cache"
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=192.168.1.39,rw,rsize=32768,wsize=32768,tcp,timeo=14,nfsvers=4"
      device: ":$STORAGE/$STACK/cache"

  db:
    name: "$STACK-db"
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=192.168.1.39,rw,rsize=32768,wsize=32768,tcp,timeo=14,nfsvers=4"
      device: ":$STORAGE/$STACK/db"

networks:
  nextcloud:
    name: nextcloud
  nextcloud-backend:
    name: nextcloud-backend
```
