### DISCUSSION TITLE
Nextcloud AIO can't connect + whole NC failure after reboot with code 404

### DISCUSSION THREAD

**Discussion by janaxhell** [nextcloud/all-in-one#3256] [Questions] [answered]
### Steps to reproduce
Nothing to reproduce, as it was already broken, anyway
- try to access AIO UI from admin settings tab
- see below

### Expected behavior 

I should be able to access AIO UI and start all NC containers.

### Actual behavior 

I've been running NC AIO on a OMV-Docker machine for a few months.
Yesterday I saw a notification in NC that announced updates for containers, so I moved to admin settings and clicked AIO link to open AIO UI, which failed to open (it always did before and I was always able to stop/update/restart containers).
So I rebooted the machine, but it still won't open. So I checked the log that said:

> Could not resolve the host nextcloud.com.
> Most likely the DNS resolving does not work.
> You should be able to fix this by following https://dockerlabs.collabnix.com/intermediate/networking/Configuring_DNS.html
> Apart from that, there has been this: https://github.com/nextcloud/all-in-one/discussions/2065

My daemon.json was ok, pointing at my 2 piholes, which run fine. My nextcloud domain is on Cloudflare and it's up, my cloudflare-ddns service takes care of updating my IP every 5 mins.
I did every step explained in the github link and the result is that now no NC container starts, they all say:

> Failure
> Request failed with status code 404

The only one that runs is nextcloud-aio-mastercontainer that repeats over and over the above DNS error.

### Host OS 

OMV 6 - Docker - x86

#### Nextcloud AIO version 

Cannot access, NC version before crash was 26.0.4

#### Current channel 

Inaccessible

#### Other valuable info 

This is my docker-compose:

```
version: "3.8"

volumes:
  nextcloud_aio_mastercontainer:
    name: nextcloud_aio_mastercontainer

services:
  nextcloud:
    image: nextcloud/all-in-one:beta
    restart: always
    container_name: nextcloud-aio-mastercontainer
    volumes:
      - nextcloud_aio_mastercontainer:/mnt/docker-aio-config
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      # - 80:80
      - 8080:8080
      # - 11000:11000
      # - 8443:8443
    dns:
      - 192.168.1.158
      - 192.168.1.2
      - 8.8.8.8
    environment:
      - APACHE_PORT=11000

      - SKIP_DOMAIN_VALIDATION=true
      - DOCKER_SOCKET_PATH=/var/run/docker.sock
      - NEXTCLOUD_DATADIR=/srv/dev-disk-by-uuid-ba4514c7-4c36-4c08-9827-3f3f584ab6b0/data/nextcloud
```
