### DISCUSSION TITLE
missing manifest list entries on aarch64 / Raspberry Pi 4 Model B

### DISCUSSION THREAD

**Discussion by tgoettel9401** [nextcloud/all-in-one#3292] [Questions] [answered]
On a Raspberry Pi 4 Model B running the nextcloud-aio container does not work due to missing manifest list entries. 

### Steps to reproduce
1. run docker pull nextcloud/all-in-one:latest-arm64

### Expected behavior 
Valid image can be pulled for arm64 platform

### Actual behavior 
Command results in error message: no matching manifest for linux/arm/v8 in the manifest list entries

### Host OS 
aarch64 (Raspbian)

#### Nextcloud AIO version 
latest / latest-arm64

#### Other valuable info 
The same issue does not occur when pulling the develop-arm64 image, however then the container does not start and stays in restarting state. It then fails with exit code 159 and does not show any logs using docker logs nextcloud-aio-mastercontainer. 
Following compose.yaml has been used in Portainer to create the container / stack (nextcloud is running behind nginx-proxy-manager):

```
services:
  nextcloud-aio-mastercontainer:
    image: nextcloud/all-in-one:latest-arm64
    init: true
    restart: always
    container_name: nextcloud-aio-mastercontainer # This line is not allowed to be changed as otherwise AIO will not work correctly
    volumes:
      - nextcloud_aio_mastercontainer:/mnt/docker-aio-config # This line is not allowed to be changed as otherwise the built-in backup solution will not work
      - /var/run/docker.sock:/var/run/docker.sock:ro # May be changed on macOS, Windows or docker rootless. See the applicable documentation. If adjusting, don't forget to also set 'WATCHTOWER_DOCKER_SOCKET_PATH'!
    ports:
      - 8080:8080
    environment: 
      - APACHE_PORT=11000
      - APACHE_IP_BINDING=0.0.0.0
      
volumes:
  nextcloud_aio_mastercontainer:
    name: nextcloud_aio_mastercontainer # This line is not allowed to be changed as otherwise the built-in backup solution will not work

networks:
  default:
    external: true
    name: proxy
```
