### DISCUSSION TITLE
Can't reach port 11000 on Nextcloud AIO running Traefik

### DISCUSSION THREAD

**Discussion by stantios** [nextcloud/all-in-one#3294] [Questions] [answered]
Description: I tried to run Nextcloud AIO with docker-compose and behind my regular reverse proxy which is Traefik. I followed the guide found [here](https://github.com/nextcloud/all-in-one/blob/main/reverse-proxy.md#traefik-2) and applied them to my config.yml and traefik.yml as asked in the documentation. I span up the docker container and logged in, when I go to the domain entering page, I noticed that Nextcloud AIO or Apache was not finding my domain even though I did the steps correctly for my reverse proxy.

Note: I masked my domain under example.com for security reasons. I would also like to say that my DNS record is proxied through cloudflare but even turning the proxy off did not work.

I went to the logs for the mastercontainer and found this line:
```
NOTICE: PHP message: The response of the connection attempt to "https://nextcloud.example.com:443" was: 404 page not found

NOTICE: PHP message: Expected was: 4dda55db2f80df913d9732fde58e632be1804a5f2a2565cd
```

Then, I went to the traefik dashbaord and found this in the http router for the nextcloud domain and found this:

![image](https://github.com/nextcloud/all-in-one/assets/98621617/a785d98c-8796-4765-9293-34f8d074ddcc)

What my config.yml looks like:
```
http:

  routers:
      nextcloud:
          rule: "Host(nextcloud.example.com)"
          entrypoints:
              - "https"
          service: nextcloud
          middlewares:
              - nextcloud-chain
          tls:
              certresolver: "cloudflare"

  services:
      nextcloud:
          loadBalancer:
              servers:
                  - url: "http://<ip-of-server>:11000"

  middlewares:
    https-redirect:
      redirectScheme:
        scheme: https

    nextcloud-secure-headers:
        headers:
            hostsProxyHeaders:
                - "X-Forwarded-Host"
            referrerPolicy: "same-origin"


    nextcloud-chain:
        chain:
            middlewares:
                - https-redirect
                - nextcloud-secure-headers

    authelia:
      forwardAuth:
        address: "http://authelia:9091/api/verify?rd=https://auth.example.com"

    default-headers:
      headers:
        frameDeny: true
        sslRedirect: true
        browserXssFilter: true
        contentTypeNosniff: true
        forceSTSHeader: true
        stsIncludeSubdomains: true
        stsPreload: true
        stsSeconds: 15552000
        customFrameOptionsValue: SAMEORIGIN
        customRequestHeaders:
          X-Forwarded-Proto: https

    default-whitelist:
      ipWhiteList:
        sourceRange:
        - "10.0.0.0/8"
        - "192.168.0.0/16"
        - "172.0.0.0/12"

    secured:
      chain:
        middlewares:
        - default-whitelist
        - default-headers
```

What my traefik.yml looks like:
```
api:
  dashboard: true
  debug: true
entryPoints:
  http:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: https
          scheme: https
  https:
    address: ":443"
serversTransport:
  insecureSkipVerify: true
providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
  file:
    filename: /config.yml
certificatesResolvers:
  cloudflare:
    acme:
      email: example@gmail.com
      storage: acme.json
      dnsChallenge:
        provider: cloudflare
        resolvers:
          - "1.1.1.1:53"
          - "1.0.0.1:53"
```

Finally, what my docker-compose file looks like:
```
services:
  nextcloud-aio-mastercontainer:
    image: nextcloud/all-in-one:latest
    init: true
    restart: always
    container_name: nextcloud-aio-mastercontainer
    volumes:
      - nextcloud_aio_mastercontainer:/mnt/docker-aio-config
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 9080:8080
    environment:
      - AIO_DISABLE_BACKUP_SECTION=true
      - APACHE_PORT=11000
      - APACHE_IP_BINDING=127.0.0.1
      - COLLABORA_SECCOMP_DISABLED=false
      - NEXTCLOUD_UPLOAD_LIMIT=10G
      - NEXTCLOUD_MAX_TIME=3600
      - NEXTCLOUD_MEMORY_LIMIT=512M

volumes:
  nextcloud_aio_mastercontainer:
    name: nextcloud_aio_mastercontainer
```
