### DISCUSSION TITLE
Getting nexcloud with traefik to work

### DISCUSSION THREAD

**Discussion by taos15** [nextcloud/all-in-one#3303] [Questions] [answered]
I have a hard time trying to setup nexcloud AIO behind traefik. this is my current compose 

```yaml
services:
  nextcloud-aio-mastercontainer:
    image: nextcloud/all-in-one:latest
    init: true
    restart: always
    container_name: nextcloud-aio-mastercontainer
    volumes:
      - nextcloud_aio_mastercontainer:/mnt/docker-aio-config
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 9080:8080
    security_opt:
      - apparmor:unconfined
    environment:
      - AIO_DISABLE_BACKUP_SECTION=true
      - APACHE_PORT=11000
      - APACHE_IP_BINDING=127.0.0.1
      - COLLABORA_SECCOMP_DISABLED=false
      - NEXTCLOUD_UPLOAD_LIMIT=10G
      - NEXTCLOUD_MAX_TIME=3600
      - NEXTCLOUD_MEMORY_LIMIT=512M

volumes:
  nextcloud_aio_mastercontainer:
    name: nextcloud_aio_mastercontainer
```
this is the traefik config

```yaml
http:
    routers:
        nextcloud:
            entryPoints:
                - https
            rule: "Host(`nextcloud.domain.tld`)" # make sure to check the guide if and add your domain if blank
            service: nextcloud
            middlewares:
                - "local-ipwhitelist@file"
                - "nextcloud-chain@file"
            tls:
                certresolver: "cloudflare"

    ## SERVICES EXAMPLE ##
    services:
        nextcloud:
            loadBalancer:
                servers:
                    - url: https://192.168.1.160:11000/


    ## MIDDLEWARES ##
    middlewares:
        # Only Allow Local networks
        local-ipwhitelist:
            ipWhiteList:
                sourceRange:
                    - 127.0.0.1/32 # localhost
                    - 192.168.1.1/24 # LAN Subnet

        nextcloud-secure-headers:
            headers:
                hostsProxyHeaders:
                    - "X-Forwarded-Host"
                referrerPolicy: "same-origin"

        https-redirect:
            redirectscheme:
                scheme: https

        nextcloud-chain:
            chain:
                middlewares:
                    - https-redirect
                    - nextcloud-secure-headers
```

but I keep getting this error

```NOTICE: PHP message: Could not start domaincheck container: Server error: `POST http://localhost/v1.41/containers/nextcloud-aio-domaincheck/start` resulted in a `500 Internal Server Error` ```
