### DISCUSSION TITLE
Is it possible to use AIO with caddy without exposing AIO outside of docker

### DISCUSSION THREAD

**Discussion by Rido-o** [nextcloud/all-in-one#3383] [Questions] [answered]
Is it possible to use the expose function within docker-compose for AIO in combination with caddy. I prefer to have all of my containers use 'expose' so that way none of them need to publish their ports outside of docker, and I am still able to access everything via caddy. I tried to do the same with AIO but I couldn't get it to work. I picture a basic compose file looking something like the following. 
```
version: "3.8"

services:
  caddy:
    image: caddy:alpine
    restart: unless-stopped
    container_name: caddy
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./certs:/certs
      - ./config:/config
      - ./data:/data
      - ./sites:/srv
    ports:
      - 443:443
      - 80:80

  nextcloud:
    image: nextcloud/all-in-one:latest
    restart: unless-stopped
    container_name: nextcloud-aio-mastercontainer
    expose:
      - 8080
    volumes:
      - nextcloud_aio_mastercontainer:/mnt/docker-aio-config
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:
      - caddy

volumes:
  nextcloud_aio_mastercontainer:
    name: nextcloud_aio_mastercontainer
```
with a caddy file looking something like so
```
https://nextcloud.<domain>.com:443 {
    reverse_proxy nextcloud:8080
}
```
My actual config is a bit more complicated than that, but I think it illustrates what I'm trying to achieve at least. I understand if something like this isn't possible as I couldn't find anyone else trying the same thing.
