### DISCUSSION TITLE
(docker rootles+ nginx proxy)  502 Bad Gateway

### DISCUSSION THREAD

**Discussion by zaqrt-zaq** [nextcloud/all-in-one#3633] [Questions] [answered]
Hello, I have been having problems with set up my AIO recently. 
i've been following the https://github.com/nextcloud/all-in-one/blob/main/multiple-instances.md
that is the configuration I run : 
```
services:
  nextcloud-aio-mastercontainer:
    image: nextcloud/all-in-one:latest
    init: true
    restart: always
    container_name: nextcloud-aio-mastercontainer
    volumes:
      - nextcloud_aio_mastercontainer:/mnt/docker-aio-config
      - $XDG_RUNTIME_DIR/docker.sock:/var/run/docker.sock:ro
    ports:
      - 8001:8080
    environment:
      - SKIP_DOMAIN_VALIDATION=true
      - APACHE_PORT=11001
      - APACHE_IP_BINDING=0.0.0.0
      - NEXTCLOUD_UPLOAD_LIMIT=10G
      - TALK_PORT=3478
      - WATCHTOWER_DOCKER_SOCKET_PATH=$XDG_RUNTIME_DIR/docker.sock

volumes:
  nextcloud_aio_mastercontainer:
    name: nextcloud_aio_mastercontainer
```

nigix proxy that i taken form proxy documentation
```
map $http_upgrade $connection_upgrade {
    default upgrade;
     close;
}

server {
    listen 80;
        return 301 https://$host$request_uri;
}
server {
    listen 443 ssl http2;      # for nginx versions below v1.25.1

    server_name cloud.example;

    location / {
        proxy_pass http://localhost:11001$request_uri;

        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Port $server_port;
        proxy_set_header X-Forwarded-Scheme $scheme;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Accept-Encoding "";
        proxy_set_header Host $host;
    
        client_body_buffer_size 512k;
        proxy_read_timeout 86400s;
        client_max_body_size 0;

        # Websocket
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $connection_upgrade;
    }

    ssl_certificate /etc/letsencrypt/live/example/fullchain.pem;   # managed by certbot on host machine
    ssl_certificate_key /etc/letsencrypt/live/example/privkey.pem; # managed by certbot on host machine

    ssl_session_timeout 1d;
    ssl_session_cache shared:MozSSL:10m; # about 40000 sessions
    ssl_session_tickets off;

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:DHE-RSA-CHACHA20-POLY1305;
    ssl_prefer_server_ciphers on;
}
```
output of docker ps 
![image](https://github.com/nextcloud/all-in-one/assets/70597626/9d6b9eb7-fe63-4ff3-8c2a-9eb99fea1cfc)
i dont known if port 80 should be up 

and when i open the page i get 
502 Bad Gateway

PS. sorry if i add it on the wrong thing im new to github
