### DISCUSSION TITLE
use cloudflare tunnel to access nextcloud

### DISCUSSION THREAD

**Discussion by game-loader** [nextcloud/all-in-one#3697] [Questions] [answered]
I want to use cloudflare tunnel to get access to the nextcloud I install in my home. I look into the document and find so much attention thing and I try to config as the document said. But I met 502 bad gateway. I use the home network to access nextcloud by https. Everything is ok but browser show it using unsafe certificate. I think it cause of using self-signed certificate. I suddenly think of cloudflare tunnel can set skipping verifying certificate. Then I try to set cloudflare tunnel config file and reopen the page. Everything is ok now. The config is below 
```yaml
tunnel: <your-tunnel-id>
credentials-file: <your-credential-file>
protocol: <protocol-you-need default:h2mux>
ingress:
  -  hostname: <your-host-name>
      service: https://localhost:<your-nextcloud-port default:8080>
      originRequest:
        noTLSVerify: true
        originServerName: <your-host-name>
  -   service: http_status:404
```

--------------------------------------------------------------------------------------------------
Full steps:
1. Install nextcloud as reverse document
```shell
# For Linux:
sudo docker run \
--init \
--sig-proxy=false \
--name nextcloud-aio-mastercontainer \
--restart always \
--publish 8080:8080 \
--env APACHE_PORT=11000 \
--env APACHE_IP_BINDING=0.0.0.0 \
--volume nextcloud_aio_mastercontainer:/mnt/docker-aio-config \
--volume /var/run/docker.sock:/var/run/docker.sock:ro \
nextcloud/all-in-one:latest
```
2. change the cloudflare tunnel `config.yml` file as below
```yaml
tunnel: <your-tunnel-id>
credentials-file: <your-credential-file>
protocol: <protocol-you-need default:h2mux>
ingress:
  -  hostname: <your-host-name>
      service: https://localhost:<your-nextcloud-port default:8080>
      originRequest:
        noTLSVerify: true
        originServerName: <your-host-name>
  -   service: http_status:404
```
Then open your domain everything will be ok now.
