### DISCUSSION TITLE
Problem with permissions

### DISCUSSION THREAD

**Discussion by posLop** [nextcloud/all-in-one#3738] [Questions] [answered]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

I can see the top folders inside of my raid array mounted using local external storage but i cannot see anything inside of them

I am using AIO in docker.
docker.yml
```
  nextcloud:
    container_name: nextcloud-aio-mastercontainer
    init: true
    restart: unless-stopped
    image: nextcloud/all-in-one:latest
    volumes:
      - nextcloud_aio_mastercontainer:/mnt/docker-aio-config
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      # - 8666:80
      - 8080:8080
        # - 8443:8443
    environment:
      - APACHE_PORT=11000
      - APACHE_IP_BINDING=0.0.0.0
      - NEXTCLOUD_DATADIR=/docker/store/ncaio
      - NEXTCLOUD_MOUNT=/mnt/nextcloud/
      - NEXTCLOUD_MEMORY_LIMIT=4096M
```

I currently have a raid 1 array of 2 4tb hard drives useing mdadm on arch linux.
It is mounted at /mnt/massdrive and /mnt/massdrive is bind mounted to /mnt/nextcloud/massdrive

fstab
```

/dev/md127 /mnt/massdrive ext4 defaults 0 0

/home/poslop /mnt/nextcloud/poslop none bind

/mnt/massdrive /mnt/nextcloud/massdrive none bind
```

ls -l /mnt/nextcloud/
```
drwxrwxrwx  7 poslop poslop   4096 Oct 29 10:16 massdrive
drwxrwxrwx 15 poslop poslop   4096 Oct 31 11:38 poslop
```

ls -l /mnt/nextcloud/massdrive
```
drwxrwxr--  5 poslop   poslop  4096 Oct 29 10:11 games
drwxrwxr--  2 poslop   poslop   16384 May 16 10:00 lost+found
drwxrwxr--  6 poslop   poslop    4096 Oct 19 16:08 media
drwxrwxr-- 11 poslop   poslop    4096 Oct  2 18:33 Pictures
```

ls -l /mnt/nextcloud/massdrive/games
```
drwxrwxr-- 4 poslop poslop 4096 Oct 24 16:12 archive
drwxrwxr-- 2 poslop poslop 4096 Oct 19 15:49 mc
drwxrwxr-- 2 poslop poslop 4096 Oct 19 15:46 wii
```

id www-data
```
uid=33(www-data) gid=33(www-data) groups=33(www-data),1000(poslop)
```

My home directory is also mounted into /mnt/nextcloud and has the exact same file permissions.  I am able to see and use everything properly in /mnt/nextcloud/poslop as expected.

/massdrive in nextcloud
![3a47b28b56e6000181760df660100257c3ed96db](https://github.com/nextcloud/server/assets/62452667/7bdc7489-4960-471e-9a08-7d00bf64b31c)

/massdrive/games in nextcloud
![26dbc8507f0aaee04a88bcbc640a2ac8e9b81f48](https://github.com/nextcloud/server/assets/62452667/66096cc1-8cd7-420c-8e42-02aeff839af0)

### Steps to reproduce

I did a clean reinstall and got the same issue.  Im also having the issue now with my home directory /home/poslop.  files in /poslop are visible but anything under in /poslop/*/ i cannot find.

### Expected behavior

I should be able to find all the files with these permissions

### Installation method

Official All-in-One appliance

### Nextcloud Server version

27

### Operating system

Other

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

Fresh Nextcloud Server install

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other
