### DISCUSSION TITLE
Reverse Proxy Configuration

### DISCUSSION THREAD

**Discussion by tuetenk0pp** [nextcloud/all-in-one#3946] [Questions] [answered]
Hi, I have a problem with my reverse proxy configuration. It seems like Nextcloud does not get the correct X-Forwarded-For IP and assumes the reverse proxy IP:

![grafik](https://github.com/nextcloud/all-in-one/assets/55783419/fc6eb4f8-906a-4404-b387-eefe22351ba4)

## `compose.yml`

```yml
version: "3.8"

services:
  caddy:
    image: caddy:alpine
    restart: unless-stopped
    container_name: caddy
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./certs:/certs
      - ./config:/config
      - ./data:/data
      - ./sites:/srv
    network_mode: host

  nextcloud-aio-mastercontainer:
    image: nextcloud/all-in-one:latest
    init: true
    restart: unless-stopped
    container_name: nextcloud-aio-mastercontainer
    volumes:
      - nextcloud_aio_mastercontainer:/mnt/docker-aio-config
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 8080:8080
    environment:
      - APACHE_PORT=11000
      - APACHE_IP_BINDING=127.0.0.1
      - NEXTCLOUD_MEMORY_LIMIT=6000M
      - NEXTCLOUD_STARTUP_APPS=twofactor_totp
      - NEXTCLOUD_ADDITIONAL_APKS=imagemagick
      - NEXTCLOUD_ADDITIONAL_PHP_EXTENSIONS=imagick
    depends_on:
      - caddy

volumes:
  nextcloud_aio_mastercontainer:
    name: nextcloud_aio_mastercontainer
```

## `Caddyfile`

```Caddyfile
https://cloud.domain.tdl:443 {
    header Strict-Transport-Security max-age=31536000;
    reverse_proxy localhost:11000

#    handle_errors {
#        rewrite * /srv/500.html
#        file_server
#    }

}

https://cloud.domain.tld:8443 {
    reverse_proxy https://localhost:8080 {
        transport http {
            tls_insecure_skip_verify
        }
    }
}
```

## `config.php`

I tried to add `172.20.0.1` to  `config.php` in the `trusted_proxies` section with this command: `docker run -it --rm --volume nextcloud_aio_nextcloud:/var/www/html:rw alpine sh -c "apk add --no-cache nano && nano /var/www/html/config/config.php"` and can confirm that the setting gets overwritten as mentioned in #3396.
