### DISCUSSION TITLE
No Disk Space left error, even though over 800 GB free

### DISCUSSION THREAD

**Discussion by miranyx** [nextcloud/all-in-one#3954] [Questions] [answered]
Hey, I just restored from a backup. Before I restored the backup everything worked fine. But after no longer. Now I get the error `No disk space left on server`, even though I have over 830G free space. It is happening on both of my accounts. How can I fix it?

I am using this docker-compose.yml file:
```
version: "3.8"

services:
  nextcloud-aio-mastercontainer:
    image: nextcloud/all-in-one:latest
    init: true
    restart: always
    container_name: nextcloud-aio-mastercontainer
    volumes:
      - nextcloud_aio_mastercontainer:/mnt/docker-aio-config
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 8080:8080
    environment: # Is needed when using any of the options below
      - APACHE_PORT=11000 
      - NEXTCLOUD_DATADIR=/data/nextcloud 
   
volumes: # If you want to store the data on a different drive, see https://github.com/nextcloud/all-in-one#how-to-store-the-filesinstallation-on-a-separate-drive
  nextcloud_aio_mastercontainer:
    name: nextcloud_aio_mastercontainer # This line is not allowed to be changed as otherwise the built-in backup solution will not work
```

From the collabora container logs:
```
wsd-00007-00244 2023-12-20 22:23:43.552408 +0100 [ docbroker_005 ] WRN  File system of [/opt/cool/child-roots/7-1eb1f87d/.] is dangerously low on disk space.| wsd/COOLWSD.cpp:390
wsd-00007-00244 2023-12-20 22:23:44.178297 +0100 [ docbroker_005 ] WRN  Client session [05f] not found to forward message: o168 canonicalidchange: viewid=0 canonicalid=1000 viewrenderedstate=Empty| wsd/DocumentBroker.cpp:3676
wsd-00007-00244 2023-12-20 22:23:44.178532 +0100 [ docbroker_005 ] WRN  Client session [05f] not found to forward message: o169 status: type=drawing parts=1 current=0 width=11722 height=16569 viewid=0 mode=0...| wsd/DocumentBroker.cpp:3676
```
I execed into it and ran df on that file system:
```sh
df -h /opt/cool/child-roots/7-1eb1f87d/
Filesystem      Size  Used Avail Use% Mounted on
overlay         9.1G  8.5G  187M  98% /
```
