### DISCUSSION TITLE
502 Bad Gateway: AIO + Nginx Proxy Manager + Cloudflare DNS

### DISCUSSION THREAD

**Discussion by neilasiii** [nextcloud/all-in-one#3958] [Questions] [answered]
I just installed the AIO according the the [reverse proxy guide](https://github.com/nextcloud/all-in-one/blob/main/reverse-proxy.md). I still get the 502 bad gateway issue.  I installed both AIO and NGINX Proxy Manager on Portainer stack. I had NPM running just fine before. Please help me troubleshoot my configuration.

My Docker-Compose script:
 
```
version: "3.8"

volumes:
  nextcloud_aio_mastercontainer:
    name: nextcloud_aio_mastercontainer
services:
  nginx_proxy_manager:
    image: jc21/nginx-proxy-manager:latest
    restart: unless-stopped
    container_name: nginx-proxy-manager
    network_mode: host
    environment: # Uncomment this if IPv6 is not enabled on your host
      - DISABLE_IPV6=true # Uncomment this if IPv6 is not enabled on your host
    volumes:
      - /data/compose/8/data:/data
      - /data/compose/8/letsencrypt:/etc/letsencrypt
  nextcloud:
    image: nextcloud/all-in-one:latest
    restart: unless-stopped
    container_name: nextcloud-aio-mastercontainer
    depends_on:
      - nginx_proxy_manager
    volumes:
      - nextcloud_aio_mastercontainer:/mnt/docker-aio-config
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 8080:8080
    environment:
      - APACHE_PORT=11000
      - APACHE_IP_BINDING=0.0.0.0
      - SKIP_DOMAIN_VALIDATION=true
```
NGINX Proxy Manager:

![image](https://github.com/nextcloud/all-in-one/assets/17012908/c2cc7bca-3fb4-4207-8939-17438116c5cb)

![image](https://github.com/nextcloud/all-in-one/assets/17012908/796b1870-ff34-412b-95b4-005416962d28)

![image](https://github.com/nextcloud/all-in-one/assets/17012908/4db85135-1dd3-4fe8-a636-cd19aec49487)

![image](https://github.com/nextcloud/all-in-one/assets/17012908/7c309051-a0d3-4928-9c7f-2b3028b9c696)

Cloudflare DNS settings:

![image](https://github.com/nextcloud/all-in-one/assets/17012908/157ab91c-6eba-4eba-9dc3-7836ea9d3fe7)

The Error Message:

![image](https://github.com/nextcloud/all-in-one/assets/17012908/704f536f-43db-4388-abf5-15bec413e180)

nextcloud-aio-nextcloud container logs:

```
System config value trusted_proxies => 0 set to string 127.0.0.1
System config value trusted_proxies => 1 set to string ::1
Config value base_endpoint for app notify_push set to https://nextcloud.my-domain.com/push
Config value wopi_url for app richdocuments set to https://nextcloud.my-domain.com/
Config value wopi_allowlist for app richdocuments set to 104.21.80.81,2606:4700:3032::ac43:b054,127.0.0.1/8,192.168.0.0/16,172.16.0.0/12,10.0.0.0/8,fd00::/8,::1,<my-ip>
Config value av_mode for app files_antivirus set to daemon
Config value av_port for app files_antivirus set to 3310
Config value av_host for app files_antivirus set to nextcloud-aio-clamav
Config value av_stream_max_length for app files_antivirus set to 104857600
Config value av_max_file_size for app files_antivirus set to 104857600
Config value av_infected_action for app files_antivirus set to only_log
System config value enabledPreviewProviders => 0 set to string OC\Preview\Imaginary
System config value preview_imaginary_url set to string http://nextcloud-aio-imaginary:9000
waiting for Fulltextsearch to become available...
waiting for Fulltextsearch to become available...
waiting for Fulltextsearch to become available...
waiting for Fulltextsearch to become available...
waiting for Fulltextsearch to become available...
waiting for Fulltextsearch to become available...
waiting for Fulltextsearch to become available...
waiting for Fulltextsearch to become available...
waiting for Fulltextsearch to become available...
waiting for Fulltextsearch to become available...
waiting for Fulltextsearch to become available...
waiting for Fulltextsearch to become available...
waiting for Fulltextsearch to become available...
waiting for Fulltextsearch to become available...
waiting for Fulltextsearch to become available...
waiting for Fulltextsearch to become available...
waiting for Fulltextsearch to become available...
waiting for Fulltextsearch to become available...
waiting for Fulltextsearch to become available...
waiting for Fulltextsearch to become available...
{
    "search_platform": "OCA\\FullTextSearch_Elasticsearch\\Platform\\ElasticSearchPlatform",
    "app_navigation": "0",
    "provider_indexed": "",
    "cron_err_reset": "1703191154",
    "tick_ttl": "1800",
    "collection_indexing_list": "50",
    "migration_24": "1",
    "collection_internal": "local"
}
{
    "elastic_host": "http:\/\/elastic:3d113e187ca3fc2583aea829370c525d69b0a91e925777bc@nextcloud-aio-fulltextsearch:9200",
    "elastic_index": "nextcloud-aio",
    "fields_limit": "10000",
    "es_ver_below66": "0",
    "elastic_logger_enabled": "1",
    "analyzer_tokenizer": "standard",
    "allow_self_signed_cert": "false"
}
{
    "files_local": "1",
    "files_external": "0",
    "files_group_folders": "0",
    "files_encrypted": "0",
    "files_federated": "0",
    "files_size": "20",
    "files_pdf": "1",
    "files_office": "1",
    "files_image": "0",
    "files_audio": "0",
    "files_chunk_size": "2"
}
+ '[' true = true ']'
+ '[' 11000 = 443 ']'
+ '[' 0.0.0.0 = 127.0.0.1 ']'
+ '[' 0.0.0.0 = ::1 ']'
+ set +x
[21-Dec-2023 18:51:42] NOTICE: fpm is running, pid 571
[21-Dec-2023 18:51:42] NOTICE: ready to handle connections
Activating Collabora config...
Failed to activate any config changes
Server error: `GET https://nextcloud.my-domain.com/hosting/discovery` resulted in a `502 Bad Gateway` response:
error code: 502
#0 /var/www/html/3rdparty/guzzlehttp/guzzle/src/Middleware.php(69): GuzzleHttp\Exception\RequestException::create(Object(GuzzleHttp\Psr7\Request), Object(GuzzleHttp\Psr7\Response), NULL, Array, NULL)
#1 /var/www/html/3rdparty/guzzlehttp/promises/src/Promise.php(204): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Response))
#2 /var/www/html/3rdparty/guzzlehttp/promises/src/Promise.php(153): GuzzleHttp\Promise\Promise::callHandler(1, Object(GuzzleHttp\Psr7\Response), NULL)
#3 /var/www/html/3rdparty/guzzlehttp/promises/src/TaskQueue.php(48): GuzzleHttp\Promise\Promise::GuzzleHttp\Promise\{closure}()
#4 /var/www/html/3rdparty/guzzlehttp/promises/src/Promise.php(248): GuzzleHttp\Promise\TaskQueue->run(true)
#5 /var/www/html/3rdparty/guzzlehttp/promises/src/Promise.php(224): GuzzleHttp\Promise\Promise->invokeWaitFn()
#6 /var/www/html/3rdparty/guzzlehttp/promises/src/Promise.php(269): GuzzleHttp\Promise\Promise->waitIfPending()
#7 /var/www/html/3rdparty/guzzlehttp/promises/src/Promise.php(226): GuzzleHttp\Promise\Promise->invokeWaitList()
#8 /var/www/html/3rdparty/guzzlehttp/promises/src/Promise.php(62): GuzzleHttp\Promise\Promise->waitIfPending()
#9 /var/www/html/3rdparty/guzzlehttp/guzzle/src/Client.php(187): GuzzleHttp\Promise\Promise->wait()
#10 /var/www/html/lib/private/Http/Client/Client.php(230): GuzzleHttp\Client->request('get', 'https://nextclo...', Array)
#11 /var/www/html/custom_apps/richdocuments/lib/WOPI/DiscoveryManager.php(89): OC\Http\Client\Client->get('https://nextclo...', Array)
#12 /var/www/html/custom_apps/richdocuments/lib/WOPI/DiscoveryManager.php(61): OCA\Richdocuments\WOPI\DiscoveryManager->fetchFromRemote()
#13 /var/www/html/custom_apps/richdocuments/lib/WOPI/Parser.php(41): OCA\Richdocuments\WOPI\DiscoveryManager->get()
#14 /var/www/html/custom_apps/richdocuments/lib/Command/ActivateConfig.php(67): OCA\Richdocuments\WOPI\Parser->getUrlSrc('Capabilities')
#15 /var/www/html/3rdparty/symfony/console/Command/Command.php(298): OCA\Richdocuments\Command\ActivateConfig->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#16 /var/www/html/3rdparty/symfony/console/Application.php(1040): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#17 /var/www/html/3rdparty/symfony/console/Application.php(301): Symfony\Component\Console\Application->doRunCommand(Object(OCA\Richdocuments\Command\ActivateConfig), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#18 /var/www/html/3rdparty/symfony/console/Application.php(171): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#19 /var/www/html/lib/private/Console/Application.php(211): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#20 /var/www/html/console.php(100): OC\Console\Application->run()
#21 /var/www/html/occ(11): require_once('/var/www/html/c...')
#22 {main}
```
Thanks in advance for the help.  I've been racking my brain all day trying to get this working.
