### DISCUSSION TITLE
Clicking blue link called "Open Your Nextcloud" just reloads the webpage.

### DISCUSSION THREAD

**Discussion by fishscene** [nextcloud/all-in-one#3973] [Questions] [answered]
After initial web config for Nextcloud AIO Master Container, clicking blue link called "Open Your Nextcloud" just reloads the webpage.
![2023-12-28 07_35_17-AIO - Brave](https://github.com/nextcloud/all-in-one/assets/1910351/0d7cfc07-4c1c-49ff-bc47-55dc4951f659)

I am behind a reverse proxy, nginx-gui
One slight deviation from https://github.com/nextcloud/all-in-one/blob/main/reverse-proxy.md#nginx-proxy-manager
Forward IP is set to IP of my server.
Forward Port is set to 8723 (the exposed port of the mastercontainer - see portainer config below.
*This gets me to the mastercontainer config webpage. Changing the config port to 11000 and navigating to the URL throws a "502 Bad Gateway"

Portainer Config:
```
version: '3'

volumes:
  nextcloud_aio_mastercontainer:
    name: nextcloud_aio_mastercontainer # This line is not allowed to be changed

services:
  nextcloud-aio-mastercontainer:
    container_name: nextcloud-aio-mastercontainer # This line is not allowed to be changed
    image: nextcloud/all-in-one:latest
    restart: always
    ports:
      - 8722:80
      - 8723:8080
      - 8724:8443
    volumes:
      - nextcloud_aio_mastercontainer:/mnt/docker-aio-config # This line is not allowed to be changed
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      #- TZ=America/Los_Angeles
      - /etc/localtime:/etc/localtime:ro
      - APACHE_PORT=11000 # Needed when running behind a reverse proxy. See https://github.com/nextcloud/all-in-one/blob/main/reverse-proxy.md
      - APACHE_IP_BINDING=127.0.0.1 # Should be set when running behind a reverse proxy that is running on the same host. See https://github.com/nextcloud/all-in-one/blob/main/reverse-proxy.md
      # - COLLABORA_SECCOMP_DISABLED=false # Setting this to true allows to disable Collabora's Seccomp feature. See https://github.com/nextcloud/all-in-one#how-to-disable-collaboras-seccomp-feature
      # - DOCKER_SOCKET_PATH=/var/run/docker.sock # Needs to be specified if the docker socket on the host is not located in the default '/var/run/docker.sock'. Otherwise mastercontainer updates will fail. For macos it needs to be '/var/run/docker.sock'
      # - DISABLE_BACKUP_SECTION=false # Setting this to true allows to hide the backup section in the AIO interface.
      # - NEXTCLOUD_DATADIR=/media/musichdd/nextcloud # Allows to set the host directory for Nextcloud's datadir. See https://github.com/nextcloud/all-in-one#how-to-change-the-default-location-of-nextclouds-datadir
      # - NEXTCLOUD_MOUNT=/mnt/ # Allows the Nextcloud container to access the chosen directory on the host. See https://github.com/nextcloud/all-in-one#how-to-allow-the-nextcloud-container-to-access-directories-on-the-host
      # - NEXTCLOUD_UPLOAD_LIMIT=1000G # Can be adjusted if you need more. See https://github.com/nextcloud/all-in-one#how-to-adjust-the-upload-limit-for-nextcloud
      - NEXTCLOUD_MAX_TIME=7200 # Can be adjusted if you need more. See https://github.com/nextcloud/all-in-one#how-to-adjust-the-max-execution-time-for-nextcloud
      # - NEXTCLOUD_MEMORY_LIMIT=512M # Can be adjusted if you need more. See https://github.com/nextcloud/all-in-one#how-to-adjust-the-php-memory-limit-for-nextcloud
      # - NEXTCLOUD_TRUSTED_CACERTS_DIR=/path/to/my/cacerts # CA certificates in this directory will be trusted by the OS of the nexcloud container (Useful e.g. for LDAPS) See See https://github.com/nextcloud/all-in-one#how-to-trust-user-defiend-certification-authorities-ca
      # - NEXTCLOUD_STARTUP_APPS=deck twofactor_totp tasks calendar contacts # Allows to modify the Nextcloud apps that are installed on starting AIO the first time. See https://github.com/nextcloud/all-in-one#how-to-change-the-nextcloud-apps-that-are-installed-on-the-first-startup
      #- "NEXTCLOUD_ADDITIONAL_APKS=imagemagick mesa-dri-gallium libva-intel-driver" # This allows to add additional packages to the Nextcloud container permanently. Default is imagemagick but can be overwritten by modifying this value. See https://github.com/nextcloud/all-in-one#how-to-add-os-packages-permanently-to-the-nextcloud-container
      # - NEXTCLOUD_ADDITIONAL_PHP_EXTENSIONS=imagick # This allows to add additional php extensions to the Nextcloud container permanently. Default is imagick but can be overwritten by modifying this value. See https://github.com/nextcloud/all-in-one#how-to-add-php-extensions-permanently-to-the-nextcloud-container
      - NEXTCLOUD_ENABLE_DRI_DEVICE=true # This allows to enable the /dev/dri device in the Nextcloud container which is needed for hardware-transcoding. See https://github.com/nextcloud/all-in-one#how-to-enable-hardware-transcoding-for-nextcloud
      # - TALK_PORT=3478 # This allows to adjust the port that the talk container is using.
      - SKIP_DOMAIN_VALIDATION=true
```

mastercontainer log:
```
+ '[' -f /dev-dri-group-was-added ']'
++ find /dev -maxdepth 1 -mindepth 1 -name dri
+ '[' -n /dev/dri ']'
++ find /dev/dri -maxdepth 1 -mindepth 1 -name renderD128
+ '[' -n /dev/dri/renderD128 ']'
++ stat -c %g /dev/dri/renderD128

9
+ groupadd -g 109 render2
++ getent group 109
++ cut -d: -f1
+ GROUP=render2
+ usermod -aG render2 www-data
+ touch /dev-dri-group-was-added
+ set +x
Installing imagemagick via apk...
Enabling Imagick...
WARNING: opening from cache https://dl-cdn.alpinelinux.org/alpine/v3.18/main: No such file or directory
WARNING: opening from cache https://dl-cdn.alpinelinux.org/alpine/v3.18/community: No such file or directory
Configuring Redis as session handler...
Initializing nextcloud 27.1.5.1 ...
Initializing finished
New Nextcloud instance.
Installing with PostgreSQL database
Starting Nextcloud installation...
Nextcloud was successfully installed
 - Repair MySQL collation
     - Not a mysql database -> nothing to do
 - Repair mime types
 - Clean tags and favorites
     - 0 tags of deleted users have been removed.
     - 0 tags for delete files have been removed.
     - 0 tag entries for deleted tags have been removed.
     - 0 tags with no entries have been removed.
 - Repair invalid shares
 - Move .step file of updater to backup location
 - Add move avatar background job
     - Add background job
 - Add preview cleanup background jobs
 - Migrate oauth2_clients table to nextcloud schema
     - Update the oauth2_access_tokens table schema.
     - Update the oauth2_clients table schema.
     - Delete clients (and their related access tokens) with the redirect_uri starting with oc:// or ending with *
 - Fix potential broken mount points
     - No mounts updated
 - Repair language codes
 - Add log rotate job
 - Clear frontend caches
     - Image cache cleared
     - JS cache cleared
 - Clear every generated avatar
 - Add preview background cleanup job
 - Queue a one-time job to cleanup old backups of the updater
 - Cleanup invalid photocache files for carddav
 - Add background job to cleanup login flow v2 tokens
 - Remove potentially over exposing share links
     - No need to remove link shares.
 - Clear access cache of projects
 - Reset generated avatar flag
 - Keep legacy encryption enabled
 - Check encryption key format
 - Remove old dashboard app config data
 - Add job to cleanup the bruteforce entries
 - Queue a one-time job to check for user uploaded certificates
 - Repair DAV shares
 - Add background job to set the lookup server share state for users
 - Add token cleanup job
 - Clean up abandoned apps
 - Add possibly missing system config
 - Add language model tasks cleanup job
 - Upgrading Circles App
 - Fix component of birthday calendars
     - 0 birthday calendars updated.
 - Regenerating birthday calendars to use new icons and fix old birthday events without year
     - Adding background jobs to regenerate birthday calendar
 - Fix broken values of calendar objects
    0 [>---------------------------]
 - Registering building of calendar search index as background job
     - Add background job
 - Register building of social profile search index as background job
 - Registering background jobs to update cache for webcal calendars
     - Added 0 background jobs to update webcal calendars
 - Registering building of calendar reminder index as background job
     - Add background job
 - Clean up orphan event and contact data
     - 0 events without a calendar have been cleaned up
     - 0 properties without an events have been cleaned up
     - 0 changes without a calendar have been cleaned up
     - 0 cached events without a calendar subscription have been cleaned up
     - 0 changes without a calendar subscription have been cleaned up
     - 0 contacts without an addressbook have been cleaned up
     - 0 properties without a contact have been cleaned up
     - 0 changes without an addressbook have been cleaned up
 - Remove activity entries of private events
     - Removed 0 activity entries
 - Clean up old calendar subscriptions from deleted users that were not cleaned-up
    0 [->--------------------------]
     - 0 calendar subscriptions without an user have been cleaned up
 - Remove invalid object properties
     - 0 invalid object properties removed.
 - Fix the share type of guest shares when migrating from ownCloud
 - Copy the share password into the dedicated column
 - Set existing shares as accepted
 - Update OAuth token expiration times
 - Switches from default updater server to the customer one if a valid subscription is available
 - Send an admin notification if monthly report is disabled
 - Force-reset all Text sessions before Yjs migration
 - Initialize migration of background images from dashboard to theming app
 - Add background job to check for backup codes
 - Populating added database structures for workflows
System config value updatedirectory set to string /nc-updater
Config value installedat for app core set to 1703723324.7600
Nextcloud Updater - version: v27.1.0rc3-15-gfa7af53

Current version is 27.1.5.

Update to Nextcloud 28.0.1 available. (channel: "stable")
Following file will be downloaded automatically: https://download.nextcloud.com/server/releases/nextcloud-28.0.1.zip
Open changelog ↗

Updater run in non-interactive mode.


date

Info: Pressing Ctrl-C will finish the currently running step and then stops the updater.

[ ] Check for expected files ...
] Check for expected files
[ ] Check for write permissions ...
] Check for write permissions
[ ] Create backup ...
] Create backup
[ ] Downloading ...
] Downloading
[ ] Verify integrity ...
] Verify integrity
[ ] Extracting ...
] Extracting
[ ] Enable maintenance mode ...
] Enable maintenance mode
[ ] Replace entry points ...
] Replace entry points
[ ] Delete old files ...
] Delete old files
[ ] Move new files in place ...
] Move new files in place
[ ] Done ...
] Done

Update of code successful.
Updater run in non-interactive mode - will start "occ upgrade" now.

Nextcloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
Setting log level to debug
Repair step: Repair MySQL collation
Repair info: Not a mysql database -> nothing to do
Repair step: Copy data from accounts table when migrating from ownCloud
Repair step: Drop account terms table when migrating from ownCloud
Updating database schema
Updated database
Disabled incompatible app: files_rightclick
Updating <federation> ...
Updated <federation> to 1.18.0
Updating <lookup_server_connector> ...
Updated <lookup_server_connector> to 1.16.0
Updating <oauth2> ...
Repair step: Update OAuth token expiration times
Updated <oauth2> to 1.16.3
Updating <password_policy> ...
Updated <password_policy> to 1.18.0
Updating <photos> ...
Updated <photos> to 2.4.0
Updating <files> ...
Updated <files> to 2.0.0
Updating <activity> ...
Updated <activity> to 2.20.0
Updating <circles> ...
Repair step: Upgrading Circles App
Updated <circles> to 28.0.0-dev
Updating <cloud_federation_api> ...
Updated <cloud_federation_api> to 1.11.0
Updating <dav> ...
Repair step: Fix component of birthday calendars
Repair info: 0 birthday calendars updated.
Repair step: Regenerating birthday calendars to use new icons and fix old birthday events without year
Repair info: Repair step already executed
Repair step: Fix broken values of calendar objects
Fix broken values of calendar objects

 Starting ...
    0/0 [>---------------------------]   0%
Repair step: Registering building of calendar search index as background job
Repair info: Repair step already executed
Repair step: Register building of social profile search index as background job
Repair step: Registering background jobs to update cache for webcal calendars
Repair info: Added 0 background jobs to update webcal calendars
Repair step: Registering building of calendar reminder index as background job
Repair info: Repair step already executed
Repair step: Clean up orphan event and contact data
Repair info: 0 events without a calendar have been cleaned up
Repair info: 0 properties without an events have been cleaned up
Repair info: 0 changes without a calendar have been cleaned up
Repair info: 0 cached events without a calendar subscription have been cleaned up
Repair info: 0 changes without a calendar subscription have been cleaned up
Repair info: 0 contacts without an addressbook have been cleaned up
Repair info: 0 properties without a contact have been cleaned up
Repair info: 0 changes without an addressbook have been cleaned up
Repair step: Remove activity entries of private events
Repair info: Removed 0 activity entries
Repair step: Clean up old calendar subscriptions from deleted users that were not cleaned-up
Clean up old calendar subscriptions from deleted users that were not cleaned-up

 Starting ...
    0/0 [->--------------------------]   0%
Repair info: 0 calendar subscriptions without an user have been cleaned up
Repair step: Remove invalid object properties
Repair info: 0 invalid object properties removed.
Updated <dav> to 1.29.1
Updating <files_sharing> ...
Repair step: Fix the share type of guest shares when migrating from ownCloud
Repair step: Copy the share password into the dedicated column
Repair step: Set existing shares as accepted
Updated <files_sharing> to 1.20.0
Updating <files_trashbin> ...
Updated <files_trashbin> to 1.18.0
Updating <files_versions> ...
Updated <files_versions> to 1.21.0
Updating <sharebymail> ...
Updated <sharebymail> to 1.18.0
Updating <workflowengine> ...
Repair step: Populating added database structures for workflows
Updated <workflowengine> to 2.10.0
Updating <comments> ...
Updated <comments> to 1.18.0
Updating <firstrunwizard> ...
Updated <firstrunwizard> to 2.17.0
Updating <logreader> ...
Updated <logreader> to 2.13.0
Updating <nextcloud_announcements> ...
Updated <nextcloud_announcements> to 1.17.0
Updating <notifications> ...
Updated <notifications> to 2.16.0
Updating <systemtags> ...
Updated <systemtags> to 1.18.0
Updating <theming> ...
Repair step: Failed to clean up the old administration theming images folder
Repair info: Migrating administration images
Repair info: No administration images to migrate
Repair step: Migrate old user accessibility config
Migrate old user accessibility config

 Starting ...
    0/0 [--->------------------------]   0%
Repair step: Initialize migration of background images from dashboard to theming app
Updated <theming> to 2.3.0
Updating <contactsinteraction> ...
Updated <contactsinteraction> to 1.9.0
Updating <dashboard> ...
Updated <dashboard> to 7.8.0
Updating <federatedfilesharing> ...
Updated <federatedfilesharing> to 1.18.0
Updating <files_pdfviewer> ...
Updated <files_pdfviewer> to 2.9.0
Updating <files_reminders> ...
Updated <files_reminders> to 1.1.0
Updating <privacy> ...
Updated <privacy> to 1.12.0
Updating <provisioning_api> ...
Updated <provisioning_api> to 1.18.0
Updating <recommendations> ...
Updated <recommendations> to 2.0.0
Updating <related_resources> ...
Updated <related_resources> to 1.3.0
Updating <serverinfo> ...
Updated <serverinfo> to 1.18.0
Updating <settings> ...
Updated <settings> to 1.10.1
Updating <support> ...
Repair step: Switches from default updater server to the customer one if a valid subscription is available
Repair info: Repair step already executed
Updated <support> to 1.11.0
Updating <survey_client> ...
Repair step: Send an admin notification if monthly report is disabled
Updated <survey_client> to 1.16.0
Updating <text> ...
Repair step: Force-reset all Text sessions before Yjs migration
Updated <text> to 3.9.1
Updating <twofactor_backupcodes> ...
Repair step: Add background job to check for backup codes
Updated <twofactor_backupcodes> to 1.17.0
Updating <user_status> ...
Updated <user_status> to 1.8.1
Updating <viewer> ...
Updated <viewer> to 2.2.0
Updating <weather_status> ...
Updated <weather_status> to 1.8.0
Repair step: Repair MySQL collation
Repair info: Not a mysql database -> nothing to do
Repair step: Repair mime types
Repair step: Clean tags and favorites
Repair info: 0 tags of deleted users have been removed.
Repair info: 0 tags for delete files have been removed.
Repair info: 0 tag entries for deleted tags have been removed.
Repair info: 0 tags with no entries have been removed.
Repair step: Repair invalid shares
Repair step: Move .step file of updater to backup location
Repair info: .step file exists
Repair info: .step file moved to .step-previous-update
Repair step: Add move avatar background job
Repair info: Repair step already executed
Repair step: Add preview cleanup background jobs
Repair step: Migrate oauth2_clients table to nextcloud schema
Repair info: Update the oauth2_access_tokens table schema.
Repair info: Update the oauth2_clients table schema.
Repair info: Delete clients (and their related access tokens) with the redirect_uri starting with oc:// or ending with *
Repair step: Fix potential broken mount points
Repair info: No mounts updated
Repair step: Repair language codes
Repair step: Add log rotate job
Repair step: Clear frontend caches
Repair info: Image cache cleared
Repair info: JS cache cleared
Repair step: Clear every generated avatar
Repair step: Add preview background cleanup job
Repair step: Queue a one-time job to cleanup old backups of the updater
Repair step: Cleanup invalid photocache files for carddav
Repair step: Add background job to cleanup login flow v2 tokens
Repair step: Remove potentially over exposing share links
Repair info: No need to remove link shares.
Repair step: Clear access cache of projects
Repair step: Reset generated avatar flag
Repair step: Keep legacy encryption enabled
Repair step: Check encryption key format
Repair step: Remove old dashboard app config data
Repair step: Add job to cleanup the bruteforce entries
Repair step: Queue a one-time job to check for user uploaded certificates
Repair step: Repair DAV shares
Repair step: Add background job to set the lookup server share state for users
Repair step: Add token cleanup job
Repair step: Clean up abandoned apps
Repair step: Add possibly missing system config
Repair step: Add AI tasks cleanup job
Repair step: Queue a job to generate metadata
Starting code integrity check...
Finished code integrity check
Update successful
Maintenance mode is kept active
Resetting log level

Updater run in non-interactive mode - will disable maintenance mode now.
Maintenance mode disabled

Maintenance mode is disabled
Nextcloud 28.0.1
updatenotification 1.18.0 disabled
nextcloud-aio 0.4.0 enabled
Adding additional fs_storage_path_prefix index to the oc_filecache table, this can take some time...
oc_filecache table updated successfully.
Done.
Done.
All tables already up to date!
Applying default settings...
System config value loglevel set to string 2
System config value log_type set to string file
System config value logfile set to string /var/www/html/data/nextcloud.log
System config value log_rotate_size set to string 10485760
admin_audit 1.18.0 enabled
Config value logfile for app admin_audit set to /var/www/html/data/audit.log
System config value log.condition => apps => 0 set to string admin_audit
Applying preview settings...
System config value preview_max_x set to string 2048
System config value preview_max_y set to string 2048
System config value jpeg_quality set to string 60
Config value jpeg_quality for app preview set to 60
System config value enabledPreviewProviders deleted
System config value enabledPreviewProviders => 1 set to string OC\Preview\Image
System config value enabledPreviewProviders => 2 set to string OC\Preview\MarkDown
System config value enabledPreviewProviders => 3 set to string OC\Preview\MP3
System config value enabledPreviewProviders => 4 set to string OC\Preview\TXT
System config value enabledPreviewProviders => 5 set to string OC\Preview\OpenDocument
System config value enabledPreviewProviders => 6 set to string OC\Preview\Movie
System config value enabledPreviewProviders => 7 set to string OC\Preview\Krita
System config value enable_previews set to boolean true
Applying other settings...
System config value upgrade.disable-web set to boolean true
System config value mail_smtpmode set to string smtp
System config value trashbin_retention_obligation set to string auto, 30
System config value versions_retention_obligation set to string auto, 30
System config value activity_expire_days set to string 30
System config value simpleSignUpLink.shown set to boolean false
System config value share_folder set to string /Shared
deck 1.12.0 installed

bled
twofactor_totp 10.0.0-beta.2 enabled
tasks 0.15.0 installed
tasks enabled
calendar 4.6.1 installed
calendar enabled
contacts 5.5.0 installed
contacts enabled
notes 4.9.1 installed
notes enabled
Applying one-click-instance settings...
System config value one-click-instance set to boolean true
System config value one-click-instance.user-limit set to integer 100
System config value one-click-instance.link set to string https://nextcloud.com/all-in-one/
support already enabled
Adjusting log files...
System config value upgrade.cli-upgrade-link set to string https://github.com/nextcloud/all-in-one/discussions/2726
System config value logfile set to string /var/www/html/data/nextcloud.log
Config value logfile for app admin_audit set to /var/www/html/data/audit.log
System config value updatedirectory set to string /nc-updater
Applying network settings...
System config value allow_local_remote_servers set to boolean true
System config value davstorage.request_timeout set to integer 7200
System config value trusted_domains => 1 set to string subdomain.redacted.com
System config value overwrite.cli.url set to string https://subdomain.redacted.com/
System config value htaccess.RewriteBase set to string /
.htaccess has been updated
System config value dbpersistent set to boolean false
System config value files_external_allow_create_new_local set to boolean false
notify_push 0.6.6 installed
notify_push enabled
System config value trusted_proxies => 0 set to string 127.0.0.1
System config value trusted_proxies => 1 set to string ::1
Config value base_endpoint for app notify_push set to https://subdomain.redacted.com/push
richdocuments 8.3.0 installed
richdocuments enabled
Config value wopi_url for app richdocuments set to https://subdomain.redacted.com/
No ipv6-address found for subdomain.redacted.com.
Config value wopi_allowlist for app richdocuments set to 73.225.82.222,127.0.0.1/8,192.168.0.0/16,172.16.0.0/12,10.0.0.0/8,fd00::/8,::1
spreed 18.0.1 installed
spreed enabled
Added subdomain.redacted.com:3478.
Added subdomain.redacted.com:3478.
There is nothing to delete.
Added signaling server https://subdomain.redacted.com/standalone-signaling/.
Config value recording_servers of app spreed deleted
System config value enabledPreviewProviders => 0 set to string OC\Preview\Imaginary
System config value preview_imaginary_url set to string http://nextcloud-aio-imaginary:9000
+ '[' true = true ']'
+ '[' 11000 = 443 ']'
+ '[' 127.0.0.1 = 127.0.0.1 ']'
++ dig nextcloud-aio-apache A +short +search
++ sort
++ head -n1
++ grep '^[0-9.]\+$'
+ IPv4_ADDRESS_APACHE=172.20.0.10
++ dig nextcloud-aio-apache AAAA +short +search
++ grep '^[0-9a-f:]\+$'
++ sort
++ head -n1
+ IPv6_ADDRESS_APACHE=
++ dig nextcloud-aio-mastercontainer A +short +search
++ head -n1
++ ++ sort
grep '^[0-9.]\+$'
+ IPv4_ADDRESS_MASTERCONTAINER=172.20.0.2
++ dig nextcloud-aio-mastercontainer AAAA +short +search
++ sort
++ grep '^[0-9a-f:]\+$'
++ head -n1
+ IPv6_ADDRESS_MASTERCONTAINER=
+ sed -i 's|^;listen.allowed_clients|listen.allowed_clients|' /usr/local/etc/php-fpm.d/www.conf
+ sed -i 's|listen.allowed_clients.*|listen.allowed_clients = 127.0.0.1,::1,172.20.0.10,,172.20.0.2,|' /usr/local/etc/php-fpm.d/www.conf
+ sed -i '/^listen.allowed_clients/s/,,/,/g' /usr/local/etc/php-fpm.d/www.conf
+ sed -i '/^listen.allowed_clients/s/,$//' /usr/local/etc/php-fpm.d/www.conf
+ grep listen.allowed_clients /usr/local/etc/php-fpm.d/www.conf
listen.allowed_clients = 127.0.0.1,::1,172.20.0.10,172.20.0.2
+ set +x
[27-Dec-2023 16:30:42] NOTICE: fpm is running, pid 820
[27-Dec-2023 16:30:42] NOTICE: ready to handle connections
Activating Collabora config...
✓ Reset callback url autodetect
Checking configuration
🛈 Configured WOPI URL: https://subdomain.redacted.com/
🛈 Configured public WOPI URL: https://subdomain.redacted.com/
🛈 Configured callback URL: 

✓ Fetched /hosting/discovery endpoint
Failed to fetch discovery endpoint from https://subdomain.redacted.com/
Call to a member function xpath() on bool
```

Any ideas?

**Comment by Zoey2936** [comment]
```
      - APACHE_PORT=11000 # Needed when running behind a reverse proxy. See https://github.com/nextcloud/all-in-one/blob/main/reverse-proxy.md
      - APACHE_IP_BINDING=127.0.0.1 # Should be set when running behind a reverse proxy that is running on the same host.
```
you need to proxy to 127.0.0.1:11000

**Comment by fishscene** [comment]
Changed nginx to forward to 127.0.0.1:11000, then re-built my environment from scratch.

![2023-12-28 11_50_55-AIO - Brave](https://github.com/nextcloud/all-in-one/assets/1910351/5077a800-f801-4853-b778-806c265be900)

The log:
NOTICE: PHP message: The error message was: 
NOTICE: PHP message: The response of the connection attempt to "https://subdomain.redacted.com:443" was: <html>
<head><title>502 Bad Gateway</title></head>
<body>
<center><h1>502 Bad Gateway</h1></center>
<hr><center>openresty</center>
</body>
</html>
NOTICE: PHP message: Expected was: ea20f80a46f8357566592e85302fa234f5e875b6e8fdebfa

**Reply by fishscene** [reply]
I may have made a breakthrough. Will report back when it finishes spawning containers.

**Comment by fishscene** [comment, marked as answer]
oh snap it worked. 
@Zoey2936 Thank you for replying so quickly and reinforcing the documentation. Looks like I had goofed and missed that I had set nginx to https instead of http (as a result of me trying random configs to see if I could get it working. This was the final piece of the puzzle.

I'm a HUGE believer in documenting the fix. So here goes...


Portainer compose:
```
version: '3'

volumes:
  nextcloud_aio_mastercontainer:
    name: nextcloud_aio_mastercontainer

services:
  nextcloud-aio-mastercontainer:
    image: nextcloud/all-in-one:latest
    init: true
    restart: always
    container_name: nextcloud-aio-mastercontainer # This line is not allowed to be changed as otherwise AIO will not work correctly
    volumes:
      - nextcloud_aio_mastercontainer:/mnt/docker-aio-config # This line is not allowed to be changed as otherwise the built-in backup solution will not work
      - /var/run/docker.sock:/var/run/docker.sock:ro # May be changed on macOS, Windows or docker rootless. See the applicable documentation. If adjusting, don't forget to also set 'WATCHTOWER_DOCKER_SOCKET_PATH'!
    ports:
      #- 80:80 # Can be removed when running behind a web server or reverse proxy (like Apache, Nginx, Cloudflare Tunnel and else). See https://github.com/nextcloud/all-in-one/blob/main/reverse-proxy.md
      - 8723:8080
      #- 8443:8443 # Can be removed when running behind a web server or reverse proxy (like Apache, Nginx, Cloudflare Tunnel and else). See https://github.com/nextcloud/all-in-one/blob/main/reverse-proxy.md
    environment: # Is needed when using any of the options below
      - /etc/localtime:/etc/localtime:ro
      # - TZ=America/Los_Angeles
      # - AIO_DISABLE_BACKUP_SECTION=false # Setting this to true allows to hide the backup section in the AIO interface. See https://github.com/nextcloud/all-in-one#how-to-disable-the-backup-section
      - APACHE_PORT=11000 # Is needed when running behind a web server or reverse proxy (like Apache, Nginx, Cloudflare Tunnel and else). See https://github.com/nextcloud/all-in-one/blob/main/reverse-proxy.md
      - APACHE_IP_BINDING=0.0.0.0 # Should be set when running behind a web server or reverse proxy (like Apache, Nginx, Cloudflare Tunnel and else) that is running on the same host. See https://github.com/nextcloud/all-in-one/blob/main/reverse-proxy.md
      # - BORG_RETENTION_POLICY=--keep-within=7d --keep-weekly=4 --keep-monthly=6 # Allows to adjust borgs retention policy. See https://github.com/nextcloud/all-in-one#how-to-adjust-borgs-retention-policy
      # - COLLABORA_SECCOMP_DISABLED=false # Setting this to true allows to disable Collabora's Seccomp feature. See https://github.com/nextcloud/all-in-one#how-to-disable-collaboras-seccomp-feature
      # - NEXTCLOUD_DATADIR=/mnt/ncdata # Allows to set the host directory for Nextcloud's datadir. ⚠️⚠️⚠️ Warning: do not set or adjust this value after the initial Nextcloud installation is done! See https://github.com/nextcloud/all-in-one#how-to-change-the-default-location-of-nextclouds-datadir
      # - NEXTCLOUD_MOUNT=/mnt/ # Allows the Nextcloud container to access the chosen directory on the host. See https://github.com/nextcloud/all-in-one#how-to-allow-the-nextcloud-container-to-access-directories-on-the-host
      # - NEXTCLOUD_UPLOAD_LIMIT=10G # Can be adjusted if you need more. See https://github.com/nextcloud/all-in-one#how-to-adjust-the-upload-limit-for-nextcloud
      # - NEXTCLOUD_MAX_TIME=3600 # Can be adjusted if you need more. See https://github.com/nextcloud/all-in-one#how-to-adjust-the-max-execution-time-for-nextcloud
      # - NEXTCLOUD_MEMORY_LIMIT=512M # Can be adjusted if you need more. See https://github.com/nextcloud/all-in-one#how-to-adjust-the-php-memory-limit-for-nextcloud
      # - NEXTCLOUD_TRUSTED_CACERTS_DIR=/path/to/my/cacerts # CA certificates in this directory will be trusted by the OS of the nexcloud container (Useful e.g. for LDAPS) See See https://github.com/nextcloud/all-in-one#how-to-trust-user-defined-certification-authorities-ca
      # - NEXTCLOUD_STARTUP_APPS=deck twofactor_totp tasks calendar contacts notes # Allows to modify the Nextcloud apps that are installed on starting AIO the first time. See https://github.com/nextcloud/all-in-one#how-to-change-the-nextcloud-apps-that-are-installed-on-the-first-startup
      # - NEXTCLOUD_ADDITIONAL_APKS=imagemagick # This allows to add additional packages to the Nextcloud container permanently. Default is imagemagick but can be overwritten by modifying this value. See https://github.com/nextcloud/all-in-one#how-to-add-os-packages-permanently-to-the-nextcloud-container
      # - NEXTCLOUD_ADDITIONAL_PHP_EXTENSIONS=imagick # This allows to add additional php extensions to the Nextcloud container permanently. Default is imagick but can be overwritten by modifying this value. See https://github.com/nextcloud/all-in-one#how-to-add-php-extensions-permanently-to-the-nextcloud-container
      - NEXTCLOUD_ENABLE_DRI_DEVICE=true # This allows to enable the /dev/dri device in the Nextcloud container. ⚠️⚠️⚠️ Warning: this only works if the '/dev/dri' device is present on the host! If it should not exist on your host, don't set this to true as otherwise the Nextcloud container will fail to start! See https://github.com/nextcloud/all-in-one#how-to-enable-hardware-transcoding-for-nextcloud
      # - NEXTCLOUD_KEEP_DISABLED_APPS=false # Setting this to true will keep Nextcloud apps that are disabled in the AIO interface and not uninstall them if they should be installed. See https://github.com/nextcloud/all-in-one#how-to-keep-disabled-apps
      # - TALK_PORT=3478 # This allows to adjust the port that the talk container is using. See https://github.com/nextcloud/all-in-one#how-to-adjust-the-talk-port
      # - WATCHTOWER_DOCKER_SOCKET_PATH=/var/run/docker.sock # Needs to be specified if the docker socket on the host is not located in the default '/var/run/docker.sock'. Otherwise mastercontainer updates will fail. For macos it needs to be '/var/run/docker.sock'
    # networks: # Is needed when you want to create the nextcloud-aio network with ipv6-support using this file, see the network config at the bottom of the file
      # - nextcloud-aio # Is needed when you want to create the nextcloud-aio network with ipv6-support using this file, see the network config at the bottom of the file
    # # Uncomment the following line when using SELinux
    # security_opt: ["label:disable"]
```

Nginx config:
https://github.com/nextcloud/all-in-one/blob/main/reverse-proxy.md#nginx-proxy-manager
Note: I changed "IP" to the LAN IP of my server. All other settings are the same.

To manage the AIO container:
https://(LAN IP of server):8723

To access Nextcloud:
https://(url)
(I have my firewall ports 80 and 443 forwarded to nginx)

Run through initial config. After the containers start, the link to "Open your Nextcloud" should appear and now works.
