### DISCUSSION TITLE
The 'nextcloud-aio-mastercontainer' container was not found.

### DISCUSSION THREAD

**Discussion by Lex1020** [nextcloud/all-in-one#3984] [Questions] [answered]
Using the compose.yml file from the project's root directory gives the following errors.

```
Trying to fix docker.sock permissions internally...
Creating docker group internally with id 119
It seems like you did not give the mastercontainer the correct name? (The 'nextcloud-aio-mastercontainer' container was not found.)
```

**Comment by Acsigen** [comment]
If you use `docker run` please use `--name nextcloud-aio-mastercontainer` inside the command, before the image name.

If you use docker compose, please add `container_name: "nextcloud-aio-mastercontainer"` to the configuration. Also do not rename the service.

**Comment by Lex1020** [comment]
> If you use `docker run` please use `--name nextcloud-aio-mastercontainer` inside the command, before the image name.
> 
> If you use docker compose, please add `container_name: "nextcloud-aio-mastercontainer"` to the configuration. Also do not rename the service.

container_name: nextcloud-aio-mastercontainer is already in the docker-compose file. I've used the exact docker-compose file the Readme says here: https://github.com/nextcloud/all-in-one?tab=readme-ov-file#how-to-run-aio-with-portainer

**Reply by szaimen** [reply]
See the difference between volume and container name. That is what you missed. The volume uses underscore and the container dashes...

**Reply by MCT-MIT** [reply]
Yup, walking error message. 👎 
Thanks for the correction.

**Comment by joshtrichards** [comment]
Are you perhaps running rootless?

https://github.com/nextcloud/all-in-one/blob/main/docker-rootless.md

EDIT: Fixed link

**Comment by Lex1020** [comment]
> Are you perhaps running rootless?
> 
> https://github.com/MarvvanPal/all-in-one/blob/main/docker-rootless.md

I'm trying to start it in Portainer. Docker has root access

**Comment by fishscene** [comment]
Hey mate, I too use Portainer and I'm slowly working out issues. I too had the same issue, but worked it out by adding the apache port and IP bindings. 
Here's my Portainer stack, which got me most of the way, but clicking the "Open your Nextcloud" button just re-opens the mastercontainer management page. That's an issue for another thread though - just wanted you to be aware.
Note: I'm still working on this config, so if you're wondering why things are disabled/enabled, that's why. :)
Note2: This will be running behind nginx, which I have not configured correctly yet either.

```
version: '3'

volumes:
  nextcloud_aio_mastercontainer:
    name: nextcloud_aio_mastercontainer # This line is not allowed to be changed

services:
  nextcloud-aio-mastercontainer:
    container_name: nextcloud-aio-mastercontainer # This line is not allowed to be changed
    image: nextcloud/all-in-one:latest
    restart: always
    ports:
      - 8722:80
      - 8723:8080
      #- 8724:8443
    volumes:
      - nextcloud_aio_mastercontainer:/mnt/docker-aio-config # This line is not allowed to be changed
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      #- TZ=America/Los_Angeles
      - /etc/localtime:/etc/localtime:ro
      - APACHE_PORT=11000 # Needed when running behind a reverse proxy. See https://github.com/nextcloud/all-in-one/blob/main/reverse-proxy.md
      - APACHE_IP_BINDING=127.0.0.1 # Should be set when running behind a reverse proxy that is running on the same host. See https://github.com/nextcloud/all-in-one/blob/main/reverse-proxy.md
      # - COLLABORA_SECCOMP_DISABLED=false # Setting this to true allows to disable Collabora's Seccomp feature. See https://github.com/nextcloud/all-in-one#how-to-disable-collaboras-seccomp-feature
      # - DOCKER_SOCKET_PATH=/var/run/docker.sock # Needs to be specified if the docker socket on the host is not located in the default '/var/run/docker.sock'. Otherwise mastercontainer updates will fail. For macos it needs to be '/var/run/docker.sock'
      # - DISABLE_BACKUP_SECTION=false # Setting this to true allows to hide the backup section in the AIO interface.
      # - NEXTCLOUD_DATADIR=/media/musichdd/nextcloud # Allows to set the host directory for Nextcloud's datadir. See https://github.com/nextcloud/all-in-one#how-to-change-the-default-location-of-nextclouds-datadir
      # - NEXTCLOUD_MOUNT=/mnt/ # Allows the Nextcloud container to access the chosen directory on the host. See https://github.com/nextcloud/all-in-one#how-to-allow-the-nextcloud-container-to-access-directories-on-the-host
      # - NEXTCLOUD_UPLOAD_LIMIT=1000G # Can be adjusted if you need more. See https://github.com/nextcloud/all-in-one#how-to-adjust-the-upload-limit-for-nextcloud
      - NEXTCLOUD_MAX_TIME=7200 # Can be adjusted if you need more. See https://github.com/nextcloud/all-in-one#how-to-adjust-the-max-execution-time-for-nextcloud
      # - NEXTCLOUD_MEMORY_LIMIT=512M # Can be adjusted if you need more. See https://github.com/nextcloud/all-in-one#how-to-adjust-the-php-memory-limit-for-nextcloud
      # - NEXTCLOUD_TRUSTED_CACERTS_DIR=/path/to/my/cacerts # CA certificates in this directory will be trusted by the OS of the nexcloud container (Useful e.g. for LDAPS) See See https://github.com/nextcloud/all-in-one#how-to-trust-user-defiend-certification-authorities-ca
      # - NEXTCLOUD_STARTUP_APPS=deck twofactor_totp tasks calendar contacts # Allows to modify the Nextcloud apps that are installed on starting AIO the first time. See https://github.com/nextcloud/all-in-one#how-to-change-the-nextcloud-apps-that-are-installed-on-the-first-startup
      #- "NEXTCLOUD_ADDITIONAL_APKS=imagemagick mesa-dri-gallium libva-intel-driver" # This allows to add additional packages to the Nextcloud container permanently. Default is imagemagick but can be overwritten by modifying this value. See https://github.com/nextcloud/all-in-one#how-to-add-os-packages-permanently-to-the-nextcloud-container
      # - NEXTCLOUD_ADDITIONAL_PHP_EXTENSIONS=imagick # This allows to add additional php extensions to the Nextcloud container permanently. Default is imagick but can be overwritten by modifying this value. See https://github.com/nextcloud/all-in-one#how-to-add-php-extensions-permanently-to-the-nextcloud-container
      - NEXTCLOUD_ENABLE_DRI_DEVICE=true # This allows to enable the /dev/dri device in the Nextcloud container which is needed for hardware-transcoding. See https://github.com/nextcloud/all-in-one#how-to-enable-hardware-transcoding-for-nextcloud
      # - TALK_PORT=3478 # This allows to adjust the port that the talk container is using.
      - SKIP_DOMAIN_VALIDATION=true
```
