### DISCUSSION TITLE
How can I get Nextcloud to actually use the data directory I'm setting?

### DISCUSSION THREAD

**Discussion by slamphear** [nextcloud/all-in-one#3994] [Questions] [answered]
I've been trying for the last week or so to get Nextcloud to use a specific folder on my external RAID bay as its data directory, and I've gotten to the point where I think it's time to ask here.

Here's what I've got in my docker-compose.yml:

```
version: '3'

services:
  nextcloud-aio:
    image: nextcloud/all-in-one:latest
    container_name: nextcloud-aio-mastercontainer
    restart: always
    ports:
      - "80:80"
      - "8080:8080"
      - "8443:443"
    volumes:
      - nextcloud_aio_mastercontainer:/mnt/docker-aio-config
      - /Volumes/Storage/Nextcloud:/mnt/ncdata
      - /var/run/docker.sock.raw:/var/run/docker.sock:ro
      - <my certs directory>:/etc/apache2/ssl
    environment:
      - NEXTCLOUD_DATADIR=/mnt/ncdata
      - APACHE_PORT=443

volumes:
  nextcloud_aio_mastercontainer:
    name: nextcloud_aio_mastercontainer
```

Notice that the `volumes` section for the `nextcloud-aio` service includes `- /Volumes/Storage/Nextcloud:/mnt/ncdata` (which I assume maps the host's directory where I'm wanting to see my data end up to `/mnt/ncdata`), and the `environment` section includes `- NEXTCLOUD_DATADIR=/mnt/ncdata` (which I believe should tell Nextcloud to use `/mnt/ncdata` for all of its data storage).

This seems to be working correctly for everything except the data directory. However, when I create a user, log into the iOS app as that user, turn on photo upload, take a photo, sync it to my Nextcloud instance, then check that folder on the host machine, it's still entirely empty (`/Volumes/Storage/Nextcloud` still has nothing in it).

Does anyone have any idea what could be going on here? Perhaps there's a typo somewhere? I did see some instructions using `NEXTCLOUD_DATA_DIR` as the env flag name, but all of the official documentation seems to exclude that second underscore; regardless, adding that underscore didn't fix this. Or is this perhaps related to the fact that I'm trying to use an external device for storage? (I did make sure that Docker has permission to access files on removable volumes, for whatever that's worth.)

Any help anyone can provide would be greatly appreciated!
