### DISCUSSION TITLE
"Cannot connect to the docker socket. Cannot proceed."

### DISCUSSION THREAD

**Discussion by zine999** [nextcloud/all-in-one#4008] [Questions] [answered]
Hi, I'm using Fedora Linux, and a docker setup with [namespace username remapping](https://docs.docker.com/engine/security/userns-remap/) enabled.

I cannot get the AIO container to run. No matter what I do, I get `Cannot connect to the docker socket. Cannot proceed.`.

Here is my `docker-compose` setup below. As you can see, I've added the relevant `security_opt` stuff (even went overboard by adding in `seccomp=unconfined`, and added `cap_add: ALL` for good measure, as well as mounted the docker socket with write permissions, and still it doesn't run:

```yml
  nextcloud_aio_mastercontainer:
    image: nextcloud/all-in-one:latest 
    init: true
    container_name: nextcloud-aio-mastercontainer
    restart: unless-stopped
    expose:
      - "8080"
      - "11000"
    environment:
      - APACHE_PORT=11000
      - APACHE_IP_BINDING=0.0.0.0
    security_opt:
      - label=disable
      - seccomp=unconfined
    cap_add:
      - ALL
    volumes:
      - nextcloud_aio_mastercontainer:/mnt/docker-aio-config
      - /var/run/docker.sock:/var/run/docker.sock
```

I even ran it after setting `setenforce 0` just to see if it would run with SELinux completely disabled, and it still didn't run and gave the same error.

Help?
