### DISCUSSION TITLE
Only Numbers in PDF converter

### DISCUSSION THREAD

**Discussion by HartmutA** [nextcloud/all-in-one#4025] [Questions] [answered]
## Steps to reproduce
1. Create a Workflow with filename: “/^testpdf*/”
2. Create a Excel Sheet with Numbers and Chars
3. 

### Expected behaviour
A PDF should be created  similar to the XLS

### Actual behaviour
Numers are correct, chars displayed as a Block

## PDF Converter app

**PDF Converter app version:** 1.10.1

## Server configuration
[Nextcloud Hub 3](https://nextcloud.com/) (25.0.4)

**Operating system**:  Ubuntu 20.04.5 LTS 

**Web server:** Nextcloud AIO with Caddy as Proxy

**Database:** PostgreSQL

**PHP version:**

**Nextcloud Version:** 25.0.4

**Where did you install Nextcloud from:** Docker AIO

**Signing status:**

Login as admin user into your Nextcloud and access
http://example.com/index.php/settings/integrity/failed
paste the results here.
`No errors have been found`

**List of activated apps:**

added
- NEXTCLOUD_ADDITIONAL_APKS=libreoffice libreoffice-lang-de
to docker-Compose.yml

If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your server installation folder
Enabled:
<details>
  - activity: 2.17.0
  - admin_audit: 1.15.0
  - calendar: 4.2.4
  - circles: 25.0.0
  - cloud_federation_api: 1.8.0
  - comments: 1.15.0
  - contacts: 5.1.0
  - contactsinteraction: 1.6.0
  - dashboard: 7.5.0
  - dav: 1.24.0
  - deck: 1.8.3
  - federatedfilesharing: 1.15.0
  - federation: 1.15.0
  - files: 1.20.1
  - files_pdfviewer: 2.6.0
  - files_rightclick: 1.4.0
  - files_sharing: 1.17.0
  - files_trashbin: 1.15.0
  - files_versions: 1.18.0
  - firstrunwizard: 2.14.0
  - logreader: 2.10.0
  - lookup_server_connector: 1.13.0
  - nextcloud-aio: 0.3.0
  - nextcloud_announcements: 1.14.0
  - notifications: 2.13.1
  - notify_push: 0.6.0
  - oauth2: 1.13.0
  - password_policy: 1.15.0
  - photos: 2.0.1
  - privacy: 1.9.0
  - provisioning_api: 1.15.0
  - recommendations: 1.4.0
  - related_resources: 1.0.4
  - richdocuments: 7.1.2
  - serverinfo: 1.15.0
  - settings: 1.7.0
  - sharebymail: 1.15.0
  - spreed: 15.0.4
  - support: 1.8.0
  - survey_client: 1.13.0
  - systemtags: 1.15.0
  - tasks: 0.14.5
  - text: 3.6.0
  - theming: 2.0.1
  - twofactor_backupcodes: 1.14.0
  - user_status: 1.5.0
  - viewer: 1.9.0
  - weather_status: 1.5.0
  - workflow_pdf_converter: 1.10.1
  - workflowengine: 2.7.0
</details>
Disabled:
<details>
  - bruteforcesettings
  - encryption
  - files_external
  - suspicious_login
  - twofactor_totp
  - user_ldap

</details>

**Nextcloud configuration:**

<details>

If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

{
    "system": {
        "memcache.local": "\\OC\\Memcache\\APCu",
        "apps_paths": [
            {
                "path": "\/var\/www\/html\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/www\/html\/custom_apps",
                "url": "\/custom_apps",
                "writable": true
            }
        ],
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "password": "***REMOVED SENSITIVE VALUE***",
            "port": 6379
        },
        "overwritehost": "cloud.rehrstieg102.de",
        "overwriteprotocol": "https",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "localhost",
            "cloud.rehrstieg102.de"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "pgsql",
        "version": "25.0.4.1",
        "overwrite.cli.url": "https:\/\/cloud.rehrstieg102.de\/",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "loglevel": "2",
        "log_type": "file",
        "logfile": "\/var\/www\/html\/data\/nextcloud.log",
        "log_rotate_size": "10485760",
        "log.condition": {
            "apps": [
                "admin_audit"
            ]
        },
        "preview_max_x": "2048",
        "preview_max_y": "2048",
        "jpeg_quality": "60",
        "enabledPreviewProviders": {
            "1": "OC\\Preview\\Image",
            "2": "OC\\Preview\\MarkDown",
            "3": "OC\\Preview\\MP3",
            "4": "OC\\Preview\\TXT",
            "5": "OC\\Preview\\OpenDocument",
            "6": "OC\\Preview\\Movie",
            "0": "OC\\Preview\\Imaginary"
        },
        "enable_previews": true,
        "upgrade.disable-web": true,
        "mail_smtpmode": "smtp",
        "mail_smtpsecure": "ssl",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauth": 1,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "trashbin_retention_obligation": "auto, 30",
        "versions_retention_obligation": "auto, 30",
        "activity_expire_days": "30",
        "simpleSignUpLink.shown": false,
        "share_folder": "\/Shared",
        "tempdirectory": "\/mnt\/ncdata\/tmp\/",
        "one-click-instance": true,
        "one-click-instance.user-limit": 100,
        "one-click-instance.link": "https:\/\/nextcloud.com\/all-in-one\/",
        "htaccess.RewriteBase": "\/",
        "files_external_allow_create_new_local": false,
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "allow_local_remote_servers": true,
        "default_phone_region": "DE",
        "maintenance": false,
        "preview_imaginary_url": "http:\/\/nextcloud-aio-imaginary:9000"
    }
}
</details>

**Are you using external storage, if yes which one:**  no
**Are you using encryption:** no

### Server log (data/nextcloud.log)
While Converting, a error is logged:
<details>
Fontconfig error: No writable cache directories
</details>
But I don’t how to fix this.

![Workflow Problem PDF](https://user-images.githubusercontent.com/62034753/225380131-624eb285-b391-41e9-a79e-11fc798259d4.png)
![Workflow Problem Excel](https://user-images.githubusercontent.com/62034753/225380183-b488f5c6-034b-46a3-8b3a-cd845d4b4780.png)

**Comment by blizzz** [comment]
@szaimen :shrug:

**Comment by szaimen** [comment]
Sorry, no idea either 🤷

What should I check? Is maybe a dependency missing in the alpine based container?

**Comment by HartmutA** [comment]
It should be a dependency. Before i switched to AIO I used Nextcloud 24. There I had to add "libreoffice libreoffice-l10n-de libreoffice-help-de " to the Nextcloud Container. But I didn't find an APK for "libreoffice-l10n-de".
I don't use the App "Collabora Online - Built-in CODE Server". I activated the Collabora Online Server (the part of the AIO).

**Comment by szaimen** [comment]
> But I didn't find an APK for "libreoffice-help-de".

Probably this is the reason then 🤷‍♂️

**Comment by HartmutA** [comment]
Exists an alternative for "libreoffice-l10n-de"?
(I think the "help" ist not the problem ;-) )

I searched here:
https://pkgs.alpinelinux.org/packages?name=&branch=v3.16&repo=&arch=&maintainer=

**Comment by szaimen** [comment]
I think libreoffice-lang-de should actually be doing that. Maybe you need to add the calc package?

**Comment by HartmutA** [comment]
I changed it to 
      - NEXTCLOUD_ADDITIONAL_APKS=libreoffice libreoffice-calc libreoffice-lang-de
no change. The same is in word/odt files.
Is this only in my configuration? Do you have an Nextcloud AIO where this is ok?

**Comment by rototom** [comment]
same problem here

**Comment by HartmutA** [comment]
Does anyone got this work? Should be good to know if the issue is in front or behind my keyboard ;-)

**Comment by HartmutA** [comment]
one step forward. Think the issue is behind my keyboard.
I found that in the PDF is only one embedded font: OpenSymbol
The command "ls /usr/lib/libreoffice/share/fonts/truetype" show only "opens___.ttf"
If I copy the fonts from the collabora container to the Nextcloud-App container it seems to be OK.

docker cp nextcloud-aio-collabora:/opt/collaboraoffice/share/fonts/truetype/ ./fonts
docker cp ./fonts nextcloud-aio-nextcloud:/usr/lib/libreoffice/share
fc-cache -f -v

But I think with the next update that will be gone.

**Comment by HartmutA** [comment]
Correction: It's gone with the next reboot :-(

**Comment by blizzz** [comment]
moved to AIO repo.

**Comment by szaimen** [comment]
Hi, I think this should be fixed in the collabora container that we re-use here. So please open an issue here: https://github.com/CollaboraOnline/online/issues

**Comment by HartmutA** [comment]
Thank you very much for your work here. But sorry, from my view it looks like, that the collabora container is not used from the workflow pdf converter. So it makes no sense to open an issue there.
It is ok, when i copy the font into the nextcloud-aio-nextcloud container.
Maybe it was not clear enough:
I copy the fonts FROM the collabora container TO the nextcloud app (nextcloud-aio-nextcloud) container.
So I think the issue is: 
either: The workflow pdf converter has to use the collabora container (but it don't) --> Issue for The workflow pdf converter
or: my stupidity ;-) because I don't know how to configure or install the workflow pdf converter correctly.
or: I have to configure the workflow pdf converter to use the collabora container but I don't know how.

Again: I added NEXTCLOUD_ADDITIONAL_APKS=libreoffice libreoffice-lang-de
to docker-Compose.yml
like I did it in Nextcloud (not AIO) where it worked as expected.
But I don't know  how to add the missing fonts. I didn't find an apk with fonts.

**Comment by szaimen** [comment]
Ah I see. Didnt read to the end.

**Comment by szaimen** [comment, marked as answer]
Hi, I just fond https://wiki.alpinelinux.org/wiki/Fonts#Installation.

Can you try if `- NEXTCLOUD_ADDITIONAL_APKS=libreoffice libreoffice-lang-de font-terminus font-inconsolata font-dejavu font-noto font-noto-cjk font-awesome font-noto-extra` makes it work?

**Comment by HartmutA** [comment]
Strange. There is no change. I dont see more fonts after that. Here is a part of the log:

```
              now              
-------------------------------
 2024-01-10 10:05:08.045242+01
(1 row)

+ '[' -f /dev-dri-group-was-added ']'
++ find /dev -maxdepth 1 -mindepth 1 -name dri
+ '[' -n '' ']'
+ set +x
Installing imagemagick via apk...
Installing libreoffice via apk...
Installing libreoffice-lang-de via apk...
Enabling Imagick...
WARNING: opening from cache https://dl-cdn.alpinelinux.org/alpine/v3.18/main: No such file or directory
WARNING: opening from cache https://dl-cdn.alpinelinux.org/alpine/v3.18/community: No such file or directory
Configuring Redis as session handler...
Applying one-click-instance settings...
System config value one-click-instance set to boolean true
System config value one-click-instance.user-limit set to integer 100
System config value one-click-instance.link set to string https://nextcloud.com/all-in-one/
support already enabled
Adjusting log files...
System config value upgrade.cli-upgrade-link set to string https://github.com/nextcloud/all-in-one/discussions/2726
System config value logfile set to string /var/www/html/data/nextcloud.log
Config value logfile for app admin_audit set to /var/www/html/data/audit.log
System config value updatedirectory set to string /nc-updater
Applying network settings...
System config value allow_local_remote_servers set to boolean true
System config value davstorage.request_timeout set to integer 3600
System config value trusted_domains => 1 set to string cloud.rehrstieg102.de
System config value overwrite.cli.url set to string https://cloud.rehrstieg102.de/
System config value htaccess.RewriteBase set to string /
.htaccess has been updated
System config value dbpersistent set to boolean false
System config value files_external_allow_create_new_local set to boolean false
System config value trusted_proxies => 0 set to string 127.0.0.1
System config value trusted_proxies => 1 set to string ::1
Config value base_endpoint for app notify_push set to 
```

This is my docker-compose.yaml:
```
version: "3.8"

services:
  caddy:
    image: caddy:alpine
    restart: unless-stopped
    container_name: caddy
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./certs:/certs
      - ./config:/config
      - ./data:/data
      - ./sites:/srv
    network_mode: "host"

  nextcloud:
    image: nextcloud/all-in-one:latest
    restart: unless-stopped
    container_name: nextcloud-aio-mastercontainer
    ports:
      - "8080:8080"
    environment:
      - APACHE_PORT=11000
#      - APACHE_IP_BINDING=127.0.0.1 # Should be set when running behind a reverse proxy that is running on the same host. See https://github.com/nextcloud/all-in-one/blob/main/reverse-proxy.md
      # - TALK_PORT=3478 # This allows to adjust the port that the talk container is using.
      - NEXTCLOUD_DATADIR=/mnt/sdb1/nextcloud_aio_data # Allows to set the host directory for Nextcloud's datadir. See https://github.com/nextcloud/all-in-one#how-to-change-the-default-location-of-nextclouds-datadir
      # - NEXTCLOUD_MOUNT=/mnt/ # Allows the Nextcloud container to access the chosen directory on the host. See https://github.com/nextcloud/all-in-one#how-to-allow-the-nextcloud-container-to-access-directories-on-the-$
      # - DOCKER_SOCKET_PATH=/var/run/docker.sock # Needs to be specified if the docker socket on the host is not located in the default '/var/run/docker.sock'. Otherwise mastercontainer updates will fail.
      # - DISABLE_BACKUP_SECTION=true # Setting this to true allows to hide the backup section in the AIO interface.
      - NEXTCLOUD_UPLOAD_LIMIT=10G # Can be adjusted if you need more. See https://github.com/nextcloud/all-in-one#how-to-adjust-the-upload-limit-for-nextcloud
      # - NEXTCLOUD_MAX_TIME=3600 # Can be adjusted if you need more. See https://github.com/nextcloud/all-in-one#how-to-adjust-the-max-execution-time-for-nextcloud
      # - TRUSTED_CACERTS_DIR=/path/to/my/cacerts # CA certificates in this directory will be trusted by the OS of the nexcloud container (Useful e.g. for LDAPS) See See https://github.com/nextcloud/all-in-one#how-to-tr$
      - COLLABORA_SECCOMP_DISABLED=false # Setting this to true allows to disable Collabora's Seccomp feature. See https://github.com/nextcloud/all-in-one#how-to-disable-collaboras-seccomp-feature
     #  - AIO_COMMUNITY_CONTAINERS="vaultwarden pi-hole"
      - NEXTCLOUD_ADDITIONAL_APKS=libreoffice libreoffie-calc libreoffice-lang-de font-terminus font-inconsolata font-dejavu font-noto font-noto-cjk font-awesome font-noto-extra
#imagemagick openjdk11-jre-headless fontconfig
# libreoffice-l10n-de libreoffice-help-de
# libmagickcore-6.q16-6-extra
      - SKIP_DOMAIN_VALIDATION=true
    volumes:
      - nextcloud_aio_mastercontainer:/mnt/docker-aio-config
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:
      - caddy

volumes:
  nextcloud_aio_mastercontainer:
    name: nextcloud_aio_mastercontainer # This line is not allowed to be changed

)
```
