### DISCUSSION TITLE
Can't login to AIO again after Nextcloud install finishes

### DISCUSSION THREAD

**Discussion by zine999** [nextcloud/all-in-one#4059] [Questions] [answered]
### Steps to reproduce

On Fedora 39 using the following `docker-compose.yml`:

```yml
  nextcloud-aio-mastercontainer:
    image: nextcloud/all-in-one:latest 
    init: true
    container_name: nextcloud-aio-mastercontainer
    restart: unless-stopped
    ports:
      - "80:80"
      - "8080:8080"
      - "8443:8443"
    security_opt:
      - label=disable
    logging:
      driver: fluentd
      options:
        tag: "{{.Name}}.log"
    depends_on:
      - logs
    volumes:
      - nextcloud_aio_mastercontainer:/mnt/docker-aio-config
      - /var/run/docker.sock:/var/run/docker.sock:ro
```

I was finally able to get Nextcloud running. I set it up via the AIO on port :8080, which was over HTTPS self-signed. All the containers got setup and running.

Afterward, I tried logging in to the AIO again via the link in `https://<domain>/settings/admin/overview`, which took me to `https://<domain>:8080/api/auth/getlogin?token=<token>`

I was greeted with the error below:

![Screenshot 2024-01-13 at 5 45 28 PM](https://github.com/nextcloud/all-in-one/assets/155118056/74550e3d-baca-4dba-990f-fac566cd61bc)

Now there is no way to access the AIO interface anymore.

Help?

#### Nextcloud AIO version 

Nextcloud Hub 7 (28.0.1)

#### Current channel 

Can't access
