### DISCUSSION TITLE
Backups don't seem to go to the right place...

### DISCUSSION THREAD

**Discussion by zine999** [nextcloud/all-in-one#4072] [Questions] [answered]
Using the AIO interface, I tried creating backups. According to the log output from the backup container, they are being put in `/mnt/borgbackup/borg`:

```
Performing backup...
Starting the backup...
Creating archive at "/mnt/borgbackup/borg::20240116_013337-nextcloud-aio"
------------------------------------------------------------------------------
Repository: /mnt/borgbackup/borg
Archive name: 20240116_013337-nextcloud-aio
Archive fingerprint: 6c607672bb92b49721d0a3fa07d768c7430e6c6183c436c37efa40b1e31b4c2f
Time (start): Tue, 2024-01-16 01:33:38
Time (end):   Tue, 2024-01-16 01:33:52
Duration: 13.67 seconds
Number of files: 28630
Utilization of max. archive size: 0%
------------------------------------------------------------------------------
                       Original size      Compressed size    Deduplicated size
This archive:                1.27 GB            461.60 MB             11.52 MB
All archives:                2.49 GB            887.69 MB            373.13 MB

                       Unique chunks         Total chunks
Chunk index:                   26507                56776
------------------------------------------------------------------------------
BORG_PRUNE_OPTS are --keep-within=7d --keep-weekly=4 --keep-monthly=6
Pruning the archives...
------------------------------------------------------------------------------
                       Original size      Compressed size    Deduplicated size
Deleted data:                    0 B                  0 B                  0 B
All archives:                2.49 GB            887.69 MB            373.13 MB

                       Unique chunks         Total chunks
Chunk index:                   26507                56776
------------------------------------------------------------------------------
Compacting the archives...
Backup finished successfully on 16.01.2024 - 01:33:55 (00 hours 00 minutes 18 seconds).
```

However, the AIO UI says:

> Backups get created in the following directory on the host: /mnt/backup/borg

A contradiction.

Plus, on the host, checking the directory that is mapped to `/mnt/backup` inside of the container, shows that it is empty:

```
-> % tree -a vol/nextcloud
vol/nextcloud
└── backup

2 directories, 0 files
```

So where are the backups going?

Here is the service configuration from my `docker-compose.yml` file:

```yml
  nextcloud-aio-mastercontainer:
    image: nextcloud/all-in-one:latest 
    init: true
    container_name: nextcloud-aio-mastercontainer
    restart: always
    ports:
      - "80:80"
      - "8080:8080"
      - "8443:8443"
    environment:
      - NEXTCLOUD_MOUNT=/mnt/backup
    security_opt:
      - label=disable
    logging:
      driver: fluentd
      options:
        tag: "{{.Name}}.log"
    depends_on:
      - logs
    volumes:
      - nextcloud_aio_mastercontainer:/mnt/docker-aio-config
      - ./vol/nextcloud/backup:/mnt/backup
      - /var/run/docker.sock:/var/run/docker.sock:ro
```

You can see that I have:

```yml
    environment:
      - NEXTCLOUD_MOUNT=/mnt/backup
```

And for the volumes:

```yml
      - ./vol/nextcloud/backup:/mnt/backup
```

So what's going on with the backups? Where are they going and why aren't they going into `/mnt/backup` like AIO claims they are?
