### DISCUSSION TITLE
Nextcloud and Caddy

### DISCUSSION THREAD

**Discussion by ComradDart** [nextcloud/all-in-one#4091] [Questions] [answered]
Hello, I want my nextcloud to be available only via LAN or VPN. So, I’ve installed nextcloud aio and caddy via docker compose via [local instance manual](https://github.com/nextcloud/all-in-one/blob/main/local-instance.md) and given examples of docker compose. So this is my docker-compose:
```
version: "3.8"

services:
  caddy:
    image: caddy:alpine
    restart: unless-stopped
    container_name: caddy
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./certs:/certs
      - ./config:/config
      - ./data:/data
      - ./sites:/srv
    network_mode: "host"

  nextcloud:
    image: nextcloud/all-in-one:latest
    restart: unless-stopped
    container_name: nextcloud-aio-mastercontainer
    ports:
      - "8080:8080"
    environment:
      - APACHE_IP_BINDING=127.0.0.1
      - APACHE_PORT=11000
      - NEXTCLOUD_DATADIR=/mnt/nas 
      - NEXTCLOUD_MOUNT=/mnt/
      - SKIP_DOMAIN_VALIDATION=true
    volumes:
      - nextcloud_aio_mastercontainer:/mnt/docker-aio-config
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:
      - caddy

volumes:
  nextcloud_aio_mastercontainer:
    name: nextcloud_aio_mastercontainer
```

And here is my Caddyfile:
my_server.ddns.net:443 {
    reverse_proxy localhost:11000
}

The main problem is that I can access my nextcloud via Internet. If I close 443 port on my router I get an error with cert. How should I solve it? Caddy and nextcloud are installed on one PC. My router is Xiaomi Redmi AX6S with openwrt
