### DISCUSSION TITLE
502 Bad Gateway: AIO + Nginx Proxy Manager

### DISCUSSION THREAD

**Discussion by bremme** [nextcloud/all-in-one#4125] [Questions] [answered]
I'm probably doing something wrong, but can't figure it out. I'm trying to access nextcloud (aio) in combination with Nginx Proxy Manager.

I followed the guide here: https://github.com/nextcloud/all-in-one/blob/main/reverse-proxy.md.

This is my Docker compose:

```yaml
services:

  nginx-proxy-manager:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: nginx-proxy-manager
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ${SSD_VOLUMES}/nginx-proxy-manager/data:/data
      - ${SSD_VOLUMES}/nginx-proxy-manager/letsencrypt:/etc/letsencrypt

  nextcloud-aio-mastercontainer:
    image: nextcloud/all-in-one:latest
    init: true
    container_name: nextcloud-aio-mastercontainer # This line is not allowed to be changed as otherwise AIO will not work correctly
    volumes:
      - nextcloud_aio_mastercontainer:/mnt/docker-aio-config # This line is not allowed to be changed as otherwise the built-in backup solution will not work
      - /var/run/docker.sock:/var/run/docker.sock:ro # May be changed on macOS, Windows or docker rootless. See the applicable documentation. If adjusting, don't forget to also set 'WATCHTOWER_DOCKER_SOCKET_PATH'!
    ports:
      # - 80:80 # Can be removed when running behind a web server or reverse proxy (like Apache, Nginx, Cloudflare Tunnel and else). See https://github.com/nextcloud/all-in-one/blob/main/reverse-proxy.md
      - 8080:8080
      # - 8443:8443 # Can be removed when running behind a web server or reverse proxy (like Apache, Nginx, Cloudflare Tunnel and else). See https://github.com/nextcloud/all-in-one/blob/main/reverse-proxy.md
      # Not in the documentation, but I tried to to check if it would solve my issues?
      - 11000:11000
    environment:
      - APACHE_PORT=11000 # Is needed when running behind a web server or reverse proxy (like Apache, Nginx, Cloudflare Tunnel and else). See https://github.com/nextcloud/all-in-one/blob/main/reverse-proxy.md
      - APACHE_IP_BINDING=0.0.0.0 # Should be set when running behind a web server or reverse proxy (like Apache, Nginx, Cloudflare Tunnel and else) that is running on the same host. See https://github.com/nextcloud/all-in-one/blob/main/reverse-proxy.md
      - BORG_RETENTION_POLICY=--keep-within=7d --keep-weekly=4 --keep-monthly=6 # Allows to adjust borgs retention policy. See https://github.com/nextcloud/all-in-one#how-to-adjust-borgs-retention-policy
      - NEXTCLOUD_DATADIR=nextcloud_aio_nextcloud_datadir # Allows to set the host directory for Nextcloud's datadir. ⚠️⚠️⚠️ Warning: do not set or adjust this value after the initial Nextcloud installation is done! See https://github.com/nextcloud/all-in-one#how-to-change-the-default-location-of-nextclouds-datadir
    restart: unless-stopped
```

Nginx Proxy Manager configuration
![image](https://github.com/nextcloud/all-in-one/assets/6715707/ffba7abf-079b-4f47-a930-a767146a0b4a)

![image](https://github.com/nextcloud/all-in-one/assets/6715707/bf9156a0-0782-44ac-94fe-045939a3676f)

![image](https://github.com/nextcloud/all-in-one/assets/6715707/8dfc6a18-0e72-4bd5-aeea-fdf9de0bfba1)

Container output:

```shell
 ✔ Container nextcloud-aio-mastercontainer  Created                                                                                                                                                                            0.0s 
Attaching to nextcloud-aio-mastercontainer
nextcloud-aio-mastercontainer  | Initial startup of Nextcloud All-in-One complete!
nextcloud-aio-mastercontainer  | You should be able to open the Nextcloud AIO Interface now on port 8080 of this server!
nextcloud-aio-mastercontainer  | E.g. https://internal.ip.of.this.server:8080
nextcloud-aio-mastercontainer  | 
nextcloud-aio-mastercontainer  | If your server has port 80 and 8443 open and you point a domain to your server, you can get a valid certificate automatically by opening the Nextcloud AIO Interface via:
nextcloud-aio-mastercontainer  | https://your-domain-that-points-to-this-server.tld:8443
nextcloud-aio-mastercontainer  | [28-Jan-2024 13:33:03] NOTICE: fpm is running, pid 109
nextcloud-aio-mastercontainer  | [28-Jan-2024 13:33:03] NOTICE: ready to handle connections
nextcloud-aio-mastercontainer  | {"level":"info","ts":1706448783.8229678,"msg":"using provided configuration","config_file":"/Caddyfile","config_adapter":""}
nextcloud-aio-mastercontainer  | [Sun Jan 28 13:33:03.835421 2024] [mpm_event:notice] [pid 104:tid 140097577843528] AH00489: Apache/2.4.58 (Unix) OpenSSL/3.1.4 configured -- resuming normal operations
nextcloud-aio-mastercontainer  | [Sun Jan 28 13:33:03.836589 2024] [core:notice] [pid 104:tid 140097577843528] AH00094: Command line: 'httpd -D FOREGROUND
```

I guess I don't fully understand how its supposed to work. For every other application I would just fill in the `container_name` under the host field. But for AIO it seems that I'm trying to connect using the host. That's why I though that I should perhaps expose 11000.

But if I navigate to host-ip:11000 I get nothing, I would have expected to get to nextcloud. If I go to host-ip:8080 I do get the nextcloud interface with a self signed certificate.

I also logged on to the container to but I could not find the Apache config which Listens on 11000.

While writing this post, perhaps this whole thing should not work yet? Perhaps I need to finish the installation first? Gonna try that right now. Will remove/close this if it solves my issues.
