### DISCUSSION TITLE
Nexcloud AIO with traefik as reverse proxy - 502

### DISCUSSION THREAD

**Discussion by sorentorp** [nextcloud/all-in-one#4176] [Questions] [answered]
Hi. I'm eager to get Nextcloud AIO up and running, using my existing Traefik setup, with Cloudflare af DNS provider. However I keep getting 502'ed when trying to access the sollution. I have access to the local setup-page. Any hints or things to test are welcome, see my problem and configuration below.

Any help will result in input to improve the Nextcloud AIO Reverse proxy guide, which I have followed to the best of my knowledge. Similar threads have not helped me towards a sollution, or lack documentation for the actualt sollution.
  
![Screenshot 2024-02-05 10 04 53](https://github.com/nextcloud/all-in-one/assets/4117997/4783924a-5639-4a50-85c8-12ca4296cebc)

![Screenshot 2024-02-05 10 05 53](https://github.com/nextcloud/all-in-one/assets/4117997/c4cc66c6-cfda-4364-8d8a-2d296bc34e13)

> docker exec traefik nc -z 0.0.0.0 11000; echo $?
> 1

> sudo netstat -tulpn
> Active Internet connections (only servers)
> Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
> xxxxxx
> tcp        0      0 0.0.0.0:11000           0.0.0.0:*               LISTEN      2126942/docker-prox 
> xxxx

traefik docker compose
> services:
>   nextcloud-aio-mastercontainer:
>     image: nextcloud/all-in-one:latest
>     init: true
>     restart: always
>     container_name: nextcloud-aio-mastercontainer
>     volumes:
>       - nextcloud_aio_mastercontainer:/mnt/docker-aio-config 
>       - /var/run/docker.sock:/var/run/docker.sock:ro 
>     ports:
>       - 8080:8080
>     environment:
>       - APACHE_PORT=11000 
>       - APACHE_IP_BINDING=127.0.0.1 
> volumes:
>   nextcloud_aio_mastercontainer:
>     name: nextcloud_aio_mastercontainer 
> ----- rest left out ------

traefik.yml
> entryPoints:
>   http:
>     address: ":80"                            # Create the HTTP entrypoint on port 80
>     http:
>       redirections:                           # HTTPS redirection (80 to 443)
>         entryPoint:
>           to: "https"                         # The target element
>           scheme: "https"                     # The redirection target scheme
>   https:
>     address: ":443"                           # Create the HTTPS entrypoint on port 443
> 
> api:
>   dashboard: true
> 
> 
> serversTransport:
>   insecureSkipVerify: 'true'
> providers:
>   docker:
>     endpoint: "unix:///var/run/docker.sock"
>     exposedByDefault: 'false'
>   file:
>     directory: "/etc/traefik/" # Adjust the path according your needs.
>     watch: true
> 
> certificatesResolvers:
>   cloudflare:
>     acme:
>       email: xxxxx.xxxx@gmail.com
>       storage: acme.json
>       dnsChallenge:
>         provider: cloudflare
>         resolvers:
>           - "1.1.1.1:53"
>           - "1.0.0.1:53"
> 

nextcloud.yml

> http:
>   routers:
>     nextcloud:
>       rule: "Host(`nextcloud. xxxxxxxx.dk`)"
>       entrypoints:
>         - "https"
>       service: nextcloud
>       middlewares:
>         - nextcloud-chain
>       tls:
>         certresolver: "cloudflare"
> 
>   services:
>     nextcloud:
>       loadBalancer:
>         servers:
>           - url: "http://127.0.0.1:11000" # Use the host's IP address if Traefik runs outside the host network
> 
>   middlewares:
>     nextcloud-secure-headers:
>       headers:
>         hostsProxyHeaders:
>           - "X-Forwarded-Host"
>         referrerPolicy: "same-origin"
> 
>     https-redirect:
>       redirectscheme:
>         scheme: https 
> 
>     nextcloud-chain:
>       chain:
>         middlewares:
>           - https-redirect
>           - nextcloud-secure-headers

nextcloud docker compose

> services:
>   nextcloud-aio-mastercontainer:
>     image: nextcloud/all-in-one:latest
>     init: true
>     restart: always
>     container_name: nextcloud-aio-mastercontainer
>     volumes:
>       - nextcloud_aio_mastercontainer:/mnt/docker-aio-config 
>       - /var/run/docker.sock:/var/run/docker.sock:ro 
>     ports:
>       - 8080:8080
>     environment:
>       - APACHE_PORT=11000 
>       - APACHE_IP_BINDING=127.0.0.1 
> volumes:
>   nextcloud_aio_mastercontainer:
>     name: nextcloud_aio_mastercontainer

**Comment by szaimen** [comment]
Hi, can you follow https://github.com/nextcloud/all-in-one/blob/main/reverse-proxy.md#6-how-to-debug-things?

**Comment by sorentorp** [comment]
Yes, I have done all those things. No change.

**Comment by szaimen** [comment]
> - APACHE_IP_BINDING=127.0.0.1

You still have this in it which indicated that you havent actually followed https://github.com/nextcloud/all-in-one/blob/main/reverse-proxy.md#6-how-to-debug-things.

> - url: "http://0.0.0.0:11000"

Also how should that work? Please follow https://github.com/nextcloud/all-in-one/blob/main/reverse-proxy.md#6-how-to-debug-things

**Comment by sorentorp** [comment]
I'm sorry. I have tried the other way around, so that was a mistake. I corrected above and in my installation. No change.

  services:
    nextcloud:
      loadBalancer:
        servers:
          - url: "http://127.0.0.1:11000"

**Reply by szaimen** [reply]
> - url: "http://127.0.0.1:11000"

This can only work if the traefik container runs with `network_mode: host`. Does it do that?

**Reply by sorentorp** [reply]
Hi. No, it does now run as Host - and it is not possible on this machine. 

What should my config be, if I'm not running it as host?

**Reply by szaimen** [reply]
See 
![image](https://github.com/nextcloud/all-in-one/assets/42591237/5245d052-1c9f-4c7c-9b95-6cb107f6c303)

**Reply by sorentorp** [reply]
Okay, that got me some of the way - almost there I guess. 

![image](https://github.com/nextcloud/all-in-one/assets/4117997/27c06545-1e9a-4886-889e-2c0ddc4b4ed7)

traefik-nextcloud.yml
```
http:
  routers:
    nextcloud:
      rule: "Host(`nextcloud.xxxxxxxxxxx.dk`)"
      entrypoints:
        - "https"
      service: nextcloud
      middlewares:
        - nextcloud-chain
      tls:
        certresolver: "cloudflare"

  services:
    nextcloud:
      loadBalancer:
        servers:
          - url: "http://172.27.0.12:11000" 

  middlewares:
    nextcloud-secure-headers:
      headers:
        hostsProxyHeaders:
          - "X-Forwarded-Host"
        referrerPolicy: "same-origin"

    https-redirect:
      redirectscheme:
        scheme: https 

    nextcloud-chain:
      chain:
        middlewares:
          - https-redirect
          - nextcloud-secure-headers
```

Now I'm getting "Gateway time-out Error code 504"
