### DISCUSSION TITLE
Multiple issues reported on new instance

### DISCUSSION THREAD

**Discussion by maffo999** [nextcloud/all-in-one#4207] [Questions] [answered]
Hello all,
I have deployed a new instance of Nextcloud AIO on a VPS using Apache2 as web server for reverse proxy.
Everything seems ok besides the fact that I keep getting setup errors and warnings, i.e.:

- Error occurred while checking server setup

- Your web server is not properly set up to resolve "/ocm-provider/". This is most likely related to a web server configuration that was not updated to deliver this folder directly. Please compare your configuration against the shipped rewrite rules in ".htaccess" for Apache or the provided one in the documentation for Nginx at it's [documentation page ↗](https://docs.nextcloud.com/server/27/go.php?to=admin-nginx). On Nginx those are typically the lines starting with "location ~" that need an update.

- Your web server is not properly set up to resolve "/.well-known/webfinger". Further information can be found in the [documentation ↗](https://docs.nextcloud.com/server/27/go.php?to=admin-setup-well-known-URL).

- Your web server is not properly set up to resolve "/.well-known/caldav". Further information can be found in the [documentation ↗](https://docs.nextcloud.com/server/27/go.php?to=admin-setup-well-known-URL).

- Your web server is not properly set up to resolve "/.well-known/carddav". Further information can be found in the [documentation ↗](https://docs.nextcloud.com/server/27/go.php?to=admin-setup-well-known-URL).

Interestingly, refreshing the page, might make some of these messages disappear. I have refreshed the page just after getting the messages above and received a different outcome:

- Your web server is not properly set up to resolve "/.well-known/carddav". Further information can be found in the [documentation ↗](https://docs.nextcloud.com/server/27/go.php?to=admin-setup-well-known-URL).

- Your installation has no default phone region set. This is required to validate phone numbers in the profile settings without a country code. To allow numbers without a country code, please add "default_phone_region" with the respective [ISO 3166-1 code ↗](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2#Officially_assigned_code_elements) of the region to your config file.

### Steps to reproduce
1. Deploy Nextcloud-AIO with Apache host/port set to 127.0.0.1:11000
2. Configure Apache2 as reverse proxy with the example [here](https://github.com/nextcloud/all-in-one/blob/main/reverse-proxy.md)
3. Review "Security & Setup warnings" in the Overview section of the asministrative settings

### Expected behavior
If those errors are genuine, the same errors should continue to appear upon every refresh; otherwise they should not appear at all.

### Actual behavior
Random warnings and errors are thrown without any sort of consistency (refresh the page and the errors/warnings will change) which makes it impossible to understand if an issue is genuine and where it lies.

### Host OS 
Debian 12 bookworm

#### Nextcloud AIO version
[Nextcloud Hub 6](https://nextcloud.com/) (27.1.5)

#### Current channel
stable

#### Other valuable info
I had to disable IPv6 for the nextcloud-aio network as leaving it on would make the whole thing unusable (hanging, long response time, multiple name error resolution) but the problem was present also with IPv6 enabled.
There are also multiple entries in the log section which I'm not sure they might be relevant, but here's a screenshot of them
![image](https://github.com/nextcloud/all-in-one/assets/29754114/aef5d03d-92e6-4484-8e35-85684f7727ab)

**Comment by maffo999** [comment]
Forgot to mention before, but it's also very common for pages to not load with the following error. Refreshing the page will work but it clearly makes me think there is something wrong in the containers
![image](https://github.com/nextcloud/all-in-one/assets/29754114/c41aadc7-6047-4ac5-8e10-483792c874a6)

**Comment by maffo999** [comment]
Not sure why this was converted to an answer since it's actually an issue which makes NC basically unusable from browsers and completely unusable from other clients (e.g. Android client or Gnome/KDE online account features).
I would appreciate if this would be treated as an issue since it's really what it is about.

**Comment by szaimen** [comment]
Hi, it sounds like you are running into this: https://github.com/nextcloud/all-in-one/discussions/2557

**Comment by maffo999** [comment]
I believe to have solved the problem, not really due to #2557 but that gave me an idea.
I recall when I started to configure this server, I wanted to use IPv4 only for Docker and I deployed NC with a compose file similar to this (just relevant bits - as you can see I did not have any network specified)
```
services:                                                                                                                                                                                                                                   
  nextcloud:                                                                                                                                                                                                                                
    image: nextcloud/all-in-one:latest                                                                                                                                                                                                      
    restart: always                                                                                                                                                                                                                         
    container_name: nextcloud-aio-mastercontainer # This line is not allowed to be changed as otherwise AIO will not work correctly                                                                                                         
    volumes:                                                                                                                                                                                                                                
      - nextcloud_aio_mastercontainer:/mnt/docker-aio-config # This line is not allowed to be changed as otherwise the built-in backup solution will not work                                                                               
      - /var/run/docker.sock:/var/run/docker.sock:ro # May be changed on macOS, Windows or docker rootless. See the applicable documentation. If adjusting, don't forget to also set 'WATCHTOWER_DOCKER_SOCKET_PATH'!                       
    ports:                                                                                                                                                                                                                                  
      - 8081:8080                                                                                                                                                                                                                           
    environment: # Is needed when using any of the options below                                                                                                                                                                            
      - APACHE_PORT=11000 # Is needed when running behind a web server or reverse proxy (like Apache, Nginx, Cloudflare Tunnel and else). See https://github.com/nextcloud/all-in-one/blob/main/reverse-proxy.md                            
      - APACHE_IP_BINDING=127.0.0.1 # Should be set when running behind a web server or reverse proxy (like Apache, Nginx, Cloudflare Tunnel and else) that is running on the same host. See https://github.com/nextcloud/all-in-one/blob/main/reverse-proxy.md                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
                                                                                                                                                                                                                                            
volumes:                                                                                                                                                                                                                                      nextcloud_aio_mastercontainer:                                                                                                                                                                                                            
    name: nextcloud_aio_mastercontainer # This line is not allowed to be changed as otherwise the built-in backup solution will not work                                                                                                    
```

After a few days I started deploying other docker compose project which required IPv6, so I enabled it in docker, destroyed all NC containers and modified docker-compose.yml with the following:
```
services:                                                                                                                                                                                                                                   
  nextcloud:                                                                                                                                                                                                                                
    image: nextcloud/all-in-one:latest                                                                                                                                                                                                      
    restart: always                                                                                                                                                                                                                         
    container_name: nextcloud-aio-mastercontainer # This line is not allowed to be changed as otherwise AIO will not work correctly                                                                                                         
    volumes:                                                                                                                                                                                                                                
      - nextcloud_aio_mastercontainer:/mnt/docker-aio-config # This line is not allowed to be changed as otherwise the built-in backup solution will not work                                                                               
      - /var/run/docker.sock:/var/run/docker.sock:ro # May be changed on macOS, Windows or docker rootless. See the applicable documentation. If adjusting, don't forget to also set 'WATCHTOWER_DOCKER_SOCKET_PATH'!                       
    ports:                                                                                                                                                                                                                                  
      - 8081:8080                                                                                                                                                                                                                           
    environment: # Is needed when using any of the options below                                                                                                                                                                            
      - APACHE_PORT=11000 # Is needed when running behind a web server or reverse proxy (like Apache, Nginx, Cloudflare Tunnel and else). See https://github.com/nextcloud/all-in-one/blob/main/reverse-proxy.md                            
      - APACHE_IP_BINDING=127.0.0.1 # Should be set when running behind a web server or reverse proxy (like Apache, Nginx, Cloudflare Tunnel and else) that is running on the same host. See https://github.com/nextcloud/all-in-one/blob/main/reverse-proxy.md                                                                                                                                                                                                                                                                                                                                                                                                                                          
    **networks: # Is needed when you want to create the nextcloud-aio network with ipv6-support using this file, see the network config at the bottom of the file                                                                            
      - nextcloud-aio # Is needed when you want to create the nextcloud-aio network with ipv6-support using this file, see the network config at the bottom of the file**                                                                    
                                                                                                                                                                                                                                            
volumes:                                                                                                                                                                                                                                      nextcloud_aio_mastercontainer:                                                                                                                                                                                                            
    name: nextcloud_aio_mastercontainer # This line is not allowed to be changed as otherwise the built-in backup solution will not work                                                                                                    
                                                                                                                                                                                                                                                                                                                                      **networks:                                                                                                                                                                                                                                  
  nextcloud-aio:                                                                                                                                                                                                                           
    name: nextcloud-aio # This line is not allowed to be changed as otherwise the created network will not be used by the other containers of AIO                                                                                          
    driver: bridge                                                                                                                                                                                                                         
    enable_ipv6: false                                                                                                                                                                                                                     
    ipam:                                                                                                                                                                                                                                  
      driver: default                                                                                                                                                                                                                      
      config:                                                                                                                                                                                                                              
    - subnet: fd12:3456:789a:2::/64 # IPv6 subnet to use**        
```

After changing the docker compose file I manually stopped and removed all NC containers and rebooted the machine, re-deployed the containers and that's when I started having issues.

Today while doing some other troubleshooting I noticed there were 2 different NC networks in docker: nextcloud_default (created  when no network is specified in the compose file) and nextcloud-aio (created by the compose file).
```
root@vps:/srv/nextcloud# docker network ls | grep -i next                                                                                                                                                                                          
NETWORK ID     NAME                    DRIVER    SCOPE                                                                                                                                                                                                                                                                                                                                                                          
fbac2301dd01   nextcloud-aio           bridge    local                                                                                                                                                                                      
4a33ff7e5036   nextcloud_default       bridge    local
```
I then inspected those network and found - quite shockingly - that the master container was actually connected to both!
```
root@vps:/srv/nextcloud# docker network inspect nextcloud_default                                                                                                                                                                      
[                                                                                                                                                                                                                                           
    {                                                                                                                                                                                                                                       
        "Name": "nextcloud_default",                                                                                                                                                                                                        
        "Id": "4a33ff7e5036022dd2d1a223d4f49bae6fdc61eed6a603f111bb113da4f0d17a",                                                                                                                                                           
        "Created": "2024-02-13T14:44:54.764921924+01:00",                                                                                                                                                                                   
        "Scope": "local",                                                                                                                                                                                                                   
        "Driver": "bridge",                                                                                                                                                                                                                 
        "EnableIPv6": false,                                                                                                                                                                                                                
        "IPAM": {                                                                                                                                                                                                                           
            "Driver": "default",                                                                                                                                                                                                            
            "Options": null,                                                                                                                                                                                                                
            "Config": [                                                                                                                                                                                                                     
                {                                                                                                                                                                                                                           
                    "Subnet": "172.22.0.0/16",                                                                                                                                                                                              
                    "Gateway": "172.22.0.1"                                                                                                                                                                                                 
                }                                                                                                                                                                                                                           
            ]
        },
        "Internal": false,
        "Attachable": false,
        "Ingress": false,
        "ConfigFrom": {
            "Network": ""
        },
        "ConfigOnly": false,
        "Containers": {
            "ffa5ecb1931a5d755e6f26816c2dcdbc7970bd041575fdc2daa5965660dc5d1d": {
                "Name": "nextcloud-aio-mastercontainer",
                "EndpointID": "8ff2e306f15d4fc2606f4e5dcf782313f93bba7506e76220995ff06f47952df2",
                "MacAddress": "02:42:ac:16:00:02",
                "IPv4Address": "172.22.0.2/16",
                "IPv6Address": ""
            }
        },
        "Options": {},
        "Labels": {
            "com.docker.compose.network": "default",
            "com.docker.compose.project": "nextcloud",
            "com.docker.compose.version": "2.24.5"
        }
    }
]
root@vps:/srv/nextcloud# docker network inspect nextcloud-aio                                                                                                                                                                          
[                                                                                                                                                                                                                                           
    {                                                                                                                                                                                                                                       
        "Name": "nextcloud-aio",                                                                                                                                                                                                            
        "Id": "fbac2301dd018b4dc28019b6dafe996d8d6f73e29be4119c9452b289169c6805",                                                                                                                                                           
        "Created": "2024-02-13T14:44:59.63291353+01:00",                                                                                                                                                                                    
        "Scope": "local",                                                                                                                                                                                                                   
        "Driver": "bridge",                                                                                                                                                                                                                 
        "EnableIPv6": false,                                                                                                                                                                                                                
        "IPAM": {                                                                                                                                                                                                                           
            "Driver": "default",                                                                                                                                                                                                            
            "Options": null,
            "Config": [
                {
                    "Subnet": "172.23.0.0/16",
                    "Gateway": "172.23.0.1"
                }
            ]
        },
        "Internal": false,
        "Attachable": false,
        "Ingress": false,
        "ConfigFrom": {
            "Network": ""
        },
        "ConfigOnly": false,
        "Containers": {
            "ffa5ecb1931a5d755e6f26816c2dcdbc7970bd041575fdc2daa5965660dc5d1d": {
                "Name": "nextcloud-aio-mastercontainer",
                "EndpointID": "5fdcda8b1f4a2ac70b1ca70c6b42f33f16957e727e3875ffeef82a9b18ffd626",
                "MacAddress": "02:42:ac:17:00:02",
                "IPv4Address": "172.23.0.2/16",
                "IPv6Address": ""
            }
        },
        "Options": {},
        "Labels": {}
    }
]
```

I took down all containers and destroyed them, then destroyed both networks and restarted everything: no more issues!!
Now, I'm not really sure why the master container would still bind to the nextcloud_default network when nextcloud-aio is specified in the composer file. Is this an expected behavior?
