### DISCUSSION TITLE
PHP Version stuck on 8.1.27

### DISCUSSION THREAD

**Discussion by FaySmash** [nextcloud/all-in-one#4278] [Questions] [answered]
Hello there, I just spun up a NC AIO instance but noticed that I can't use some extensions, as they require PHP >= 8.2. I Already switched to the beta Version, but the instance still runs on PHP 8.1.27:

```
docker exec --user www-data -it nextcloud-aio-nextcloud php -v
PHP 8.1.27 (cli) (built: Jan 27 2024 05:17:38) (NTS)
```

```
docker exec --user www-data -it nextcloud-aio-nextcloud php occ -V
28.0.2
```

```
services:
  nextcloud-aio-mastercontainer:
    container_name: nextcloud-aio-mastercontainer
    env_file: stack.env
    image: nextcloud/all-in-one:beta
    init: true
    ports:
      - 11000:8080
    restart: unless-stopped
    volumes:
      - nextcloud_aio_mastercontainer:/mnt/docker-aio-config
      - /var/run/docker.sock:/var/run/docker.sock:ro

volumes:
  nextcloud_aio_mastercontainer:
    name: nextcloud_aio_mastercontainer
```

```
AIO_DISABLE_BACKUP_SECTION=true
APACHE_PORT=12000
NEXTCLOUD_UPLOAD_LIMIT=1000G
NEXTCLOUD_MAX_TIME=3600
NEXTCLOUD_MEMORY_LIMIT=1024M
NEXTCLOUD_ADDITIONAL_APKS=imagemagick
NEXTCLOUD_ADDITIONAL_PHP_EXTENSIONS=imagick
PHP_URL=https://www.php.net/distributions/php-8.2.16.tar.xz
PHP_VERSION=8.2.16
```

Is this expected behavior? Can I force a PHP Upgrade somehow?

Thanks in advance
