### DISCUSSION TITLE
NextPush uses 33% of battery over 2 hours.

### DISCUSSION THREAD

**Discussion by Handrail9** [nextcloud/all-in-one#4303] [Questions] [answered]
Hello, I am trying to troubleshoot why NextPush uses so much battery on my phone. I have been looking into already opened issues/discussions/forum posts and am really struggling to figure out how to fix this. I tried increasing the timeout to 10 minutes as shown on the NextPush code repo, but that appears to have stopped me from being able to connect to Nextcloud a all? I'm using traefik. The reason I ask here is because it seems like the [dev may think it will be better to ask here](https://codeberg.org/NextPush/nextpush-android/issues/4#issuecomment-1624757)? Any help figuring out how to properly configure this is appreciated. :)
P.S.
Here is the traefik config I tried, i also tried commenting out each one because I'm not sure if one or more of them isn't needed.
```
serversTransport:
  forwardingTimeouts:
    dialTimeout: 10m
    responseHeaderTimeout: 10m
    idleConnTimeout: 10m
```

EDIT: I found this 
```
    transport:
      respondingTimeouts:
        readTimeout: 10m
        writeTimeout: 10m
        idleTimeout: 10m
```
which goes under the entrypoints which looks similar to the NGINX recommended settings. Will close if this fixes the issue.

EDIT 2: It did not fix the issue. It almost looks like it's worse now.
![image](https://github.com/nextcloud/all-in-one/assets/86343914/70b3f49f-19ae-4794-af11-15befcd97cb9)
