### DISCUSSION TITLE
Am i forced to use "nextcloud_aio_mastercontainer" volume ?

### DISCUSSION THREAD

**Discussion by fabiencharrasse** [nextcloud/all-in-one#4355] [Questions] [answered]
Hello,

Here is my compose file : 

```
services:
  nextcloud-aio-mastercontainer:
    image: nextcloud/all-in-one:latest
    init: true
    restart: always
    container_name: nextcloud-aio-mastercontainer 
    volumes:
      - /home/myuser/docker/nextcloud/:/mnt/docker-aio-config 
      - /var/run/docker.sock:/var/run/docker.sock:ro 
    ports:
      - 7480:80
      - 7488:8080
      - 7443:8443 
    environment: 
      - AIO_DISABLE_BACKUP_SECTION=true 
      - APACHE_PORT=11000 


#volumes: 
  #nextcloud_aio_mastercontainer:
    #name: nextcloud_aio_mastercontainer 

networks:
  default:
    external:
      name: my-network
```

I deleted the comments for readability. I only want to use the volume "/home/myuser/docker/nextcloud/" and not use "nextcloud_aio_mastercontainer" (i commented it), is this possible?
Currently I get the following error:
```
It seems like you did not give the mastercontainer volume the correct name? (The 'nextcloud_aio_mastercontainer' volume was not found.)
Using a different name is not supported since the built-in backup solution will not work in that case!
```

But I don't want to use the integrated backup solution, already saving everything in /home/myuser/docker (where the configuration of all my other services is located.

Thanks for your help.
