### DISCUSSION TITLE
Best practices for mounting external storage SFTP (local)?

### DISCUSSION THREAD

**Discussion by leoniscsem** [nextcloud/all-in-one#4485] [Questions] [answered]
**Preface**: I am a complete idiot when it comes to Docker.

I am using docker compose to run the Nextcloud AIO, an there are certain local directories I want to mount via admin UI as SFTP storages. Directory structure looks like this:

```
/srv/nextcloud/
|_ docker-compose.yml
|_ nextcloud data directory #as defined in the yml
|_ local storage
    |_  subdir 1
    |_  subdir 2
```

The local directories have permissions permissions set to UNIX user accordingly, SFTP configuration works fine so far. As for the`Ḩost`I enter the Docker bridge IP, e.g. `172.18.0.1`. This is where my problem starts: Whenever I restart the containers (`docker compose up -d`), the bridge IPs also change, resulting in an error when mounting the directories.

Is there a smarter way to mount the local directories locally in a "dockerish way"? The reason why we have to mount the directories via the adminUI is to assign group ownership to certain LDAP/Nextcloud groups.
Should I possibly add any Docker network definition in the `docker-compose.yml`? If so, how/what/where?
Can I define the bridge IP somewhere?

**Comment by szaimen** [comment, marked as answer]
Hi, better would be using this: https://github.com/nextcloud/all-in-one?tab=readme-ov-file#how-to-allow-the-nextcloud-container-to-access-directories-on-the-host

**Comment by leoniscsem** [comment]
As stated above, I am not familiar with Docker environments, and the `docker-compose.yml` left me a bit confused. Defining thes volumes would take place in which section? The top part reads the following volumes:

```yml
services:
  nextcloud-aio-mastercontainer:
    image: nextcloud/all-in-one:latest
    init: true
    restart: always
    container_name: nextcloud-aio-mastercontainer
    volumes:
      - nextcloud_aio_mastercontainer:/mnt/docker-aio-config
      - /var/run/docker.sock:/var/run/docker.sock:ro
```

Yet below is the separate section for volumes:

```yml
volumes: 
  nextcloud_aio_mastercontainer:
    name: nextcloud_aio_mastercontainer 
```

Let's say my local directories are `/srv/nextcloud/local/folder1` and `/srv/nextcloud/local/folder2`, and I want to define the mounts in the container as:

```yml
    volumes:
      - /srv/nextcloud/local/folder1:/mnt/folder1
      - /srv/nextcloud/local/folder2:/mnt/folder2
```

Do these volume definitions go in the top section, or do they need a separate volumes definition in the lower section? The description in the initial setup guide only covers mounting the directories via a Docker command, whereas I am trying to find a solution do go with docker compoese.
