### DISCUSSION TITLE
The www-data user doesn't seem to have access rights in the datadir.

### DISCUSSION THREAD

**Discussion by AlexHuebi** [nextcloud/all-in-one#4554] [Questions] [answered]
Hi, 
I am currently trying to set up Nextcloud AIO but I've run into the issue that when AIO tries to start the Nextcloud Container, it just throws the following error message:

```
Connection to nextcloud-aio-database (172.27.0.3) 5432 port [tcp/postgresql] succeeded!
+ '[' -f /dev-dri-group-was-added ']'
++ find /dev -maxdepth 1 -mindepth 1 -name dri
+ '[' -n '' ']'
+ set +x
chown: changing ownership of '/mnt/ncdata': Operation not permitted
chmod: changing permissions of '/mnt/ncdata': Operation not permitted
rm: cannot remove '/mnt/ncdata/this-is-a-test-file': Permission denied
The www-data user doesn't seem to have access rights in the datadir.
Most likely are the files located on a drive that does not follow linux permissions.
Please adjust the permissions like mentioned below.
The found permissions are:
65534:65534 754
(userID:groupID permissions)
but they should be:
33:0 750
(userID:groupID permissions)
Also make sure that the parent directories on the host of the directory that you've chosen as datadir are publicly readable with e.g. 'sudo chmod +r /mnt' (adjust the command accordingly to your case) and the same for all subdirectories.
Additionally, if you want to use a Fuse-mount as datadir, set 'allow_other' as additional mount option.
For SMB/CIFS mounts as datadir, see https://github.com/nextcloud/all-in-one#can-i-use-a-cifssmb-share-as-nextclouds-datadir
```

The used compose file is this: 
```yml
services:
  nextcloud-aio-mastercontainer:
    image: nextcloud/all-in-one:latest
    init: true
    restart: unless-stopped
    container_name: nextcloud-aio-mastercontainer
    volumes:
      - nextcloud_aio_mastercontainer:/mnt/docker-aio-config
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 8080:8080
    environment:
      - NEXTCLOUD_UPLOAD_LIMIT=64G
      - NEXTCLOUD_MEMORY_LIMIT=2048M
      - NEXTCLOUD_DATADIR=/mnt/data0/nc-root/data
      - NEXTCLOUD_MOUNT=/mnt/data0/nc-root
      - APACHE_PORT=80


volumes:
  nextcloud_aio_mastercontainer:
    name: nextcloud_aio_mastercontainernot work
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/mnt/data0/nextcloud-mastercontainer'
```

The Nextcloud container didn't write anything into the mount drive yet so the folder structure is empty
```
├── nc-root
    └── data
```

and the permissions should be set as needed.
```
root@docker-nextcloud:/mnt/data0/nc-root# ls -la
total 12
drwxr-xr-- 3   32 root 4096 Apr 16 22:03 .
drwxr-x--- 5 root root 4096 Apr 16 22:02 ..
drwxr-xr-- 2   32 root 4096 Apr 16 22:03 data
```

The whole setup is running inside a clean Debian Cloud VM instance.
So there shouldn't be any issues.
But what did I miss during the setup? 
I noticed that the userID:groupID permissions are different but how do I fix that? 
Thanks for any help!
