### DISCUSSION TITLE
Is it possible to use Nextcloud-AIO's Watchtower for external containers?

### DISCUSSION THREAD

**Discussion by b9AcE** [nextcloud/all-in-one#4561] [Questions] [answered]
Is it possible to use the Watchtower container which is already integrated into Nextcloud-AIO (and working fine for me) to update also containers that are not part of Nextcloud-AIO running on the same host?
It seems to me it should be unnecessary to run two Watchtower-containers, one of Nextcloud-AIO and one for all other containers, but I don't know where one would configure Nextcloud-AIO's one to also cover some specific other containers (e.g. Jellyfin, Navidrome, etc) without risk of that Watchtower-configuration being overwritten by some Nextcloud-AIO update.

**Comment by szaimen** [comment]
> Is it possible to use Nextcloud-AIO's Watchtower for external containers?

It isnt

**Comment by banigithub-2** [comment, marked as answer]
You sort of can; I sort of do.  
You need to define a WATCHTOWER_SCOPE for the one that isn't the AIO instance (e.g. "WATCHTOWER_SCOPE"="not-nextcloud"), and on the AIO instance set it as "WATCHTOWER_SCOPE"="none".  They will then work nicely with each other.
The problem is that you have to re-add the "WATCHTOWER_SCOPE"="none" to the AIO instance every time it is updated.  Yes, that does get tiring.
I'm not the brightest, so if someone has a better idea, I'm very happy to hear it!

**Reply by szaimen** [reply]
> if someone has a better idea, I'm very happy to hear it!

Simply use your own watchtower container.

**Comment by banigithub-2** [comment]
Sorry- that's what I was saying. I have my own watchtower container, but the Nextcloud one in AIO interferes with it. Perhaps I should disable the AIO one?

**Reply by szaimen** [reply]
Why should it interfere with yours?

**Reply by banigithub-2** [reply]
Seems the not-nextcloud one can sense the nextcloud one, and when it starts (despite having a WATCHTOWER_SCOPE defined, I get the following.  You'll see it thinking there's another one, and then it continues to stop and remove a number of containers:
```
time="2024-09-05T22:22:19+01:00" level=info msg="Found multiple running watchtower instances. Cleaning up."
time="2024-09-05T22:22:19+01:00" level=info msg="Stopping /adguardhome (cacd58ea3196) with SIGTERM"
time="2024-09-05T22:22:20+01:00" level=info msg="Removing image 6543abecfa41"
time="2024-09-05T22:22:20+01:00" level=info msg="Stopping /speedtest (6e3997d60a59) with SIGTERM"
time="2024-09-05T22:22:24+01:00" level=info msg="Removing image 1b1d9425404b"
time="2024-09-05T22:22:25+01:00" level=info msg="Stopping /syncthing (8a4e2366f07e) with SIGTERM"
time="2024-09-05T22:22:30+01:00" level=info msg="Removing image fb05a0d45b8c"
time="2024-09-05T22:22:30+01:00" level=info msg="Stopping /uptime-kuma (d150c4e0aec4) with SIGTERM"
time="2024-09-05T22:22:35+01:00" level=info msg="Removing image e1ca7233c2fa"
time="2024-09-05T22:22:37+01:00" level=info msg="Stopping /signal-cli-rest-api (5a14c779caab) with SIGTERM"
time="2024-09-05T22:22:38+01:00" level=info msg="Removing image 373dfc197ee3"
time="2024-09-05T22:22:39+01:00" level=info msg="Watchtower 1.7.1"
time="2024-09-05T22:22:39+01:00" level=info msg="Using no notifications"
time="2024-09-05T22:22:39+01:00" level=info msg="Only checking containers using enable label, in scope \not-nextcloud\""
time="2024-09-05T22:22:39+01:00" level=info msg="Scheduling first run: 2024-09-06 00:59:00 +0100 BST"
time="2024-09-05T22:22:39+01:00" level=info msg="Note that the first check will be performed in 2 hours, 36 minutes, 20 seconds"
time="2024-09-06T00:59:00+01:00" level=info msg="Session done" Failed=0 Scanned=0 Updated=0 notify=no
```

**Reply by szaimen** [reply]
Okay it finds multiple but is that a problem?
The container still seems to work normally, no?

**Reply by banigithub-2** [reply]
Yes, they both seem to work fine; it's annoying to have to re-add the WATCHTOWER_SCOPE=none to the AIO watchtower, and then use a script / docker compose to pull and restart all of the containers that got deleted, but I'm living with it.  Nextcloud AIO has just been so bombproof, I'm very grateful and happy to forgive this minor inconvenience.

**Comment by Reetryyy** [comment]
For anyone wanting to update other containers on the same host as Nextcloud-AIO without interfering with its Watchtower, you can run a separate Watchtower instance using scopes instead of the `watchtower.enable=true` label.

**Example Watchtower compose:**

```yaml
name: watchtower
services:
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    environment:
      WATCHTOWER_SCOPE: custom
      WATCHTOWER_CLEANUP: "true"
      WATCHTOWER_ROLLING_RESTART: "true"
      WATCHTOWER_TIMEOUT: "30s"
      WATCHTOWER_SCHEDULE: "0 0 7 * * 4"  # Every Thursday at 07:00 AM
    dns:
      - 1.1.1.1
      - 9.9.9.9
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro
    network_mode: bridge
    restart: always
```

**For other containers, set these labels:**

- Docker compose example:

  ```yaml
  services:
    app:
      image: myapp
      labels:
        com.centurylinklabs.watchtower.enable: "true"
        com.centurylinklabs.watchtower.scope: "custom"
  ```
- Docker run example:
  ```
  docker run -d --label com.centurylinklabs.watchtower.enable=true --label com.centurylinklabs.watchtower.scope=custom myapp
  ```
Note: If you change `WATCHTOWER_SCOPE` to something other than `custom`, update the labels accordingly for your containers.

This setup lets you run two Watchtower instances on the same host without conflicts. Still, take safety measures like testing in a staging environment or backing up before applying in production.
