### DISCUSSION TITLE
Cannot install using Nextcloud AIO

### DISCUSSION THREAD

**Discussion by AndreiArdei** [nextcloud/all-in-one#4639] [Questions] [answered]
I am currently trying to setup nextcloud, my docker is running on machine A, meanwhile the docker volumes folder is mounted on a different NFS share. This means that all volumes managed by docker are created on the NFS share

my current compose.yml file looks like this:
```yaml
version: "3.8"

services:
  nextcloud:
    image: nextcloud/all-in-one:latest
    init: true
    restart: unless-stopped
    container_name: nextcloud-aio-mastercontainer
    ports:
      - "8080:8080"
    environment:
      - APACHE_PORT=11000
      - SKIP_DOMAIN_VALIDATION=true
      - APACHE_IP_BINDING=0.0.0.0
    volumes:
      - nextcloud_aio_mastercontainer:/mnt/docker-aio-config
      - /var/run/docker.sock:/var/run/docker.sock:ro

volumes:
  nextcloud_aio_mastercontainer:
    name: nextcloud_aio_mastercontainer
```

When AIO starts, i can connect to the AIO interface and then click on download and install, everything works apart from all containers that depend on the **nextcloud** container. When checking the logs of the nextcloud container I find the following:
```
Waiting for database to start...
Waiting for database to start...
Connection to nextcloud-aio-database (172.23.0.3) 5432 port [tcp/postgresql] succeeded!
+ '[' -f /dev-dri-group-was-added ']'
++ find /dev -maxdepth 1 -mindepth 1 -name dri
+ '[' -n '' ']'
+ set +x
Enabling Imagick...
WARNING: opening from cache https://dl-cdn.alpinelinux.org/alpine/v3.19/main: No such file or directory
WARNING: opening from cache https://dl-cdn.alpinelinux.org/alpine/v3.19/community: No such file or directory
Initializing nextcloud 28.0.5.1 ...
rsync: [receiver] mkstemp "/var/www/html/.htaccess.XXXXXX" failed: Permission denied (13)
rsync: [receiver] mkstemp "/var/www/html/.user.ini.XXXXXX" failed: Permission denied (13)
rsync: [receiver] mkstemp "/var/www/html/.AUTHORS.XXXXXX" failed: Permission denied (13)
rsync: [receiver] mkstemp "/var/www/html/.COPYING.XXXXXX" failed: Permission denied (13)
rsync: [receiver] mkstemp "/var/www/html/.composer.json.XXXXXX" failed: Permission denied (13)
rsync: [receiver] mkstemp "/var/www/html/.composer.lock.XXXXXX" failed: Permission denied (13)
rsync: [receiver] mkstemp "/var/www/html/.console.php.XXXXXX" failed: Permission denied (13)
rsync: [receiver] mkstemp "/var/www/html/.cron.php.XXXXXX" failed: Permission denied (13)
rsync: [receiver] mkstemp "/var/www/html/.index.html.XXXXXX" failed: Permission denied (13)
rsync: [receiver] mkstemp "/var/www/html/.index.php.XXXXXX" failed: Permission denied (13)
rsync: [receiver] mkstemp "/var/www/html/.occ.XXXXXX" failed: Permission denied (13)
rsync: [receiver] mkstemp "/var/www/html/.package-lock.json.XXXXXX" failed: Permission denied (13)
rsync: [receiver] mkstemp "/var/www/html/.package.json.XXXXXX" failed: Permission denied (13)
rsync: [receiver] mkstemp "/var/www/html/.public.php.XXXXXX" failed: Permission denied (13)
rsync: [receiver] mkstemp "/var/www/html/.remote.php.XXXXXX" failed: Permission denied (13)
rsync: [receiver] mkstemp "/var/www/html/.robots.txt.XXXXXX" failed: Permission denied (13)
rsync: [receiver] mkstemp "/var/www/html/.status.php.XXXXXX" failed: Permission denied (13)
```

docker has full write permission to the NFS share and since I am using the same user, i would've thought this to work.
Any help is welcome! Thanks!
