### DISCUSSION TITLE
Keep getting thrown out of nextcloud, temporary error.

### DISCUSSION THREAD

**Discussion by Japhys** [nextcloud/all-in-one#4656] [Questions] [answered]
### Steps to reproduce
1. Login
2. After a while I start seeing all sort of errors in the GUI and unable to see my Files, Bookmarks etc
3. Automatically logged out
4. Unable to login
5. Restarting containers will help for a short while.
6. 1 to 5 again...

### Expected behavior 

I should be able to log in.

### Actual behavior 

I keep getting thrown out of my nextcloud. It has been like this for weeks now. After running smoothly for over a year. Sometimes I will be able to login after restarting containers. I updated master container and other containers so I am on the latest version.

### Host OS 
Ubuntu 22.04

#### Nextcloud AIO version 
28.05

#### Current channel 
Stable

#### Other valuable info 

I am also using NGINX proxy manager
```

version: "3.8"

volumes:
  nextcloud_aio_mastercontainer:
    name: nextcloud_aio_mastercontainer

services:
  nextcloud:
    image: nextcloud/all-in-one:latest
    restart: always
    container_name: nextcloud-aio-mastercontainer
    volumes:
      - nextcloud_aio_mastercontainer:/mnt/docker-aio-config 
      - /var/run/docker.sock:/var/run/docker.sock:ro 
    ports:
      - 8189:8080
    environment: 
      - APACHE_PORT=11000 
      - APACHE_DISABLE_REWRITE_IP=1
      - NEXTCLOUD_TRUSTED_DOMAINS=example.com xx.xxx.xxx.xx
      - TRUSTED_PROXIES=xx.xxx.xxx.xx

```
(changed domain to example and anonymized ip)

![2024-05-15_07-17](https://github.com/nextcloud/all-in-one/assets/24695937/de369f80-5b02-4ade-a293-6bf4cea909f8)
