### DISCUSSION TITLE
Setting up Nextcloud behind a campus network

### DISCUSSION THREAD

**Discussion by stanleysliu** [nextcloud/all-in-one#4725] [Questions] [answered]
I am trying to run a Nextcloud AIO instance on a linux machine that is behind a university firewall (Only people connected to the campus network can access). I have been given a bought and signed certificate from the University but I am not sure where to put that. I have tried to play around with the reverse proxy instructions and the local instance instructions but I could not get anything to work. I am able to get into the admin dashboard of the Nextcloud AIO instance with port 8080 but I cannot access the actual file server on ports 443 or 8443. Where should I put the signed certificates and what configurations should I make?

**Comment by szaimen** [comment, marked as answer]
Hi, I guess you are looking for this: https://github.com/nextcloud/all-in-one/blob/main/local-instance.md#4-buy-a-certificate-and-use-that

btw, is this a globally trusted certificate or a self-signed one?

**Reply by stanleysliu** [reply]
I believe that it is a global trusted certificate.

What I did was used something like the docker-compose file shown in this discussion https://github.com/nextcloud/all-in-one/discussions/575

```
version: "3.0"

services:
  caddy:
    image: caddy:alpine
    restart: unless-stopped
    container_name: caddy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./certs/cert.crt:/etc/caddy/keys/cert.crt
      - ./certs/privkey.key:/etc/caddy/keys/privkey.key
    network_mode: "host"

  nextcloud:
    image: nextcloud/all-in-one:latest
    restart: unless-stopped
    container_name: nextcloud-aio-mastercontainer
    ports:
      - "8080:8080"
    environment:
      - APACHE_PORT=11000
    volumes:
      - nextcloud_aio_mastercontainer:/mnt/docker-aio-config
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:
      - caddy

volumes:
  nextcloud_aio_mastercontainer:
    external: true

```

I have a .crt and a .key (which I decrypted using **openssl rsa -in key -out key**)

My caddy file looks like 

```

https://domain.com:443 {
    reverse_proxy localhost:11000

    tls /etc/caddy/keys/cert.crt /etc/caddy/keys/privkey.key

    header {
        # Enforce HTTPS
        Strict-Transport-Security "max-age=31536000; includeSubDomains; preload"
        # Enable cross-site filter (XSS) and tell the browser to block detected attacks
        X-XSS-Protection "1; mode=block"
        # Disallow the site to be rendered within a frame (clickjacking protection)
        X-Frame-Options "DENY"
        # Prevent search engines from indexing (optional)
        X-Robots-Tag "none"
        # Remove Caddy signature
        -Server
    }
}

```


After running these using
```
docker volume create nextcloud_aio_mastercontainer
docker-compose up -d
```

I am able to get onto the interface where I have to put in my domain, but when I put in the domain, I get

**"Domain does not point to this server or the reverse proxy is not configured correctly. See the mastercontainer logs for more details. ('sudo docker logs -f nextcloud-aio-mastercontainer')"**
