### DISCUSSION TITLE
Another "Domaincheck container is not running" question

### DISCUSSION THREAD

**Discussion by paul** [nextcloud/all-in-one#4833] [Questions] [answered]
I searched the discussions and issues about this, and none of them seemed to help me.

I'm trying to add this to ansible-nas, since the nextcloud version they include is old.

I'm using traefik as the proxy, and I've got it connecting, but I'm getting the error:

![image](https://github.com/nextcloud/all-in-one/assets/184/b1c8b221-8e50-452f-acf8-3ddb66995936)

Here's the docker logs for the `nextcloud-aio-mastercontainer`. There are no other `nextcloud-aio` containers running.

```
 Trying to fix docker.sock permissions internally...
 Adding internal www-data to group ping
 Initial startup of Nextcloud All-in-One complete!
 You should be able to open the Nextcloud AIO Interface now on port 8080 of this server!
 E.g. https://internal.ip.of.this.server:8080
 ⚠️ Important: do always use an ip-address if you access this port and not a domain as HSTS might block access to it later!

 If your server has port 80 and 8443 open and you point a domain to your server, you can get a valid certificate automatically by opening the Nextcloud AIO Interface via:
 https://your-domain-that-points-to-this-server.tld:8443
 [Fri Jun 14 22:52:58.974556 2024] [mpm_event:notice] [pid 149:tid 140711412656904] AH00489: Apache/2.4.59 (Unix) OpenSSL/3.1.5 configured -- resuming normal operations
 [Fri Jun 14 22:52:58.974600 2024] [core:notice] [pid 149:tid 140711412656904] AH00094: Command line: 'httpd -D FOREGROUND'
 {"level":"info","ts":1718405578.990486,"msg":"using provided configuration","config_file":"/Caddyfile","config_adapter":""}
 [14-Jun-2024 22:52:58] NOTICE: fpm is running, pid 155
 [14-Jun-2024 22:52:58] NOTICE: ready to handle connections
 NOTICE: PHP message: Could not start domaincheck container: Could not start container nextcloud-aio-domaincheck: Server error: `POST http://localhost/v1.41/containers/nextcloud-aio-domaincheck/start` resulted in a `500 Internal Server Error` response:
 {"message":"driver failed programming external connectivity on endpoint nextcloud-aio-domaincheck (89452823748dfee43e637 (truncated...)
```

How do I find out more about what the problem is? I `docker exec bash` into the mastercontainer, but none of the logs have any of the above output. The "truncated..." part is especially frustrating, I'm not sure what's truncating the output, either.

Trying to make the same request from within the machine doesn't help, I'm not sure what machine is making the request, so I don't know what `localhost` refers to in the log output.

```
aecb54c11e8f:/var/www/docker-aio# curl -v -X POST http://localhost/v1.41/containers/nextcloud-aio-domaincheck/start
...
> POST /v1.41/containers/nextcloud-aio-domaincheck/start HTTP/1.1
...
< HTTP/1.1 301 Moved Permanently
< Location: https://localhost/v1.41/containers/nextcloud-aio-domaincheck/start
< Server: Caddy
...

aecb54c11e8f:/var/www/docker-aio# curl -v -X POST https://localhost/v1.41/containers/nextcloud-aio-domaincheck/start
...
curl: (7) Failed to connect to localhost port 443 after 0 ms: Couldn't connect to server

aecb54c11e8f:/var/www/docker-aio# curl -v -k -X POST https://localhost:8443/v1.41/containers/nextcloud-aio-domaincheck/start
...
curl: (35) OpenSSL/3.1.5: error:0A000438:SSL routines::tlsv1 alert internal error
```

**Comment by szaimen** [comment]
Hi, can you follow https://github.com/nextcloud/all-in-one/blob/main/reverse-proxy.md#6-how-to-debug-things?

**Reply by paul** [reply]
Yeah, I've done all that. I even have `SKIP_DOMAIN_VALIDATION=true` in the env, but its still trying to start that domaincheck container. 

Do you know if there's any way to see the rest of the log line that gets `(truncated...)`?

**Reply by szaimen** [reply, marked as answer]
Can you post your docker-compose file or docker run command that you used here?

**Reply by paul** [reply]
I'm trying to add it to my ansible-nas, so its an ansible docker task, rather than docker-compose or docker directly, which I don't expect to be supported. (which is why I'm asking how I debug what's wrong, rather than trying to fix it)

Regardless, here's that ansible task yaml:

```yaml
---
- name: Start Nextcloud AIO
  block:
    - name: Create Nextcloud AIO directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
      with_items:
        - "{{ nextcloud_aio_data_directory }}/nextcloud"

    - name: Nextcloud AIO Docker Container
      community.docker.docker_container:
        name: "{{ nextcloud_aio_container_name }}"
        image: "{{ nextcloud_aio_image_name }}:{{ nextcloud_aio_image_version }}"
        pull: true
        init: true
        volumes:
          - "nextcloud_aio_mastercontainer:/mnt/docker-aio-config"
          - "{{ nextcloud_aio_data_directory }}/nextcloud:/var/www/html:rw"
          - "{{ nextcloud_aio_documents_directory }}:/var/www/html/data/rando/files:rw"
          - "/var/run/docker.sock:/var/run/docker.sock"
        ports:
          # - "{{ nextcloud_aio_port }}:80"
          - "8080:8080"
          - "11000:11000"
        env:
          APACHE_PORT: "11000"
          APACHE_IP_BINDING: "0.0.0.0"
          NEXTCLOUD_DATADIR: "/var/www/html"
          SKIP_DOMAIN_VALIDATION: "true"
          # OVERWRITE_HOST: "{{ nextcloud_aio_hostname }}.{{ ansible_nas_domain }}"
          # OVERWRITE_PROTOCOL: https
        restart_policy: unless-stopped
        memory: "{{ nextcloud_aio_memory }}"
        labels:
          traefik.enable: "{{ nextcloud_aio_available_externally | string }}"
          traefik.http.routers.nextcloud.rule: "Host(`{{ nextcloud_aio_hostname }}.{{ ansible_nas_domain }}`)"
          traefik.http.routers.nextcloud.tls.certresolver: "letsencrypt"
          traefik.http.routers.nextcloud.tls.domains[0].main: "{{ ansible_nas_domain }}"
          traefik.http.routers.nextcloud.tls.domains[0].sans: "*.{{ ansible_nas_domain }}"
          traefik.http.services.nextcloud.loadbalancer.server.port: "11000"
          traefik.http.services.nextcloud.loadbalancer.server.scheme: "https"
          homepage.group: Media
          homepage.name: Nextcloud
          homepage.icon: nextcloud.png
          homepage.href: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ nextcloud_aio_port }}"
          homepage.description: Open source dropbox alternative
          homepage.widget.type: nextcloud
          homepage.widget.url: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ nextcloud_aio_port }}"
  when: nextcloud_aio_enabled is true
```
