### DISCUSSION TITLE
Nextcloud AiO inside nspawn Linux Jail : Could not resolve the host nextcloud.com.

### DISCUSSION THREAD

**Discussion by ckbisek** [nextcloud/all-in-one#4868] [Questions] [answered]
Not sure if this is really a question or to help future me, however...

I'm creating a Linux jail on a TrueNAS Scale server via [jailmaker](https://github.com/Jip-Hop/jailmaker)

Host /etc/resolv.conf:
`nameserver 192.168.1.1`
`search my.domain`

Docker Run:
`docker run --init --sig-proxy=false --name nextcloud-aio-mastercontainer --restart always --publish 8080:8080 --env APACHE_PORT=11000 --env APACHE_IP_BINDING=192.168.1.16 --env NEXTCLOUD_DATADIR="/mnt/data/nextcloud/data" --volume nextcloud_aio_mastercontainer:/mnt/docker-aio-config --dns=192.168.1.1 --dns-search=my.domain --volume /var/run/docker.sock:/var/run/docker.sock:ro nextcloud/all-in-one:latest`

However, the master container is mad at the world:
`Could not resolve the host nextcloud.com.`
`Most likely the DNS resolving does not work.`
`You should be able to fix this by following https://dockerlabs.collabnix.com/intermediate/networking/Configuring_DNS.html`
`Apart from that, there has been this: https://github.com/nextcloud/all-in-one/discussions/2065`

I believe I have satisfied both links, but I am not finding any solution.
I've looked at the docker logs, I've scoured the wiki..

The only thing that I was able to get this to work was by utilizing `--network host`
` docker run --init --sig-proxy=false --name nextcloud-aio-mastercontainer --restart always --publish 8080:8080 --env APACHE_PORT=11000 --env APACHE_IP_BINDING=192.168.1.16 --network host --env NEXTCLOUD_DATADIR="/mnt/data/nextcloud/data" --volume nextcloud_aio_mastercontainer:/mnt/docker-aio-config --volume /var/run/docker.sock:/var/run/docker.sock:ro nextcloud/all-in-one:latest`

I'm sure I am missing something (pretty obvious), but because of running on the host network I am utilizing a dedicated Linux jail to host Nextcloud AiO.

**Comment by szaimen** [comment]
Hi, based on https://dockerlabs.collabnix.com/intermediate/networking/Configuring_DNS.html, can you try if the following works?
![Screenshot_20240622_152553_Brave](https://github.com/nextcloud/all-in-one/assets/42591237/69aa80d2-6c9f-4046-a991-245628f39c7a)

**Reply by ckbisek** [reply]
I'm assuming this is expected to be on the host

![image](https://github.com/nextcloud/all-in-one/assets/47727235/3699bc70-8b10-42b0-95ac-4b1d354034a6)

**Reply by szaimen** [reply]
Yes, the host that runs docker and aio. If it is not found you need to create it ans restart docker.

**Reply by ckbisek** [reply]
In docker Linux jail

1. Created `/etc/docker/daemon.json`
2. Populated `/etc/docker/daemon.json` with `{ "dns" : [ "114.114.114.114" , "8.8.8.8" ] }`
3. Restarted Docker Linux Jail
4. Created Nextcloud AiO compose.yaml
```
services:
  nextcloud-aio-mastercontainer:
    image: nextcloud/all-in-one:latest
    init: true
    restart: always
    container_name: nextcloud-aio-mastercontainer
    volumes:
      - nextcloud_aio_mastercontainer:/mnt/docker-aio-config
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 8080:8080
    environment:
      - APACHE_PORT=11000
      - APACHE_IP_BINDING=192.168.1.16
      - NEXTCLOUD_DATADIR=/mnt/data/nextcloud/data
volumes:
  nextcloud_aio_mastercontainer:
    name: nextcloud_aio_mastercontainer
networks: {}
```
Could not resolve the host nextcloud.com.
Most likely the DNS resolving does not work.
You should be able to fix this by following https://dockerlabs.collabnix.com/intermediate/networking/Configuring_DNS.html
Apart from that, there has been this: https://github.com/nextcloud/all-in-one/discussions/2065


![image](https://github.com/nextcloud/all-in-one/assets/47727235/9f1d0169-adc5-40a5-8dbb-a67d922f326d)
