### DISCUSSION TITLE
AIO Docker container doesn't create /config directory

### DISCUSSION THREAD

**Discussion by seannie-sharko** [nextcloud/all-in-one#4880] [Questions] [answered]
sudo docker run \
--init \
--sig-proxy=false \
--name nextcloud-aio-mastercontainer \
--restart always \
--publish 80:80 \
--publish 8080:8080 \
--publish 8443:8443 \
--volume nextcloud_aio_mastercontainer:/mnt/docker-aio-config \
--volume /var/run/docker.sock:/var/run/docker.sock:rw \
--volume /media/some_volume:/mnt/some_volume \
--env APACHE_PORT=11000 \
--env APACHE_IP_BINDING=0.0.0.0 \
--env NEXTCLOUD_MOUNT="/mnt/some_volume" \
--env NEXTCLOUD_UPLOAD_LIMIT=100G \
--env NEXTCLOUD_MAX_TIME=36000 \
--env NEXTCLOUD_MEMORY_LIMIT=1024M \
--add-host my_domain_example.com:xxx.xx.xx.xx \
nextcloud/all-in-one:latest

This docker run example given in the documentation doesn't create the required config.php file thus my page resolves to the 

Cannot write into "config" directory!

page

**Comment by szaimen** [comment]
Hi, I fear I cannot repeoduce the problem. Is the installation failing in your case or where does this error come from? Can you maybe post the complete logs?

**Comment by seannie-sharko** [comment]
```
version: "3.8"

services:
  caddy:
    image: caddy:alpine
    restart: unless-stopped
    container_name: caddy
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./certs:/certs
      - ./config:/config
      - ./data:/data
      - ./sites:/srv
    network_mode: host

  nextcloud:
    image: nextcloud/all-in-one:latest
    init: true
    restart: unless-stopped
    container_name: nextcloud-aio-mastercontainer
    volumes:
      - nextcloud_aio_mastercontainer:/mnt/docker-aio-config
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 8080:8080
    environment:
      - APACHE_PORT=11000
      - APACHE_IP_BINDING=127.0.0.1
      - NEXTCLOUD_UPLOAD_LIMIT=100G
      - NEXTCLOUD_MEMORY_LIMIT=1024M
    extra_hosts: ['host.docker.internal:host-gateway']
    depends_on:
      - caddy

volumes:
  nextcloud_aio_mastercontainer:
    name: nextcloud_aio_mastercontainer
```

```
Caddyfile
https://mydomain.example.tld:443 {
    header Strict-Transport-Security max-age=31536000;
    reverse_proxy host.docker.internal:11000
}
```

I tried a new docker-compose file and still the same problems

NOTICE: PHP message: Expected was: 7e0c0e236d0ikf845a19a7041158c2dee175701526thaf41
NOTICE: PHP message: The error message was:
NOTICE: PHP message: Please follow https://github.com/nextcloud/all-in-one/blob/main/reverse-proxy.md#6-how-to-debug-things in order to debug things!


I elected to use a reverse proxy and can reach local_host_ip:8080/containers 

but I'm constantly greeted with this:


New AIO instance

AIO is currently in "reverse proxy mode" which means that it can be installed behind a web server or reverse proxy (like Apache, Nginx, Cloudflare Tunnel and else) and does not do the TLS proxying itself.

Please type the domain that will be used for Nextcloud below in order to create a new AIO instance.


putting my domain in results with:

Domain does not point to this server or the reverse proxy is not configured correctly. See the mastercontainer logs for more details. ('sudo docker logs -f nextcloud-aio-mastercontainer')
