### DISCUSSION TITLE
How to recreate the `nextcloud-aio` network?

### DISCUSSION THREAD

**Discussion by szaimen** [nextcloud/all-in-one#4989] [Wiki]
In some cases you might need to recreate the `nextcloud-aio` network. Here is how to do it:

1. Stop your containers from the AIO interface
2. After the docker daemon started correctly run `sudo docker network disconnect nextcloud-aio nextcloud-aio-mastercontainer` to disconnect the mastercontainer from the nextcloud-aio network.
3. now remove the nextcoud-aio network by running `sudo docker network rm nextcloud-aio`
4. Then run `sudo docker network create --driver bridge nextcloud-aio` in order to recreate the nextcloud-aio network
5. Finally run `sudo docker network connect nextcloud-aio nextcloud-aio-mastercontainer` to connect the mastercontainer to the network again.
6. run `sudo docker restart nextcloud-aio-mastercontainer`
7. At last, open the AIO interface and start your containers again

**Comment by jamespurnama1** [comment]
After following the steps above, I still have `"EnableIPv6": false`.
For those who have this issue, simply add the argument `--ipv6` when creating a docker network.

> 4. Then run `sudo docker network create --ipv6 --driver bridge nextcloud-aio`  in order to recreate the nextcloud-aio network

[Source](https://docs.docker.com/engine/daemon/ipv6/)

**Reply by szaimen** [reply]
After following https://github.com/nextcloud/all-in-one/blob/main/docker-ipv6-support.md, the --ipv6 flag would have been added automatically

**Comment by priyankub** [comment]
> 5\. connect nextcloud-aio nextcloud-aio-mastercontainer

On Unraid, maybe because I have multiple networks, I had to specify ipv6, subnet, and gateway:

```
docker network create --driver bridge --ipv6 --subnet fd02:1234:5678::/64 --gateway fd02:1234:5678::1 nextcloud-aio
```

**Comment by MrRinkana** [comment]
How does one proceed if it is desired to set a specific nextcloud-aio subnet?

<details>
<summary>I have played around with creating a network in my docker compose:</summary>

```yml
services:
    all-in-one:
        init: true
        container_name: nextcloud-aio-mastercontainer
        restart: always
        ports:
            - 8080:8080
        networks: # added this
            - nextcloud_network
        volumes:
            - nextcloud_aio_mastercontainer:/mnt/docker-aio-config
            - /var/run/docker.sock:/var/run/docker.sock:ro
        environment:
            - NEXTCLOUD_DATADIR=/srv/ncdata
            - APACHE_PORT=11000
            - APACHE_IP_BINDING=127.0.0.1
        image: nextcloud/all-in-one:latest

networks: # and this
    nextcloud_network:
        ipam:
          config:
            - subnet: 172.25.0.0/16 # this is what im trying to get the nextcloud container to reside within

volumes:
    nextcloud_aio_mastercontainer:
        external: true
        name: nextcloud_aio_mastercontainer
```

</details>

But that creates a network with a different name than "nextcloud-aio" (name-of-compose+nextcloud_network), and keeps the previous nextcloud-aio network as is, meaning the ip of the nextcloudcontainer does not change.

1. does the network need to be called "nextcloud-aio" and in that case where do i specify its subnet?
2. How lasting is the default network? Will its subnet declaration last trough nextcloud container or master container updates?

The purpose of explicitly specifying a subnet is to allow the docker container to send mail to the host postfix (postfix conf, firewall rules), and such that the containers are easily moved to another host without needing to make new configurations..
