### DISCUSSION TITLE
Clicking "open your nextcloud button" opens the /containers page again and prevents from completing setup.

### DISCUSSION THREAD

**Discussion by Besugo03** [nextcloud/all-in-one#5104] [Questions] [answered]
### Steps to reproduce
1. Install the AIO via portainer with the skip validation argument (i am using cloudflare to send traffic from my domain to NGINX proxy manager, and from there redirecting to nextcloud)

### Expected behavior 
Clicking the "open your Nexctloud" button should open the dedicated screen

### Actual behavior 
Another instance of the /containers page is opened, making it unable to login

### Host OS 
an Arch Linux PC

#### Other valuable info 

open ports in firewalld : `21/tcp 21/udp 40000/tcp 9443/tcp 9443/udp 8000/udp 8000/tcp 53/tcp 53/udp 80/tcp 8080/tcp 8080/udp 8181/tcp 8181/udp 8100/udp 8100/tcp 8008/tcp 8008/udp 4443/tcp 4443/udp 443/tcp 443/udp 80/udp 11000/tcp 11000/udp`

Portainer configuration : 
![image](https://github.com/user-attachments/assets/4dc3f285-107a-45dd-ad1f-1ed0a9e1e0d9)

Open ports on my router (all redirected to my.local.ip of the arch machine i use as the home server. formatted wan-port -> lan port)

443 -> 4443
80 -> 8008
81 -> 8100
11000 -> 11000

i already did everything in the cloudflare guide, like setting it on "only DNS", setting the security to "full" etc... etc...

apache log : 
```
2024-08-07T08:01:27.700526723Z Waiting for Nextcloud to start...
2024-08-07T08:01:32.701977392Z Waiting for Nextcloud to start...
2024-08-07T08:01:37.703230376Z Waiting for Nextcloud to start...
2024-08-07T08:01:42.705223658Z Connection to nextcloud-aio-nextcloud (172.19.0.7) 9000 port [tcp/*] succeeded!
2024-08-07T08:01:43.989148473Z [Wed Aug 07 08:01:43.988735 2024] [mpm_event:notice] [pid 42:tid 42] AH00489: Apache/2.4.61 (Unix) configured -- resuming normal operations
2024-08-07T08:01:43.989180560Z [Wed Aug 07 08:01:43.988792 2024] [core:notice] [pid 42:tid 42] AH00094: Command line: '/usr/local/apache2/bin/httpd -D FOREGROUND'
2024-08-07T08:01:44.009934601Z {"level":"info","ts":1723017704.0097203,"msg":"using config from file","file":"/tmp/Caddyfile"}
2024-08-07T08:01:44.011602889Z {"level":"info","ts":1723017704.0114224,"msg":"adapted config to JSON","adapter":"caddyfile"}
```

mastercontainer log :  
```
Trying to fix docker.sock permissions internally...
Creating docker group internally with id 963
Initial startup of Nextcloud All-in-One complete!
You should be able to open the Nextcloud AIO Interface now on port 8080 of this server!
E.g. https://internal.ip.of.this.server:8080
⚠️ Important: do always use an ip-address if you access this port and not a domain as HSTS might block access to it later!
If your server has port 80 and 8443 open and you point a domain to your server, you can get a valid certificate automatically by opening the Nextcloud AIO Interface via:
https://your-domain-that-points-to-this-server.tld:8443
[Wed Aug 07 06:22:09.058221 2024] [mpm_event:notice] [pid 149:tid 149] AH00489: Apache/2.4.61 (Unix) OpenSSL/3.3.1 configured -- resuming normal operations
[Wed Aug 07 06:22:09.058261 2024] [core:notice] [pid 149:tid 149] AH00094: Command line: 'httpd -D FOREGROUND'
[07-Aug-2024 06:22:09] NOTICE: fpm is running, pid 155
[07-Aug-2024 06:22:09] NOTICE: ready to handle connections
INF ts=1723011729.0646281 msg=using config from file file=/Caddyfile
INF ts=1723011729.0658782 msg=adapted config to JSON adapter=caddyfile
Initial startup of Nextcloud All-in-One complete!
You should be able to open the Nextcloud AIO Interface now on port 8080 of this server!
E.g. https://internal.ip.of.this.server:8080
⚠️ Important: do always use an ip-address if you access this port and not a domain as HSTS might block access to it later!
If your server has port 80 and 8443 open and you point a domain to your server, you can get a valid certificate automatically by opening the Nextcloud AIO Interface via:
https://your-domain-that-points-to-this-server.tld:8443
INF ts=1723012092.4570265 msg=using config from file file=/Caddyfile
INF ts=1723012092.4584465 msg=adapted config to JSON adapter=caddyfile
[Wed Aug 07 06:28:12.489408 2024] [mpm_event:notice] [pid 141:tid 141] AH00489: Apache/2.4.61 (Unix) OpenSSL/3.3.1 configured -- resuming normal operations
[Wed Aug 07 06:28:12.489434 2024] [core:notice] [pid 141:tid 141] AH00094: Command line: 'httpd -D FOREGROUND'
[07-Aug-2024 06:28:12] NOTICE: fpm is running, pid 147
[07-Aug-2024 06:28:12] NOTICE: ready to handle connections
Initial startup of Nextcloud All-in-One complete!
You should be able to open the Nextcloud AIO Interface now on port 8080 of this server!
E.g. https://internal.ip.of.this.server:8080
⚠️ Important: do always use an ip-address if you access this port and not a domain as HSTS might block access to it later!
If your server has port 80 and 8443 open and you point a domain to your server, you can get a valid certificate automatically by opening the Nextcloud AIO Interface via:
https://your-domain-that-points-to-this-server.tld:8443
[07-Aug-2024 07:38:55] NOTICE: fpm is running, pid 152
[07-Aug-2024 07:38:55] NOTICE: ready to handle connections
[Wed Aug 07 07:38:55.896736 2024] [mpm_event:notice] [pid 142:tid 142] AH00489: Apache/2.4.61 (Unix) OpenSSL/3.3.1 configured -- resuming normal operations
[Wed Aug 07 07:38:55.896767 2024] [core:notice] [pid 142:tid 142] AH00094: Command line: 'httpd -D FOREGROUND'
INF ts=1723016335.9056828 msg=using config from file file=/Caddyfile
INF ts=1723016335.9065168 msg=adapted config to JSON adapter=caddyfile
Deleting duplicate sessions
Deleting duplicate sessions
NOTICE: PHP message: 404 Not Found
Type: Slim\Exception\HttpNotFoundException

4
Message: Not found.
File: /var/www/docker-aio/php/vendor/slim/slim/Slim/Middleware/RoutingMiddleware.php
Line: 76
Trace: #0 /var/www/docker-aio/php/vendor/slim/slim/Slim/Routing/RouteRunner.php(62): Slim\Middleware\RoutingMiddleware->performRouting(Object(GuzzleHttp\Psr7\ServerRequest))
#1 /var/www/docker-aio/php/vendor/slim/csrf/src/Guard.php(482): Slim\Routing\RouteRunner->handle(Object(GuzzleHttp\Psr7\ServerRequest))
#2 /var/www/docker-aio/php/vendor/slim/slim/Slim/MiddlewareDispatcher.php(177): Slim\Csrf\Guard->process(Object(GuzzleHttp\Psr7\ServerRequest), Object(Slim\Routing\RouteRunner))
#3 /var/www/docker-aio/php/vendor/slim/twig-view/src/TwigMiddleware.php(115): Psr\Http\Server\RequestHandlerInterface@anonymous->handle(Object(GuzzleHttp\Psr7\ServerRequest))
#4 /var/www/docker-aio/php/vendor/slim/slim/Slim/MiddlewareDispatcher.php(129): Slim\Views\TwigMiddleware->process(Object(GuzzleHttp\Psr7\ServerRequest), Object(Psr\Http\Server\RequestHandlerInterface@anonymous))
#5 /var/www/docker-aio/php/src/Middleware/AuthMiddleware.php(38): Psr\Http\Server\RequestHandlerInterface@anonymous->handle(Object(GuzzleHttp\Psr7\ServerRequest))
#6 /var/www/docker-aio/php/vendor/slim/slim/Slim/MiddlewareDispatcher.php(280): AIO\Middleware\AuthMiddleware->__invoke(Object(GuzzleHttp\Psr7\ServerRequest), Object(Psr\Http\Server\RequestHandlerInterface@anonymous))
#7 /var/www/docker-aio/php/vendor/slim/slim/Slim/Middleware/ErrorMiddleware.php(77): Psr\Http\Server\RequestHandlerInterface@anonymous->handle(Object(GuzzleHttp\Psr7\ServerRequest))
#8 /var/www/docker-aio/php/vendor/slim/slim/Slim/MiddlewareDispatcher.php(129): Slim\Middleware\ErrorMiddleware->process(Object(GuzzleHttp\Psr7\ServerRequest), Object(Psr\Http\Server\RequestHandlerInterface@anonymous))
#9 /var/www/docker-aio/php/vendor/slim/slim/Slim/MiddlewareDispatcher.php(73): Psr\Http\Server\RequestHandlerInterface@anonymous->handle(Object(GuzzleHttp\Psr7\ServerRequest))
#10 /var/www/docker-aio/php/vendor/slim/slim/Slim/App.php(209): Slim\MiddlewareDispatcher->handle(Object(GuzzleHttp\Psr7\ServerRequest))
#11 /var/www/docker-aio/php/vendor/slim/slim/Slim/App.php(193): Slim\App->handle(Object(GuzzleHttp\Psr7\ServerRequest))
#12 /var/www/docker-aio/php/public/index.php(185): Slim\App->run()
#13 {main}
Tips: To display error details in HTTP response set "displayErrorDetails" to true in the ErrorHandler constructor.
Deleting duplicate sessions
Initial startup of Nextcloud All-in-One complete!
You should be able to open the Nextcloud AIO Interface now on port 8080 of this server!
E.g. https://internal.ip.of.this.server:8080
⚠️ Important: do always use an ip-address if you access this port and not a domain as HSTS might block access to it later!
If your server has port 80 and 8443 open and you point a domain to your server, you can get a valid certificate automatically by opening the Nextcloud AIO Interface via:
https://your-domain-that-points-to-this-server.tld:8443
[Wed Aug 07 08:00:58.939257 2024] [mpm_event:notice] [pid 143:tid 143] AH00489: Apache/2.4.61 (Unix) OpenSSL/3.3.1 configured -- resuming normal operations
[Wed Aug 07 08:00:58.939289 2024] [core:notice] [pid 143:tid 143] AH00094: Command line: 'httpd -D FOREGROUND'
[07-Aug-2024 08:00:58] NOTICE: fpm is running, pid 149
[07-Aug-2024 08:00:58] NOTICE: ready to handle connections
INF ts=1723017658.9682274 msg=using config from file file=/Caddyfile
INF ts=1723017658.9694498 msg=adapted config to JSON adapter=caddyfile
```

**Comment by szaimen** [comment]
Hi, can you follow https://github.com/nextcloud/all-in-one/blob/main/reverse-proxy.md#6-how-to-debug-things?

**Reply by Besugo03** [reply]
Followed every step in the guide and everything is as described, only issue i have is that, even though the reverse proxy is configured as described, i get a "502 bad gateway" error when opening the server through it, using the apache port as described. Using the GUI port (81) does open the initial setup and start the thing again but i get back in the loop of clicking the button and having the same page re-open again.

**Comment by szaimen** [comment]
Are you using cloudflare tunnel?

Also can you post the docker run command that you used or the docker compose file that you used here?

**Reply by Besugo03** [reply]
i have cloudflare DNS records setup with a dynamic dns updater that updates an A type record to always map *.mydomain.com to my public, dynamic ip (set as DNS only, no proxy) and it works on all other services i installed (portainer, home assistant etc...)

Here is the docker compose file i used on portainer :

```
services:
  nextcloud-aio-mastercontainer:
    image: nextcloud/all-in-one:latest
    init: true
    restart: always
    container_name: nextcloud-aio-mastercontainer # This line is not allowed to be changed as otherwise AIO will not work correctly
    volumes:
      - nextcloud_aio_mastercontainer:/mnt/docker-aio-config # This line is not allowed to be changed as otherwise the built-in backup solution will not work
      - /var/run/docker.sock:/var/run/docker.sock:ro # May be changed on macOS, Windows or docker rootless. See the applicable documentation. If adjusting, don't forget to also set 'WATCHTOWER_DOCKER_SOCKET_PATH'!
    network_mode: bridge # add to the same network as docker run would do
    ports:
      - 80:80 # Can be removed when running behind a web server or reverse proxy (like Apache, Nginx, Caddy, Cloudflare Tunnel and else). See https://github.com/nextcloud/all-in-one/blob/main/reverse-proxy.md
      - 8181:8080
      - 8443:8443 # Can be removed when running behind a web server or reverse proxy (like Apache, Nginx, Caddy, Cloudflare Tunnel and else). See https://github.com/nextcloud/all-in-one/blob/main/reverse-proxy.md
    environment: # Is needed when using any of the options below
      # AIO_DISABLE_BACKUP_SECTION: false # Setting this to true allows to hide the backup section in the AIO interface. See https://github.com/nextcloud/all-in-one#how-to-disable-the-backup-section
      APACHE_PORT: 11000 # Is needed when running behind a web server or reverse proxy (like Apache, Nginx, Caddy, Cloudflare Tunnel and else). See https://github.com/nextcloud/all-in-one/blob/main/reverse-proxy.md
      APACHE_IP_BINDING: 0.0.0.0 # Should be set when running behind a web server or reverse proxy (like Apache, Nginx, Caddy, Cloudflare Tunnel and else) that is running on the same host. See https://github.com/nextcloud/all-in-one/blob/main/reverse-proxy.md
      # BORG_RETENTION_POLICY: --keep-within=7d --keep-weekly=4 --keep-monthly=6 # Allows to adjust borgs retention policy. See https://github.com/nextcloud/all-in-one#how-to-adjust-borgs-retention-policy
      # COLLABORA_SECCOMP_DISABLED: false # Setting this to true allows to disable Collabora's Seccomp feature. See https://github.com/nextcloud/all-in-one#how-to-disable-collaboras-seccomp-feature
      # NEXTCLOUD_DATADIR: /mnt/ncdata # Allows to set the host directory for Nextcloud's datadir. ⚠️⚠️⚠️ Warning: do not set or adjust this value after the initial Nextcloud installation is done! See https://github.com/nextcloud/all-in-one#how-to-change-the-default-location-of-nextclouds-datadir
      # NEXTCLOUD_MOUNT: /mnt/ # Allows the Nextcloud container to access the chosen directory on the host. See https://github.com/nextcloud/all-in-one#how-to-allow-the-nextcloud-container-to-access-directories-on-the-host
      # NEXTCLOUD_UPLOAD_LIMIT: 10G # Can be adjusted if you need more. See https://github.com/nextcloud/all-in-one#how-to-adjust-the-upload-limit-for-nextcloud
      # NEXTCLOUD_MAX_TIME: 3600 # Can be adjusted if you need more. See https://github.com/nextcloud/all-in-one#how-to-adjust-the-max-execution-time-for-nextcloud
      # NEXTCLOUD_MEMORY_LIMIT: 512M # Can be adjusted if you need more. See https://github.com/nextcloud/all-in-one#how-to-adjust-the-php-memory-limit-for-nextcloud
      # NEXTCLOUD_TRUSTED_CACERTS_DIR: /path/to/my/cacerts # CA certificates in this directory will be trusted by the OS of the nexcloud container (Useful e.g. for LDAPS) See See https://github.com/nextcloud/all-in-one#how-to-trust-user-defined-certification-authorities-ca
      # NEXTCLOUD_STARTUP_APPS: deck twofactor_totp tasks calendar contacts notes # Allows to modify the Nextcloud apps that are installed on starting AIO the first time. See https://github.com/nextcloud/all-in-one#how-to-change-the-nextcloud-apps-that-are-installed-on-the-first-startup
      # NEXTCLOUD_ADDITIONAL_APKS: imagemagick # This allows to add additional packages to the Nextcloud container permanently. Default is imagemagick but can be overwritten by modifying this value. See https://github.com/nextcloud/all-in-one#how-to-add-os-packages-permanently-to-the-nextcloud-container
      # NEXTCLOUD_ADDITIONAL_PHP_EXTENSIONS: imagick # This allows to add additional php extensions to the Nextcloud container permanently. Default is imagick but can be overwritten by modifying this value. See https://github.com/nextcloud/all-in-one#how-to-add-php-extensions-permanently-to-the-nextcloud-container
      # NEXTCLOUD_ENABLE_DRI_DEVICE: true # This allows to enable the /dev/dri device in the Nextcloud container. ⚠️⚠️⚠️ Warning: this only works if the '/dev/dri' device is present on the host! If it should not exist on your host, don't set this to true as otherwise the Nextcloud container will fail to start! See https://github.com/nextcloud/all-in-one#how-to-enable-hardware-transcoding-for-nextcloud
      # NEXTCLOUD_KEEP_DISABLED_APPS: false # Setting this to true will keep Nextcloud apps that are disabled in the AIO interface and not uninstall them if they should be installed. See https://github.com/nextcloud/all-in-one#how-to-keep-disabled-apps
      # TALK_PORT: 3478 # This allows to adjust the port that the talk container is using. See https://github.com/nextcloud/all-in-one#how-to-adjust-the-talk-port
      # WATCHTOWER_DOCKER_SOCKET_PATH: /var/run/docker.sock # Needs to be specified if the docker socket on the host is not located in the default '/var/run/docker.sock'. Otherwise mastercontainer updates will fail. For macos it needs to be '/var/run/docker.sock'
    # security_opt: ["label:disable"] # Is needed when using SELinux

  # # Optional: Caddy reverse proxy. See https://github.com/nextcloud/all-in-one/blob/main/reverse-proxy.md
  # # You can find further examples here: https://github.com/nextcloud/all-in-one/discussions/588
  # caddy:
  #   image: caddy:alpine
  #   restart: always
  #   container_name: caddy
  #   volumes:
  #     - ./Caddyfile:/etc/caddy/Caddyfile
  #     - ./certs:/certs
  #     - ./config:/config
  #     - ./data:/data
  #     - ./sites:/srv
  #   network_mode: "host"

volumes: # If you want to store the data on a different drive, see https://github.com/nextcloud/all-in-one#how-to-store-the-filesinstallation-on-a-separate-drive
  nextcloud_aio_mastercontainer:
    name: nextcloud_aio_mastercontainer # This line is not allowed to be changed as otherwise the built-in backup solution will not work
```

**Reply by szaimen** [reply]
Okay and what config are you using in npm? Can you post a screenshot? Also please post the docker-compose of npm here

**Reply by Besugo03** [reply]
Here is the NPM Config:
![image](https://github.com/user-attachments/assets/0d55c749-6d0b-46cf-945d-f02f9b7bab48)

And here is the Dockercompose for NPM : 
```
version: '3.8'
services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '8008:80'
      - '8100:81'
      - '4443:443'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
```

As far as NPM goes, all other services i hosted have run without any particular issues
