### DISCUSSION TITLE
can not set a custom container nor volume name, why?

### DISCUSSION THREAD

**Discussion by dkebler** [nextcloud/all-in-one#517] [Questions] [answered]
Hmm..

when I run the docker compose file below with custom container and volume names the spin up complains about names and exits.   Never had an issue with docker image forcing a particular container name and volume name. The internal volume name is `nextcloud` so why should it care what the `name` property is.  Same with container name.  If I specify nothing docker will assign one so why does this image force a particular name?  I'm used to services refering to their name (using `depends_on`) not their `container_name`.   Is there a way to set these?   Makes it hard to spin up multiple instances or have some customized names that make managing easier. 

BTW is there a single list/file of all possible environment variables  

```
gpcca-files-server | Trying to fix docker.sock permissions internally...
gpcca-files-server | Creating docker group internally with id 999
gpcca-files-server | It seems like you did not give the mastercontainer the correct name?
```
```
nextcloud-aio-mastercontainer | Trying to fix docker.sock permissions internally...
nextcloud-aio-mastercontainer | Creating docker group internally with id 999
nextcloud-aio-mastercontainer | It seems like you did not give the mastercontainer volume the correct name?
```

```
version: "3.8"

volumes:
  nextcloud:
    name: gpcca-files-test

services:
  nextcloud:
    image: nextcloud/all-in-one:latest
    restart: unless-stopped
    container_name: gpcca-files-server
    env_file:
      - nextcloud.env
    volumes:
      - nextcloud:/mnt/docker-aio-config
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 8080:8080
```
