### DISCUSSION TITLE
NEXTCLOUD AIO migration from NPM to Traefik    curl errors

### DISCUSSION THREAD

**Discussion by tws101** [nextcloud/all-in-one#5211] [Questions] [answered]
An entire server and all of its stacks have been migrated to Traefik v3  as reverse proxy from NPM

the only stack that is holding out is Nextcloud..  HELP PLEASE

with the following compose that is attached below the following change was made for the migration

```
`labels:
      - traefik.enable=true
      - traefik.http.routers.nextcloud.entrypoints=websecure
      - traefik.http.routers.nextcloud.rule=Host(`${NC_DOMAIN}`)
      - traefik.http.routers.nextcloud.tls=true
      - traefik.http.services.nextcloud.loadbalancer.server.port=11000`
```

Traefik see the nextcloud stack spin up and resolves for about 60seconds...  Then apache goes unhealthy and everything stops working 

Logs show the following 

```
`nextcloud-aio-nextcloud       | [05-Sep-2024 17:40:42] NOTICE: ready to handle connections
nextcloud-aio-apache          | Connection to nextcloud-aio-nextcloud (172.24.1.35) 9000 port [tcp/*] succeeded!`
```

This may not be related 
`nextcloud-aio-apache          | {"level":"error","ts":1725576046.2021744,"msg":"unable to create folder for config autosave","dir":"/.config/caddy","error":"mkdir /.config: read-only file system"`

This is directly related 

```
`nextcloud-aio-nextcloud       | Failed to fetch discovery endpoint from https://redacted.domainname
nextcloud-aio-nextcloud       | cURL error 7: Failed to connect to redacted.domainname port 443 after 192 ms: Could not connect to server (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://redacted.domainname/hosting/discovery`
```

`nextcloud-aio-notify-push     | [2024-09-05 22:41:21.116869 +00:00] WARN [notify_push::connection] /build/source/src/connection.rs:99: Error while sending authentication request to nextcloud: Error while connecting to nextcloud: error sending request for url (https://redacted.domainname/index.php/apps/notify_push/uid)`

on NPM we just sent network traffic to        nextcloud-aio-apache:11000    and that worked fine     external domain had no issues....  but with Traefik we have had no such luck.....   We have tried the reverse proxy guide but for Traefik it says it is rather lacking and the video it references does not discuss nextcloud AIO..  Also a manual nextcloud by config file route was built like the documentation recommends  as follows with changing expose to port in the compose also with no results....

```
`http:
  routers:
    nextcloud:
      rule: "Host(`redacted.domainname`)"
      entrypoints:
        - "websecure"
      service: nextcloud
      middlewares:
        - nextcloud-chain
      tls: {}

  services:
    nextcloud:
      loadBalancer:
        servers:
          - url: "http://localhost:11000" # Use the host's IP address if Traefik runs outside the host network

  middlewares:
    nextcloud-secure-headers:
      headers:
        hostsProxyHeaders:
          - "X-Forwarded-Host"
        referrerPolicy: "same-origin"

    https-redirect:
      redirectscheme:
        scheme: https 

    nextcloud-chain:
      chain:
        middlewares:
          # - ... (e.g. rate limiting middleware)
          - https-redirect
          - nextcloud-secure-headers`

```
Here is the main compose.... we are still plague by these curl errors.....  Anyone have any advice?

```
`networks:
  main:
    name: main
    external: true
services:
  nextcloud-aio-apache:
    container_name: nextcloud-aio-apache
    depends_on:
      nextcloud-aio-onlyoffice:
        condition: service_started
        required: false
      nextcloud-aio-collabora:
        condition: service_started
        required: false
      nextcloud-aio-nextcloud:
        condition: service_started
        required: false
      nextcloud-aio-notify-push:
        condition: service_started
        required: false
    image: nextcloud/aio-apache:${APACHE_VERSION}
    user: 568:0
    init: true
    expose:
      - 11000
    environment:
      - NC_DOMAIN=${NC_DOMAIN}
      - NEXTCLOUD_HOST=${NEXTCLOUD_HOST}
      - APACHE_HOST=${APACHE_HOST}
      - COLLABORA_HOST=${COLLABORA_HOST}
      - APACHE_PORT=${APACHE_PORT}
      - ONLYOFFICE_HOST=${ONLYOFFICE_HOST}
      - TZ=${TIMEZONE}
      - APACHE_MAX_SIZE=${APACHE_MAX_SIZE}
      - APACHE_MAX_TIME=${NEXTCLOUD_MAX_TIME}
      - NOTIFY_PUSH_HOST=${NOTIFY_HOST}
    volumes:
      - ${NEXTCLOUD_DATA}:/var/www/html:ro
      - ${APACHE_DATA}:/mnt/data:rw
    restart: unless-stopped
    networks:
      - main
    labels:
      - traefik.enable=true
      - traefik.http.routers.nextcloud.entrypoints=websecure
      - traefik.http.routers.nextcloud.rule=Host(`${NC_DOMAIN}`)
      - traefik.http.routers.nextcloud.tls=true
      - traefik.http.services.nextcloud.loadbalancer.server.port=11000
    read_only: true
    tmpfs:
      - /var/log/supervisord
      - /var/run/supervisord
      - /usr/local/apache2/logs
      - /tmp
      - /home/www-data
    cap_drop:
      - NET_RAW
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 4G
  nextcloud-aio-database:
    container_name: nextcloud-aio-database
    image: nextcloud/aio-postgresql:${DATABASE_VERSION}
    user: 999:0
    init: true
    expose:
      - 5432
    volumes:
      - ${DATABASE_DATA}:/var/lib/postgresql/data:rw
      - ${DATABASE_DUMP_DATA}:/mnt/data:rw
    environment:
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=nextcloud_database
      - POSTGRES_USER=nextcloud
      - TZ=${TIMEZONE}
      - PGTZ=${TIMEZONE}
    stop_grace_period: 1800s
    restart: unless-stopped
    shm_size: 268435456
    networks:
      - main
    read_only: true
    tmpfs:
      - /var/run/postgresql
    cap_drop:
      - NET_RAW
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 4G
  nextcloud-aio-nextcloud:
    container_name: nextcloud-aio-nextcloud
    depends_on:
      nextcloud-aio-database:
        condition: service_started
        required: false
      nextcloud-aio-redis:
        condition: service_started
        required: false
      nextcloud-aio-fulltextsearch:
        condition: service_started
        required: false
      nextcloud-aio-imaginary:
        condition: service_started
        required: false
    image: nextcloud/aio-nextcloud:${NEXTCLOUD_VERSION}
    user: 0:0
    init: true
    expose:
      - 9000
      - 9001
    volumes:
      - ${NEXTCLOUD_DATA}:/var/www/html:rw
      - ${NEXTCLOUD_DATADIR}:/mnt/ncdata:rw
      #- ${NEXTCLOUD_MOUNT}:${NEXTCLOUD_MOUNT}:rw
      #- ${NEXTCLOUD_TRUSTED_CACERTS_DIR}:/usr/local/share/ca-certificates:ro
    environment:
      - POSTGRES_HOST=${DATABASE_HOST}
      - POSTGRES_PORT=5432
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=nextcloud_database
      - POSTGRES_USER=nextcloud
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_HOST_PASSWORD=${REDIS_PASSWORD}
      - NC_DOMAIN=${NC_DOMAIN}
      - ADMIN_USER=admin
      - ADMIN_PASSWORD=${NEXTCLOUD_PASSWORD}
      - NEXTCLOUD_DATA_DIR=/mnt/ncdata
      - OVERWRITEHOST=${NC_DOMAIN}
      - OVERWRITEPROTOCOL=https
      - TURN_SECRET=${TURN_SECRET}
      - SIGNALING_SECRET=${SIGNALING_SECRET}
      - ONLYOFFICE_SECRET=${ONLYOFFICE_SECRET}
      - CLAMAV_ENABLED=${CLAMAV_ENABLED}
      - ONLYOFFICE_ENABLED=${ONLYOFFICE_ENABLED}
      - COLLABORA_ENABLED=${COLLABORA_ENABLED}
      - COLLABORA_HOST=${COLLABORA_HOST}
      - TALK_ENABLED=${TALK_ENABLED}
      - ONLYOFFICE_HOST=${ONLYOFFICE_HOST}
      - UPDATE_NEXTCLOUD_APPS=${UPDATE_NEXTCLOUD_APPS}
      - TZ=${TIMEZONE}
      - IMAGINARY_ENABLED=${IMAGINARY_ENABLED}
      - IMAGINARY_HOST=${IMAGINARY_HOST}
      - PHP_UPLOAD_LIMIT=${NEXTCLOUD_UPLOAD_LIMIT}
      - PHP_MEMORY_LIMIT=${NEXTCLOUD_MEMORY_LIMIT}
      - FULLTEXTSEARCH_ENABLED=${FULLTEXTSEARCH_ENABLED}
      - FULLTEXTSEARCH_HOST=${FULLTEXT_HOST}
      - PHP_MAX_TIME=${NEXTCLOUD_MAX_TIME}
      - STARTUP_APPS=${NEXTCLOUD_STARTUP_APPS}
      - ADDITIONAL_APKS=${NEXTCLOUD_ADDITIONAL_APKS}
      - ADDITIONAL_PHP_EXTENSIONS=${NEXTCLOUD_ADDITIONAL_PHP_EXTENSIONS}
      - INSTALL_LATEST_MAJOR=${INSTALL_LATEST_MAJOR}
      - FULLTEXTSEARCH_PASSWORD=${FULLTEXTSEARCH_PASSWORD}
      - REMOVE_DISABLED_APPS=${REMOVE_DISABLED_APPS}
      - APACHE_PORT=${APACHE_PORT}
      - IMAGINARY_SECRET=${IMAGINARY_SECRET}
    stop_grace_period: 600s
    restart: unless-stopped
    networks:
      - main
    cap_drop:
      - NET_RAW
    deploy:
      resources:
        limits:
          cpus: "8"
          memory: 8G
  nextcloud-aio-notify-push:
    container_name: nextcloud-aio-notify-push
    image: nextcloud/aio-notify-push:${NOTIFY_VERSION}
    user: 0:0
    init: true
    expose:
      - 7867
    volumes:
      - ${NEXTCLOUD_DATA}:/nextcloud:ro
    environment:
      - NC_DOMAIN=${NC_DOMAIN}
      - NEXTCLOUD_HOST=${NEXTCLOUD_HOST}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_HOST_PASSWORD=${REDIS_PASSWORD}
      - POSTGRES_HOST=${DATABASE_HOST}
      - POSTGRES_PORT=5432
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=nextcloud_database
      - POSTGRES_USER=nextcloud
    restart: unless-stopped
    networks:
      - main
    read_only: true
    cap_drop:
      - NET_RAW
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 4G
  nextcloud-aio-redis:
    container_name: nextcloud-aio-redis
    image: nextcloud/aio-redis:${REDIS_VERSION}
    user: 568:0
    init: true
    expose:
      - 6379
    environment:
      - REDIS_HOST_PASSWORD=${REDIS_PASSWORD}
      - TZ=${TIMEZONE}
    volumes:
      - ${REDIS_DATA}:/data:rw
    restart: unless-stopped
    networks:
      - main
    read_only: true
    cap_drop:
      - NET_RAW
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 4G
  nextcloud-aio-collabora:
    container_name: nextcloud-aio-collabora
    image: nextcloud/aio-collabora:${COLLABORA_VERSION}
    init: true
    expose:
      - 9980
    environment:
      - aliasgroup1=https://${NC_DOMAIN}:443
      - extra_params=--o:ssl.enable=false --o:ssl.termination=true
        --o:mount_jail_tree=false --o:logging.level=warning
        --o:home_mode.enable=true ${COLLABORA_SECCOMP_POLICY}
        --o:remote_font_config.url=https://${NC_DOMAIN}/apps/richdocuments/settings/fonts.json
      - dictionaries=${COLLABORA_DICTIONARIES}
      - TZ=${TIMEZONE}
      - server_name=${NC_DOMAIN}
      - DONT_GEN_SSL_CERT=1
    restart: unless-stopped
    networks:
      - main
    cap_add:
      - MKNOD
      - SYS_ADMIN
    cap_drop:
      - NET_RAW
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 4G
  nextcloud-aio-onlyoffice:
    container_name: nextcloud-aio-onlyoffice
    image: nextcloud/aio-onlyoffice:${ONLYOFFICE_VERSION}
    user: 0:0
    init: true
    expose:
      - 80
    environment:
      - TZ=${TIMEZONE}
      - JWT_ENABLED=true
      - JWT_HEADER=AuthorizationJwt
      - JWT_SECRET=${ONLYOFFICE_SECRET}
    volumes:
      - ${ONLYOFFICE_DATA}:/var/lib/onlyoffice:rw
    restart: unless-stopped
    networks:
      - main
    cap_drop:
      - NET_RAW
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 4G
  nextcloud-aio-imaginary:
    container_name: nextcloud-aio-imaginary
    image: nextcloud/aio-imaginary:${IMAGINARY_VERSION}
    init: true
    expose:
      - 9000
    environment:
      - TZ=${TIMEZONE}
      - IMAGINARY_SECRET=${IMAGINARY_SECRET}
    restart: unless-stopped
    cap_add:
      - SYS_NICE
    cap_drop:
      - NET_RAW
    networks:
      - main
    read_only: true
    tmpfs:
      - /tmp
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 4G
  nextcloud-aio-fulltextsearch:
    container_name: nextcloud-aio-fulltextsearch
    image: nextcloud/aio-fulltextsearch:${FULLTEXT_VERSION}
    user: 568:0
    init: false
    expose:
      - 9200
    environment:
      - TZ=${TIMEZONE}
      - ES_JAVA_OPTS=-Xms512M -Xmx512M
      - bootstrap.memory_lock=true
      - cluster.name=nextcloud-aio
      - discovery.type=single-node
      - logger.org.elasticsearch.discovery=WARN
      - http.port=9200
      - xpack.license.self_generated.type=basic
      - xpack.security.enabled=false
      - FULLTEXTSEARCH_PASSWORD=${FULLTEXTSEARCH_PASSWORD}
    volumes:
      - ${FULLTEXT_DATA}:/usr/share/elasticsearch/data:rw
    restart: unless-stopped
    networks:
      - main
    cap_drop:
      - NET_RAW
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 4G
`
```
