### DISCUSSION TITLE
Help Needed: Configuring Nextcloud AIO to Use SMB-Mounted Host Path for User Data Directory

### DISCUSSION THREAD

**Discussion by socratesprime** [nextcloud/all-in-one#5223] [Questions] [answered]
Hello,

I'm having trouble getting Nextcloud AIO to use a specific host path as the user data directory, and I would appreciate any guidance!

### Setup Details:
- Fresh installation of Nextcloud AIO (Docker container using `docker-compose`) on an **Ubuntu 22.04.4 LTS VM**.
- Nginx is configured, and the GUI works perfectly. I’m able to create users and upload files without any issues.
- My goal is to store all user data on a host path mapped to an SMB share: `/home/sfrog/Nextcloud_User_Data_SMB`. 
- This directory is owned by the `www-data` user and is automatically mounted via **autofs**. Writing to the directory works fine using the `www-data` user outside of the container.

### The Problem:
Despite configuring the `docker-compose.yml` to map the SMB-mounted directory for Nextcloud user data, the files uploaded through the Nextcloud GUI aren’t being saved in this directory. Here's the relevant portion of my `docker-compose.yml`:

```yaml
volumes:
  - /home/sfrog/Nextcloud_User_Data_SMB:/mnt/ncdata  # User data location
environment:
  - NEXTCLOUD_DATADIR=/mnt/ncdata  # Setting the data directory
```

When I upload files through the GUI, I expect them to appear in `/home/sfrog/Nextcloud_User_Data_SMB`, but the folder remains empty.

**Important Note:**
- Since Nextcloud doesn’t allow changing the data directory after installation, no changes have been made to the `docker-compose.yml` after the initial setup. The data directory was configured at installation to avoid this issue.

### Troubleshooting:
1. **Access Check:**  
   I verified that the Docker container can access the host path. Inside the `nextcloud-aio-mastercontainer`, I created a test file:
   ```bash
   sudo docker exec -it nextcloud-aio-mastercontainer bash
   touch /mnt/ncdata/testfile2.txt
   ```
   The file appeared in the host directory as expected, confirming the path is mapped correctly.

2. **File Location:**  
   I also checked where the files were actually being uploaded by running:
   ```bash
   sudo docker exec --user www-data -it nextcloud-aio-nextcloud ls /mnt/ncdata
   ```
   This command showed the user folder and the uploaded files, but they’re not reflected in the host path.

### Conclusion:
It seems like the `ncdata` path is mapped correctly on the **mastercontainer**, but for some reason, it’s not working the same way inside the `nextcloud-aio-nextcloud` container. I’m not sure if I’ve misconfigured something or if there’s a specific step I’m missing to get the SMB mount working as expected.

I’m relatively new to this, so I’m open to suggestions. I don’t mind starting from scratch since this is a fresh installation. I’d appreciate any help in fixing this issue. I've already spent the entire weekend on this, and I’m running out of ideas (and patience)! 😅

### Other Info:
- The SMB share is mounted using autofs, and I can confirm that it's stable and accessible outside the container.
- Permissions on `/home/sfrog/Nextcloud_User_Data_SMB` are set to `www-data:www-data`, and I’ve tested writing to it as `www-data` without any issues.
- Let me know if logs or specific config details are needed to assist with troubleshooting.

### A Copy of my `docker-compose.yml`:

```yaml
version: '3.8'

services:
  nextcloud:
    image: nextcloud/all-in-one:latest
    init: true
    restart: always
    container_name: nextcloud-aio-mastercontainer
    volumes:
      - nextcloud_aio_mastercontainer:/mnt/docker-aio-config
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /home/sfrog/Nextcloud_User_Data_SMB:/mnt/ncdata  # Mapping user data location
    ports:
      - 8080:8080
    environment:
      - APACHE_PORT=11000
      - APACHE_IP_BINDING=0.0.0.0
      - NC_TRUSTED_PROXIES="172.19.0.1"  # Adjust as per your Docker network
      - NEXTCLOUD_DATADIR=/mnt/ncdata  # Setting the data directory
      - SKIP_DOMAIN_VALIDATION=true

volumes:
  nextcloud_aio_mastercontainer:
    name: nextcloud_aio_mastercontainer
```

Thanks in advance for any help!

**Comment by Zoey2936** [comment]
I think you minder understood how it works:
NEXTCLOUD_DATADIR should be /home/sfrog/Nextcloud_User_Data_SM
also you don't need to mount /home/sfrog/Nextcloud_User_Data_SMB, AIO does this for you
and NC_TRUSTED_PROXIES does nothing, you can remove it

**Reply by socratesprime** [reply]
Thanks for the help!

If I understand correctly, you are suggesting that I make the following changes to the docker-compose.yaml file:


### Suggested Changes to the `docker-compose.yml`:

```yaml
version: '3.8'

services:
  nextcloud:
    image: nextcloud/all-in-one:latest
    init: true
    restart: always
    container_name: nextcloud-aio-mastercontainer
    volumes:
      - nextcloud_aio_mastercontainer:/mnt/docker-aio-config
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 8080:8080
    environment:
      - APACHE_PORT=11000
      - APACHE_IP_BINDING=0.0.0.0
      - NEXTCLOUD_DATADIR=/home/sprime/Nextcloud_User_Data_SMB  # Setting the data directory
      - SKIP_DOMAIN_VALIDATION=true

volumes:
  nextcloud_aio_mastercontainer:
    name: nextcloud_aio_mastercontainer
```
