### DISCUSSION TITLE
PHP memory setting

### DISCUSSION THREAD

**Discussion by mikebakke** [nextcloud/all-in-one#5282] [Questions] [answered]
### Steps to reproduce
1. configy  NEXTCLOUD_MEMORY_LIMIT=1024M
2. execute OCC command in nextcloud container
3. See message about minimum php memory not set

### Expected behavior 
No message about PHP minimum memory

### Actual behavior 
Example:
97f0e810663e:/var/www/html# sudo -u www-data php occ status

Warning: Failed to set memory limit to 0 bytes (Current memory usage is 2097152 bytes) in Unknown on line 0
The current PHP memory limit is below the recommended value of 512MB.
  - installed: true
  - version: 29.0.6.1
  - versionstring: 29.0.6
  - edition: 
  - maintenance: false
  - needsDbUpgrade: false
  - productname: Nextcloud
  - extendedSupport: false

### Other information
```
version: "3.6"

volumes:
  nextcloud_aio_mastercontainer:
    name: nextcloud_aio_mastercontainer # This line is not allowed to be changed

services:
  nextcloud:
    image: nextcloud/all-in-one:latest # Must be changed to 'nextcloud/all-in-one:latest-arm64' when used with an arm64 CPU
    restart: "unless-stopped"
    container_name: nextcloud-aio-mastercontainer # This line is not allowed to be changed
    volumes:
      - nextcloud_aio_mastercontainer:/mnt/docker-aio-config # This line is not allowed to be changed
      - /var/run/docker.sock:/var/run/docker.sock:ro # May be changed on macOS, Windows or docker rootless. See the applicable documentation
    ports:
      - 8087:8080
    environment: # Is needed when using any of the options below
       - APACHE_PORT=11000 # Is needed when running behind a reverse proxy. See https://github.com/nextcloud/all-in-one/blob/main/reverse-proxy.md
       - TALK_PORT=3477 # This allows to adjust the port that the talk container is using.
       - NEXTCLOUD_DATADIR=/mnt/external/aio/datadir
       - NEXTCLOUD_MEMORY_LIMIT=1024M
       - NEXTCLOUD_MOUNT=/mnt/external/aio/hostdir
       - COLLABORA_SECCOMP_DISABLED=false # Setting this to true allows to disable Collabora's Seccomp feature. See https://github.com/nextcloud/all-in-one#how-to-disable-collaboras-seccomp-feature
       - SIG-PROXY=false
#       - SKIP_DOMAIN_VALIDATION=true
```
