### DISCUSSION TITLE
Can not use Collabora to edit documents, Nextcloud Office never loads

### DISCUSSION THREAD

**Discussion by nogweii** [nextcloud/all-in-one#5326] [Questions] [answered]
I've had 3 problems, one of which I solved by doing a little more research:

1. Collabora was crashing due to it's inability to apply a seccomp profile. That was resolved with a full restart of the containers after adding the `COLLABORA_SECCOMP_DISABLED=true` environment variable to my master container. (Aside: Is there a way to restart specific containers with updated settings beyond restarting *everything*?) :heavy_check_mark: 
2. `/hosting/discovery` doesn't appear to work, it always times out. Nextcloud gives up after 5 seconds, and connecting directly with my reverse proxy set to a 60 seconds window it still times out. Increasing it to an hour (!) still doesn't work, curl gives up before then instead.
3. Nextcloud can't get a token from richdocuments, that returns a 503 internal error, though I haven't been able to find any log messages associated with it to debug further. I hope that if problem 2 is resolved, this should be fixed as well.  

I'm running AIO on my Synology NAS behind a nginx reverse proxy, here is my current compose file:

```yaml
services:
  nextcloud-aio-mastercontainer:
    image: nextcloud/all-in-one:latest
    init: true
    restart: always
    container_name: nextcloud-aio-mastercontainer # This line is not allowed to be changed as otherwise AIO will not work correctly
    volumes:
      - nextcloud_aio_mastercontainer:/mnt/docker-aio-config # This line is not allowed to be changed as otherwise the built-in backup solution will not work
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 11008:8080
    environment:
      - APACHE_PORT=11000 # Is needed when running behind a web server or reverse proxy (like Apache, Nginx, Cloudflare Tunnel and else). See https://github.com/nextcloud/all-in-one/blob/main/reverse-proxy.md
      - COLLABORA_SECCOMP_DISABLED=false # Setting this to true allows to disable Collabora's Seccomp feature. See https://github.com/nextcloud/all-in-one#how-to-disable-collaboras-seccomp-feature
      - NEXTCLOUD_DATADIR=/volume1/docker/nextcloud-aio/data
      - NEXTCLOUD_UPLOAD_LIMIT=10G # Can be adjusted if you need more. See https://github.com/nextcloud/all-in-one#how-to-adjust-the-upload-limit-for-nextcloud
      - NEXTCLOUD_MAX_TIME=3600 # Can be adjusted if you need more. See https://github.com/nextcloud/all-in-one#how-to-adjust-the-max-execution-time-for-nextcloud
      - NEXTCLOUD_MEMORY_LIMIT=512M # Can be adjusted if you need more. See https://github.com/nextcloud/all-in-one#how-to-adjust-the-php-memory-limit-for-nextcloud
      - NEXTCLOUD_TRUSTED_CACERTS_DIR=/volume1/terminal/pub-certs # CA certificates in this directory will be trusted by the OS of the nexcloud container (Useful e.g. for LDAPS) See See https://github.com/nextcloud/all-in-one#how-to-trust-user-defined-certification-authorities-ca
      - NEXTCLOUD_ENABLE_DRI_DEVICE=true # See https://github.com/nextcloud/all-in-one#how-to-enable-hardware-transcoding-for-nextcloud
      - WATCHTOWER_DOCKER_SOCKET_PATH=/var/run/docker.sock

volumes:
  nextcloud_aio_mastercontainer:
    name: nextcloud_aio_mastercontainer # This line is not allowed to be changed as otherwise the built-in backup solution will not work
```

My nginx reverse proxy is a remote dedicated box running Arch Linux and nginx version 1.26.2. All other nextcloud paths and features seem to work.

I have no community containers enabled at the moment, and have disabled Nextcloud Talk. I have enabled Collabora, ClamAV, FullTextSearch, and Imaginary. This is a fairly fresh install, no files or other data has been uploaded outside of a random `.otf` file I've created. I've installed the [gpodder](https://github.com/thrillfall/nextcloud-gpodder/), [RePod](https://git.crystalyx.net/Xefir/repod/src/branch/main), and [OIDC user backend](https://github.com/nextcloud/user_oidc) apps, adding a couple of users. The behavior still happens with the AIO-generated `admin` account though. I have even updated Nextcloud itself to 30 in order to get the latest version of the richdocuments app.

I'd love some help in troubleshooting this, as I'm at a loss as to the underlying details. Parsing through the container logs for nextcloud, apache, and collabora doesn't reveal any details to me about why the discovery document isn't loading. Especially since everything else loads correctly, what is special about Collabora that causes it to fail?
