### DISCUSSION TITLE
can't access /whiteboard

### DISCUSSION THREAD

**Discussion by punkyard** [nextcloud/all-in-one#5339] [Questions] [answered]
### Steps to reproduce
1. update aio to latest version with whiteboard container
2. settings menu shows whiteboard's URL and settings
3. whiteboard icon is not displayed in icons bar
4. domain.net/whiteboard read 'page not found'

### Expected behavior 
new icon for whiteboard  app in icons bar

### Actual behavior 
no icon in the icons bar for whiteboard app

#### Host OS debian 11

```
version: "3.8"
volumes:
  nextcloud_aio_mastercontainer:
    name: nextcloud_aio_mastercontainer
services:
  nextcloud:
    image: nextcloud/all-in-one:latest
    restart: always
    container_name: nextcloud-aio-mastercontainer
    volumes:
      - nextcloud_aio_mastercontainer:/mnt/docker-aio-config
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 8895:8080
    environment:
     - APACHE_PORT=11000
     - APACHE_IP_BINDING=0.0.0.0
     - APACHE_DISABLE_REWRITE_IP=1
     - NEXTCLOUD_TRUSTED_DOMAINS=
     - TRUSTED_PROXIES= 172.22.0.0/16
     - NEXTCLOUD_MOUNT=/mnt/nextcloud-aio/
     - NEXTCLOUD_UPLOAD_LIMIT=1G
     - NEXTCLOUD_MEMORY_LIMIT=4096M
     - NEXTCLOUD_ADDITIONAL_APKS=imagemagick libpq-dev
     - NEXTCLOUD_ADDITIONAL_PHP_EXTENSIONS=imagick pgsql
     - TALK_PORT=3478
     - OVERWRITEPROTOCOL=https
```

#### Output of `sudo docker info`
```
Client: Docker Engine - Community
 Version:    27.3.1
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.17.1
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.29.7
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Server Version: 27.3.1
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7f7fdf5fed64eb6a7caf99b3e12efcf9d60e311c
 runc version: v1.1.14-0-g2c9f560
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 5.10.0-32-amd64
 Operating System: Debian GNU/Linux 11 (bullseye)
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 7.759GiB
 Name: 
 ID: 
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

#### Other valuable info 
I used a personal excalidraw instance on this server in an external link before and have tried whiteboard app before on this aio instance

### Whiteboard container's logs:
```
2024-09-27T21:43:06.706995498Z Connection to nextcloud-aio-redis (172.22.0.7) 6379 port [tcp/redis] succeeded!
2024-09-27T21:43:07.742890129Z 
2024-09-27T21:43:07.743049055Z > whiteboard@1.0.2 server:start
2024-09-27T21:43:07.743057231Z > node websocket_server/main.js
2024-09-27T21:43:07.743061238Z 
2024-09-27T21:43:09.846404577Z Setting up Redis Streams adapter
2024-09-27T21:43:09.850523015Z Redis Streams adapter set up successfully
2024-09-27T21:43:09.861099439Z Listening on port: 3002
2024-09-27T21:43:09.861301025Z Server started successfully on port 3002
```

I haven't found anything docs for installing whiteboard with aio, maybe i didn't do it right for the first time.
Can I post any more details of my config?
Am i the only one to run into this issue?
