### DISCUSSION TITLE
Curl resolves hostnames to incorrect IP addresses

### DISCUSSION THREAD

**Discussion by JUMBUZI** [nextcloud/all-in-one#5355] [Questions] [answered]
### Steps to reproduce
1. Install Fulltextsearch or Docker Socket Proxy

### Expected behavior 
The nextcloud container can reach Fulltextsearch or Docker Socket Proxy containers

### Actual behavior 
curl resolves the hostname incorrectly and fails to connect
![image](https://github.com/user-attachments/assets/547f1daa-f0c2-439a-a8c4-51c2f0a70d0b)
192.168.1.10 is a response from my router and not the IP of the Docker Socket Proxy container. Other programs resolve the IP correctly.

#### Host OS 
Debian 12

#### Output of `sudo docker info`
```
Client: Docker Engine - Community
 Version:    27.3.1
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.17.1
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.29.7
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 19
  Running: 17
  Paused: 0
  Stopped: 2
 Images: 21
 Server Version: 27.3.1
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7f7fdf5fed64eb6a7caf99b3e12efcf9d60e311c
 runc version: v1.1.14-0-g2c9f560
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 6.1.94-sriov
 Operating System: Debian GNU/Linux 12 (bookworm)
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 15.58GiB
 Name: cloud
 ID: dd0bb86f-b321-4fa3-8ca2-7f3f0868f77c
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
```

#### Docker run command or docker-compose file that you used
```
services:
  nextcloud:
      container_name: nextcloud-aio-mastercontainer
      volumes:
        - 'nextcloud_aio_mastercontainer:/mnt/docker-aio-config'
        - '/var/run/docker.sock:/var/run/docker.sock:ro'
      environment:
        - APACHE_PORT=11000
        - NEXTCLOUD_DATADIR=/mnt/nextcloud
        - NEXTCLOUD_MOUNT=/mnt/nextcloud-vault
      ports:
        - '8080:8080'
      image: nextcloud/all-in-one:beta
      restart: always

volumes:
  nextcloud_aio_mastercontainer:
    name: nextcloud_aio_mastercontainer
```

#### Other valuable info 
Fixed in c-ares 1.33.1 now in the alpine 3.20 stable repository
![image](https://github.com/user-attachments/assets/55019e3e-0edc-429a-8883-373cbc8f472e)
