### DISCUSSION TITLE
ver. 9.7.0: "nextcloud-aio-memories" doesn't have an access to Nvidia GPU and can't do HW transcoding

### DISCUSSION THREAD

**Discussion by shperrung** [nextcloud/all-in-one#5450] [Questions] [answered]
Hi!

After Nextcloud-AIO update from ver 9.6.0 to 9.7.0 Memories doesn't use HW transcoding with NVENC acceleration. nvidia-smi command inside  "nextcloud-aio-memories" container doesn't show a presence of Nvidia GPU. However, if I create external go-vod container based on the same image "radialapps/go-vod:latest" and set its address:port in Nextcloud-AIO Memories app, NVENC will work but very slowly. This external go-vod returns information about GPU in response on nvidia-smi.

### Steps to reproduce
1. Install Nextcloud-AIO version 9.6.0
2. Setup HW transcoding on Nvidia GPU in Memories with success.
3. Update Nextcloud-AIO to version 9.7.0 and loose HW transcode in Memories.

### Expected behavior  
Nvidia GPU is accessible inside "nextcloud-aio-memories" container and adequate response on `nvidia-smi`. Transcoding videos with Nvenc capabilities in Memories app
--
### Actual behavior 
Memories app doesn't paly video when "acceleration with NVENC" is enabled.  `nvidia-smi` command inside "nextcloud-aio-memories" container returns `bash: nvidia-smi: command not found`

#### Host OS 
Debian 12 (Openmediavault 7)
#### Output of `sudo docker info`
`~$ docker info
Client: Docker Engine - Community
 Version:    27.3.1
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.17.1
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.29.7
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 45
  Running: 43
  Paused: 0
  Stopped: 2
 Images: 51
 Server Version: 27.3.1
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 nvidia runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7f7fdf5fed64eb6a7caf99b3e12efcf9d60e311c
 runc version: v1.1.14-0-g2c9f560
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 6.8.12-2-pve
 Operating System: Debian GNU/Linux 12 (bookworm)
 OSType: linux
 Architecture: x86_64
 CPUs: 16
 Total Memory: 62.72GiB
 Name: omv6
 ID: 6I4Q:3WBL:UVNA:MNFF:ZUYY:E6JI:UXLY:L7YC:2EY5:ODVU:UPQB:5HIZ
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false`
#### Docker run command or docker-compose file that you used
see attached [aio_compose.txt](https://github.com/user-attachments/files/17451783/aio_compose.txt)

#### Other valuable info

**Comment by szaimen** [comment, marked as answer]
Hi, the community container for memories does indeed not support nvidia gpus yet afaik. This is missing first: https://github.com/nextcloud/all-in-one/pull/5132

**Comment by shperrung** [comment]
Thank you for clear answer.
For those, who still wants to utilize their nvidia, use external container with go-vod attached to "nextcloud-aio" docker network:
```
services:
  memories:
    image: radialapps/go-vod
    restart: always
    networks:
      - go-vod-ext
    environment:
      - NEXTCLOUD_HOST=https://aio.YOUR_DOMAIN.duckdns.org
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - GPU=all
    #devices:
      #- /dev/dri:/dev/dri
    volumes:
      - /docker/aiodata:/mnt/ncdata:ro
      - /mnt/pool:/mnt/pool:ro
    runtime: nvidia
networks:
  go-vod-ext:
    name: nextcloud-aio
    external: true
```

You will get second "go-vod" container named "go-vod-memories-1" based on the same image as "nextcloud-aio-memories" but it's powered with NVENC.
Use in Memories "external transcoder" settings this: "Connection address (same as bind if local): **go-vod-memories-1:47788**".
