### DISCUSSION TITLE
Installation of Nextcloud AIO on new Truenas Scale 24.10.0 (Electric Eel)

### DISCUSSION THREAD

**Discussion by ghost** [nextcloud/all-in-one#5506] [Wiki]
1. Create a dataset on your Scale instance for your docker containers / stacks (e.g. /mnt/tank/docker)
2. Install dockge app (Apps -> Discover Apps -> search Dockge -> Install -> In the Dockge Configuration select:
- Port for Dockge (standard is 5001)
- Hostpath folder for stacks /mnt/tank/docker
- Hostpath folder for dockge data /mnt/tank/docker/dockge
 
3. Go to the Dockge Webui http://<TRUENASIP:5001> and create a new Stack for the AIO Mastercontainer

```
services:
  nextcloud:
    image: nextcloud/all-in-one:latest # Must be changed to 'nextcloud/all-in-one:latest-arm64' when used with an arm64 CPU
    restart: always
    container_name: nextcloud-aio-mastercontainer
    volumes:
      - nextcloud_aio_mastercontainer:/mnt/docker-aio-config
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 8080:8080
    environment:
      - APACHE_PORT=11000
      - NEXTCLOUD_DATADIR=/mnt/tank/docker/nextcloud_aio/data # Allows to set the host directory for Nextcloud's datadir. See https://github.com/nextcloud/all-in-one#how-to-change-the-default-location-of-nextclouds-datadir
      - NEXTCLOUD_MOUNT=/mnt/tank/docker/nextcloud_aio # Allows the Nextcloud container to access the chosen directory on the host. See https://github.com/nextcloud/all-in-one#how-to-allow-the-nextcloud-container-to-access-directories-on-the-host
      - NEXTCLOUD_MEMORY_LIMIT=4096M
networks: {}
volumes:
  nextcloud_aio_mastercontainer:
    name: nextcloud_aio_mastercontainer
```
4. Deploy the Stack and Nextcloud AIO is running on your Truenas Scale

**Comment by danni-storm** [comment]
I've been excited about this during the beta period and just updated to 24.10. However, can't we also use the custom 'Install via YAML' option? This would, in theory, easily allow management through the TrueNAS WebUI and skip having to worry about external volumes on a different pool working within the Dockge environment.

(edit) I believe you could also use the CLI/SSH and deploy the old fashioned way with a `docker-compose.yaml` and `docker compose up -d`. But it's not clear to me if the UI will pick up the manually created container.

**Reply by ghost** [reply]
I am sure you can, but for my part I prefer a dedicated Docker stacks application like dockge or portainer.
The UI is so much better than the Truenas one.
As always with Linux - there are 1000 ways that lead to Rome.
I migrated my whole docker host today to Truenas Scale  using the way above and it works like a charm.

**Reply by danni-storm** [reply]
Currently my TrueNAS server is an underpowered i5 6500 on an old Lenovo board so I have been debating how I want to migrate as I prefer not to use a network to transfer data to containers on another machine, even if it is a dedicated 10Gb line separate from the main network. However, I don't think 4 ancient threads would be near sufficient for my workload. Hell even my test Jellyfin container peaked the 2 cores I gave it for hours while is scraped my collection.

I could also move everything over slowly and then do a quick transplant of hardware when I am done so I can keep my R5 2600. Hmmm choices. 🤔

**Reply by ghost** [reply]
I'm running everything on ASRock Rack B650D4U-2L2T with a AMD Ryzen 7 PRO 5750GE with Radeon Graphics (35W TDP), 128GB ECC RAM virtualized on Proxmox.
Proxmox has its own 2VDEV Mirrored ZFS Pool with 4x Micron 5300 Max SSDs on the MBs SATA Ports.
16x HBA is passed through to Truenas (for spinning rust).
Docker containers previously ran on a dedicated Arch VM using an NFS mount on Truenas Core.
After the upgrade  to Truenas Scale now the Arch VM is gone and all Docker containers are running directly on Truenas Scale.
My Jellyfin is running in a dedicated non privileged Proxmox LXC with iGPU passed through with only with one CPU core due to the passed through iGPU doing the heavy load.

**Comment by orrinwitt** [comment]
I would really like to be able to do this directly through the truenas custom app/yaml file implementation, but I can't get the above yaml to work that way. Does anyone know why that would be?

**Reply by danni-storm** [reply]
I was able to use the following docker compose yaml config without any issues. It's not my favorite setup due to the way the custom yaml app is shown in the UI but I didn't want to bother passing a bunch of directories through to Dockge.

```yaml
networks: {} # I think this was added by the TrueNAS Docker daemon
services:
  nextcloud:
    container_name: nextcloud-aio-mastercontainer
    environment:
      - APACHE_PORT=11000
      - APACHE_IP_BINDING=IP_TO_EXPOSE_TO_PROXY
      - NEXTCLOUD_DATADIR=DIR_TO_NC_DATASET
      - NEXTCLOUD_MEMORY_LIMIT=4096M
      - NEXTCLOUD_UPLOAD_LIMIT=50G
      - NEXTCLOUD_MAX_TIME=36000
    image: nextcloud/all-in-one:latest
    ports:
      - '8080:8080'
    restart: always
    volumes:
      - nextcloud_aio_mastercontainer:/mnt/docker-aio-config
      - /var/run/docker.sock:/var/run/docker.sock:ro
volumes:
  nextcloud_aio_mastercontainer:
    name: nextcloud_aio_mastercontainer
```
