### DISCUSSION TITLE
Notify Push Container won't start - permission denied

### DISCUSSION THREAD

**Discussion by umoenks** [nextcloud/all-in-one#5580] [Questions] [answered]
### Steps to reproduce
1. Install Nextcloud AIO v9.8.0
2. Start containers

### Expected behavior 
All containers are running after waiting for some time, showing in Nexcloud AIO

> **Containers**
> 
> 🟢 Apache (Running)
> 🟢 Database (Running)
> 🟢 Nextcloud (Running)
> 🟢 Notify Push (Stopped)
> 🟢 Redis (Running)
> 🟢 Collabora (Running)
> 🟢 Imaginary (Running) 

### Actual behavior 
The Notify Push container will never leave the "Starting" status and shows up as

> 🟡 Notify Push (Starting)

Its log says something like
```
2024-11-11T22:30:29.944309069Z [FATAL tini (7)] exec /start.sh failed: Permission denied
2024-11-11T22:30:31.331426401Z [FATAL tini (7)] exec /start.sh failed: Permission denied
2024-11-11T22:30:32.232970931Z [FATAL tini (6)] exec /start.sh failed: Permission denied
2024-11-11T22:30:33.494759794Z [FATAL tini (7)] exec /start.sh failed: Permission denied
2024-11-11T22:30:35.550828418Z [FATAL tini (8)] exec /start.sh failed: Permission denied
```

A never-ending Google journey did not bring any clue, file permissions of ```notify_push``` in the ```nextcloud-aio-nextcloud-data``` seemed OK (```o=rx```).
I then thought maybe starting the container manually, outside from AIO, will bring more information. And indeed: while invoking the container manually, e.g. by ```docker run --env NEXTCLOUD_HOST="nextcloud" --env POSTGRES_HOST="postgres" --env REDIS_HOST="redis" nextcloud/aio-notify-push:latest```, the following lines repeat in an endless loop on the console:
```
Waiting for Nextcloud to start...
/start.sh: line 17: /bin/sleep: Permission denied
/start.sh: line 15: /usr/bin/nc: Permission denied
```

I also tested 9.9.0/9.7.0/9.6.0: For all of these, Nextcloud AIO shows
> 🟡 Notify Push (Starting)

Nextcloud AIO 9.5.1 gives me a full running stack:

> **Containers**
> 🟢 Apache (Running)
> 🟢 Database (Running)
> 🟢 Nextcloud (Running)
> 🟢 Notify Push (Stopped)
> 🟢 Redis (Running)
> 🟢 Collabora (Running)
> 🟢 Imaginary (Running)

I hope, this status can somehow be reproduced in AIO 9.8.0 and later. 😊

I have to admit, aside from this: NC AIO is paramount! ⛰

#### Host OS 
Ubuntu 22.04.3 LTS 5.15.0-124-generic x86_64 GNU/Linux

#### Output of `sudo docker info`
```
Client: Docker Engine - Community
 Version:    24.0.6
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.11.2
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.21.0
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 35
  Running: 16
  Paused: 0
  Stopped: 19
 Images: 54
 Server Version: 24.0.6
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 61f9fd88f79f081d64d6fa3bb1a0dc71ec870523
 runc version: v1.1.9-0-gccaecfc
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 5.15.0-124-generic
 Operating System: Ubuntu 22.04.3 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 7.578GiB
 Name: host
 ID: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
 Docker Root Dir: /media/host-ssd/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

#### Docker run command or docker-compose file that you used

```
version: "3.8"

volumes:
  nextcloud_aio_mastercontainer:
    name: nextcloud_aio_mastercontainer # This line is not allowed to be changed

services:
  nextcloud:
    image: nextcloud/all-in-one:latest # Must be changed to 'nextcloud/all-in-one:latest-arm64' when used with an arm64 CPU
    restart: always
    container_name: nextcloud-aio-mastercontainer # This line is not allowed to be changed
    volumes:
      - nextcloud_aio_mastercontainer:/mnt/docker-aio-config # This line is not allowed to be changed
      - /var/run/docker.sock:/var/run/docker.sock:ro # May be changed on macOS, Windows or docker rootless. See the applicable documentation. If adjusting, don't forget to also set 'DOCKER_SOCKET_PATH'!
    ports:
      - 80:80 # Can be removed when running behind a web server or reverse proxy (like Apache, Nginx and else). See https://github.com/nextcloud/all-in-one/blob/main/reverse-proxy.md
      - 8080:8080
      - 8443:8443 # Can be removed when running behind a web server or reverse proxy (like Apache, Nginx and else). See https://github.com/nextcloud/all-in-one/blob/main/reverse-proxy.md

```
