### DISCUSSION TITLE
Error: It seems like you did not give the mastercontainer volume the correct name?

### DISCUSSION THREAD

**Discussion by arvigeus** [nextcloud/all-in-one#567] [Questions] [answered]
I am using docker-compose + caddy as a reverse proxy. Here's what I get in logs:

```
Trying to fix docker.sock permissions internally...
Creating docker group internally with id 998
It seems like you did not give the mastercontainer volume the correct name?
Container stopped
```

My docker-compose:

```yaml
  nextcloud-aio-mastercontainer:
    restart: unless-stopped
    image: "nextcloud/all-in-one:latest"
    container_name: nextcloud-aio-mastercontainer
    hostname: nextcloud-aio-mastercontainer
    ports:
      - "8080:8080"
    environment:
      - APACHE_PORT=11000
    volumes:
      - "${CONFIG}/nc/:/mnt/docker-aio-config"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
```

My Caddyfile:

```
https://nextcloud.{$DOMAIN}:443 {
    header Strict-Transport-Security max-age=31536000;
    reverse_proxy localhost:11000
}

nc.{$DOMAIN} {
    reverse_proxy https://localhost:8080 {
        transport http {
            tls_insecure_skip_verify
        }
    }
}
```

Missing something?
