### DISCUSSION TITLE
Caddy Independent Reverse Proxy Configuration

### DISCUSSION THREAD

**Discussion by acetousk** [nextcloud/all-in-one#569] [Questions] [answered]
I've looked at the discussion at #553 and I've basically come upon a similar problem. This is a similar problem (as mentioned in #543) to #543. 

It looks like both [nginx proxy](https://github.com/nginx-proxy/nginx-proxy) and other automatic discovery reverse proxies require some configuration. 

After looking at the [apache container](https://github.com/nextcloud/all-in-one/blob/main/Containers/apache/Dockerfile) dockerfile and the [master container](https://github.com/nextcloud/all-in-one/blob/77fa851391f83095bbf85a596d9a540437228fee/Containers/mastercontainer/Dockerfile) dockerfile both it look like the configuration is very Caddy proxy manager specific.

Are there any plans or prs that would be accepted and collaborated on to make it possible for other reverse proxies like nginx or/and traefik to be able to have configuration files and an official setup (like: #491 #450 #447)? It would require some work to make the dockerfiles flexible enough to enable different configuration files and code necessary to make that happen.

**Comment by szaimen** [comment]
Hello, I see we have to drastically improve the reverse proxy documentation. I already have some ideas but will probably not come to it before this afternoon.

**Reply by acetousk** [reply]
No worries. Thanks for letting me know.

**Comment by szaimen** [comment, marked as answer]
Hello, please follow the reworked reverse proxy documentation:  https://github.com/nextcloud/all-in-one/blob/main/reverse-proxy.md
Feedback is welcome!

**Reply by acetousk** [reply]
@szaimen Is there a docker-compose equivalent to the all-in-one? In [nextcloud/docker](https://github.com/nextcloud/docker/blob/master/.examples/docker-compose/with-nginx-proxy/postgres/apache/docker-compose.yml) the best I've found doesn't include collabora, backups, talk, clamav, watchtower, etc. It doesn't need to include the mastercontainer, or domaincheck

I realize you probably don't know the answer to this, but:

I've been trying to figure out how to use nginx proxy with the acme companion to connect to the APACHE_PORT of 11000, but it's got HSTS error.

![image](https://user-images.githubusercontent.com/29029373/167036828-7b21fcdb-6405-43ce-baa7-7573083c265b.png)


Is there a way to disable HSTS on a browser or nginx?

**Reply by szaimen** [reply]
> @szaimen Is there a docker-compose equivalent to the all-in-one? In [nextcloud/docker](https://github.com/nextcloud/docker/blob/master/.examples/docker-compose/with-nginx-proxy/postgres/apache/docker-compose.yml) the best I've found doesn't include collabora, backups, talk, clamav, watchtower, etc.

You can build it on your own... Otherwise what You might be interested is this: https://github.com/nextcloud/all-in-one/issues/557

> I've been trying to figure out how to use nginx proxy with the acme companion to connect to the APACHE_PORT of 11000, but it's got HSTS error.

~~Please try again by starting from scratch and following the reverse proxy config from top to bottom.~~ I just realized that you run nginx-proxy which is not documented, yet. What does your current config look like?

**Reply by acetousk** [reply]
Also in https://github.com/nextcloud/all-in-one/blob/main/reverse-proxy.md#nginx where are you supposed to add it to the nginx.conf and are there other ways to add it like with a [virtual host configuration file](https://github.com/nginx-proxy/nginx-proxy#per-virtual_host-location-configuration)?

**Reply by szaimen** [reply]
I suppose it needs to be added in a virtual host config file, yes but I fear I don't know nginx-proxy good enough to be able to help here...
Question is if they always rely on docker labels or if there is a way to provide a completely custom virtual host file which does not at all rely on docker labels...

**Reply by acetousk** [reply]
> just realized that you run nginx-proxy which is not documented, yet. What does your current config look like?

This is it

```yml
version: '2'

services:
  nginx-proxy:
    build: proxy
    restart: unless-stopped
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro

  acme-companion:
    image: nginxproxy/acme-companion
    container_name: nginx-proxy-acme
    restart: unless-stopped
    environment:
      - DEFAULT_EMAIL=michael@dejc.com
    volumes_from:
      - nginx-proxy
    volumes:
      - certs:/etc/nginx/certs:rw
      - acme:/etc/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock:ro

  nextcloud:
    image: nextcloud/all-in-one:latest
    restart: unless-stopped
    container_name: nextcloud-aio-mastercontainer
    expose:
      - "8080"
    ports:
      - "8080:8080"
    environment:
      - APACHE_PORT=11000
      - LETSENCRYPT_HOST=aio.cloud.domain.com
      - VIRTUAL_HOST=aio.cloud.domain.com
      - VIRTUAL_PORT=8080
      - VIRTUAL_PROTO=https
    volumes:
      - nextcloud_aio_mastercontainer:/mnt/docker-aio-config
      - /var/run/docker.sock:/var/run/docker.sock:ro


volumes:
  conf:
  vhost:
  html:
  certs:
  acme:
  nextcloud_aio_mastercontainer:
```
