### DISCUSSION TITLE
Explicitly define nextcloud-aio docker network subnet

### DISCUSSION THREAD

**Discussion by MrRinkana** [nextcloud/all-in-one#5698] [Questions] [answered]
How does one proceed if it is desired to set a specific nextcloud-aio subnet?

<details>
<summary>I have played around with creating a network in my docker compose:</summary>

```yml
services:
    all-in-one:
        init: true
        container_name: nextcloud-aio-mastercontainer
        restart: always
        ports:
            - 8080:8080
        networks: # added this
            - nextcloud_network
        volumes:
            - nextcloud_aio_mastercontainer:/mnt/docker-aio-config
            - /var/run/docker.sock:/var/run/docker.sock:ro
        environment:
            - NEXTCLOUD_DATADIR=/srv/ncdata
            - APACHE_PORT=11000
            - APACHE_IP_BINDING=127.0.0.1
        image: nextcloud/all-in-one:latest

networks: # and this
    nextcloud_network:
        ipam:
          config:
            - subnet: 172.25.0.0/16 # this is what im trying to get the nextcloud container to reside within

volumes:
    nextcloud_aio_mastercontainer:
        external: true
        name: nextcloud_aio_mastercontainer
```

</details>

But that creates a network with a different name than "nextcloud-aio" (name-of-compose+nextcloud_network), and keeps the previous nextcloud-aio network as is, meaning the ip of the nextcloudcontainer does not change.

1. Does the network need to be called "nextcloud-aio" and in that case where do I specify its subnet?
2. How lasting is the default network? Will its subnet declaration last trough nextcloud container or master container updates? As in is explicitly specifying the subnet pointless?

The purpose of explicitly specifying a subnet is to allow the docker container to send mail to the host postfix (host postfix conf wants ip range, firewall rules, see for examle [here](https://help.nextcloud.com/t/docker-how-to-use-postfix-from-host/137151/6)), and so that the containers are easily moved to another host without needing to make new configurations (can keep configs)..
