### DISCUSSION TITLE
Caddy Docker Compose Example

### DISCUSSION THREAD

**Discussion by acetousk** [nextcloud/all-in-one#575] [Wiki]
Here's a docker-compose that I was able to get working with Caddy:
```yml
version: "3.8"

services:
  caddy:
    image: caddy:alpine
    restart: unless-stopped
    container_name: caddy
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./certs:/certs
      - ./config:/config
      - ./data:/data
      - ./sites:/srv
    network_mode: "host"

  nextcloud:
    image: nextcloud/all-in-one:latest
    restart: unless-stopped
    container_name: nextcloud-aio-mastercontainer
    ports:
      - "8080:8080"
    environment:
      - APACHE_PORT=11000
    volumes:
      - nextcloud_aio_mastercontainer:/mnt/docker-aio-config
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:
      - caddy

volumes:
  nextcloud_aio_mastercontainer:
    name: nextcloud_aio_mastercontainer
```

With this as the `Caddyfile`:
```Caddyfile
https://cloud.domain.com:443 {
    header Strict-Transport-Security max-age=31536000;
    reverse_proxy localhost:11000
}
```

I think that it'd be a good idea to have a `.examples` folder like in [nextcloud/docker](https://github.com/nextcloud/docker/tree/master/.examples). This would help make the documentation more clear and easier to setup for everyone. 

@szaimen Are you open to a PR to add this?

**Comment by szaimen** [comment]
Hello, I have something different in mind: See https://github.com/nextcloud/all-in-one/discussions/588

**Reply by szaimen** [reply]
feel free to add your working config there so that others can profit from your findings :)

**Reply by szaimen** [reply]
@acetousk what do you think about my idea? :)

**Reply by szaimen** [reply]
adding an example directory to this repo will not scale, hence my idea to allow anyone to post their working config into this thread...

**Reply by acetousk** [reply]
> adding an example directory to this repo will not scale, hence my idea to allow anyone to post their working config into this thread...

@szaimen What do you mean it won't scale?

**Reply by acetousk** [reply]
> @acetousk what do you think about my idea? :)

Not everyone looks at the discussions, they get lost in time, and you'd have to copy and paste multiple files to get your setup working. 

There's gotta be a better alternative, but honestly as long as there are compose files and the config I think it'll be helpful for future people using the aio.

**Reply by szaimen** [reply]
Adding many docker compose files to the repo is just too much maintenance work, imho. When we would change or add something we would need to change/address it everywhere. Having this in a thread allows the creators of each example to easily modify the examples themselves without the maintainer (me) needing to merge or create PRs...

**Reply by szaimen** [reply]
We already link to this thread from multiple places in the documentation itself and it is pinned so I don't think it will get lost :)

**Reply by szaimen** [reply]
@acetousk So would you be so kind to start adding your working example to the mentioned thread?

**Reply by Not-a-Cylon-010011100100111101010100** [reply]
sorry but just to say,. I've jsut been through the installation process and I couldn't agree more with @acetousk I've wasted so much time trying so many differnt variations of config files from the docs and then after all the to have to wade through a load of unorganised entries littered with comments and random setups - this couldn't be a more confusing/messier way to help people get started and honestly several times I was just going to give up and go somewhere else for it and so there is definitely a barrier to entry doing it this way. Setting this up should be as user-friendly as possible and honestly, you've got the polar opposite at the moment. I don't understand why we make this difficult and complicated  when it doesn't need to be. Also just to say that this is not referenced all over the place at all as a place to go for example config files - I stumbled across it in one place only - on the reverse proxy instructions page. This would be a million times better in GitHub - and I don't understand at all the argument that doing it there doesn't scale - how is an unorganised random load of messages mixed in with general chit chat in any way more scalable than  a GitHub repo. If maintenance work is needed then at least on GitHub it's controlled and maintained by the community -how are people going to go into other peoples comments to make updates

**Reply by acetousk** [reply]
It's not worth it to worry about the proxy to use. 

I ended up using the nextcloud AIO docker container that handles all the configuration, backups, and auto upgrades. Very handy if you want a good experience.

**Comment by matthijsbro** [comment]
How would you add other urls to the Caddyfile that need reverse proxy? (because it doesn't work for me now, but I don't know where the issue lies). For example like below?
```
https://cloud1.domain.com:443 {
    header Strict-Transport-Security max-age=31536000;
    reverse_proxy localhost:11000
}
https://cloud2.domain.com:443 {
    header Strict-Transport-Security max-age=31536000;
    reverse_proxy localhost:7843
}
```

**Reply by szaimen** [reply]
What exactly does not work? I suppose this should probably rather be asked in a caddy forum...

**Reply by matthijsbro** [reply]
I may not be in the right place at all. Just looking for someone who may know the answer. And nextcloud AIO asks to put network_mode=host, which I suspect to be part of my problem. The second container (vaultwarden, not nextcloud) says it's address is already in use:
`docker logs vaultwarden`
```
Error: Rocket.
[CAUSE] Bind(
    Os {
        code: 98,
        kind: AddrInUse,
        message: "Address already in use",
    },
)
```
I wonder if this is because of the `reverse_proxy localhost` appearing twice. Perhapse these should be explicit (internal, docker) ip? But nextcloud AIO's guide says how to find the ip if you cannot /want not use localhost, and that ip is just the host server ip. So... hope I still make sense.

**Reply by szaimen** [reply]
If you want to point caddy running on the host network onto vaultwarden, you would need to publish the vaultwarden port on the host so that localhost works.

**Reply by matthijsbro** [reply]
Thansk for your reply. I'm thinking about this, but I just don't know how to do this. How do I 'publish the port'? Just in docker-compose
```
ports:
  - 80:80
  - 443:443
```

**Reply by szaimen** [reply]
yes in the docker-compose of the vaultwarden container. however not using port 80 and 443 obvously but instead port 7843

**Reply by szaimen** [reply]
It should work like this:

```
https://nc.domain.com:443 {
    header Strict-Transport-Security max-age=31536000;
    reverse_proxy localhost:11000
}

https://vault.domain.com:443 {
#    header Strict-Transport-Security max-age=31536000;
    reverse_proxy localhost:7843
}
```

```
My docker-compose.yml

services:
  caddy:
    image: caddy:alpine
    restart: unless-stopped
    container_name: caddy
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./certs:/certs
      - ./config:/config
      - ./data:/data
      - ./sites:/srv
    network_mode: "host"

  nextcloud:
    image: nextcloud/all-in-one:latest
    restart: unless-stopped
    container_name: nextcloud-aio-mastercontainer
    ports:
      - "8080:8080"
    environment:
      - APACHE_PORT=11000
      - APACHE_IP_BINDING=127.0.0.1
    volumes:
      - nextcloud_aio_mastercontainer:/mnt/docker-aio-config
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:
      - caddy

  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: always
    environment:
      - WEBSOCKET_ENABLED=false  # Enable WebSocket notifications.
      - SIGNUPS_ALLOWED=false
      - DOMAIN=https://vault.domain.com
      - SMTP_HOST=mail.domain.com
      - SMTP_FROM=vault@domain.com
      - SMTP_PORT=587
      - SMTP_SECURITY=starttls
      - SMTP_USERNAME=vault@domain.com
      - SMTP_PASSWORD=123
      - ADMIN_TOKEN=123
    ports:
      - 127.0.0.1:7843:80
    volumes:
      - ./vw-data:/data

volumes:
  nextcloud_aio_mastercontainer:
    name: nextcloud_aio_mastercontainer # This line is not allowed to be changed
```

**Reply by matthijsbro** [reply]
Thank you so much! This works. I hope that one day I gain the wisdom and knowledge to understand why :) 
I'll study it a bit more.

**Comment by JPDF** [comment]
I just want to point out how important naming the volume is. If you don't name the volume the backup function wont work. I was having this issue when I followed the guide https://github.com/nextcloud/all-in-one/blob/main/reverse-proxy.md#caddy-recommended which lead me to this example.

This is what it should look like:
```
volumes:
  nextcloud_aio_mastercontainer:
    name: nextcloud_aio_mastercontainer # <-- VERY IMPORTANT
```
Since compose V2 is using the parent directory of the compose file as a prefix for the volumes to avoid naming collisions. This can be avoided by either naming the container as above or using the [external](https://docs.docker.com/compose/compose-file/#external) option.
As @szaimen also answered here https://help.nextcloud.com/t/borg-cant-backup/141117/6

**Reply by matthijsbro** [reply]
To my shame I must admit I did not try to use that backup function yet. I will today however, and as a precaution I added the name statement. Although a `docker volume ls` shows all the volumes named already.

**Reply by matthijsbro** [reply]
Hmm, at first site that worked to the contrary. I had:
```
volumes:
  nextcloud_aio_mastercontainer:
```
I added your line with `name:` but when I restarted backup failed with exactly the error you  linked to on help.nextcloud. Looking at my ip:8080 then suggested I install Nextcloud aio is if it wasn't installed. So I removed the line with `name:` again and voila, it is currently running a backup to /mnt/backup (where I mounted an external samba volume).

Perhaps to do with docker compose versions. But it was just an issue I didn't have :)

**Reply by JPDF** [reply]
Hm, intresting. Perhaps it is the compose versions. I am currently using v2.16.0. My compose file is in a folder named docker which resulted in volumes named with 'docker' as prefix `docker_nextcloud_aio_mastercontainer` which I noticed when the backup didn't find the configuration file since it is only looking for volume `nextcloud_aio_mastercontainer`. To resolve this without loosing my progress I manually created a new volume with the correct name and copied the content over, put the `name:` config in and rebuilt the container which was successful after that

**Comment by demuxer86** [comment]
I am coming from Truecharts with Traefik.   I need newer versions of nextcloud, and they are severely behind.  

When I try to deploy this stack, I get the following error.   I think I need to create volumes manually, but I'm not quite sure the right way to do it? 
`
Container vaultwarden Started Error response from daemon: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error mounting "/data/compose/54/Caddyfile" to rootfs at "/etc/caddy/Caddyfile": mount /data/compose/54/Caddyfile:/etc/caddy/Caddyfile (via /proc/self/fd/6), flags: 0x5000: not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type `

**Reply by szaimen** [reply]
Edit: yes, you need to add and edit the Caddyfile yourself in ./Caddyfile

**Reply by demuxer86** [reply]
Thank you for the reply.   Where I am stuck is, how do I make the caddy file?   I am using Portainer, and I am new to it, so it's not clear to me what steps I have to take before launching the yaml.     I assume I need to make a volume called ./Caddyfile, but I thought portainer normally creates these volumes automatically?

**Reply by szaimen** [reply]
./Caddyfile is relative to the current dir so not sure if that even works in portainer. Best to ask in a Portainer forum how to create this file in Portainer as I am not familiar with Portainer.

**Reply by demuxer86** [reply]
Ok thanks.  I will post back here if I can get it working.  I mean when I get it working.   When.... ahem...

**Reply by demuxer86** [reply]
> ./Caddyfile is relative to the current dir so not sure if that even works in portainer. Best to ask in a Portainer forum how to create this file in Portainer as I am not familiar with Portainer.

Also, just your opinion... I run Proxmox, so I could do this in a fresh Ubuntu Server install with native Docker-Compose.   That may be the best way to run Nextcloud anyway, as I would have the least obstacles over time with updates and configuration.     My question is, do I need to run Caddy in this container, or can I make a separate container for Caddy?   Reason being is I want to use Caddy for other services I have, and I don't want them to all go down if I have to restart or maintain the Nextcloud container.

**Reply by szaimen** [reply]
If you want to run other services as well you need a reverse proxy like caddy.

**Reply by BrianHenryIE** [reply]
I used absolute paths for the host Docker and Portainer are running on:
```
  caddy:
...
    volumes:
      - /home/brian/Caddyfile:/etc/caddy/Caddyfile
      - /home/brian/certs:/certs
      - /home/brian/config:/config
      - /home/brian/data:/data
      - /home/brian/sites:/srv
```

I created the Caddyfile with `nano Caddyfile` and pasted in the configuration from above (edited to match my domain), and also ran `mkdir certs; mkdir data; mkdir sites` because those folders didn't exist already.

**Reply by demuxer86** [reply]
OK I believe I have it working.   I can reach the caddy welcome page if I point to [portainer address]:80  

This means caddy is working, and listening on port 80

From here, I can't find any guide that is easy to understand for the caddyfile.   I can simply do this, but it's failing on ACME and TLS settings, 

hacura.cc {
    header Strict-Transport-Security max-age=31536000;
    reverse_proxy 10.20.30.253:9443
}


I feel like I have a lot more to add to my caddy file...


![image](https://user-images.githubusercontent.com/122547776/236323550-f3110d80-dd77-400f-b284-710959e147b4.png)

**Reply by BrianHenryIE** [reply]
My `Caddyfile` is:
```
https://cloud.brianhenry.ie:443 {
    header Strict-Transport-Security max-age=31536000;
    reverse_proxy localhost:11000
}
```

The differences are that your `https://` and `:443` are missing, and you're pointing to `9443`.

```
services:
  nextcloud:
    image: nextcloud/all-in-one:latest
...
    ports:
      # - 80:80 # Can be removed when running behind a web server or reverse proxy (like Apache, Nginx and else). See https://github.com/nextcloud/all-in-one/blob/main/reverse-proxy.md
      - 8080:8080
      # - 8443:8443 # Can be removed when running behind a web server or reverse proxy (like Apache, Nginx and else). See https://github.com/nextcloud/all-in-one/blob/main/reverse-proxy.md

    environment: # Is needed when using any of the options below
      - APACHE_PORT=11000 # Is needed when running behind a web server or reverse proxy (like Apache, Nginx and else). See https://github.com/nextcloud/all-in-one/blob/main/reverse-proxy.md
      - APACHE_IP_BINDING=127.0.0.1 # Should be set when running behind a web server or reverse proxy (like Apache, Nginx and else) that is running on the same host. See https://github.com/nextcloud/all-in-one/blob/main/reverse-proxy.md
 ```
 
Have you commented out the two ports which say "Can be removed" and uncommented Apache "Is needed" and "Should be set"?

And have you port forwarding configured on your router? I have `80:80` `443:443` ~~`8080:8080` and `8443:8443`~~, all pointing to my PI, ~~although I think the latter two should be removed!~~(edit: removed without issue)

**Reply by demuxer86** [reply]
> And have you port forwarding configured on your router? I have `80:80` `443:443` `8080:8080` and `8443:8443`, all pointing to my PI, although I think the latter two should be removed!

BALLS!!!!  You are brilliant!    I forgot my Traefik setup was on a different IP.    I changed my router to forward to Caddy, and started getting a response. 

Still not working with Portainer web gui.   Frustrated, I tried my firewall web GUI

IT WORKS!   

This is my caddyfile.   It does not need https:// or 443 port.   The Caddy docs explain it auto routes those anyway. 

```
hacura.cc {
        reverse_proxy 10.20.30.1:82
}

```

So now I am off to the races.   I don't know why Portainer web GUI won't connect.   I get a secure HTTPS response, but the GUI won't parse through.   I can deal with that for now, as I feel confident now I will get Nextcloud connected.   

Thank you so much for responding.   It's weird how far down rabbit holes you can go and completely miss the high level basics.

**Comment by WDMdanila** [comment]
Is there a way to configure caddy (and NC) in such a way that NC master container and Apache are actually fully behind it? What I want to achieve is that caddy docker is not in a host network so that I can point Caddy straight to the master container (which is technically done, but we still expose `8080` port for the master container as well as `11000` port for apache, which I would want to restrict to be reachable only through caddy)

Feels like such exposure of ports defeats the purpose of reverse proxy all together as services are reachable even without proxy.

Sorry for posting it here, did not know where to put such question and here seems like it would be the best place.

**Reply by devnoname120** [reply]
You can set `APACHE_IP_BINDING=127.0.0.1` to limit access of Apache to stuff running locally on your server. It's not a silver bullet but it protects you from accidental exposure to your local network and/or the public internet.

By default [`APACHE_IP_BINDING=0.0.0.0`](https://github.com/nextcloud/all-in-one/blob/7e56c912f742d96311388c9b6d2c9acf0e0f90a1/manual-install/sample.conf#L22) which means bind on all network interfaces — if you don't have a NAT in front of your server it even makes it publicly accessible.

**Comment by jm355** [comment]
This is what I did to use the dns check with duckdns:

~/Caddy/Dockerfile
```
FROM caddy:latest AS builder

RUN caddy add-package github.com/caddy-dns/duckdns

FROM caddy:latest

COPY --from=builder /usr/bin/caddy /usr/bin/caddy
```

~/compose.yaml
```
version: "3.6"

services:
  nextcloud-aio-mastercontainer:
    image: nextcloud/all-in-one:latest
    init: true
    restart: unless-stopped
    container_name: nextcloud-aio-mastercontainer
    ports:
      - "8080:8080"
    volumes:
      - nextcloud_aio_mastercontainer:/mnt/docker-aio-config
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - APACHE_PORT=11000
      - APACHE_IP_BINDING=127.0.0.1
      - BORG_RETENTION_POLICY=--keep-within=7d --keep-weekly=4 --keep-monthly=6 --keep-yearly=4
      - NEXTCLOUD_STARTUP_APPS=deck twofactor_totp tasks calendar contacts notes
      - NEXTCLOUD_ENABLE_DRI_DEVICE=true
      - SKIP_DOMAIN_VALIDATION=true
    depends_on:
      - caddy

  caddy:
    build: ./Caddy
    restart: unless-stopped
    container_name: caddy
    volumes:
     - ./Caddyfile:/etc/caddy/Caddyfile
     - ./certs:/certs
     - ./config:/config
     - ./data:/data
     - ./sites:/srv
    network_mode: host

volumes:
  nextcloud_aio_mastercontainer:
    name: nextcloud_aio_mastercontainer
```

~/Caddyfile
```
{
	auto_https disable_redirects
}
https://<domain>.duckdns.org:443 {
	reverse_proxy localhost:11000
	tls {
		dns duckdns <token>
	}
}
```

**Comment by nemr0** [comment]
i am new into this guys, I don't know where to place the caddy file how to add it in it's place for it all to run correctly.
i'm deploying docker-compose file using portainer.

**Reply by RealDishwash** [reply]
Store the Caddyfile in the same directory as your docker-compose.yml

**Comment by timur-g** [comment]
How could we run caddy via `docker run`, so not having caddyfile but settting somehow `reverse_proxy localhost:11000` ?
If that is possible, would `volumes` remain the same?
Is it OK that in Caddyfile I set twice `test.local`? Asking because I cannot pass Domain validation in AIO.
This whole complication with caddy is because I want to test AIO in local machine where ports 80 443 are already used.

**Comment by Scorg** [comment]
I could not get this setup to work for me. The domain check just does not pass. The request comes as http on port 443, as per the docs, to which Caddy replies with "Client sent an HTTP request to an HTTPS server." Sending the request straight to Apache on $APACHE_PORT correctly replies with the expected string. Nothing I have tried to make Caddy pass this request to Apache works.

**Comment by whacky671** [comment]
Hi, why does this approach not work on my setup? https://github.com/nextcloud/all-in-one/discussions/6084

**Comment by ramteid** [comment]
I use Caddy as a reverse proxy for multiple services, Nextcloud being one among them. I had to put Nextcloud into a bridged network on my Synology NAS. I had to modify the example above a bit to work for me. Using Nextcloud AIO 11.9.0.

`/volume1/docker/caddy/docker-compose.yml`
```
services:
  caddy:
    image: lucaslorentz/caddy-docker-proxy:2.8-alpine
    restart: unless-stopped
    environment:
      CADDY_DOCKER_ACME_EMAIL: info@example.com
      CADDY_DOCKER_CADDYFILE_PATH: /etc/caddy/Caddyfile
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./vol/caddy/config:/config
      - ./vol/caddy/data:/data
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
    ports:
      - "3080:80"
      - "3443:443"
    networks:
      - proxy
    logging:
      driver: local

networks:
  proxy:
    driver: bridge
    external: true
```

`/volume1/docker/caddy/Caddyfile`
```
https://mycloud.example.com:443 {
    header Strict-Transport-Security max-age=31536000;
    reverse_proxy 10.45.29.55:11000
}
```

`/volume1/docker/nextcloud/docker-compose.yml`
```
services:
  nextcloud:
    image: nextcloud/all-in-one:latest
    restart: unless-stopped
    container_name: nextcloud-aio-mastercontainer
    ports:
      - 8080:8080
    networks:
      - proxy
    environment:
      - NEXTCLOUD_DATADIR=/volume1/docker/nextcloud/data
      - APACHE_PORT=11000
      - APACHE_ADDITIONAL_NETWORK=proxy
    volumes:
      - /volume2/docker/nextcloud/data:/volume1/docker/nextcloud/data
      - nextcloud_aio_mastercontainer:/mnt/docker-aio-config
      - /var/run/docker.sock:/var/run/docker.sock:ro

networks:
  proxy:
    external: true

volumes:
  nextcloud_aio_mastercontainer:
    name: nextcloud_aio_mastercontainer
```

Testing configuration changes the full Nextcloud config must be pruned. I found this little script helpful, it deletes **all data and settings**. Use with caution!
`delete_with_caution.sh`
```
NC_PATH=/volume1/docker/nextcloud
cd "$NC_PATH"
docker compose down -v
sudo rm -rf "$NC_PATH/data"
mkdir "$NC_PATH/data"
docker ps -aq --filter "name=nextcloud" | xargs -r docker stop && docker ps -aq --filter "name=nextcloud" | xargs -r docker rm -f -v
sudo docker volume ls -q --filter "name=nextcloud" | xargs -r sudo docker volume rm
docker volume rm nextcloud_aio_apache nextcloud_aio_backup_cache nextcloud_aio_clamav nextcloud_aio_elasticsearch nextcloud_aio_mastercontainer nextcloud_aio_talk_recording nextcloud_aio_redis nextcloud_aio_nextcloud 2>/dev/null
``` 

To customize this example for you, you might want to:
- modify `info@example.com`
- modify `mycloud.example.com`
- change `10.45.29.55` into the **static** IP of _your_ server (it's the IP of my NAS)
- make sure your router forwards public port 80 to your server port `3080` and public port 443 to `3443` (or adjust these custom ports)
- modify `/volume1/docker/` to the location of your caddy and nextcloud dirs
- create the proxy network, e. g. `docker network create proxy`

**Reply by Beachttail** [reply]
What does the :ro mean at the end of the volume statement?

**Reply by ramteid** [reply]
It means read-only. That means, it cannot be modified.

**Comment by Felbi3000** [comment]
Hi! I need some help with the way how networks...work. Banging my head against that problem for three days now.

The example on top works like a charm for me. But I want to split the containers in two compose files to start them separately. For this, I created a new network "proxy" and put both containers inside it. For a test, the forwarding of a traefik/whoami container works with caddy, but nextcloud doesn't respond to the domain. I only get a 502 Bad Gateway in the console. 
I can get to the setup Screen, but cant go over the domain check obviously. The containers can see each other, but I'm sure, I don't get something else with the networks.

Caddy compose.yml
```
services:
  caddy:
    image: caddy:alpine
    restart: unless-stopped
    container_name: caddy
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - ./site:/srv
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - proxy

volumes:
  caddy_data:
  caddy_config:

networks:
  proxy:
    external: true

```
Caddyfile:
```
https://nextcloud.my-domain.com:443 {
    header Strict-Transport-Security max-age=31536000;
    reverse_proxy nextcloud-aio-mastercontainer:11000
}
```

Nextcloud compose.yml
```

services:
  nextcloud:
    image: nextcloud/all-in-one:latest
    container_name: nextcloud-aio-mastercontainer
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - APACHE_PORT=11000
      - APACHE_IP_BINDING=0.0.0.0
      - APACHE_ADDITIONAL_NETWORK=proxy
    volumes:
      - nextcloud_aio_mastercontainer:/mnt/docker-aio-config
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - proxy

volumes:
  nextcloud_aio_mastercontainer:
    name: nextcloud_aio_mastercontainer

networks:
  proxy:
    external: true

```

**Reply by dapzer** [reply]
Do you found solution for it?

**Reply by Felbi3000** [reply]
I just managed it today. My problem was the Caddyfile. It shouldn't connect to nextcloud-aio-mastercontainer:11000 but instead aio-apache:11000. I knew, that the mastercontainer opens up new container, but thought, that it routes the port through to the apache container.

So now it works. I still have a problem with the DDOS Protection, but I just have to find out how to add my reverse proxy to the trusted list.

**Reply by dapzer** [reply]
Can you share please your caddy file and docker compose with nextcloud?

**Comment by Felbi3000** [comment]
Don't forget to create the network first:
`docker network create proxy`

Caddyfile:
```
nextcloud.mydomain.com {
    header Strict-Transport-Security "max-age=31536000;"
    reverse_proxy nextcloud-aio-apache:11000
}
```

caddy compose.yml
```
services:
  caddy:
    image: caddy:alpine
    container_name: caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - ./site:/srv
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - proxy

volumes:
  caddy_data:
  caddy_config:

networks:
  proxy:
    external: true
```

Nextcloud compose.yml:
```
services:
  nextcloud:
    image: nextcloud/all-in-one:latest
    container_name: nextcloud-aio-mastercontainer
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - APACHE_PORT=11000
      - APACHE_IP_BINDING=0.0.0.0
      - APACHE_ADDITIONAL_NETWORK=proxy
      - NEXTCLOUD_TRUSTED_PROXIES=172.18.0.2 #Caddy Server, not sure if this works
    volumes:
      - nextcloud_aio_mastercontainer:/mnt/docker-aio-config
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - proxy

volumes:
  caddy_data:
  caddy_config:
  nextcloud_aio_mastercontainer:
    name: nextcloud_aio_mastercontainer

networks:
  proxy:
    external: true
```

**Reply by dapzer** [reply]
in my case it doesn't work, i don't know why, i don't see apache container at all and can't do curl from container inside

**Reply by Felbi3000** [reply]
So can you reach the mastercontainer at your-ip:8080 ?

**Reply by dapzer** [reply]
curl localhost:8080
Client sent an HTTP request to an HTTPS server.

**Reply by Felbi3000** [reply]
Try https://your-ip:8080

**Reply by dapzer** [reply]
i fixed it, i forgot  to open ports, thank you)

**Comment by WDMdanila** [comment]
Sharing relevant lines from my configuration that work for me.

My Caddyfile looks like this:
```
nextcloud.domain.name {
    encode
    reverse_proxy host.docker.internal:11000
}

aio.domain.name {
    encode
    reverse_proxy nextcloud:8080 {
        transport http {
            tls_insecure_skip_verify
        }
    }
}
```

And compose is like this:
```
volumes:
  nextcloud_aio_mastercontainer:
    name: nextcloud_aio_mastercontainer

networks:
  nextcloud:
    name: nextcloud
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/16

services:
  caddy:
    image: caddy:alpine
    restart: unless-stopped
    container_name: caddy
    networks:
      nextcloud:
        ipv4_address: 172.18.0.2
    extra_hosts:
       - "host.docker.internal:host-gateway"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./certs:/certs
      - ./config:/config
      - ./data:/data
      - ./sites:/srv

  nextcloud:
    image: nextcloud/all-in-one:latest
    restart: unless-stopped
    container_name: nextcloud-aio-mastercontainer
    networks:
      nextcloud:
        ipv4_address: 172.18.0.3
    environment:
      - APACHE_PORT=11000
      - APACHE_IP_BINDING=0.0.0.0
      - NEXTCLOUD_MOUNT=/mnt/nextcloud-nfs
      - ADDITIONAL_TRUSTED_PROXY=172.18.0.2
    volumes:
      - nextcloud_aio_mastercontainer:/mnt/docker-aio-config
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:
      - caddy
```
