### DISCUSSION TITLE
assure apache_container to keep same local IP after updates

### DISCUSSION THREAD

**Discussion by punkyard** [nextcloud/all-in-one#5847] [Questions] [answered]
hi
when containers are restarted, they won't necessarily be assigned to the same local IP address which can cause link breaking with external apps (ie Nginx with local IP bindings)

in AiO yaml file template, could it be possible to add network specs to assure the nextcloud-aio-apache container to be linked to the same local IP after each update and restart?

**Comment by szaimen** [comment]
Hi, honestly if you are using the private ip-address of the mastercontainer in your nginx config, you are doing something wrong...


Can you post your nginx config here and how did you install nginx? 

If it should be running as a separate container, can you also post its docker run command or docker compose file here?

**Comment by punkyard** [comment]
thanks Simon @szaimen for your reply and analysis

I made a mistake mentioning the `nextcloud-aio-mastercontainer`. I meant `nextcloud-aio-apache`

here is my yaml - in Portainer which allocates apache to 172.22.0.13 this time and mastercontainer to 172.22.0.3

```yaml
version: "3.8"
volumes:
  nextcloud_aio_mastercontainer:
    name: nextcloud_aio_mastercontainer #
services:
  nextcloud:
    image: nextcloud/all-in-one:latest
    restart: always
    container_name: nextcloud-aio-mastercontainer #
    volumes:
      - nextcloud_aio_mastercontainer:/mnt/docker-aio-config #
      - /var/run/docker.sock:/var/run/docker.sock:ro #
    ports:
      - 8895:8080
    environment:
     - APACHE_PORT=11000
     - APACHE_IP_BINDING=0.0.0.0
     - APACHE_DISABLE_REWRITE_IP=1
     - NEXTCLOUD_TRUSTED_DOMAINS=mydomain.net #123.345.456.789
     - TRUSTED_PROXIES= 172.22.0.0/16
     - NEXTCLOUD_MOUNT=/mnt/docker/nextcloud-aio/
     - NEXTCLOUD_UPLOAD_LIMIT=1G
     - NEXTCLOUD_MEMORY_LIMIT=4096M
     - NEXTCLOUD_ADDITIONAL_APKS=imagemagick libpq-dev
     - NEXTCLOUD_ADDITIONAL_PHP_EXTENSIONS=imagick pgsql
     - TALK_PORT=3478
     - OVERWRITEPROTOCOL=https
```

<img width="1295" alt="Capture d’écran 2025-01-13 à 19 09 36" src="https://github.com/user-attachments/assets/8848b27d-fe79-46b2-88c7-5a20512cb7b8" />


Next to it, i'm using Nginx Proxy Manager

<img width="486" alt="Capture d’écran 2025-01-13 à 19 23 13" src="https://github.com/user-attachments/assets/14d638d6-e2d0-41bf-833a-681b1332645c" />

**Reply by szaimen** [reply, marked as answer]
I see. Can you add NPM to the `nextcloud-aio` network and then use `nextcloud-aio-apache` instead of `172.22.0.13` in your NPM config?

**Comment by punkyard** [comment]
well.. Nginx network_mode is set to "host" as documentation requests (or requested 2 years ago ^^)

removing this broke all my proxies

```yaml
networks:
  default:
    external: true
    name: nextcloud-aio
```

are you asking to add this network to only **Nginx Prowy Manager**? 
Quid of all my other containers and docker compose yaml stacks?

doing this change, i can still access my NPM UI with public IP but it won't take my login and password.. 🥺
cool, i'm gonna spend the evening on this i guess
