### DISCUSSION TITLE
Domain validation issue and 502 error when using Nextcloud AIO with OMV, Docker Compose, Nginx Proxy Manager, and Cloudflare

### DISCUSSION THREAD

**Discussion by Bojo67** [nextcloud/all-in-one#5906] [Questions] [answered]
Hello Nextcloud AIO community,

I’m encountering an issue during the setup of Nextcloud AIO on my NAS running OpenMediaVault (OMV) with Docker Compose and Nginx Proxy Manager. I’m also using Cloudflare for DNS. Here’s my setup and the problem I’m facing:

My Setup:
NAS: OMV with Docker Compose and Nginx Proxy Manager.

![image](https://github.com/user-attachments/assets/46e132b8-5ebe-400a-864d-faa0f7f73749)

DNS: Cloudflare.

Docker Compose File:
I’m using the following `docker-compose.yml` file for Nextcloud AIO:

yaml
```
services:
  nextcloud-aio-mastercontainer:
    image: nextcloud/all-in-one:latest
    init: true
    restart: always
    container_name: nextcloud-aio-mastercontainer
    volumes:
      - nextcloud_aio_mastercontainer:/mnt/docker-aio-config
      - /var/run/docker.sock:/var/run/docker.sock:ro
    network_mode: bridge
    ports:
      - 8888:8080
    environment:
      APACHE_PORT: 11000
      APACHE_IP_BINDING: 0.0.0.0
      SKIP_DOMAIN_VALIDATION: true

volumes:
  nextcloud_aio_mastercontainer:
    name: nextcloud_aio_mastercontainer
```
The Problem:
Domain Validation Issue:
During the domain validation step, I’m forced to skip the domain validation (`SKIP_DOMAIN_VALIDATION: true`) because I always get the following error:

```
Domain does not point to this server or the reverse proxy is not configured correctly. See the mastercontainer logs for more details. ('sudo docker logs -f nextcloud-aio-mastercontainer')
I’ve confirmed that my DNS settings on Cloudflare are correct, and all my other reverse proxies (via Nginx Proxy Manager) are working fine.
```

502 Bad Gateway Error:
After skipping the domain validation, the containers install successfully, but when I try to access Nextcloud, I get a 502 Bad Gateway error. I’ve tried various configurations in Nginx Proxy Manager, but the issue persists.

What I’ve Tried:
Verified that my DNS records on Cloudflare are correct and pointing to my server.

Ensured that Nginx Proxy Manager is correctly configured to forward traffic to the Nextcloud AIO container.

Checked the logs of the `nextcloud-aio-mastercontainer` and other containers, but couldn’t find any obvious errors.

Tried adjusting the `APACHE_PORT` and `APACHE_IP_BINDING` settings, but it didn’t resolve the issue.

Questions:
1. Has anyone encountered a similar issue when using Nextcloud AIO with Nginx Proxy Manager and Cloudflare?

2. Are there any specific settings or configurations I might be missing in Nginx Proxy Manager or the `docker-compose.yml` file?

3. Is there a way to debug the 502 error further to pinpoint the root cause?

Any help or guidance would be greatly appreciated! Thank you in advance.

**Comment by Zoey2936** [comment]
does npm run in network mode host?

**Comment by Bojo67** [comment]
No, I left it as I installed it!
Like this

```
services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    network_mode: host
    ports:
      # These ports are in format <host-port>:<container-port>
      - '80:80' # Public HTTP Port
      - '443:443' # Public HTTPS Port
      - '8111:81' # Admin Web Port
      # Add any other Stream port you want to expose
      # - '21:21' # FTP
    volumes:
      - /pool/appdata/npm/data:/data
      - /pool/appdata/npm/letsencrypt:/etc/letsencrypt
    depends_on:
      - db
  db:
    image: 'jc21/mariadb-aria:latest'
    restart: unless-stopped
    volumes:
      - /pool/appdata/npm/mysql:/var/lib/mysql
```
