### DISCUSSION TITLE
Is it possible to set locations for aio volumes? Eg Postgres container data volume

### DISCUSSION THREAD

**Discussion by rowanmoul** [nextcloud/all-in-one#6020] [Questions] [answered]
Nextcloud AIO creates the following volumes for the various containers that it manages:
```
DRIVER    VOLUME NAME
local     nextcloud_aio_apache
local     nextcloud_aio_clamav
local     nextcloud_aio_database
local     nextcloud_aio_database_dump
local     nextcloud_aio_elasticsearch
local     nextcloud_aio_mastercontainer
local     nextcloud_aio_nextcloud
local     nextcloud_aio_redis
```
By default docker places these in it's internal volume directory at `/var/lib/docker/volumes`, for example:
`/var/lib/docker/volumes/nextcloud_aio_database/_data`

I would like to put these volumes in another location that not tied so closely to the host OS filesystem.
I know I could do this with a [manual install](https://github.com/nextcloud/all-in-one/tree/main/manual-install), but I appreciate the features provided by the master container.
I could also do this by changing the default docker volume directory, as described in [How to store the files/installation on a separate drive?](https://github.com/nextcloud/all-in-one?tab=readme-ov-file#how-to-store-the-filesinstallation-on-a-separate-drive), but such changes would not survive an OS update on my host system (TrueNAS SCALE - and no, I don't want to use the built-in nextcloud app).

If I define volumes like in the manual install compose file: https://github.com/nextcloud/all-in-one/blob/db81abed09f70b4919f26db5d5c455f415595f93/manual-install/latest.yml#L479-L499  except in the [main compose file](https://github.com/nextcloud/all-in-one/blob/main/compose.yaml) with specific mount points, for example:
```yaml
 volumes: 
   nextcloud_aio_apache: 
     name: nextcloud_aio_apache
     driver: local
     driver_opts:
       type: auto
       o: bind
       device: "/path/to/my/location/nextcloud_aio_apache"
```
 will it use them as defined, or will the master container overwrite the volume mount locations?

I will probably try this later, but it's a bit of a pain to spin up an instance of AIO just to try something due to the domain and ssl requirements.

**Comment by rowanmoul** [comment, marked as answer]
~~I just tested pre-defining the volumes like above, and the master container did indeed overwrite the mount points. So I guess this is not currently possible without either changing the system default or doing a manual install.~~

Update: I actually tried this again as I realized later that compose doesn't create volumes defined in the top level "volumes" if they are not referenced by at least one container. It looks like volumes will NOT be overwritten if they are pre-defined, which makes sense, as that could inadvertently cause data loss, so my above proposed method can work, but is certainly cumbersome (I had to make a dummy container just to force the volume creation).

Would there be any openness to adding an option to the master container to specify an alternate volume directory?

**Reply by juaaslo** [reply]
Hello!
It is not clear for me if you managed to make it work....I suspect you didn't but I ask just in case :)
I have created manually config and db volumes pointing to external HD disk, to make easier a possible migration to a different server, but they are not considered for nextcloud-aio-nextcloud and nextcloud-aio-database container creation.
Thanks and BR!

**Reply by rowanmoul** [reply]
Yes, I did get it to work and I'm actually running AIO on TrueNAS now!
I did exactly as I described above - I defined all of the volumes in the compose file and then created a dummy container to force it to create them. I kept the dummy container under a compose profile so that it doesn't have to be created every time I do a `compose up`.
I could have also just created the volumes manually with `docker volume create`, but having all of the volumes defined in the compose file is more like infrastructure as code, which I prefer.
The one thing that I did do manually is create a ZFS data set for each volume's target directory and set permissions on those datasets matching the ones that AIO sets automatically when the volumes are created in the docker volume directory. This step may not be necessary for a fresh install as each container should be able to set these permissions when they initialize for the first time, but I was migrating my installation from another location where the volumes had been created in the docker volume directory and I wanted to be 100% sure that it would "just work" when I ran `docker compose up`, which I am happy to report it did.

So in summary, if you define docker volumes with the correct names through some process outside of AIO, they will be used by the AIO containers.

_Just remember, with great power comes great responsibility. If you decide to create a docker volume for your Postgres container using the NFS driver to store the database on a network share, don't expect to have a good time 😉_

Here are the relevant parts of my compose file. I added this to the standard AIO compose file provided in this repo, but you could also run it separately. DO NOT USE THIS BLINDLY.
```yaml
services:
  bootstrap-volumes:
    container_name: bootstrap-volumes
    image: caddy:alpine # so we don't have to pull something new
    profiles:
      - bootstrap-volumes
    restart: no
    command: sh -c "echo hello"
    networks:
      - nextcloud-aio
    volumes:
      - nextcloud_aio_mastercontainer:/namc
      - nextcloud_aio_apache:/naap
      - nextcloud_aio_clamav:/nacav
      - nextcloud_aio_database:/nadb
      - nextcloud_aio_database_dump:/nadbd
      - nextcloud_aio_elasticsearch:/naes
      - nextcloud_aio_nextcloud:/nanc
      - nextcloud_aio_redis:/nard

volumes:
  nextcloud_aio_mastercontainer:
    name: nextcloud_aio_mastercontainer # This line is not allowed to be changed as otherwise the built-in backup solution will not work
    driver: local
    driver_opts:
      type: auto
      o: bind
      device: $NC_VOLUME_DIR/nextcloud_aio_mastercontainer
  nextcloud_aio_apache:
    name: nextcloud_aio_apache
    driver: local
    driver_opts:
      type: auto
      o: bind
      device: $NC_VOLUME_DIR/nextcloud_aio_apache
  nextcloud_aio_clamav:
    name: nextcloud_aio_clamav
    driver: local
    driver_opts:
      type: auto
      o: bind
      device: $NC_VOLUME_DIR/nextcloud_aio_clamav
  nextcloud_aio_database:
    name: nextcloud_aio_database
    driver: local
    driver_opts:
      type: auto
      o: bind
      device: $NC_VOLUME_DIR/nextcloud_aio_database
  nextcloud_aio_database_dump:
    name: nextcloud_aio_database_dump
    driver: local
    driver_opts:
      type: auto
      o: bind
      device: $NC_VOLUME_DIR/nextcloud_aio_database_dump
  nextcloud_aio_elasticsearch:
    name: nextcloud_aio_elasticsearch
    driver: local
    driver_opts:
      type: auto
      o: bind
      device: $NC_VOLUME_DIR/nextcloud_aio_elasticsearch
  nextcloud_aio_nextcloud:
    name: nextcloud_aio_nextcloud
    driver: local
    driver_opts:
      type: auto
      o: bind
      device: $NC_VOLUME_DIR/nextcloud_aio_nextcloud
  nextcloud_aio_redis:
    name: nextcloud_aio_redis
    driver: local
    driver_opts:
      type: auto
      o: bind
      device: $NC_VOLUME_DIR/nextcloud_aio_redis
```
