### DISCUSSION TITLE
Nextcloud AIO cannot be reached from the internet and internally - NPM, wireguard

### DISCUSSION THREAD

**Discussion by oerms** [nextcloud/all-in-one#6041] [Questions] [answered]
Hi all.

### Situation:
- I am trying to set up Nextcloud AIO behind a reverse proxy (NPM).
- The proxy and Nextcloud run on different machines.
- When setting up a simple httpd on the Nextcloud machine (no containers running) via `sudo busybox httpd -f -p 11000` this works flawlessly: The host is reached via `https://<mydomain>.de` and delivers the `index.html`. This shows to me that the reverse proxy (including SSL) and the routing/firewalling to the Nextcloud machine are set up correctly.
- I have used the https://github.com/nextcloud/all-in-one/blob/main/compose.yaml file with minor changes: disabled ports 80 and 8443, enabled Apache port 11000 and binding to `0.0.0.0`, set a data directory.

### Outcome so far:
- I am not able to connect to the Nextcloud web page via `https://<mydomain>.de`: Timeout/Infinite loading 
- The Nextcloud Container log shows:
```
2025-02-15T15:39:29.366487188Z 🛈 Configured callback URL: 
2025-02-15T15:39:29.366492696Z 
2025-02-15T15:39:34.409229948Z Failed to fetch discovery endpoint from https://<mydomain>.de
2025-02-15T15:39:34.409284142Z cURL error 28: Operation timed out after 5002 milliseconds with 0 bytes received (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://<mydomain>.de/hosting/discovery
```

### My own Troubleshooting:
- I tried to suppress the above error by enabling `SKIP_DOMAIN_VALIDATION: true` in the compose file. But this line is yielding the error
```
services.nextcloud-aio-mastercontainer.environment.SKIP_DOMAIN_VALIDATION contains true, which is an invalid type, it should be a string, number, or a null
```
I also tried with `True`, `yes`, etc. and the error remains the same. Type boolean is apparently not accepted...?
- I worked through https://github.com/nextcloud/all-in-one/blob/main/reverse-proxy.md#6-how-to-debug-things and did all, except the "Hairpin NAT" because I have no idea, how to to it.

### My questions:
- Is setting `SKIP_DOMAIN_VALIDATION: true` supposed to suppressing this curl command which is timing out?
- What other checks can I do to get an idea what is going wrong?

Thank you very much!

**Comment by szaimen** [comment]
Hi, please post the config of NPM here (screenshots as well as compose file) and please also post the whole compose file of AIO here.

**Comment by oerms** [comment]
Thank you for the quick reply!

- In the meantime I have tried a bit more, stripping down stuff, that I don't need yet. This included starting over and de-selecting all optional containers in the web interface during the initial AIO install.
- I have also commented out the `SKIP_DOMAIN_VALIDATION` line. During install, the domain was validated and the domain delivered the hash!
- Funnily enough, the message `Failed to fetch discovery endpoint` doesn't appear anymore. It might have been connected to some of the optional packages.
- But the result is the same: Host cannot be reached after successful install (all containers green).

Here the configs:

### NPM:
```
services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80' # Public HTTP Port
      - '443:443' # Public HTTPS Port
      - '81:81' # Admin Web Port

    environment:
      DISABLE_IPV6: 'true'

    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
```
![image](https://github.com/user-attachments/assets/fd52bb63-6798-4337-a0db-938d0a4281d4)
No locations.
![image](https://github.com/user-attachments/assets/43edd7fa-3f70-462d-a94c-4a5bb2e902ce)
![image](https://github.com/user-attachments/assets/ff6dfade-5620-4f8f-b899-75c73f693afc)

### AIO
```
services:
  nextcloud-aio-mastercontainer:
    image: nextcloud/all-in-one:latest
    init: true
    restart: always
    container_name: nextcloud-aio-mastercontainer # This line is not allowed to be changed as otherwise AIO will not work correctly
    volumes:
      - nextcloud_aio_mastercontainer:/mnt/docker-aio-config # This line is not allowed to be changed as otherwise the built-in backup solution will not work
      - /var/run/docker.sock:/var/run/docker.sock:ro # May be changed on macOS, Windows or docker rootless. See the applicable documentation. If adjusting, don't forget to also set 'WATCHTOWER_DOCKER_SOCKET_PATH'!
    network_mode: bridge # add to the same network as docker run would do
    ports:
      # - 80:80 # Can be removed when running behind a web server or reverse proxy (like Apache, Nginx, Caddy, Cloudflare Tunnel and else). See https://github.com/nextcloud/all-in-one/blob/main/reverse-proxy.md
      - 8080:8080
      # - 8443:8443 # Can be removed when running behind a web server or reverse proxy (like Apache, Nginx, Caddy, Cloudflare Tunnel and else). See https://github.com/nextcloud/all-in-one/blob/main/reverse-proxy.md
    environment: # Is needed when using any of the options below
      APACHE_PORT: 11000 # Is needed when running behind a web server or reverse proxy (like Apache, Nginx, Caddy, Cloudflare Tunnel and else). See https://github.com/nextcloud/all-in-one/blob/main/reverse-proxy.md
      APACHE_IP_BINDING: 0.0.0.0 # Should be set when running behind a web server or reverse proxy (like Apache, Nginx, Caddy, Cloudflare Tunnel and else) that is running on the same host. See https://github.com/nextcloud/all-in-one/blob/main/reverse-proxy.md
      NEXTCLOUD_DATADIR: /www/nextcloud_data # Allows to set the host directory for Nextcloud's datadir. ⚠️⚠️⚠️ Warning: do not set or adjust this value after the initial Nextcloud installation is done! See https://github.com/nextcloud/all-in-one#how-to-change-the-default-location-of-nextclouds-datadir
      NEXTCLOUD_UPLOAD_LIMIT: 20G # Can be adjusted if you need more. See https://github.com/nextcloud/all-in-one#how-to-adjust-the-upload-limit-for-nextcloud
      NEXTCLOUD_MEMORY_LIMIT: 2048M # Can be adjusted if you need more. See https://github.com/nextcloud/all-in-one#how-to-adjust-the-php-memory-limit-for-nextcloud

volumes: # If you want to store the data on a different drive, see https://github.com/nextcloud/all-in-one#how-to-store-the-filesinstallation-on-a-separate-drive
  nextcloud_aio_mastercontainer:
    name: nextcloud_aio_mastercontainer # This line is not allowed to be changed as otherwise the built-in backup solution will not work
```
(I have stripped the file from all commented environment variables.)

### Additional thoughts
What makes me think a bit in a different direction:
- When providing a small httpd via busybox (no docker container running), the server can be reached locally and from the internet via the NPM.
- During AIO setup phase (early in install procedure) the hash can be queried from the internet and from internally via the server IP.
- But once the install is complete, the nextcloud host can neither be reached from the internet, nor locally when using the IP directly and the apache port.
- What does the apache do differently than the other http servers? Does the apache not reply to the last hop when receiving TCP packages after is is configured? Is is a routing or firewall issue?

### iptables output
There are no firewall rules, that would prevent the page from loading:
```
Chain INPUT (policy ACCEPT)
target     prot opt source               destination

Chain FORWARD (policy DROP)
target     prot opt source               destination
DOCKER-USER  all  --  anywhere             anywhere
DOCKER-ISOLATION-STAGE-1  all  --  anywhere             anywhere
ACCEPT     all  --  anywhere             anywhere             ctstate RELATED,ESTABLISHED
DOCKER     all  --  anywhere             anywhere
ACCEPT     all  --  anywhere             anywhere
ACCEPT     all  --  anywhere             anywhere
ACCEPT     all  --  anywhere             anywhere             ctstate RELATED,ESTABLISHED
DOCKER     all  --  anywhere             anywhere
ACCEPT     all  --  anywhere             anywhere
ACCEPT     all  --  anywhere             anywhere

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination

Chain DOCKER (2 references)
target     prot opt source               destination
ACCEPT     tcp  --  anywhere             172.17.0.2           tcp dpt:http-alt
ACCEPT     tcp  --  anywhere             172.18.0.7           tcp dpt:11000

Chain DOCKER-ISOLATION-STAGE-1 (1 references)
target     prot opt source               destination
DOCKER-ISOLATION-STAGE-2  all  --  anywhere             anywhere
DOCKER-ISOLATION-STAGE-2  all  --  anywhere             anywhere
RETURN     all  --  anywhere             anywhere

Chain DOCKER-ISOLATION-STAGE-2 (2 references)
target     prot opt source               destination
DROP       all  --  anywhere             anywhere
DROP       all  --  anywhere             anywhere
RETURN     all  --  anywhere             anywhere

Chain DOCKER-USER (1 references)
target     prot opt source               destination
RETURN     all  --  anywhere             anywhere
```

### routing table
The standard gateway is my router and not the wireguard endpoint, from where the http request originated (NPM via wireguard).
```
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
0.0.0.0         192.168.xxxx.1     0.0.0.0         UG    0      0        0 ens18
172.17.0.0      0.0.0.0         255.255.0.0     U     0      0        0 docker0
172.18.0.0      0.0.0.0         255.255.0.0     U     0      0        0 br-20203c247efd
192.168.xxxx.0     0.0.0.0         255.255.255.0   U     0      0        0 ens18
```
