### DISCUSSION TITLE
Whiteboard container fails to start and because of it whole NC instance is not starting (NC container and Apache)

### DISCUSSION THREAD

**Discussion by WDMdanila** [nextcloud/all-in-one#6148] [Questions] [answered]
### Steps to reproduce
1. Do nothing, have auto-upgrade enabled
2. After upgrade on 8th of March Whiteboard either appeared or stopped starting correctly (I have not been looking at AIO interface for a long time as it was running perfectly well without any supervision)

### Expected behavior 

Whole setup works well after automatic upgrade (or updated rolled back if containers did not manage to start after the upgrade?)

### Actual behavior 

- HTTP 502 error on Caddy reverse proxy
- Whiteboard container stopped / dead (when trying to open logs it showed some error page)
- Apache and NextCloud containers showing as stopped on AIO interface. Logs in NextCloud container stated something like `waiting for apache` while logs in Apache stated `waiting for Nextcloud`

Restating containers did not help. Stopping all, unchecking Whiteboard and the starting seemed to solve the issue.

#### Host OS 

Ubuntu 22.04

#### Output of `sudo docker info`

```
Client: Docker Engine - Community
 Version:    28.0.1
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.21.1
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.33.1
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 17
  Running: 13
  Paused: 0
  Stopped: 4
 Images: 22
 Server Version: 28.0.1
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: local
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: runc io.containerd.runc.v2
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: bcc810d6b9066471b0b6fa75f557a15a1cbf31bb
 runc version: v1.2.4-0-g6c52b3f
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 5.15.0-134-generic
 Operating System: Ubuntu 22.04.5 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 7.566GiB
 Name: vps-540fa268
 ID: 842892ca-d966-4fcc-a995-31ddf92ad959
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  ::1/128
  127.0.0.0/8
 Live Restore Enabled: false
```

#### Docker run command or docker-compose file that you used

```
volumes:
  nextcloud_aio_mastercontainer:
    name: nextcloud_aio_mastercontainer

networks:
  nextcloud:
    name: nextcloud
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/16

services:
  caddy:
    image: caddy:alpine
    restart: unless-stopped
    container_name: caddy
    networks:
      nextcloud:
        ipv4_address: 172.18.0.2
    extra_hosts:
       - "host.docker.internal:host-gateway"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./certs:/certs
      - ./config:/config
      - ./data:/data
      - ./sites:/srv

  nextcloud:
    image: nextcloud/all-in-one:latest
    restart: unless-stopped
    container_name: nextcloud-aio-mastercontainer
    networks:
      nextcloud:
        ipv4_address: 172.18.0.3
    environment:
      - APACHE_PORT=11000
      - APACHE_IP_BINDING=0.0.0.0
      - NEXTCLOUD_MOUNT=/some/path
    volumes:
      - nextcloud_aio_mastercontainer:/mnt/docker-aio-config
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:
      - caddy
```

#### Other valuable info 

Do not have access to Whiteboard container but will try to re-enable it this week when have more time to play with it and will post logs here

Relevant Caddyfile configuration
```
{
    email SOME_EMAIL@www.www
}

nextcloud.domain.name {
    encode gzip
    reverse_proxy host.docker.internal:11000
}

aio.domain.name {
    reverse_proxy nextcloud:8080 {
        transport http {
            tls_insecure_skip_verify
        }
    }
}

```

#### Questions / Crucial points / Thoughts (not sure how to name this section)

1. Why the `Whiteboard` container is enabled by default?
2. Is there a mechanism that would rollback the upgrade or at least send a notification that something went wrong?
3. Why was NC waiting for Apache and Apache waiting for NC? (most probably I am confusing Apache from NC container vs Apache container, but want to double check that)
