### DISCUSSION TITLE
Support for protonmail-bridge-docker: IMAP server is not reachable

### DISCUSSION THREAD

**Discussion by kravitsjacob** [nextcloud/all-in-one#6154] [Questions] [answered]
I'm attempting to setup [protonmail-bridge-docker](https://github.com/shenxn/protonmail-bridge-docker) and nextcloud AIO on my VPS and am running into the "IMAP server is not reachable" issue. I know there have been several issues opened on each project about this specific issue, and they have been helpful to get to this point! However, I am still stuck. 

# Steps to Reproduce on my VPS
1) Run: `docker run --rm -it -v protonmail:/root shenxn/protonmail-bridge init` to initialize the protonmail bridge. Using `info` I get something like:
```
Configuration for <my_email>
IMAP Settings
Address:   127.0.0.1
IMAP port: 1143
Username:  <my_email>
Password:  <my_password>
Security:  STARTTLS

SMTP Settings
Address:   127.0.0.1
SMTP port: 1025
Username:  <my_email>
Password:  <my_password>
Security:  STARTTLS
```
2) Run the following docker compose (which I've been working on, so the problem could be here) using `docker compose up -d
`:
```
services:
  nextcloud-aio-mastercontainer:
    image: nextcloud/all-in-one:latest
    init: true
    restart: always
    container_name: nextcloud-aio-mastercontainer
    volumes:
      - nextcloud_aio_mastercontainer:/mnt/docker-aio-config 
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - shared_network
    ports:
      - 80:80
      - 8080:8080
      - 8443:8443

  protonmail-bridge:
    image: shenxn/protonmail-bridge
    container_name: protonmail-bridge
    ports:
      - "1025:25/tcp"  # Bind to localhost on port 1025
      - "1143:143/tcp" # Bind to localhost on port 1143
    restart: unless-stopped
    volumes:
      - protonmail:/root
    networks:
      - shared_network

volumes:
  nextcloud_aio_mastercontainer:
    name: nextcloud_aio_mastercontainer 
  protonmail:
    name: protonmail

networks:
  shared_network:
    driver: bridge
```
3) Test if one of the ports is working on host (successful): 
```
root@ubuntu:~# nc -zv 127.0.0.1 1025
Connection to 127.0.0.1 1025 port [tcp/*] succeeded!
```
4) Go into the nextcloud container and see if the port is working (successful): 
```
root@ubuntu:~# docker exec -it nextcloud-aio-mastercontainer /bin/sh
/var/www/docker-aio # nc -zv protonmail-bridge 25
Connection to protonmail-bridge (172.20.0.2) 25 port [tcp/smtp] succeeded!
```
5) Modify the config.php [as has been mentioned](https://github.com/nextcloud/server/issues/37329#issuecomment-1488147847). 
6) Submit information in nextcloud AIO GUI:
![image](https://github.com/user-attachments/assets/2378a684-a82e-4e95-be77-f01f3a42469b)
I've tried all the combinations of security settings, specifying the IP of the protonmail-bridge container directly, and different ports with no luck...

# Expected Behavior

I'm looking to be able to connect to the protonmail-bridge from nextcloud AIO. I realize that specifying the IP address of the protonmail-bridge container directly isn't ideal as this address could change. So, it would be nice if it was a stable solution.

# Closing

I apologize if the solution is easy, I am a little new to nextcloud and protonmail. I know that as of writing this, nextcloud is looking for someone to [maintain protonmail-bridge-docker as a community container](https://github.com/nextcloud/all-in-one/discussions/5150#discussion-7070667) but I was hoping a single docker compose could be a nice interim solution for users looking to get this up and running. I really believe in both the projects and am immensely grateful to each community for their support!

**Comment by szaimen** [comment, marked as answer]
Hi, as with all other external addons, you need to add also this container to the `nextcloud-aio` docker network in order to use its name inside Nextcloud. See e.g. https://github.com/nextcloud/all-in-one?tab=readme-ov-file#user_sql

**Reply by kravitsjacob** [reply]
@szaimen Thank you for the quick response. I also provide a complete set of instructions [below](https://github.com/nextcloud/all-in-one/discussions/6154#discussioncomment-12487371)!

**Comment by kravitsjacob** [comment]
Just wanted to provide a full recap of how I was able to connect [protonmail-bridge-docker](https://github.com/shenxn/protonmail-bridge-docker) with nextcloud AIO! This process works as of writing this answer, but I do not plan to maintain this answer - use at your own risk.

# Before you start
You will need to have [docker](https://www.docker.com/) installed. Check this by running `docker --version`. You should see a version number!

# Instructions
1. Place the following `docker-compose.yml` into a directory on your machine:
```
services:
  nextcloud-aio-mastercontainer:
    image: nextcloud/all-in-one:latest
    init: true
    restart: always
    container_name: nextcloud-aio-mastercontainer
    volumes:
      - nextcloud_aio_mastercontainer:/mnt/docker-aio-config # This line is not allowed to be changed as otherwise the built-in backup solution will not work
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 80:80
      - 8080:8080
      - 8443:8443

  protonmail-bridge:
    image: shenxn/protonmail-bridge
    container_name: protonmail-bridge
    ports:
      - "1025:25/tcp"  # Bind to localhost on port 1025
      - "1143:143/tcp" # Bind to localhost on port 1143
    restart: unless-stopped
    volumes:
      - protonmail:/root

volumes:
  nextcloud_aio_mastercontainer:
    name: nextcloud_aio_mastercontainer # This line is not allowed to be changed as otherwise the built-in backup solution will not work
  protonmail:
    name: protonmail
```
2. Navigate to that directory and initialize the protonmail bridge: `docker compose run protonmail-bridge init`
a. Follow the standard initialization process by running: `login`, `info` (note this information!), and `exit`
3. Install nextcloud AIO by running: `docker compose up -d`
4. Follow the standard nextcloud AIO setup.
5. Once all containers are running, add protonmail bridge to the nextcloud network: `docker network connect nextcloud-aio protonmail-bridge`
6. In the nextcloud Mail app the settings should be:
IMAP Host: `protonmail-bridge`
IMAP Security: None
IMAP Port: `143`
IMAP User: `<your_email>`
IMAP Password: `<password_from_bridge>`
SMTP Host: `protonmail-bridge`
SMTP Security: None
SMTP Port: `25`
SMTP User: `<your_email>`
SMTP Password: `<password_from_bridge>`

Note, this method did not require me to change the `config.php` file!
