### DISCUSSION TITLE
help to deploy AIO

### DISCUSSION THREAD

**Discussion by drixouuk** [nextcloud/all-in-one#6209] [Questions] [answered]
Hi, 
I am running OMV7 with a few services. I already use Nginx Proxy Manager to access my other services and manage my SSL certificates. I tried to deploy NC AIO, but I encountered a "Domaincheck container is not running" error during setup, right after getting the passphrase (I am accessing it through https://192.168.1.91:8888/).

![image](https://github.com/user-attachments/assets/c57f3cfb-81bc-4a83-905e-5f7cee07fe4a)

can someone check my yaml please :

```
services:
  nextcloud-aio-mastercontainer:
    image: nextcloud/all-in-one:latest
    init: true
    restart: always
    container_name: nextcloud-aio-mastercontainer
    volumes:
      - nextcloud_aio_mastercontainer:/mnt/docker-aio-config
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /data/mynex:/mnt/ncdata
    ports:
      - 8080:80
      - 8888:8080
    environment:
      - APACHE_PORT=11000
      - APACHE_IP_BINDING=0.0.0.0
      - NEXTCLOUD_DATADIR=/mnt/ncdata
      - NEXTCLOUD_MOUNT=/mnt/
      - SKIP_DOMAIN_VALIDATION=true

volumes:
  nextcloud_aio_mastercontainer:
    name: nextcloud_aio_mastercontainer

networks:
  default:
    name: nextcloud-aio
    external: true
```
