### DISCUSSION TITLE
I get a notification to update even though everything is up-to-date

### DISCUSSION THREAD

**Discussion by TheSimpleZ** [nextcloud/all-in-one#6302] [Questions] [answered]
### Steps to reproduce
1. No idea. It's been like that for a few weeks now. Just suddenly started happening.

### Expected behavior 
If the instance is up-to-date, no notification should appear. And preferably, if a notification does appear, it should only be shown to administrators, so we don't get flooded with users asking us to update the instance.

### Actual behavior 
This notification appears.
![Image](https://github.com/user-attachments/assets/23abd48c-8d74-4939-bf6b-3e8b9eef74aa)

Going to the AIO interface shows this:

![Image](https://github.com/user-attachments/assets/6bf20ea2-df8b-4d53-b41e-4e8e41b625fd)

#### Host OS 
Ubuntu 24.04.1.

#### Output of `sudo docker info`

```
Client: Docker Engine - Community
 Version:    27.2.1
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.16.2
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.29.2
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 38
  Running: 36
  Paused: 0
  Stopped: 2
 Images: 52
 Server Version: 27.2.1
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7f7fdf5fed64eb6a7caf99b3e12efcf9d60e311c
 runc version: v1.1.14-0-g2c9f560
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 6.8.0-51-generic
 Operating System: Ubuntu 24.04.1 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 16
 Total Memory: 31.21GiB
 Name: dodohub
 ID: ddba7c48-7524-4fa3-a0c6-3765fee033c4
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

#### Docker run command or docker-compose file that you used
```
nextcloud:
    image: nextcloud/all-in-one:latest
    restart: unless-stopped
    container_name: nextcloud-aio-mastercontainer
    environment:
      NEXTCLOUD_DATADIR: /tank/apps/nextcloud
      APACHE_PORT: 11000
      APACHE_IP_BINDING: 0.0.0.0
      NEXTCLOUD_MOUNT: /tank/data/media
    ports:
      - 8081:8080
    volumes:
      - nextcloud_aio_mastercontainer:/mnt/docker-aio-config
      - /tank/apps/nextcloud:/mnt/ncdata
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  nextcloud_aio_mastercontainer:
    name: nextcloud_aio_mastercontainer
```
