### DISCUSSION TITLE
Talk container is advertising its internal docker ip for calls

### DISCUSSION THREAD

**Discussion by deftmartian** [nextcloud/all-in-one#6356] [Questions] [answered]
I first noticed this in my firewall log when investigating why calls intermittently would not connect during calls.  It shows up as nextcloud talk clients wanting to connect to the docker internal ip. The talk container advertises its internal docker network ip (172.18.0.6).  This is obviously not routable, and appears to be confusing clients.

Chat works great -this issue only appears during calls.

My set up is nextcloud-aio on my docker host(fedora) behind my Caddy reverse proxy which is setup in OPNsense as a plugin.

Here is how the eturnal.yml ends up being set. 

```yaml
cd2fe4f76f09:/$ cat conf/eturnal.yml 
eturnal:
  listen:
    - ip: "::"
      port: 3478
      transport: udp
    - ip: "::"
      port: 3478
      transport: tcp
  log_dir: stdout
  log_level: warning
  secret: "secretkey"
  relay_ipv4_addr: "172.18.0.6"
  blacklist_peers:
  - recommended
  whitelist_peers:
  - 127.0.0.1
  - ::1
  - "172.18.0.6"
```

Here is my docker compose.

```yaml
services:
  nextcloud-aio-mastercontainer:
    image: nextcloud/all-in-one:latest
    init: true
    restart: always
    container_name: nextcloud-aio-mastercontainer # This line is not allowed to be changed as otherwise AIO will not work correctly
    volumes:
      - nextcloud_aio_mastercontainer:/mnt/docker-aio-config # This line is not allowed to be changed as otherwise the built-in backup solution will not work
      - /var/run/docker.sock:/var/run/docker.sock:ro # May be changed on macOS, Windows or docker rootless. See the applicable documentation. If adjusting, don't forget to also set 'WATCHTOWER_DOCKER_SOCKET_PATH'!
    ports:
      # - 80:80 # Can be removed when running behind a web server or reverse proxy (like Apache, Nginx, Cloudflare Tunnel and else). See https://github.com/nextcloud/all-in-one/blob/main/reverse-proxy.md
      - 192.168.15.15:8080:8080
      # - 8443:8443 # Can be removed when running behind a web server or reverse proxy (like Apache, Nginx, Cloudflare Tunnel and else). See https://github.com/nextcloud/all-in-one/blob/main/reverse-proxy.md
    environment: # Is needed when using any of the options below
      # AIO_DISABLE_BACKUP_SECTION: false # Setting this to true allows to hide the backup section in the AIO interface. See https://github.com/nextcloud/all-in-one#how-to-disable-the-backup-section
      APACHE_PORT: 11000 # Is needed when running behind a web server or reverse proxy (like Apache, Nginx, Cloudflare Tunnel and else). See https://github.com/nextcloud/all-in-one/blob/main/reverse-proxy.md
      APACHE_IP_BINDING: 192.168.15.15 # Should be set when running behind a web server or reverse proxy (like Apache, Nginx, Cloudflare Tunnel and else) that is running on the same host. See https://github.com/nextcloud/all-in-one/blob/main/reverse-proxy.md
      # BORG_RETENTION_POLICY: --keep-within=7d --keep-weekly=3 --keep-monthly=3  # Allows to adjust borgs retention policy. See https://github.com/nextcloud/all-in-one#how-to-adjust-borgs-retention-policy
      COLLABORA_SECCOMP_DISABLED: false # Setting this to true allows to disable Collabora's Seccomp feature. See https://github.com/nextcloud/all-in-one#how-to-disable-collaboras-seccomp-feature
      NEXTCLOUD_DATADIR: /mnt/ncdata # Allows to set the host directory for Nextcloud's datadir. ⚠️⚠️⚠️ Warning: do not set or adjust this value after the initial Nextcloud installation is done! See https://github.com/nextcloud/all-in-one#how-to-change-the-default-location-of-nextclouds-datadir
      # NEXTCLOUD_MOUNT: /mnt/ # Allows the Nextcloud container to access the chosen directory on the host. See https://github.com/nextcloud/all-in-one#how-to-allow-the-nextcloud-container-to-access-directories-on-the-host
      # NEXTCLOUD_UPLOAD_LIMIT: 10G # Can be adjusted if you need more. See https://github.com/nextcloud/all-in-one#how-to-adjust-the-upload-limit-for-nextcloud
      # NEXTCLOUD_MAX_TIME: 3600 # Can be adjusted if you need more. See https://github.com/nextcloud/all-in-one#how-to-adjust-the-max-execution-time-for-nextcloud
      NEXTCLOUD_MEMORY_LIMIT: 1024M # Can be adjusted if you need more. See https://github.com/nextcloud/all-in-one#how-to-adjust-the-php-memory-limit-for-nextcloud
      # NEXTCLOUD_TRUSTED_CACERTS_DIR: /path/to/my/cacerts # CA certificates in this directory will be trusted by the OS of the nexcloud container (Useful e.g. for LDAPS) See See https://github.com/nextcloud/all-in-one#how-to-trust-user-defined-certification-authorities-ca
      NEXTCLOUD_STARTUP_APPS: memories twofactor_totp tasks calendar contacts notes # Allows to modify the Nextcloud apps that are installed on starting AIO the first time. See https://github.com/nextcloud/all-in-one#how-to-change-the-nextcloud-apps-that-are-installed-on-the-first-startup
      NEXTCLOUD_ADDITIONAL_APKS: imagemagick # This allows to add additional packages to the Nextcloud container permanently. Default is imagemagick but can be overwritten by modifying this value. See https://github.com/nextcloud/all-in-one#how-to-add-os-packages-permanently-to-the-nextcloud-container
      NEXTCLOUD_ADDITIONAL_PHP_EXTENSIONS: imagick # This allows to add additional php extensions to the Nextcloud container permanently. Default is imagick but can be overwritten by modifying this value. See https://github.com/nextcloud/all-in-one#how-to-add-php-extensions-permanently-to-the-nextcloud-container
      NEXTCLOUD_ENABLE_DRI_DEVICE: true # This allows to enable the /dev/dri device in the Nextcloud container. ⚠️⚠️⚠️ Warning: this only works if the '/dev/dri' device is present on the host! If it should not exist on your host, don't set this to true as otherwise the Nextcloud container will fail to start! See https://github.com/nextcloud/all-in-one#how-to-enable-hardware-transcoding-for-nextcloud
      NEXTCLOUD_ENABLE_NVIDIA_GPU: true
      AIO_COMMUNITY_CONTAINERS: "facerecognition"
      # NEXTCLOUD_KEEP_DISABLED_APPS: false # Setting this to true will keep Nextcloud apps that are disabled in the AIO interface and not uninstall them if they should be installed. See https://github.com/nextcloud/all-in-one#how-to-keep-disabled-apps
      # TALK_PORT: 3478 # This allows to adjust the port that the talk container is using. See https://github.com/nextcloud/all-in-one#how-to-adjust-the-talk-port
      # WATCHTOWER_DOCKER_SOCKET_PATH: /var/run/docker.sock # Needs to be specified if the docker socket on the host is not located in the default '/var/run/docker.sock'. Otherwise mastercontainer updates will fail. For macos it needs to be '/var/run/docker.sock'
      SKIP_DOMAIN_VALIDATION: true # disable domain validation which wont work with a DNS challenge
    networks: # Is needed when you want to create the nextcloud-aio network with ipv6-support using this file, see the network config at the bottom of the file
      - nextcloud-aio # Is needed when you want to create the nextcloud-aio network with ipv6-support using this file, see the network config at the bottom of the file
    security_opt: ["label:disable"] # Is needed when using SELinux

  go-vod:
    image: radialapps/go-vod
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    restart: always
    container_name: nextcloud-aio-go-vod
    depends_on:
      - nextcloud-aio-mastercontainer
    environment:
      - NEXTCLOUD_HOST=https://cloud.example.com
      # - NEXTCLOUD_ALLOW_INSECURE=1 # (self-signed certs or no HTTPS)
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - /mnt/ncdata:/mnt/ncdata:ro
    runtime: nvidia # (NVENC)

    networks:
      - nextcloud-aio

volumes: # If you want to store the data on a different drive, see https://github.com/nextcloud/all-in-one#how-to-store-the-filesinstallation-on-a-separate-drive
  nextcloud_aio_mastercontainer:
    name: nextcloud_aio_mastercontainer # This line is not allowed to be changed as otherwise the built-in backup solution will not work

networks:
  nextcloud-aio:
    name: nextcloud-aio
    external: true
```

And I can see this in the talk container logs

```
2025-04-28T23:03:40.046984102Z hub.go:2666: No MCU subscriber found for session kooyUv7d71drjXv2ANC55asdf3tJyQ9vKExWYr_j8ggNbrR8PT1nbjNWbWI5MmxlY1padXJFaWY0RsdfGNrdEZLWFJWdDB2TWtHVDVqbV95MUpnZGFqVkpJX1lEeXVPcFd3fDkxNasfDE4ODU0NzE= to send &{Type:candidate Sid: RoomType:video Payload:map[candidate:map[candidate:candidate:433490522 1 udp 41755391 172.18.0.6 63906 typ relay raddr 174.xx.xxx.172 rport 57329 generation 0 ufrag r9Hb network-id 7 network-cost 900 sdpMLineIndex:0 sdpMid:0] type:candidate] Bitrate:0 AudioCodec: VideoCodec: VP9Profile: H264Profile: offerSdp:<nil> answerSdp:<nil>} to z7qwgQ3rgVEnFrrc6eo1lj7Efh8qbZ2ZB_Rx3ARUU1t8aEdlcXI2czlfZWZ6bm4xWkhuc3pRdsamJhOE9kR2VVYnJWZUVHR1l0dVVMaHEtdUJpTUNCZGdasdf3J8MDEwMadsfDg4NTQ3MQ==

```

My suspicion is that the talk container is setting the `relay_ipv4_addr` incorrectly.  My understanding is that this should be my public/routable ip.  

I don't see a good way to change this though.

Is this a configuration error or something that needs to change in the talk start.sh script?
