### DISCUSSION TITLE
Unable to start master container using the images from the new repository

### DISCUSSION THREAD

**Discussion by Aternus** [nextcloud/all-in-one#6359] [Questions] [answered]
### Steps to reproduce
1. Create a docker compose file (a.k.a. Stack)
2. Start the stack (in my case, using Portainer)

### Expected behavior 
The master container should initiate properly and fire up the other containers

### Actual behavior 
The master container fails with the following error message:
`exec /sbin/docker-init: no such file or directory`

#### Host OS 
PhotonOS

#### Output of `sudo docker info`
```
Client: Docker Engine - Community
 Version:    27.3.1
 Context:    default
 Debug Mode: false

Server:
 Containers: 2
  Running: 1
  Paused: 0
  Stopped: 1
 Images: 2
 Server Version: 27.3.1
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: runc io.containerd.runc.v2
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 3dce8eb055cbb6872793272b4f20ed16117344f8
 runc version:
 init version:
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 6.1.133-1.ph5-esx
 Operating System: VMware Photon OS/Linux
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 7.752GiB
 Name: vm-home-cmd
 ID: e8546d93-b7c5-4cff-a566-c157425bf93a
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine

WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
```

#### Docker run command or docker-compose file that you used
```
# @see https://github.com/nextcloud/all-in-one/blob/main/compose.yaml

services:
  nextcloud-aio-mastercontainer:
    image: ghcr.io/nextcloud-releases/all-in-one:latest
    init: true
    restart: always
    container_name: nextcloud-aio-mastercontainer # This line is not allowed to be changed as otherwise AIO will not work correctly
    volumes:
      - nextcloud_aio_mastercontainer:/mnt/docker-aio-config # This line is not allowed to be changed as otherwise the built-in backup solution will not work
      - /var/run/docker.sock:/var/run/docker.sock:ro
    network_mode: bridge
    ports:
      - 80:80
      - 8080:8080
      - 8443:8443
    environment:
      AIO_DISABLE_BACKUP_SECTION: true
      NEXTCLOUD_DATADIR: /mnt/ncdata
      NEXTCLOUD_MEMORY_LIMIT: 2048M

volumes:
  nextcloud_aio_mastercontainer:
    name: nextcloud_aio_mastercontainer # This line is not allowed to be changed as otherwise the built-in backup solution will not work
```

#### Other valuable info 
Happened after an upgrade from v10.9.0

Tried creating a symlink from `/usr/bin/docker-init` to `/sbin/docker-init` but it didn't help
