### DISCUSSION TITLE
How to assign a custom TURN/STUN port in `docker-compose.yml` for a second Nextcloud AIO VM?

### DISCUSSION THREAD

**Discussion by vawaver** [nextcloud/all-in-one#6402] [Questions] [answered]
### Context

* **Host:** Proxmox VE
* **Reverse proxy:** Nginx Proxy Manager (NPM) — HTTP/HTTPS routing already works
* **Public IP:** one IPv4

Running **VM01** (Ubuntu 24.04) with Nextcloud AIO; Talk listens on default 3478 UDP/TCP:

```yaml
# version: "3.4"

volumes:
  nextcloud_aio_mastercontainer:
    external: true

services:
  nextcloud:
    image: nextcloud/all-in-one:latest
    restart: unless-stopped
    container_name: nextcloud-aio-mastercontainer
    volumes:
      - nextcloud_aio_mastercontainer:/mnt/docker-aio-config
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 6789:8080
    environment:
      - APACHE_PORT=11000
      - NEXTCLOUD_MEMORY_LIMIT=4096M
```

Preparing **VM02** (Ubuntu 24.04) for another isolated Nextcloud AIO instance. Port 3478 is already forwarded to VM01, so VM02 needs Talk on a different port (e.g. 3479 UDP + TCP). HTTP/HTTPS remain behind NPM; only the TURN/STUN port must differ.

---

### Questions

1. Is there an officially supported variable (such as `TALK_PORT`) to set a custom TURN/STUN port in `docker-compose.yml` for the second AIO instance?
2. If so, what is the minimal compose snippet for VM02?

   * Which `ports:` mappings and `environment:` keys are required?
3. Will a custom port persist across AIO image upgrades, or does the variable need to be reapplied after each update?
4. Any caveats with UFW, IPv6, or coturn when operating on a non-default port?
