### DISCUSSION TITLE
I'm using portainer

### DISCUSSION THREAD

**Discussion by Byter3** [nextcloud/all-in-one#6431] [Questions] [answered]
Hey,
I'm using portainer and I wanted to recreate the local-ai container, when I realized my stack still using the I guess now the old place of the AIO image:

```
services:
  nextcloud:
    image: nextcloud/all-in-one:latest
    restart: always
    container_name: nextcloud-aio-mastercontainer # This line is not allowed to be changed as otherwise AIO will not work correctly
    volumes:
      - nextcloud_aio_mastercontainer:/mnt/docker-aio-config # This line is not allowed to be changed as otherwise the built-in backup solution will not work
      - /var/run/docker.sock:/var/run/docker.sock:ro # May be changed on macOS, Windows or docker rootless. See the applicable documentation. If adjusting, don't forget to also set 'WATCHTOWER_DOCKER_SOCKET_PATH'!
    ports:
      - 80:80 # Can be removed when running behind a web server or reverse proxy (like Apache, Nginx, Cloudflare Tunnel and else). See https://github.com/nextcloud/all-in-one/blob/main/reverse-proxy.md
      - 8080:8080
      - 8443:8443 # Can be removed when running behind a web server or reverse proxy (like Apache, Nginx, Cloudflare Tunnel and else). See https://github.com/nextcloud/all-in-one/blob/main/reverse-proxy.md
    environment: # Is needed when using any of the options below
      - AIO_COMMUNITY_CONTAINERS=local-ai
```

My Question is, how the migration from docker to github effect my stack in Portainer?
When I now tried to restart all my containers to download a new model for local-ai I got in a loop, where it said there are updates for the containers, but it never got updated, just hanged there. My solution was to restart the entire VM that runs NC AIO, BUT now the local-ai container just disappeared from Portainer's list and the AIO interface showsit red as not started. How to clean up this mess?
Thank you!
