### DISCUSSION TITLE
Imagick module missing SVG support in AIO since 10.14.0 – how to resolve?

### DISCUSSION THREAD

**Discussion by vawaver** [nextcloud/all-in-one#6460] [Questions] [answered]
### Question

After updating to **Nextcloud AIO version 10.14.0 (Nextcloud 30.0.10)**, I started seeing the following message in the admin panel:

> The PHP module "imagick" in this instance has no SVG support. For better compatibility it is recommended to install it.

This issue did not exist before 10.14.0. It still persists after updating to **10.15.0 (Nextcloud 30.0.11)**. I’m using **Hub 9** with a standard Docker-based AIO setup on Ubuntu 24.04.

I haven't modified the container images or installed any custom extensions.

### My Question

Is there an officially recommended way to restore SVG support in the Imagick PHP module for AIO?

- Is this an intentional change?
- Can this be resolved by updating the image in a future release?
- Would it be acceptable to use a custom Docker image based on `nextcloud/aio-nextcloud`, installing `librsvg2-bin` to re-enable SVG rendering?
- Or is there a workaround that works within the AIO structure?

Thank you for any guidance.

**Comment by szaimen** [comment]
Hi, please check the last sentence in the docs [here](https://github.com/nextcloud/all-in-one?tab=readme-ov-file#how-to-add-php-extensions-permanently-to-the-nextcloud-container) and [here](https://github.com/nextcloud/all-in-one?tab=readme-ov-file#how-to-add-php-extensions-permanently-to-the-nextcloud-container): 
- `By default imagemagick is added. If you want to keep it, you need to specify it as well.` 
- `By default imagick is added. If you want to keep it, you need to specify it as well.`

**Comment by vawaver** [comment, marked as answer]
✅ I was able to resolve the issue with missing SVG support in the `imagick` module — **without adding any additional packages**.

Although the warning previously appeared in the admin overview, it no longer shows up on my setup (Nextcloud AIO version 30.0.11), even with a minimal configuration.

Here is my working `docker-compose.yml`:

```yaml
# version: "3.4"

volumes:
  nextcloud_aio_mastercontainer:
    external: true

services:
  nextcloud:
    #   image: nextcloud/all-in-one:latest
    image: ghcr.io/nextcloud-releases/all-in-one:latest
    restart: unless-stopped
    container_name: nextcloud-aio-mastercontainer
    volumes:
      - nextcloud_aio_mastercontainer:/mnt/docker-aio-config
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/cups/client.conf:/etc/cups/client.conf:ro
    ports:
      - 6789:8080  # Web UI of the mastercontainer
    environment:
      - APACHE_PORT=11000
      - NEXTCLOUD_MEMORY_LIMIT=4096M
      - NEXTCLOUD_ADDITIONAL_APKS=cups imagemagick
```

I applied the changes using:

```bash
docker compose down
docker compose up -d
```

The warning about SVG support in `imagick` disappeared and everything works as expected.

**Note:** `cups` is included here for unrelated printing functionality and is not required for resolving the `imagick` issue.
