### DISCUSSION TITLE
Docker Swarm: Using a different name is not supported!

### DISCUSSION THREAD

**Discussion by SingingFrog7** [nextcloud/all-in-one#650] [Questions] [answered]
Hello

   As anyone tried to run this container with docker swarm? I can't get it to work due to the container name not being the expected one.

I don't know if I am the only one trying to run it that way, but I have an high-available docker swarm cluster I'd like to use.

My docker-compose file:

```
version: "3.8"

services:
  app:
    image: nextcloud/all-in-one:latest
    volumes:
      - /mnt/docker-gfs/nextcloud/aio-config:/mnt/docker-aio-config
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 86:80 # Can be removed when running behind a reverse proxy. See https://github.com/nextcloud/all-in-one/blob/main/reverse-proxy.md
      - 8086:8080
      - 8446:8443 # Can be removed when running behind a reverse proxy. See https://github.com/nextcloud/all-in-one/blob/main/reverse-proxy.md

```

I tried setting the hostname of the container using `hostname: nextcloud-aio-mastercontainer` which didn't help. 

I am getting this when trying to run the container:
```
nextcloud-aio_app.1.kgvj18ode4z9@swarm-1    | Trying to fix docker.sock permissions internally...
nextcloud-aio_app.1.kgvj18ode4z9@swarm-1    | Creating docker group internally with id 997
nextcloud-aio_app.1.kgvj18ode4z9@swarm-1    | It seems like you did not give the mastercontainer the correct name?
nextcloud-aio_app.1.kgvj18ode4z9@swarm-1    | Using a different name is not supported!
```

Anybody has an idea?
Thanks
