### DISCUSSION TITLE
slow nextcloud?

### DISCUSSION THREAD

**Discussion by farzadha2** [nextcloud/all-in-one#737] [Questions] [answered]
HI
I was wondering if someone could shed some light on the issue im having,
Currently i have nextcloud docker working but noticed that its a bit slow not sure why, 
how could i troubleshoot the issue?
currently using nginx reverse proxy 
```

   server {

#        listen 80;
   listen 443 ssl;
         server_name nube.domain.com;

  ssl_certificate /etc/letsencrypt/live/nube.domain.com/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/nube.domain.com/privkey.pem;
        ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
       ssl_prefer_server_ciphers on;
        ssl_dhparam /etc/ssl/certs/dhparam.pem;
        ssl_ciphers 'EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH';
        ssl_session_timeout 1d;
        ssl_session_cache shared:SSL:50m;
        ssl_stapling on;
       ssl_stapling_verify on;

location ~ /.well-known {
        root /var/www/letsencrypt;
        allow all;
    }

location / {
        proxy_pass http://192.168.3.52:11000;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        client_max_body_size 0;

        # Websocket
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $connection_upgrade;
    }

        }
```
Thank you

**Comment by szaimen** [comment]
Hello, can you post the output of `sudo docker inspect nextcloud-aio`? Thank you!

**Reply by farzadha2** [reply]
Thank you so much for the reply, this is the outcome
```

root@dockers:~# sudo docker inspect nextcloud-aio
[
    {
        "Name": "nextcloud-aio",
        "Id": "ea42837512a477f3007d35be340a02ed9fa1c001f78066f9839b5ff2df179d17",
        "Created": "2022-05-21T13:48:09.653404749-05:00",
        "Scope": "local",
        "Driver": "bridge",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "default",
            "Options": null,
            "Config": [
                {
                    "Subnet": "172.19.0.0/16",
                    "Gateway": "172.19.0.1"
                }
            ]
        },
        "Internal": true,
        "Attachable": false,
        "Ingress": false,
        "ConfigFrom": {
            "Network": ""
        },
        "ConfigOnly": false,
        "Containers": {
            "7c5ff863bed64becb36738b8daf8206df85165407d5ac7742ed74a1a7b52cc06": {
                "Name": "nextcloud-aio-database",
                "EndpointID": "7a056e191d3424e8a314a33d54e52f4b169739b19f59631ac993342094ccc297",
                "MacAddress": "02:42:ac:13:00:06",
                "IPv4Address": "172.19.0.6/16",
                "IPv6Address": ""
            },
            "7d85d22877576b6b7f6cba283e7b94c9a15c3cff6aa843b62909ac5e93622598": {
                "Name": "nextcloud-aio-apache",
                "EndpointID": "d229a1abfdc9ea11a7bb8295220d546687c426356794e5b6c858c447346ccc29",
                "MacAddress": "02:42:ac:13:00:05",
                "IPv4Address": "172.19.0.5/16",
                "IPv6Address": ""
            },
            "827c49317aaaf0d4a4ab4acfb84439b0ffe264c81d18c16e1bdc52fc6bfd3cf1": {
                "Name": "nextcloud-aio-mastercontainer",
                "EndpointID": "4d59b278c34aaa27d6b30af2cefe6e9fd520a366081785998b82a2060c1906ff",
                "MacAddress": "02:42:ac:13:00:02",
                "IPv4Address": "172.19.0.2/16",
                "IPv6Address": ""
            },
            "bde9cc4e6a7ea2714bc10515444e32adac6285a6a0ab10a050d5850b43d6db24": {
                "Name": "nextcloud-aio-nextcloud",
                "EndpointID": "0ef34f18fa484e6f197da318ca5d0626b42254c0983a46229678201e1771b6eb",
                "MacAddress": "02:42:ac:13:00:07",
                "IPv4Address": "172.19.0.7/16",
                "IPv6Address": ""
            },
            "c6964413e7269643941b68b2dde4e0077f1f66ec1607070fdf84fe8747e8cb44": {
                "Name": "nextcloud-aio-redis",
                "EndpointID": "284fb0cc546bee743a41a2e22b3a84168ccc29197792a36694ce25fc16eaa07a",
                "MacAddress": "02:42:ac:13:00:03",
                "IPv4Address": "172.19.0.3/16",
                "IPv6Address": ""
            },
            "d9b74a6daa92299f256e38b9b96e8970e071c6af70d86ab961bf2b5406d60560": {
                "Name": "nextcloud-aio-collabora",
                "EndpointID": "6808c8724a027dea7c5fc90afcfde8e14f74bdb2c9be5f8e27042183b2e76b1a",
                "MacAddress": "02:42:ac:13:00:04",
                "IPv4Address": "172.19.0.4/16",
                "IPv6Address": ""
            }
        },
        "Options": {},
        "Labels": {}
    }
]
```

**Reply by szaimen** [reply]
I see. Can you please try to follows these steps and see if it helps?
https://github.com/nextcloud/all-in-one/issues/715#issuecomment-1136268282

**Reply by farzadha2** [reply]
thank you so much for the reply this is what i did 

```
root@dockers:~# sudo docker stop nextcloud-aio-mastercontainer
nextcloud-aio-mastercontainer
root@dockers:~# sudo docker container prune
WARNING! This will remove all stopped containers.
Are you sure you want to continue? [y/N] y
Deleted Containers:
55403a38e23fe242f8fdd2a044a67e83e4a06576b6e9b5494ee0111b3ec155ab
827c49317aaaf0d4a4ab4acfb84439b0ffe264c81d18c16e1bdc52fc6bfd3cf1

Total reclaimed space: 16.73kB
root@dockers:~# sudo docker network rm nextcloud-aio
Error response from daemon: error while removing network: network nextcloud-aio id ea42837512a477f3007d35be340a02ed9fa1c001f78066f9839b5ff2df179d17 has active endpoints
root@dockers:~# sudo docker network create nextcloud-aio
Error response from daemon: network with name nextcloud-aio already exists

```

after that i ran my docker compose 

```
version: "3.8"

volumes:
  nextcloud_aio_mastercontainer:
    name: nextcloud_aio_mastercontainer

services:
  nextcloud:
    image: nextcloud/all-in-one:latest # Must be changed to 'nextcloud/all-in-one:latest-arm64' when used with an arm64 CPU
    restart: always
    container_name: nextcloud-aio-mastercontainer
    environment: # Is needed when using any of the options below
     - APACHE_PORT=11000 # Is needed when running behind a reverse proxy. See https://github.com/nextcloud/all-in-one/blob/main/reverse-proxy.md  
     - NEXTCLOUD_DATADIR=/data/ncdata
     - NEXTCLOUD_MOUNT=/data/
    volumes:
     - nextcloud_aio_mastercontainer:/mnt/docker-aio-config
     - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 8080:8080
```
then it seemed to update from 1.2.0 to 1.3.0 restarted all the containers 


not sure if i should update the container? is there a tool i can use to check the speed for the nextcloud server? currently have 3 users at the moment the idea is to put around 50 

![image](https://user-images.githubusercontent.com/62571297/170405242-9140103f-ba19-44a4-a088-6578fce308b5.png)
