### DISCUSSION TITLE
502 Bad gateway with docker networks

### DISCUSSION THREAD

**Discussion by mtthidoteu** [nextcloud/all-in-one#787] [Questions] [answered]
Hey guys!

My setup is: Nginx-proxy-manager using a Docker network (so not via the host, this always works normally)
Essentially, the nginx-proxy-manager is connected to a app via a docker network so without exposing the port.
However, if I put an apache_port number, it doesn't work to it:

```
version: "3.8"
volumes:
  nextcloud_aio_mastercontainer:
    name: nextcloud_aio_mastercontainer 

services:
  nextcloud:
    image: nextcloud/all-in-one:latest 
    restart: always
    container_name: nextcloud-aio-mastercontainer 
    volumes:
      - nextcloud_aio_mastercontainer:/mnt/docker-aio-config 
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
     - APACHE_PORT=11000
    networks:
      - web
      - default

networks:
  web:
    name: web
  default:
```

Nginx Proxy manager is connected to this web network and it can access https://nextcloud-aio-mastercontainer:8080/ but for some reason NOT http://nextcloud-aio-mastercontainer:11000/
I can't just use https://nextcloud-aio-mastercontainer:8080/ as it does not allow me to configure it properly and its bad practice.
However, if my [Nextcloud.domain.com](https://nextcloud.domain.com/) points to http://nextcloud-aio-mastercontainer:11000/ I get a 502 Gateway error and I cannot for the life of my understand why this is.

here are the reverse proxy's logs:

`2022/06/06 15:27:04 [error] 742#742: *1949 connect() failed (111: Connection refused) while connecting to upstream, client: **redacted**, server: **redacted**, request: "GET / HTTP/2.0", upstream: "http://192.168.208.2:11000/", host: "**redacted**", referrer: "**redacted**"`

When starting the container, it says nothing about APACHE_PORT being registered in the logs. Does anyone have a clue why this is?

**What I suspect**
The nextcloud-AIO container isn't registering my APACHE_PORT variable for some reason, as the Proxy can connect to 8080 but not 11000!

I would be extremely grateful for some help :)

_Originally posted by @mtthidoteu in https://github.com/nextcloud/all-in-one/discussions/785_
