### DISCUSSION TITLE
Caddy front + back end results in "Domain does not point to this server or the reverse proxy is not configured correctly"

### DISCUSSION THREAD

**Discussion by kbdcrazy** [nextcloud/all-in-one#925] [Questions] [answered]
Hello all

I am hitting this error message during setup of the AIO image when entering the domain of the new AIO instance - up to this point it worked fine and I can refer to https://my.nextcloud-domain.org from an external host:
_"Domain does not point to this server or the reverse proxy is not configured correctly. See the mastercontainer logs for more details. ('sudo docker logs -f nextcloud-aio-mastercontainer')"_

### All log messages of the nextcloud-aio-mastercontainer after entering the domain name and hitting submit:
```
nextcloud-aio-mastercontainer | 172.22.0.2:8000 localhost - - [12/Jul/2022:18:47:09 +0000] "GET / HTTP/1.1" 302 424 "-" "-"
nextcloud-aio-mastercontainer | localhost - - [12/Jul/2022:18:47:09 +0000] "GET / HTTP/1.1" 302 424 "-" "-"
nextcloud-aio-mastercontainer | 172.22.0.2:8080 blue - - [12/Jul/2022:18:47:09 +0000] "GET / HTTP/1.1" 302 3160 "-" "-"
nextcloud-aio-mastercontainer | blue - - [12/Jul/2022:18:47:09 +0000] "GET / HTTP/1.1" 302 3160 "-" "-"
nextcloud-aio-mastercontainer | [Tue Jul 12 18:47:09.384162 2022] [php:notice] [pid 152] [client 127.0.0.1:37226] The response of the connection attempt to "https://my.nextcloud-domain.org:443" was: , referer: https://my.nextcloud-domain.org/containers
nextcloud-aio-mastercontainer | [Tue Jul 12 18:47:09.384203 2022] [php:notice] [pid 152] [client 127.0.0.1:37226] Expected was: 1c7549411e53b6090a1ade2f7e280c63e74dcfaee13e54d8, referer: https://my.nextcloud-domain.org/containers
nextcloud-aio-mastercontainer | [Tue Jul 12 18:47:09.384209 2022] [php:notice] [pid 152] [client 127.0.0.1:37226] The error message was: , referer: https://my.nextcloud-domain.org/containers
nextcloud-aio-mastercontainer | 172.22.0.2:8000 localhost - - [12/Jul/2022:18:47:09 +0000] "POST /api/configuration HTTP/1.1" 422 546 "https://my.nextcloud-domain.org/containers" "Mozilla/5.0 (X11; Linux x86_64; rv:101.0) Gecko/20100101 Firefox/101.0"
nextcloud-aio-mastercontainer | localhost - - [12/Jul/2022:18:47:09 +0000] "POST /api/configuration HTTP/1.1" 422 546 "https://my.nextcloud-domain.org/containers" "Mozilla/5.0 (X11; Linux x86_64; rv:101.0) Gecko/20100101 Firefox/101.0"
nextcloud-aio-mastercontainer | 172.22.0.2:8080 blue - - [12/Jul/2022:18:47:09 +0000] "POST /api/configuration HTTP/1.1" 422 3282 "https://my.nextcloud-domain.org/containers" "Mozilla/5.0 (X11; Linux x86_64; rv:101.0) Gecko/20100101 Firefox/101.0"
nextcloud-aio-mastercontainer | blue - - [12/Jul/2022:18:47:09 +0000] "POST /api/configuration HTTP/1.1" 422 3282 "https://my.nextcloud-domain.org/containers" "Mozilla/5.0 (X11; Linux x86_64; rv:101.0)Gecko/20100101 Firefox/101.0"
```

Due to the fact, that I can reach https://my.nextcloud-domain.org up to this point I do not see what could be wrong.

I have noticed what appears to me as an empty string right before the comma - in both these 2 log messages:
_"The response of the connection attempt to "[...]" was: , referer: [...]"
"The error message was: , referer: [...]"_

Can somebody help me understand how to debug this further or maybe you have a good idea what the issue could be ?

Cheers,
Martin

________________________________________________________________________________

### My setup:

- Host 1:
    Runs:
    * Wireguard server
    * DNS Unbound server and 
    * Caddy front end (native OS process run as root) 
    Public host with public DNS A record:  "my.nextcloud-domain.org" with static IP
    Unbound DNS A record: "proxy-front.red" (192.168.69.1 on the same wireguard subnet as "proxy-back.red") resolvable by Wireguard server and clients (Hosts 1,2)

- Host 2:
    Runs:
    * Wireguard client
    * Nextcloud AIO via Docker and
    * Caddy back end (native OS process run as root)
    Private host in a private LAN
    Unbound DNS A record "proxy-back.red" (192.168.69.2 on the same wireguard subnet as "proxy-front.red") resolvable by Wireguard server and clients (Hosts 1,2)
    Hostname is set as "blue"

NOTE: Due to the Wireguard VPN host 1 and 2 are practically on the same network with the hostnames (proxy-front.red and proxy-back.red) used in the caddy files resolving to the wireguard network IP addresses.

![BE4CC012-95D6-417E-A1B8-6713CD9E2F99](https://user-images.githubusercontent.com/107158713/178624009-11cff199-c83d-488c-89ff-d45c564fcd9c.png)

### Host 1: Caddy front end (proxy-front.red)
```
# Global Option Block
{
  debug
}
# ACME Server
proxy-front.red {
        acme_server
        tls internal
}
# Nextcloud
my.nextcloud-domain.org {
        reverse_proxy https://proxy-back.red {
                header_up Host {http.reverse_proxy.upstream.hostport}
                header_up X-Forwarded-Host {host}
        }
}
```

### Host 2: Caddy back end (proxy-back.red)
```
# Global Option Block
{
        # General Option
        debug

        # TLS Options
        acme_ca https://proxy-front.red/acme/local/directory
        acme_ca_root /etc/pki/ca-trust/source/anchors/root.crt
}
# Nextcloud
proxy-back.red {
    reverse_proxy https://localhost:8080 {
        transport http {
            tls_insecure_skip_verify
        }
    }
}
```

### Host 2: docker-compose.yml for Nextcloud AIO
```
version: "3.8"

volumes:
  nextcloud_aio_mastercontainer:
    name: nextcloud_aio_mastercontainer # This line is not allowed to be changed

services:
  nextcloud:
    image: nextcloud/all-in-one:latest # Must be changed to 'nextcloud/all-in-one:latest-arm64' when used with an arm64 CPU
    restart: always
    container_name: nextcloud-aio-mastercontainer # This line is not allowed to be changed
    volumes:
      - nextcloud_aio_mastercontainer:/mnt/docker-aio-config # This line is not allowed to be changed
      - /var/run/docker.sock:/var/run/docker.sock:ro # May be changed on macOS, Windows or docker rootless. See the applicable documentation
    ports:
      - 8080:8080
    environment: # Is needed when using any of the options below
      - APACHE_PORT=11000 # Is needed when running behind a reverse proxy. See https://github.com/nextcloud/all-in-one/blob/main/reverse-proxy.md
```
