### ISSUE TITLE
WebDAV interface broken

### ISSUE THREAD

**Issue by LMAR6** [nextcloud/all-in-one#1001]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Setup docker rootless according to docs
2. Install Nextcloud All in One
3.

### Expected behavior 
- File upload: should be possible
- User list: (/settings/users) should be accessible
### Actual behavior 
- File upload not visible, not possible to open demo files
![image](https://user-images.githubusercontent.com/43521897/183823519-4c264b58-3036-444a-a618-382760afb6cb.png)

- Users not loading
![image](https://user-images.githubusercontent.com/43521897/183823348-97fe89c1-c9e3-49f6-b47d-ffecfcd607c9.png)

### Host OS 
Debian 11.4 + Plesk Obsidian 18.0.44 Update #3 => using Nginx as reverse proxy

#### Nextcloud AIO version 
v1.7.0

#### Current channel 
latest

#### Other valuable info 
Fresh installation:
![image](https://user-images.githubusercontent.com/43521897/183820697-00b9f47b-ad5a-4634-aeb3-aeed82f006d4.png)
![image](https://user-images.githubusercontent.com/43521897/183820773-334b7b68-dde9-4616-a2cb-437594600825.png)

Plesk Additional nginx directives
```
location / {
	proxy_pass http://localhost:11000;
	proxy_set_header X-Real-IP $remote_addr;
	proxy_set_header Host $host;
	proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
	client_max_body_size 0;

	# Websocket
	proxy_http_version 1.1;
	proxy_set_header Upgrade $http_upgrade;
	proxy_set_header Connection upgrade;
}
```

docker-compose.yml
```
version: "3.8"

volumes:
  nextcloud_aio_mastercontainer:
    name: nextcloud_aio_mastercontainer # This line is not allowed to be changed

services:
  nextcloud:
    image: nextcloud/all-in-one:latest # Must be changed to 'nextcloud/all-in-one:latest-arm64' when used with an arm64 CPU
    restart: always
    container_name: nextcloud-aio-mastercontainer # This line is not allowed to be changed
    volumes:
      - nextcloud_aio_mastercontainer:/mnt/docker-aio-config # This line is not allowed to be changed
      - $XDG_RUNTIME_DIR/docker.sock:/var/run/docker.sock:ro # May be changed on macOS, Windows or docker rootless. See the applicable documentation
    ports:
      - 8080:8080
    environment: # Is needed when using any of the options below
      - APACHE_PORT=11000 # proxy. See https://github.com/nextcloud/all-in-one/blob/main/reverse-proxy.md
      - APACHE_IP_BINDING=0.0.0.0 # Should be set when running behind a reverse proxy that is running on the same host. See https://github.com/nextcloud/all-in-one/blob/main/reverse-proxy.md
      - TALK_PORT=3478 # This allows to adjust the port that the talk container is using.
      - DOCKER_SOCKET_PATH=$XDG_RUNTIME_DIR/docker.sock
      - SKIP_DOMAIN_VALIDATION=true
      # CHANGE NEXTCLOU DATA DIR ACCORDING TO https://github.com/nextcloud/all-in-one#how-to-change-the-default-location-of-nextclouds-datadir
      - NEXTCLOUD_DATADIR=/var/docker/demodocker/ncdata
      - NEXTCLOUD_MOUNT=/var/docker/demodocker/ncmount
      # - DISABLE_BACKUP_SECTION=true # Setting this to true allows to hide the backup section in the AIO interface.
```
Logs nextcloud-aio-nextloud container
```
`nc: getaddrinfo for host "nextcloud-aio-nextcloud" port 9000: Name or service not known
Waiting for Nextcloud to start...
Waiting for Nextcloud to start...
Waiting for Nextcloud to start...
Waiting for Nextcloud to start...
Waiting for Nextcloud to start...
Waiting for Nextcloud to start...
Waiting for Nextcloud to start...
Waiting for Nextcloud to start...
Waiting for Nextcloud to start...
Waiting for Nextcloud to start...
Waiting for Nextcloud to start...
Waiting for Nextcloud to start...
Waiting for Nextcloud to start...
Waiting for Nextcloud to start...
Waiting for Nextcloud to start...
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.17.0.8. Set the 'ServerName' directive globally to suppress this message
{"level":"info","ts":1660057186.6050074,"msg":"using provided configuration","config_file":"/Caddyfile","config_adapter":""}
{"level":"warn","ts":1660057186.606632,"msg":"Caddyfile input is not formatted; run the 'caddy fmt' command to fix inconsistencies","adapter":"caddyfile","file":"/Caddyfile","line":2}
{"level":"info","ts":1660057186.6077075,"logger":"admin","msg":"admin endpoint started","address":"tcp/localhost:2019","enforce_origin":false,"origins":["//localhost:2019","//[::1]:2019","//127.0.0.1:2019"]}
{"level":"warn","ts":1660057186.607918,"logger":"http","msg":"automatic HTTPS is completely disabled for server","server_name":"srv0"}
{"level":"info","ts":1660057186.6080759,"logger":"tls.cache.maintenance","msg":"started background certificate maintenance","cache":"0xc0008801c0"}
{"level":"info","ts":1660057186.60926,"logger":"tls","msg":"cleaning storage unit","description":"FileStorage:/mnt/data/caddy"}
{"level":"info","ts":1660057186.6092885,"logger":"tls","msg":"finished cleaning storage units"}
{"level":"info","ts":1660057186.6094062,"msg":"autosaved config (load with --resume flag)","file":"/var/www/.config/caddy/autosave.json"}
{"level":"info","ts":1660057186.6094162,"msg":"serving initial configuration"}
{"level":"error","ts":1660107478.0599189,"logger":"http.handlers.reverse_proxy","msg":"aborting with incomplete response","error":"context canceled"}`
```
