### ISSUE TITLE
Instructions for Nextcloud Data Dir are not clear - please provide more info

### ISSUE THREAD

**Issue by nigel-dewar** [nextcloud/all-in-one#1160]
### Is your feature request related to a problem? Please describe. 

The instructions listed at the Section "How to change the default location of Nextcloud's Datadir?" do not make sense to me.
I am trying to map the NEXTCLOUD_DATADIR to an NFS Volume. 

At first I tried this.
```
version: "3.8"

volumes:
  nextcloud_aio_mastercontainer:
    name: nextcloud_aio_mastercontainer # This line is not allowed to be changed
    driver: local
    driver_opts:
      type: nfs
      o: nfsvers=4,addr=192.168.1.50,rw
      device: ":/volume2/MegaShare/nextcloud_master"
  nextcloud_data:
    name: nextcloud_data # This line is not allowed to be changed
    driver: local
    driver_opts:
      type: nfs
      o: nfsvers=4,addr=192.168.1.50,rw
      device: ":/volume2/MegaShare/nextcloud_data"

services:
  nextcloud:
    image: nextcloud/all-in-one:latest # Must be changed to 'nextcloud/all-in-one:latest-arm64' when used with an arm64 CPU
    restart: always
    container_name: nextcloud-aio-mastercontainer # This line is not allowed to be changed
    volumes:
      - nextcloud_aio_mastercontainer:/mnt/docker-aio-config # This line is not allowed to be changed
      - /var/run/docker.sock:/var/run/docker.sock:ro # May be changed on macOS, Windows or docker rootless. See the applicable documentation
    ports:
      - 80:80 # Can be removed when running behind a reverse proxy. See https://github.com/nextcloud/all-in-one/blob/main/reverse-proxy.md
      - 8080:8080
      - 8443:8443 # Can be removed when running behind a reverse proxy. See https://github.com/nextcloud/all-in-one/blob/main/reverse-proxy.md
    environment: # Is needed when using any of the options below
      - APACHE_PORT=11000 # Is needed when running behind a reverse proxy. See https://github.com/nextcloud/all-in-one/blob/main/reverse-proxy.md
      - SKIP_DOMAIN_VALIDATION=true
      # - APACHE_IP_BINDING=127.0.0.1 # Should be set when running behind a reverse proxy that is running on the same host. See https://github.com/nextcloud/all-in-one/blob/main/reverse-proxy.md
      # - TALK_PORT=3478 # This allows to adjust the port that the talk container is using.
      - NEXTCLOUD_DATADIR="nextcloud_data" # Allows to set the host directory for Nextcloud's datadir. See https://github.com/nextcloud/all-in-one#how-to-change-the-default-location-of-nextclouds-datadir
```

But this did not work. It complained about the folder not starting with a /

So then I tried setting this to the volume that my previous attempt had created, and tried setting this

- NEXTCLOUD_DATADIR=/var/lib/docker/volumes/nextcloud_data 

But this also did not work, and complained about permissions.

I noticed on instructions for a Synology, that it says you can connect to its volume like so
![image](https://user-images.githubusercontent.com/9402456/190536289-61d99a27-a809-4c10-96ea-7affee62d9a5.png)

Does this mean, you expect the user to manually mount the synology NFS share to the host linux machine prior ? and then map that shared path into NEXTCLOUD_DATADIR ?

Please advise?

### Describe the solution you'd like
Updated instructions please for how to map NEXTCLOUD_DATADIR to an NFS Volume.
