### ISSUE TITLE
NEXTCLOUD_DATADIR doesn't seem to be respected by nextcloud-aio-nextcloud

### ISSUE THREAD

**Issue by komali2** [nextcloud/all-in-one#1175]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Have docker-compose.yml that looks like below, with `NEXTCLOUD_DATADIR` set to `/mnt/media/nextcloud/ncdata/` , or the same, without trailing slash
2. Do `docker-compose up -d`
3. Follow initial setup in AIO at localhost:8080
4. After AIO starts containers, do `docker logs nextcloud-aio-nextcloud`
5. Observe repeated error: 

```
touch: /mnt/ncdata/this-is-a-test-file: Permission denied
The www-data user doesn't seem to have access rights in /mnt/ncdata.
Did you maybe change the datadir and did forget to apply the correct permissions?
```

### Expected behavior 

There should be no logs about attempting to touch directories that don't exist. 

### Actual behavior 

It appears the program is attempting to touch directories that don't exist. 

### Host OS 

```
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.1 LTS
Release:	22.04
Codename:	jammy
```

#### Nextcloud AIO version 

```
Nextcloud AIO v2.0.2
```

#### Current channel 

(not listed anywhere I can see, but this is a fresh pull from instructions on github)

#### Other valuable info 

docker-compose.yml

```
version: "3.8"

volumes:
  nextcloud_aio_mastercontainer:
    name: nextcloud_aio_mastercontainer # This line is not allowed to be changed

services:
  nextcloud:
    image: nextcloud/all-in-one:latest # Must be changed to 'nextcloud/all-in-one:latest-arm64' when used with an arm64 CPU
    restart: always
    container_name: nextcloud-aio-mastercontainer # This line is not allowed to be changed
    volumes:
      - nextcloud_aio_mastercontainer:/mnt/docker-aio-config # This line is not allowed to be changed
      - /var/run/docker.sock:/var/run/docker.sock:ro # May be changed on macOS, Windows or docker rootless. See the applicable documentation
    ports:
     - 8080:8080
    environment:
     - APACHE_PORT=11000
     - APACHE_IP_BINDING=127.0.0.1
     - NEXTCLOUD_DATADIR=/mnt/media/nextcloud/ncdata/
     - NEXTCLOUD_MOUNT=/mnt/media/nextcloud/

```

Also, /mnt/media/ is a mountpoint for a zfs pool of two disks. Other programs use it just fine though. I didn't realize nextcloud would run as www-data, but I've since added www-data to a group that has full access recursively to /mnt/media/
