### ISSUE TITLE
allow to migrate the files and the database from nextcloud snap to aio

### ISSUE THREAD

**Issue by szaimen** [nextcloud/all-in-one#1480]
### Discussed in https://github.com/nextcloud/all-in-one/discussions/1463

<div type='discussions-op-text'>

<sup>Originally posted by **szaimen** December  1, 2022</sup>
May involves building a custom snap (without pdo_pgsql disabled), installing that and then running the migration.

See https://github.com/nextcloud-snap/nextcloud-snap/wiki/Building-your-first-Nextcloud-snap</div>

**Comment by Leptopoda** [comment]
What about instead of creating (and potentially maintaining) a custom snap we write a small script/compose that allows us to directly import mysql dumps (making all other migrations easier).

I could imagine something basic like:
```yaml
name: nextcloud-migrate
services:
  nextcloud:
    image: nextcloud-migration
    volumes:
      - app:/var/www/html

  mysql:
    image: mariadb:latest
    volumes:
      - mysql:/var/lib/mysql
  
  pgsql:
    image: postgres:latest
    volumes:
      - pgsql:/var/whatever_postgres_uses

volumes:
  app:
  mysql:
  pgsql:
```

The `nextcloud-migrate` image would be based on the normal nextcloud image but pulling in a` migration_script.sh` script that could  take a mysqldump, import it, run the occ migration to pg, and then make a pgsqldump. The image would probably also need to pull the mysql and postgresql clients so the script running in the nextcloud service could directly talk with the databases.

IMO this should only be a docker compose and the migration script making the maintaining fairly easy for people involved in AIO as it would only use docker stuff and wouldn't involve getting into snaps.

This would also make things easier for other nextcloud users that want to migrate to AIO as it wouldn't involve setting up a postgres server just for the migration.

If you like this idea I could make a PR with a POC.
