### ISSUE TITLE
Add docker-compose profiles for manual-install

### ISSUE THREAD

**Issue by ManOki** [nextcloud/all-in-one#1575]
### How to use GitHub
* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Is your feature request related to a problem? Please describe. 
The current [manual-install](https://github.com/nextcloud/all-in-one/commit/2ddd9406aa8ebb509ca6b112c7e7b42bacd8375e) docker-compose.yml (latest.yml) adds all services, regardless of whether you need them or not.

### Describe the solution you'd like
Please add [docker-compose profiles](https://docs.docker.com/compose/profiles/) configuration to the _optional_ services (like clamav, imaginary...) and name them like the services itself, so the user can decide by command line which services are needed: `docker compose --profile clamav --profile imaginary up`
Another advantage is that there are less merge conflicts, because until now you have to customize the docker-compose.yml file if you don't want to use/start/download all services.

### Additional context
Here is an example configuration.

```
version: "3.9"
services:
  nextcloud-aio-clamav:                 
    container_name: nextcloud-aio-clamav
    profiles: ["clamav"]

  nextcloud-aio-imaginary:                 
    container_name: nextcloud-aio-imaginary
    profiles: ["imaginary"]
```
Prerequisite: [docker-compose version 1.28](https://docs.docker.com/compose/release-notes/#1280)
