### ISSUE TITLE
Starting AIO with docker-compose breaks mastercontainer update

### ISSUE THREAD

**Issue by shalak** [nextcloud/all-in-one#2162]
### Steps to reproduce
1. Start nextcloud-aio something like the following compose (most likely you may need to pull some old `nextcloud/all-in-one` image beforehand):

```yaml
services:
  caddy:
    image: caddy:alpine
    restart: unless-stopped
    container_name: caddy
    volumes:
      - /srv/fast/caddy/Caddyfile:/etc/caddy/Caddyfile
      - /srv/fast/caddy/certs:/certs
      - /srv/fast/caddy/config:/config
      - /srv/fast/caddy/data:/data
      - /srv/fast/caddy/sites:/srv
      - /mnt/ssl:/mnt/ssl
    network_mode: "host"

  nextcloud:
    image: nextcloud/all-in-one:latest
    restart: unless-stopped
    container_name: nextcloud-aio-mastercontainer
    ports:
      - "8080:8080"
    environment:
      - APACHE_PORT=11000
      - NEXTCLOUD_DATADIR=/srv/fast/ncdata
      - NEXTCLOUD_MEMORY_LIMIT=2048M
    volumes:
      - nextcloud_aio_mastercontainer:/mnt/docker-aio-config
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:
      - caddy

volumes:
  nextcloud_aio_mastercontainer:
```
2. Try to update

### Expected behavior 
mastercointainer is able to handle this situation and updates without problems

### Actual behavior 
mastercontainer fails to update, because the volume is not names `nextcloud_aio_mastercontainer` - that's because `docker-compose` will prepend the name with project name, which usually is the directory name in which the `docker-compose.yaml` is located, e.g. `mydir_nextcloud_aio_mastercontainer`, thus resulting in following error showing in mastercontainer logs:
```
It seems like you did not give the mastercontainer volume the correct name? (The 'nextcloud_aio_mastercontainer' volume was not found.)
```

Either the mastercontainer should inspect the volume that is mounted to it, be it automatically or via env variable, OR it should be clearly stated in docs, to use:
```yaml
volumes:
  nextcloud_aio_mastercontainer:
    external: true
```
and run `docker volume create --name nextcloud_aio_mastercontainer` before `docker compose up -d`.

### Host OS 
Doesn't matter

#### Nextcloud AIO version 
This happened to me when I updated to Nextcloud AIO v4.6.2, I assume from v4.5.0

#### Current channel 
latest
