### ISSUE TITLE
docker desktop - connecting to docker socket inside container with different user than root is broken after updating to 4.19

### ISSUE THREAD

**Issue by szaimen** [nextcloud/all-in-one#2450]
This is a Docker Desktop 4.19 bug.
See https://github.com/docker/for-win/issues/13447
and https://github.com/docker/for-mac/issues/6823

Workaround for now: revert back to Docker Desktop 4.18. See https://github.com/docker/for-win/issues/13447#issuecomment-1579399130

**Comment by bobloadmire** [comment]
I'm running docker for windows, the installer won't let me downgrade to 4.18, just says installation is up to date. How are you downgrading?

**Comment by EwanBSmith** [comment]
This appears to be fixed with docker desktop 4.21 (at least on windows)

**Comment by moracabanas** [comment]
Still having issues to access docker sock:

### Container logs
```error
If SELinux is enabled on your host, see https://github.com/nextcloud/all-in-one#are-there-known-problems-when-selinux-is-enabled
If you are on TrueNas SCALE, see https://github.com/nextcloud/all-in-one#can-i-run-aio-on-truenas-scale
If you are on Docker Desktop v4.19 or higher, see https://github.com/nextcloud/all-in-one/issues/2450
Cannot connect to the docker socket. Cannot proceed.
```


### Docker desktop version
```info
Server: Docker Desktop 4.21.1 (114176)
 Engine:
  Version:          24.0.2
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.20.4
  Git commit:       659604f
  Built:            Thu May 25 21:52:17 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.21
  GitCommit:        3dce8eb055cbb6872793272b4f20ed16117344f8
 runc:
  Version:          1.1.7
  GitCommit:        v1.1.7-0-g860f061
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
  ```

### Docker compose 
```
version: '3'
services:
  nextcloud-aio-mastercontainer:
    image: nextcloud/all-in-one:latest
    container_name: nextcloud-aio-mastercontainer
    privileged: true
    security_opt: ["label=disabled"]
    environment:
      - SKIP_DOMAIN_VALIDATION=true
    restart: always
    ports:
      - '80:80'
      - '8080'
      - '8443'
    volumes:
      - nextcloud_aio_mastercontainer:/mnt/docker-aio-config
      - /var/run/docker.sock:/var/run/docker.sock:ro
volumes:
  nextcloud_aio_mastercontainer:
    name: nextcloud_aio_mastercontainer

```

**Comment by szaimen** [comment]
Please try this:
```
version: '3'
services:
  nextcloud-aio-mastercontainer:
    image: nextcloud/all-in-one:latest
    container_name: nextcloud-aio-mastercontainer
    environment:
      - SKIP_DOMAIN_VALIDATION=true
    restart: always
    ports:
      - '80:80'
      - '8080'
      - '8443'
    volumes:
      - nextcloud_aio_mastercontainer:/mnt/docker-aio-config
      - //var/run/docker.sock:/var/run/docker.sock:ro
volumes:
  nextcloud_aio_mastercontainer:
    name: nextcloud_aio_mastercontainer
```

Also see https://github.com/nextcloud/all-in-one#how-to-run-aio-on-windows

For further help, please ask at https://github.com/nextcloud/all-in-one/discussions/new?category=questions
