### ISSUE TITLE
Custom UID results in unreadable Docker socket

### ISSUE THREAD

**Issue by Jamy-L** [nextcloud/all-in-one#2515]
Hi, I have a user called `docker` of UID 114, from the group `docker` of GID 119. I want to use it to run Nextcloud, because it enables other containers to work with the same files without permission issues. However, when I modify the docker-compose to specify the UID, I get an opaque permission error as can be seen below. I am not really sure if it as bug or an error on my side. I have tried to completely delete the container and play with the permissions without success, but I may have overlooked some points. 

### Steps to reproduce
1. Get a working netxcloud installation
2. Modify the docker-compose to run it with a custom UID
3. Try to docker-compose

### Expected behavior 
The container should launch

### Actual behavior 
Running Nextcloud with the regular setup works flawlessly, but when I add  `user: "114:119"` in the docker compose, the mastercontainer crashes, presumably because of a permission issue with the docker socket.

### Host OS 
Ubuntu 22.04.2 LTS

#### Nextcloud AIO version 
latest (I cannot access the AIO interface)
#### Current channel 
latest
#### Other valuable info 

```
sudo: you do not exist in the passwd database
Trying to fix docker.sock permissions internally...
Creating docker group internally with id 119
groupadd: /etc/group.13: Permission denied
groupadd: cannot lock /etc/group; try again later.
usermod: group 'docker' does not exist
sudo: you do not exist in the passwd database
Docker socket is not readable by the www-data user. Cannot continue.
```

```
sudo ss -a | grep docker.sock
u_str LISTEN 0      4096                                                                     /run/docker.sock 23104                           * 0
```

`docker-compose`:
```yaml
  nextcloud:
    image: nextcloud/all-in-one:latest
    restart: unless-stopped
    container_name: nextcloud-aio-mastercontainer
    ports:
      - "${WEBUI_PORT_NEXTCLOUD?err}:8080"
    environment:
      - APACHE_PORT=11000
      - APACHE_IP_BINDING=0.0.0.0
      - NEXTCLOUD_DATADIR=/mnt/pool_0/nextcloud
    user: "114:119"
    volumes:
      - nextcloud_aio_mastercontainer:/mnt/docker-aio-config
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - media-network
```
