### ISSUE TITLE
GIF errors Unsupported image output type (libvips)

### ISSUE THREAD

**Issue by solracsf** [nextcloud/all-in-one#2543]
### Steps to reproduce
1. Upload GIF (attached)
2. Wait for Imaginry to do it's job
3. Error

> GuzzleHttp\Exception\ClientException: Client error: `POST http://10.0.0.14:9000/pipeline?operations=%5B%7B%22operation%22%3A%22autorotate%22%7D%2C%7B%22operation%22%3A%22smartcrop%22%2C%22params%22%3A%7B%22width%22%3A256%2C%22height%22%3A256%2C%22stripmeta%22%3A%22true%22%2C%22type%22%3A%22png%22%2C%22norotation%22%3A%22true%22%2C%22quality%22%3A%2280%22%7D%7D%5D` resulted in a `400 Bad Request` response: {"message":"Error while processing the image: Unsupported image output type","status":400}

Most likely related to `libvips` :
https://github.com/h2non/bimg/issues/380#issuecomment-1148566805

Consider build `libvips` from source in Dockerfile:
https://github.com/cshum/imagor/blob/09808e0d823bf3896b53c628069e0ef96a9a56a6/Dockerfile#L14

### docker-compose

```
version: "3"
services:
  imaginary:
    image: nextcloud/aio-imaginary:latest
    environment:
       PORT: 9000
    command: -enable-url-source -return-size -concurrency 10
    ports:
      - "9000:9000"
    restart: unless-stopped
```
### GIF to reproduce

![1_zXRFrYduz3C0suBoqrwXbQ](https://github.com/nextcloud/all-in-one/assets/12234510/050375d9-0015-4df2-b653-edb9890fab1b)
