### ISSUE TITLE
Clamav does not start

### ISSUE THREAD

**Issue by erwanlpfr** [nextcloud/all-in-one#3359]
### Steps to reproduce
1. use manual install
2.start/restart...
3.and see the lofs

### Expected behavior 
After tries, nextcloud just keep the clamav start.
While checking the logs I get this : 

```
nextcloud-aio-nextcloud-aio-clamav-1  | [WARN  tini (7)] Tini is not running as PID 1 and isn't registered as a child subreaper.
nextcloud-aio-nextcloud-aio-clamav-1  | Zombie processes will not be re-parented to Tini, so zombie reaping won't work.
nextcloud-aio-nextcloud-aio-clamav-1  | To fix the problem, use the -s option or set the environment variable TINI_SUBREAPER to register Tini as a child subreaper, or run Tini as PID 1.
nextcloud-aio-nextcloud-aio-clamav-1  | install: can't create directory '/run/clamav': Read-only file system
```

```yml
  nextcloud-aio-clamav:
    image: nextcloud/aio-clamav:latest
    init: true
    expose:
      - "3310"
    environment:
      - TZ=${TIMEZONE}
      - CLAMD_STARTUP_TIMEOUT=90
    volumes:
      - nextcloud_aio_clamav:/var/lib/clamav:rw
    restart: unless-stopped
    profiles:
      - clamav
    networks:
      - nextcloud-aio
    read_only: true
    tmpfs:
      - /var/lock
      - /var/log/clamav
      - /tmp
 ```

### Host OS 
Linux/Debian with last version en docker

#### Nextcloud AIO version 
7.2.1

#### Current channel 
latest
