### ISSUE TITLE
Unable to Start Apache & Talk Containers

### ISSUE THREAD

**Issue by DrShivang** [nextcloud/all-in-one#349]
Hi,

I am using Ubuntu in Arm64 based oracle cloud server for testing AIO

I followed the guidelines and using docker-compose fired the master container
docker-compose.yml
```
version: "3.8"

volumes:
  nextcloud_aio_mastercontainer:
    name: nextcloud_aio_mastercontainer

services:
  nextcloud:
    image: nextcloud/all-in-one:latest-arm64
    restart: unless-stopped
    container_name: nextcloud-aio-mastercontainer
    volumes:
      - nextcloud_aio_mastercontainer:/mnt/docker-aio-config
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 80:80
      - 8080:8080
      - 8443:8443
      - 3478:3478

```
I successfully accessed the master container on port 8080, verified the domain, logged in to the admin interface and started the child containers by clicking on "start containers"
after a while, all containers start except **apache** and **talk**.
![NC AIO](https://user-images.githubusercontent.com/94187557/157952197-47829f6f-1d87-475a-9a10-cf31f4e0dfe0.png)
upon clicking the "stopped" in front of Apache, for checking logs, I get the following error
[Apache error.txt](https://github.com/nextcloud/all-in-one/files/8235110/Apache.error.txt)
apparently, it's a 404 as far as I can understand as the container has not yet been started.
so, I bashed into mastercontainer, cd into apache and tried running start.sh where I got the following error

> NC_DOMAIN and NEXTCLOUD_HOST need to be provided. Exiting!

How and What needs to be done ?
where should I declare these 2 variables ? where have I gone wrong, if someone can point in the right direction.
Help!

**Comment by szaimen** [comment]
Hello, you made a mistake in your docker-compose file. See https://github.com/nextcloud/all-in-one/blob/main/docker-compose.yml for a working example. You need to only change `image: nextcloud/all-in-one:latest` to `image: nextcloud/all-in-one:latest-arm64` in order to make it work.

**Comment by DrShivang** [comment]
Thanks for pointing that out, I removed talk ports from docker-compose.yml and it now am getting this error after logging into mastercontainer interface

> Fatal error: Uncaught GuzzleHttp\Exception\ServerException: Server error: `POST http://localhost/v1.41/containers/nextcloud-aio-domaincheck/start` resulted in a `500 Internal Server Error` response: {"message":"driver failed programming external connectivity on endpoint nextcloud-aio-domaincheck (946a884ee5decd7e79823 (truncated...) in /var/www/docker-aio/php/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:113 Stack trace: #0 /var/www/docker-aio/php/vendor/guzzlehttp/guzzle/src/Middleware.php(69): GuzzleHttp\Exception\RequestException::create(Object(GuzzleHttp\Psr7\Request), Object(GuzzleHttp\Psr7\Response), NULL, Array, NULL) #1 /var/www/docker-aio/php/vendor/guzzlehttp/promises/src/Promise.php(204): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Response)) #2 /var/www/docker-aio/php/vendor/guzzlehttp/promises/src/Promise.php(153): GuzzleHttp\Promise\Promise::callHandler(1, Object(GuzzleHttp\Psr7\Response), NULL) #3 /var/www/docker-aio/php/vendor/guzzlehttp/promises/src/TaskQueue.php(48): GuzzleHttp\Promise\Promise::GuzzleHttp\Promise\{closure}() #4 /var/www/docker-aio/php/vendor/guzzlehttp/promises/src/Promise.php(248): GuzzleHttp\Promise\TaskQueue->run(true) #5 /var/www/docker-aio/php/vendor/guzzlehttp/promises/src/Promise.php(224): GuzzleHttp\Promise\Promise->invokeWaitFn() #6 /var/www/docker-aio/php/vendor/guzzlehttp/promises/src/Promise.php(269): GuzzleHttp\Promise\Promise->waitIfPending() #7 /var/www/docker-aio/php/vendor/guzzlehttp/promises/src/Promise.php(226): GuzzleHttp\Promise\Promise->invokeWaitList() #8 /var/www/docker-aio/php/vendor/guzzlehttp/promises/src/Promise.php(62): GuzzleHttp\Promise\Promise->waitIfPending() #9 /var/www/docker-aio/php/vendor/guzzlehttp/guzzle/src/Client.php(187): GuzzleHttp\Promise\Promise->wait() #10 /var/www/docker-aio/php/vendor/guzzlehttp/guzzle/src/ClientTrait.php(95): GuzzleHttp\Client->request('POST', 'http://localhos...', Array) #11 /var/www/docker-aio/php/src/Docker/DockerActionManager.php(147): GuzzleHttp\Client->post('http://localhos...') #12 /var/www/docker-aio/php/src/Controller/DockerController.php(40): AIO\Docker\DockerActionManager->StartContainer(Object(AIO\Container\Container)) #13 /var/www/docker-aio/php/src/Controller/DockerController.php(167): AIO\Controller\DockerController->PerformRecursiveContainerStart('nextcloud-aio-d...') #14 /var/www/docker-aio/php/public/index.php(70): AIO\Controller\DockerController->StartDomaincheckContainer() #15 /var/www/docker-aio/php/vendor/slim/slim/Slim/Handlers/Strategies/RequestResponse.php(43): Closure->{closure}(Object(GuzzleHttp\Psr7\ServerRequest), Object(GuzzleHttp\Psr7\Response), Array) #16 /var/www/docker-aio/php/vendor/slim/slim/Slim/Routing/Route.php(384): Slim\Handlers\Strategies\RequestResponse->__invoke(Object(Closure), Object(GuzzleHttp\Psr7\ServerRequest), Object(GuzzleHttp\Psr7\Response), Array) #17 /var/www/docker-aio/php/vendor/slim/slim/Slim/MiddlewareDispatcher.php(81): Slim\Routing\Route->handle(Object(GuzzleHttp\Psr7\ServerRequest)) #18 /var/www/docker-aio/php/vendor/slim/slim/Slim/MiddlewareDispatcher.php(81): Slim\MiddlewareDispatcher->handle(Object(GuzzleHttp\Psr7\ServerRequest)) #19 /var/www/docker-aio/php/vendor/slim/slim/Slim/Routing/Route.php(341): Slim\MiddlewareDispatcher->handle(Object(GuzzleHttp\Psr7\ServerRequest)) #20 /var/www/docker-aio/php/vendor/slim/slim/Slim/Routing/RouteRunner.php(84): Slim\Routing\Route->run(Object(GuzzleHttp\Psr7\ServerRequest)) #21 /var/www/docker-aio/php/vendor/slim/csrf/src/Guard.php(456): Slim\Routing\RouteRunner->handle(Object(GuzzleHttp\Psr7\ServerRequest)) #22 /var/www/docker-aio/php/vendor/slim/slim/Slim/MiddlewareDispatcher.php(209): Slim\Csrf\Guard->process(Object(GuzzleHttp\Psr7\ServerRequest), Object(Slim\Routing\RouteRunner)) #23 /var/www/docker-aio/php/vendor/slim/twig-view/src/TwigMiddleware.php(115): Psr\Http\Server\RequestHandlerInterface@anonymous->handle(Object(GuzzleHttp\Psr7\ServerRequest)) #24 /var/www/docker-aio/php/vendor/slim/slim/Slim/MiddlewareDispatcher.php(147): Slim\Views\TwigMiddleware->process(Object(GuzzleHttp\Psr7\ServerRequest), Object(Psr\Http\Server\RequestHandlerInterface@anonymous)) #25 /var/www/docker-aio/php/src/Middleware/AuthMiddleware.php(38): Psr\Http\Server\RequestHandlerInterface@anonymous->handle(Object(GuzzleHttp\Psr7\ServerRequest)) #26 /var/www/docker-aio/php/vendor/slim/slim/Slim/MiddlewareDispatcher.php(313): AIO\Middleware\AuthMiddleware->__invoke(Object(GuzzleHttp\Psr7\ServerRequest), Object(Psr\Http\Server\RequestHandlerInterface@anonymous)) #27 /var/www/docker-aio/php/vendor/slim/slim/Slim/MiddlewareDispatcher.php(81): Psr\Http\Server\RequestHandlerInterface@anonymous->handle(Object(GuzzleHttp\Psr7\ServerRequest)) #28 /var/www/docker-aio/php/vendor/slim/slim/Slim/App.php(215): Slim\MiddlewareDispatcher->handle(Object(GuzzleHttp\Psr7\ServerRequest)) #29 /var/www/docker-aio/php/vendor/slim/slim/Slim/App.php(199): Slim\App->handle(Object(GuzzleHttp\Psr7\ServerRequest)) #30 /var/www/docker-aio/php/public/index.php(141): Slim\App->run() #31 {main} thrown in /var/www/docker-aio/php/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php on line 113

**Comment by szaimen** [comment]
hm... can you stop the nextcloud-aio-apache container for a test?

**Comment by DrShivang** [comment]
Stopped the nextcloud-aio-apache docker
and the error was gone.

so should I, for the time being, first verify the domain and then manually start apache again?

**Comment by DrShivang** [comment]
Stopped Apache
Verified Domain
Went ahead to start the apache again thru docker command and received this error
`sudo docker start nextcloud-aio-apache
Error response from daemon: driver failed programming external connectivity on endpoint nextcloud-aio-apache (c797952c0b6806cda379eda52bebabfe0171e134d8e879479c10ae0bd0325f51): Bind for 0.0.0.0:443 failed: port is already allocated
Error: failed to start containers: nextcloud-aio-apache
`

**Comment by szaimen** [comment]
no, you should now be able to start  all containers using the buttons (you may need to stop them first)

**Comment by DrShivang** [comment]
@szaimen Thanks
I did that, stopped all containers and started them from mastercontainer interface.
then opened the Nextcloud login page
tried logging in with the credentials provided  and its giving 
`Wrong username or password.`
have tried several times. am just copying & pasting but to no success.

**Comment by szaimen** [comment]
> have tried several times. am just copying & pasting but to no success.

Hm... no idea.

Maybe you should think about reinstalling:
1. stop all containers from the aio interface
2. stop the mastercontainer with `sudo docker stop nextcloud-aio-mastercontainer`
3. run `sudo docker container prune`
4. run `sudo docker volume prune`
5. try again with the correct docker-compose file.

**Comment by DrShivang** [comment]
tried but still no success
getting the same error
`Wrong username or password.`

anything to do with the configuration ?
can i manually set it up to something else ?

**Comment by szaimen** [comment]
No, that should work... 
you can follow https://docs.nextcloud.com/server/latest/admin_manual/configuration_user/reset_admin_password.html?highlight=reset

**Comment by DrShivang** [comment]
Thanks
That Worked !
I was expecting it to go smooth as described.
maybe this login issue can be checked again or on some other arm64 machine so as to pinpoint the root cause.

**Comment by arsaboo** [comment]
> Hello, you made a mistake in your docker-compose file. See https://github.com/nextcloud/all-in-one/blob/main/docker-compose.yml for a working example. You need to only change `image: nextcloud/all-in-one:latest` to `image: nextcloud/all-in-one:latest-arm64` in order to make it work.

@szaimen I think it would make sense to modify the docker-compose to something like the following (to allow someone to specify local paths). 

```
version: "3.8"

volumes:
  nextcloud_aio_mastercontainer:
    name: nextcloud_aio_mastercontainer
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/mnt/docker/nextcloud/'      
services:
  nextcloud:
    image: nextcloud/all-in-one:latest
    restart: unless-stopped
    container_name: nextcloud-aio-mastercontainer
    volumes:
      - nextcloud_aio_mastercontainer:/mnt/docker-aio-config
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 80:80
      - 8080:8080
      - 8443:8443
```
If you want to use with other reverse proxy, just add the `APACHE_PORT` in the environmental variable:
```
version: "3.8"

volumes:
  nextcloud_aio_mastercontainer:
    name: nextcloud_aio_mastercontainer
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/mnt/docker/nextcloud/'      
services:
  nextcloud:
    image: nextcloud/all-in-one:latest
    restart: unless-stopped
    container_name: nextcloud-aio-mastercontainer
    volumes:
      - nextcloud_aio_mastercontainer:/mnt/docker-aio-config
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 80:80
      - 8080:8080
      - 8443:8443
    environment:
      APACHE_PORT: "11000"
```
