### ISSUE TITLE
nextcloud-aio-domaincheck: Request failed with status code 500

### ISSUE THREAD

**Issue by tiritibambix** [nextcloud/all-in-one#3677]
Hello.

I have previously installed Nextcloud AIO with no problem.
One day, all containers disapeared for no reason, but let's say I messed something up.
So I copied my files to some secure place and proceeded to erase any folder and volumes related to Nextcloud AIO.
I then reinstalled Nextcloud AIO.

Now I have a problem.
I reach the setup page and I reach the containers page, got initial password.
nextcloud-aio-domaincheck won't launcha and I can't access Nextcloud.

### Host OS 
openmediavault 6.9.5-1 (Shaitan) 

#### Nextcloud AIO version 
:lastest

#### Other valuable info 
Docker version 24.0.7, build afdd53b

Docker-compose:
```
version: "3.8"
volumes:
 nextcloud_aio_mastercontainer:
   name: nextcloud_aio_mastercontainer
services:
 nextcloud:
   image: nextcloud/all-in-one:latest
   restart: unless-stopped
   container_name: nextcloud-aio-mastercontainer
   volumes:
     - nextcloud_aio_mastercontainer:/mnt/docker-aio-config
     - /var/run/docker.sock:/var/run/docker.sock:ro
   ports:
     - 8145:8080
   environment:
     - NEXTCLOUD_DATADIR=/srv/.../Nextcloud/
     - NEXTCLOUD_UPLOAD_LIMIT=5G
     - NEXTCLOUD_MAX_TIME=360
     - NEXTCLOUD_MEMORY_LIMIT=2048M
     - APACHE_PORT=11000
```

[Apache logs](https://clip.steph.click/-dvfTMnjF7T)
[Database logs](https://clip.steph.click/-kgVzTDpLoC)
[Nextcloud logs](https://clip.steph.click/-WT5LH4u8HS)
[Notify push logs](https://clip.steph.click/-asQWuw6KWG)
[Redis logs](https://clip.steph.click/-RdY8BDAdyG)
[Collabora logs](https://clip.steph.click/-GP9iHgwoCj)
[nextcloud-aio-domaincheck logs](https://clip.steph.click/-bP8nQFa3BB)
[Imaginary logs](https://clip.steph.click/-GP9iHgwoCj)
[Master container](https://clip.steph.click/-fRKrWwpb7v)
