### ISSUE TITLE
Apache container not starting with docker 25.0.0

### ISSUE THREAD

**Issue by StuartMorrisAU** [nextcloud/all-in-one#4092]
### Steps to reproduce
1. Run `sudo docker compose up -d`
2. Check https://10.10.70.31:8080
3. Status is still the following after an hour:

```text
Nextcloud AIO v7.10.0
You are running the [latest](https://github.com/nextcloud/all-in-one#how-to-switch-the-channel) channel. ([Logs](https://10.10.70.31:8080/api/docker/logs?id=nextcloud-aio-mastercontainer))

 Containers are currently starting.

[Reload ↻](https://10.10.70.31:8080/containers)

Containers
 Apache ([Starting](https://10.10.70.31:8080/api/docker/logs?id=nextcloud-aio-apache))
 Database ([Running](https://10.10.70.31:8080/api/docker/logs?id=nextcloud-aio-database))
 Nextcloud ([Running](https://10.10.70.31:8080/api/docker/logs?id=nextcloud-aio-nextcloud))
 Notify Push ([Running](https://10.10.70.31:8080/api/docker/logs?id=nextcloud-aio-notify-push))
 Redis ([Running](https://10.10.70.31:8080/api/docker/logs?id=nextcloud-aio-redis))
 Collabora ([Running](https://10.10.70.31:8080/api/docker/logs?id=nextcloud-aio-collabora))
 Talk ([Running](https://10.10.70.31:8080/api/docker/logs?id=nextcloud-aio-talk))
 Talk Recording ([Running](https://10.10.70.31:8080/api/docker/logs?id=nextcloud-aio-talk-recording))
 ClamAV ([Running](https://10.10.70.31:8080/api/docker/logs?id=nextcloud-aio-clamav))
 Imaginary ([Running](https://10.10.70.31:8080/api/docker/logs?id=nextcloud-aio-imaginary))
 Fulltextsearch ([Running](https://10.10.70.31:8080/api/docker/logs?id=nextcloud-aio-fulltextsearch))
 Docker Socket Proxy ([Running](https://10.10.70.31:8080/api/docker/logs?id=nextcloud-aio-docker-socket-proxy))
Your containers are up-to-date.
```

### Expected behavior 

All containers started/running as normal.

### Actual behavior 

Apache container stuck in starting state, although the Nextcloud web interface does load as usual at the published domain.

### Host OS 

```bash
             .',;::::;,'.                host@nextcloud
         .';:cccccccccccc:;,.            ------------------ 
      .;cccccccccccccccccccccc;.         OS: Fedora Linux 39 (Workstation Edition) x86_64 
    .:cccccccccccccccccccccccccc:.       Host: Alienware Aurora R6 1.0.23 
  .;ccccccccccccc;.:dddl:.;ccccccc;.     Kernel: 6.6.11-200.fc39.x86_64 
 .:ccccccccccccc;OWMKOOXMWd;ccccccc:.    Uptime: 2 hours, 5 mins 
.:ccccccccccccc;KMMc;cc;xMMc:ccccccc:.   Packages: 2467 (rpm), 30 (flatpak) 
,cccccccccccccc;MMM.;cc;;WW::cccccccc,   Shell: bash 5.2.21 
:cccccccccccccc;MMM.;cccccccccccccccc:   Resolution: 2560x1440 
:ccccccc;oxOOOo;MMM0OOk.;cccccccccccc:   DE: GNOME 45.3 
cccccc:0MMKxdd:;MMMkddc.;cccccccccccc;   WM: Mutter 
ccccc:XM0';cccc;MMM.;cccccccccccccccc'   WM Theme: Adwaita 
ccccc;MMo;ccccc;MMW.;ccccccccccccccc;    Theme: Adwaita [GTK2/3] 
ccccc;0MNc.ccc.xMMd:ccccccccccccccc;     Icons: Adwaita [GTK2/3] 
cccccc;dNMWXXXWM0::cccccccccccccc:,      Terminal: gnome-terminal 
cccccccc;.:odl:.;cccccccccccccc:,.       CPU: Intel i7-7700K (8) @ 4.500GHz 
:cccccccccccccccccccccccccccc:'.         GPU: Intel HD Graphics 630 
.:cccccccccccccccccccccc:;,..            GPU: NVIDIA GeForce GTX 1080 
  '::cccccccccccccc::;,.                 Memory: 6334MiB / 31993MiB 
```

#### Nextcloud AIO version 

Nextcloud AIO v7.10.0

#### Current channel 

latest

#### Other valuable info 

<details><summary>Details</summary>
I'm using Nginx Proxy Manager on a RPi (10.10.60.31) to proxy a domain name for Nextcloud. The DNS records for Nextcloud are setup in a local Pi-hole, and the cert is done using a DNS challenge to Cloudflare where the domain is setup.

I had a weird issue earlier today where the AIO interface wouldn't load after a reboot. I wondered if there was some odd port conflict, so I ran:

```bash
sudo docker compose down
sudo systemctl stop docker.socket
sudo systemctl stop docker.service
sudo systemctl disable docker.socket
sudo systemctl disable docker.service
sudo systemctl enable docker.service
sudo systemctl enable docker.socket
sudo systemctl start docker.service
sudo systemctl start docker.socket
sudo docker compose up -d
```

At that point, the AIO interface loaded OK but Apache wouldn't start. I restarted the computer but still had the same issue of Apache not starting but the Nextcloud web interface loading OK.

##### Docker Compose File

```yml
version: '3.8'
services:
  nextcloud-aio-mastercontainer:
    image: nextcloud/all-in-one:latest
    init: true
    restart: unless-stopped # or `always`
    container_name: nextcloud-aio-mastercontainer # This line is not allowed to be changed as otherwise AIO will not work correctly
    volumes:
      - nextcloud_aio_mastercontainer:/mnt/docker-aio-config # This line is not allowed to be changed as otherwise the built-in backup solution will not work
      - /var/run/docker.sock:/var/run/docker.sock:ro # May be changed on macOS, Windows or docker rootless. See the applicable documentation. If adjusting, don't forget to also set 'WATCHTOWER_DOCKER_SOCKET_PATH'!
    ports:
      # - 80:80 # Can be removed when running behind a web server or reverse proxy (like Apache, Nginx, Cloudflare Tunnel and else). See https://github.com/nextcloud/all-in-one/blob/main/reverse-proxy.md
      - 8080:8080
      # - 8443:8443 # Can be removed when running behind a web server or reverse proxy (like Apache, Nginx, Cloudflare Tunnel and else). See https://github.com/nextcloud/all-in-one/blob/main/reverse-proxy.md
    environment: # Is needed when using any of the options below
      # - AIO_DISABLE_BACKUP_SECTION=false # Setting this to true allows to hide the backup section in the AIO interface. See https://github.com/nextcloud/all-in-one#how-to-disable-the-backup-section
      - APACHE_PORT=11000 # Is needed when running behind a web server or reverse proxy (like Apache, Nginx, Cloudflare Tunnel and else). See https://github.com/nextcloud/all-in-one/blob/main/reverse-proxy.md
      - APACHE_IP_BINDING=0.0.0.0 # Should be set when running behind a web server or reverse proxy (like Apache, Nginx, Cloudflare Tunnel and else) that is running on the same host. See https://github.com/nextcloud/all-in-one/blob/main/reverse-proxy.md
      # - BORG_RETENTION_POLICY=--keep-within=7d --keep-weekly=4 --keep-monthly=6 # Allows to adjust borgs retention policy. See https://github.com/nextcloud/all-in-one#how-to-adjust-borgs-retention-policy
      # - COLLABORA_SECCOMP_DISABLED=false # Setting this to true allows to disable Collabora's Seccomp feature. See https://github.com/nextcloud/all-in-one#how-to-disable-collaboras-seccomp-feature
      - NEXTCLOUD_DATADIR=/mnt/ncdata # Allows to set the host directory for Nextcloud's datadir. ⚠️⚠️⚠️ Warning: do not set or adjust this value after the initial Nextcloud installation is done! See https://github.com/nextcloud/all-in-one#how-to-change-the-default-location-of-nextclouds-datadir
      # - NEXTCLOUD_MOUNT=/mnt/ # Allows the Nextcloud container to access the chosen directory on the host. See https://github.com/nextcloud/all-in-one#how-to-allow-the-nextcloud-container-to-access-directories-on-the-host
      # - NEXTCLOUD_UPLOAD_LIMIT=10G # Can be adjusted if you need more. See https://github.com/nextcloud/all-in-one#how-to-adjust-the-upload-limit-for-nextcloud
      # - NEXTCLOUD_MAX_TIME=3600 # Can be adjusted if you need more. See https://github.com/nextcloud/all-in-one#how-to-adjust-the-max-execution-time-for-nextcloud
      # - NEXTCLOUD_MEMORY_LIMIT=512M # Can be adjusted if you need more. See https://github.com/nextcloud/all-in-one#how-to-adjust-the-php-memory-limit-for-nextcloud
      # - NEXTCLOUD_TRUSTED_CACERTS_DIR=/path/to/my/cacerts # CA certificates in this directory will be trusted by the OS of the nexcloud container (Useful e.g. for LDAPS) See See https://github.com/nextcloud/all-in-one#how-to-trust-user-defined-certification-authorities-ca
      # - NEXTCLOUD_STARTUP_APPS=deck twofactor_totp tasks calendar contacts notes # Allows to modify the Nextcloud apps that are installed on starting AIO the first time. See https://github.com/nextcloud/all-in-one#how-to-change-the-nextcloud-apps-that-are-installed-on-the-first-startup
      - NEXTCLOUD_ADDITIONAL_APKS=imagemagick # This allows to add additional packages to the Nextcloud container permanently. Default is imagemagick but can be overwritten by modifying this value. See https://github.com/nextcloud/all-in-one#how-to-add-os-packages-permanently-to-the-nextcloud-container
      - NEXTCLOUD_ADDITIONAL_PHP_EXTENSIONS=imagick # This allows to add additional php extensions to the Nextcloud container permanently. Default is imagick but can be overwritten by modifying this value. See https://github.com/nextcloud/all-in-one#how-to-add-php-extensions-permanently-to-the-nextcloud-container
      - NEXTCLOUD_ENABLE_DRI_DEVICE=true # This allows to enable the /dev/dri device in the Nextcloud container. ⚠️⚠️⚠️ Warning: this only works if the '/dev/dri' device is present on the host! If it should not exist on your host, don't set this to true as otherwise the Nextcloud container will fail to start! See https://github.com/nextcloud/all-in-one#how-to-enable-hardware-transcoding-for-nextcloud
      # - NEXTCLOUD_KEEP_DISABLED_APPS=false # Setting this to true will keep Nextcloud apps that are disabled in the AIO interface and not uninstall them if they should be installed. See https://github.com/nextcloud/all-in-one#how-to-keep-disabled-apps
      # - TALK_PORT=3478 # This allows to adjust the port that the talk container is using. See https://github.com/nextcloud/all-in-one#how-to-adjust-the-talk-port
      # - WATCHTOWER_DOCKER_SOCKET_PATH=/var/run/docker.sock # Needs to be specified if the docker socket on the host is not located in the default '/var/run/docker.sock'. Otherwise mastercontainer updates will fail. For macos it needs to be '/var/run/docker.sock'
    # networks: # Is needed when you want to create the nextcloud-aio network with ipv6-support using this file, see the network config at the bottom of the file
      # - nextcloud-aio # Is needed when you want to create the nextcloud-aio network with ipv6-support using this file, see the network config at the bottom of the file
    # # Uncomment the following line when using SELinux
    # security_opt: ["label:disable"]

  # # Optional: Caddy reverse proxy. See https://github.com/nextcloud/all-in-one/blob/main/reverse-proxy.md
  # # You can find further examples here: https://github.com/nextcloud/all-in-one/discussions/588
  # caddy:
  #   image: caddy:alpine
  #   restart: always
  #   container_name: caddy
  #   volumes:
  #     - ./Caddyfile:/etc/caddy/Caddyfile
  #     - ./certs:/certs
  #     - ./config:/config
  #     - ./data:/data
  #     - ./sites:/srv
  #   network_mode: "host"

volumes: # If you want to store the data on a different drive, see https://github.com/nextcloud/all-in-one#how-to-store-the-filesinstallation-on-a-separate-drive
  nextcloud_aio_mastercontainer:
    name: nextcloud_aio_mastercontainer # This line is not allowed to be changed as otherwise the built-in backup solution will not work

# # Optional: If you need ipv6, follow step 1 and 2 of https://github.com/nextcloud/all-in-one/blob/main/docker-ipv6-support.md first and then uncomment the below config in order to activate ipv6 for the internal nextcloud-aio network.
# # Please make sure to uncomment also the networking lines of the mastercontainer above in order to actually create the network with docker-compose
# networks:
#   nextcloud-aio:
#     name: nextcloud-aio # This line is not allowed to be changed as otherwise the created network will not be used by the other containers of AIO
#     driver: bridge
#     enable_ipv6: true
#     ipam:
#       driver: default
#       config:
#         - subnet: fd12:3456:789a:2::/64 # IPv6 subnet to use
```

##### sudo netstat -tulnp output

```bash
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 0.0.0.0:3478            0.0.0.0:*               LISTEN      29722/docker-proxy  
tcp        0      0 0.0.0.0:8080            0.0.0.0:*               LISTEN      33049/docker-proxy  
tcp        0      0 0.0.0.0:8180            0.0.0.0:*               LISTEN      36903/docker-proxy  
tcp        0      0 127.0.0.54:53           0.0.0.0:*               LISTEN      2340/systemd-resolv 
tcp        0      0 0.0.0.0:5355            0.0.0.0:*               LISTEN      2340/systemd-resolv 
tcp        0      0 0.0.0.0:11000           0.0.0.0:*               LISTEN      29279/docker-proxy  
tcp        0      0 127.0.0.1:631           0.0.0.0:*               LISTEN      2548/cupsd          
tcp        0      0 127.0.0.53:53           0.0.0.0:*               LISTEN      2340/systemd-resolv 
tcp        0      0 127.0.0.1:6341          0.0.0.0:*               LISTEN      4925/megasync       
tcp6       0      0 :::3478                 :::*                    LISTEN      29729/docker-proxy  
tcp6       0      0 :::8080                 :::*                    LISTEN      33057/docker-proxy  
tcp6       0      0 :::8180                 :::*                    LISTEN      36910/docker-proxy  
tcp6       0      0 :::5355                 :::*                    LISTEN      2340/systemd-resolv 
tcp6       0      0 :::9090                 :::*                    LISTEN      1/systemd           
tcp6       0      0 :::8280                 :::*                    LISTEN      2546/calibre-server 
tcp6       0      0 ::1:631                 :::*                    LISTEN      2548/cupsd          
udp        0      0 127.0.0.54:53           0.0.0.0:*                           2340/systemd-resolv 
udp        0      0 127.0.0.53:53           0.0.0.0:*                           2340/systemd-resolv 
udp        0      0 127.0.0.1:323           0.0.0.0:*                           2511/chronyd        
udp        0      0 0.0.0.0:34886           0.0.0.0:*                           6907/brave --type=u 
udp        0      0 0.0.0.0:3478            0.0.0.0:*                           29743/docker-proxy  
udp        0      0 224.0.0.251:5353        0.0.0.0:*                           6907/brave --type=u 
udp        0      0 224.0.0.251:5353        0.0.0.0:*                           6907/brave --type=u 
udp        0      0 224.0.0.251:5353        0.0.0.0:*                           6907/brave --type=u 
udp        0      0 10.10.70.31:5353        0.0.0.0:*                           2546/calibre-server 
udp        0      0 127.0.0.1:5353          0.0.0.0:*                           2546/calibre-server 
udp        0      0 0.0.0.0:5353            0.0.0.0:*                           2546/calibre-server 
udp        0      0 0.0.0.0:5353            0.0.0.0:*                           2387/avahi-daemon:  
udp        0      0 0.0.0.0:5355            0.0.0.0:*                           2340/systemd-resolv 
udp        0      0 0.0.0.0:43923           0.0.0.0:*                           2387/avahi-daemon:  
udp6       0      0 ::1:323                 :::*                                2511/chronyd        
udp6       0      0 :::3478                 :::*                                29750/docker-proxy  
udp6       0      0 :::5353                 :::*                                2387/avahi-daemon:  
udp6       0      0 :::5355                 :::*                                2340/systemd-resolv 
udp6       0      0 :::43958                :::*                                6907/brave --type=u 
udp6       0      0 :::47652                :::*                                2387/avahi-daemon: 
```
##### MasterContainer Log

```text
Trying to fix docker.sock permissions internally...
Creating docker group internally with id 976
[0;92mInitial startup of Nextcloud All-in-One complete!
You should be able to open the Nextcloud AIO Interface now on port 8080 of this server!
E.g. https://internal.ip.of.this.server:8080

If your server has port 80 and 8443 open and you point a domain to your server, you can get a valid certificate automatically by opening the Nextcloud AIO Interface via:
https://your-domain-that-points-to-this-server.tld:8443[0m
++ head -1 /mnt/docker-aio-config/data/daily_backup_time
+ BACKUP_TIME=14:00
+ export BACKUP_TIME
+ export DAILY_BACKUP=1
+ DAILY_BACKUP=1
++ sed -n 2p /mnt/docker-aio-config/data/daily_backup_time
+ '[' '' '!=' automaticUpdatesAreNotEnabled ']'
+ export AUTOMATIC_UPDATES=1
+ AUTOMATIC_UPDATES=1
++ sed -n 3p /mnt/docker-aio-config/data/daily_backup_time
+ '[' '' '!=' successNotificationsAreNotEnabled ']'
+ export SEND_SUCCESS_NOTIFICATIONS=1
+ SEND_SUCCESS_NOTIFICATIONS=1
+ set +x
{"level":"info","ts":1705829188.215347,"msg":"using provided configuration","config_file":"/Caddyfile","config_adapter":""}
[Sun Jan 21 09:26:28.222316 2024] [mpm_event:notice] [pid 141:tid 139994618813256] AH00489: Apache/2.4.58 (Unix) OpenSSL/3.1.4 configured -- resuming normal operations
[Sun Jan 21 09:26:28.222354 2024] [core:notice] [pid 141:tid 139994618813256] AH00094: Command line: 'httpd -D FOREGROUND'
[21-Jan-2024 09:26:28] NOTICE: fpm is running, pid 148
[21-Jan-2024 09:26:28] NOTICE: ready to handle connections
```

##### Apache Log

```text
Waiting for Nextcloud to start...
Waiting for Nextcloud to start...
Waiting for Nextcloud to start...
Waiting for Nextcloud to start...
Waiting for Nextcloud to start...
Waiting for Nextcloud to start...
[Sun Jan 21 01:13:54.694701 2024] [mpm_event:notice] [pid 56:tid 139680750164808] AH00489: Apache/2.4.58 (Unix) configured -- resuming normal operations
[Sun Jan 21 01:13:54.694755 2024] [core:notice] [pid 56:tid 139680750164808] AH00094: Command line: '/usr/local/apache2/bin/httpd -D FOREGROUND'
{"level":"info","ts":1705760034.699797,"msg":"using provided configuration","config_file":"/tmp/Caddyfile","config_adapter":""}
nc: getaddrinfo for host "nextcloud-aio-nextcloud" port 9000: Try again
Waiting for Nextcloud to start...
Waiting for Nextcloud to start...
Waiting for Nextcloud to start...
Waiting for Nextcloud to start...
Waiting for Nextcloud to start...
Waiting for Nextcloud to start...
Waiting for Nextcloud to start...
Waiting for Nextcloud to start...
Waiting for Nextcloud to start...
Waiting for Nextcloud to start...
Waiting for Nextcloud to start...
Waiting for Nextcloud to start...
Waiting for Nextcloud to start...
{"level":"info","ts":1705802615.5630994,"msg":"using provided configuration","config_file":"/tmp/Caddyfile","config_adapter":""}
[Sun Jan 21 13:03:36.802509 2024] [mpm_event:notice] [pid 76:tid 139631654140744] AH00489: Apache/2.4.58 (Unix) configured -- resuming normal operations
[Sun Jan 21 13:03:36.802576 2024] [core:notice] [pid 76:tid 139631654140744] AH00094: Command line: '/usr/local/apache2/bin/httpd -D FOREGROUND'
{"level":"error","ts":1705816271.026801,"logger":"http.handlers.reverse_proxy","msg":"aborting with incomplete response","upstream":"localhost:8000","duration":0.001216901,"request":{"remote_ip":"10.10.60.31","remote_port":"52656","client_ip":"10.10.100.70","proto":"HTTP/1.1","method":"GET","host":"nextcloud.example.com","uri":"/apps/firstrunwizard/img/Nextcloud.mp4","headers":{"Accept-Encoding":["identity"],"X-Real-Ip":["10.10.100.70"],"X-Forwarded-Scheme":["https"],"Accept-Language":["en-AU,en;q=0.9"],"User-Agent":["Mozilla/5.0 (iPhone; CPU iPhone OS 17_2_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.2 Mobile/15E148 Safari/604.1"],"Sec-Fetch-Dest":["video"],"X-Forwarded-Proto":["https"],"Sec-Fetch-Site":["same-origin"],"X-Forwarded-Host":["nextcloud.example.com"],"Sec-Fetch-Mode":["no-cors"],"Range":["bytes=0-2560100"],"X-Playback-Session-Id":["5D3E6AF9-12B5-4C70-8B73-A9E90D1E7375"],"Cookie":[],"X-Forwarded-For":["10.10.100.70, 10.10.60.31"],"Accept":["*/*"]}},"error":"writing: write tcp 172.22.0.2:11000->10.10.60.31:52656: write: connection reset by peer"}
[Sun Jan 21 19:03:19 2024] [error] [(111)Connection refused] [client: [AH00957: FCGI: attempt to connect to 172.22.0.13:9000 (*:80) failed]
[Sun Jan 21 19:03:19 2024] [error] [client: 10.10.70.31, 10.10.60.31] [AH01079: failed to make connection to backend: nextcloud-aio-nextcloud] [Mozilla/5.0 (Linux) mirall/3.11.0git (Nextcloud, fedora-6.6.11-200.fc39.x86_64 ClientArchitecture: x86_64 OsArchitecture: x86_64)]
[Sun Jan 21 19:03:19 2024] [error] [(111)Connection refused] [client: [AH00957: FCGI: attempt to connect to 172.22.0.13:9000 (*:80) failed]
[Sun Jan 21 19:03:19 2024] [error] [client: 10.10.70.31, 10.10.60.31] [AH01079: failed to make connection to backend: nextcloud-aio-nextcloud] [Mozilla/5.0 (Linux) mirall/3.11.0git (Nextcloud, fedora-6.6.11-200.fc39.x86_64 ClientArchitecture: x86_64 OsArchitecture: x86_64)]
[Sun Jan 21 19:03:19 2024] [error] [(111)Connection refused] [client: [AH00957: FCGI: attempt to connect to 172.22.0.13:9000 (*:80) failed]
[Sun Jan 21 19:03:19 2024] [error] [client: 10.10.70.31, 10.10.60.31] [AH01079: failed to make connection to backend: nextcloud-aio-nextcloud] [Mozilla/5.0 (Linux) mirall/3.11.0git (Nextcloud, fedora-6.6.11-200.fc39.x86_64 ClientArchitecture: x86_64 OsArchitecture: x86_64)]
[Sun Jan 21 19:03:21 2024] [error] [(111)Connection refused] [client: [AH00957: FCGI: attempt to connect to 172.22.0.13:9000 (*:80) failed]
[Sun Jan 21 19:03:21 2024] [error] [client: 10.10.70.31, 10.10.60.31] [AH01079: failed to make connection to backend: nextcloud-aio-nextcloud] [gnome-online-accounts/3.48.0 libsoup/3.4.4]
[Sun Jan 21 19:03:22 2024] [error] [(111)Connection refused] [client: [AH00957: FCGI: attempt to connect to 172.22.0.13:9000 (*:80) failed]
[Sun Jan 21 19:03:22 2024] [error] [client: 10.10.70.31, 10.10.60.31] [AH01079: failed to make connection to backend: nextcloud-aio-nextcloud] [gnome-online-accounts/3.48.0 libsoup/3.4.4]
[Sun Jan 21 19:03:25 2024] [error] [(111)Connection refused] [client: [AH00957: FCGI: attempt to connect to 172.22.0.13:9000 (*:80) failed]
[Sun Jan 21 19:03:25 2024] [error] [client: 10.10.70.31, 10.10.60.31] [AH01079: failed to make connection to backend: nextcloud-aio-nextcloud] [gnome-online-accounts/3.48.0 libsoup/3.4.4]
nc: getaddrinfo for host "nextcloud-aio-nextcloud" port 9000: Try again
Waiting for Nextcloud to start...
Waiting for Nextcloud to start...
Waiting for Nextcloud to start...
Waiting for Nextcloud to start...
Waiting for Nextcloud to start...
Waiting for Nextcloud to start...
Waiting for Nextcloud to start...
Waiting for Nextcloud to start...
{"level":"info","ts":1705824395.3064277,"msg":"using provided configuration","config_file":"/tmp/Caddyfile","config_adapter":""}
[Sun Jan 21 19:06:35.307739 2024] [mpm_event:notice] [pid 58:tid 140332034562888] AH00489: Apache/2.4.58 (Unix) configured -- resuming normal operations
[Sun Jan 21 19:06:35.307794 2024] [core:notice] [pid 58:tid 140332034562888] AH00094: Command line: '/usr/local/apache2/bin/httpd -D FOREGROUND'
nc: getaddrinfo for host "nextcloud-aio-nextcloud" port 9000: Name does not resolve
Waiting for Nextcloud to start...
Waiting for Nextcloud to start...
Waiting for Nextcloud to start...
Waiting for Nextcloud to start...
Waiting for Nextcloud to start...
Waiting for Nextcloud to start...
Waiting for Nextcloud to start...
Waiting for Nextcloud to start...
Waiting for Nextcloud to start...
Waiting for Nextcloud to start...
Waiting for Nextcloud to start...
Waiting for Nextcloud to start...
Waiting for Nextcloud to start...
Waiting for Nextcloud to start...
Waiting for Nextcloud to start...
Waiting for Nextcloud to start...
Waiting for Nextcloud to start...
Waiting for Nextcloud to start...
Waiting for Nextcloud to start...
Waiting for Nextcloud to start...
Waiting for Nextcloud to start...
Waiting for Nextcloud to start...
Waiting for Nextcloud to start...
Waiting for Nextcloud to start...
Waiting for Nextcloud to start...
Waiting for Nextcloud to start...
Waiting for Nextcloud to start...
Waiting for Nextcloud to start...
Waiting for Nextcloud to start...
Waiting for Nextcloud to start...
Waiting for Nextcloud to start...
{"level":"info","ts":1705827279.7528458,"msg":"using provided configuration","config_file":"/tmp/Caddyfile","config_adapter":""}
[Sun Jan 21 19:54:40.067425 2024] [mpm_event:notice] [pid 132:tid 139768026913608] AH00489: Apache/2.4.58 (Unix) configured -- resuming normal operations
[Sun Jan 21 19:54:40.067482 2024] [core:notice] [pid 132:tid 139768026913608] AH00094: Command line: '/usr/local/apache2/bin/httpd -D FOREGROUND'
[Sun Jan 21 20:23:13 2024] [error] [(111)Connection refused] [client: [AH00957: FCGI: attempt to connect to 172.22.0.9:9000 (*:80) failed]
[Sun Jan 21 20:23:13 2024] [error] [client: 10.10.70.31, 10.10.60.31] [AH01079: failed to make connection to backend: nextcloud-aio-nextcloud] [gnome-online-accounts/3.48.0 libsoup/3.4.4]
[Sun Jan 21 20:23:14 2024] [error] [(111)Connection refused] [client: [AH00957: FCGI: attempt to connect to 172.22.0.9:9000 (*:80) failed]
[Sun Jan 21 20:23:14 2024] [error] [client: 10.10.70.31, 10.10.60.31] [AH01079: failed to make connection to backend: nextcloud-aio-nextcloud] [gnome-online-accounts/3.48.0 libsoup/3.4.4]
[Sun Jan 21 20:23:17 2024] [error] [(111)Connection refused] [client: [AH00957: FCGI: attempt to connect to 172.22.0.9:9000 (*:80) failed]
[Sun Jan 21 20:23:17 2024] [error] [client: 10.10.70.31, 10.10.60.31] [AH01079: failed to make connection to backend: nextcloud-aio-nextcloud] [Mozilla/5.0 (Linux) mirall/3.11.0git (Nextcloud, fedora-6.6.11-200.fc39.x86_64 ClientArchitecture: x86_64 OsArchitecture: x86_64)]
[Sun Jan 21 20:23:17 2024] [error] [(111)Connection refused] [client: [AH00957: FCGI: attempt to connect to 172.22.0.9:9000 (*:80) failed]
[Sun Jan 21 20:23:17 2024] [error] [client: 10.10.70.31, 10.10.60.31] [AH01079: failed to make connection to backend: nextcloud-aio-nextcloud] [Mozilla/5.0 (Linux) mirall/3.11.0git (Nextcloud, fedora-6.6.11-200.fc39.x86_64 ClientArchitecture: x86_64 OsArchitecture: x86_64)]
[Sun Jan 21 20:23:17 2024] [error] [(111)Connection refused] [client: [AH00957: FCGI: attempt to connect to 172.22.0.9:9000 (*:80) failed]
[Sun Jan 21 20:23:17 2024] [error] [client: 10.10.70.31, 10.10.60.31] [AH01079: failed to make connection to backend: nextcloud-aio-nextcloud] [Mozilla/5.0 (Linux) mirall/3.11.0git (Nextcloud, fedora-6.6.11-200.fc39.x86_64 ClientArchitecture: x86_64 OsArchitecture: x86_64)]
[Sun Jan 21 20:23:18 2024] [error] [(111)Connection refused] [client: [AH00957: FCGI: attempt to connect to 172.22.0.9:9000 (*:80) failed]
[Sun Jan 21 20:23:18 2024] [error] [client: 10.10.70.31, 10.10.60.31] [AH01079: failed to make connection to backend: nextcloud-aio-nextcloud] [gnome-online-accounts/3.48.0 libsoup/3.4.4]
Waiting for Nextcloud to start...
Waiting for Nextcloud to start...
Waiting for Nextcloud to start...
Waiting for Nextcloud to start...
Waiting for Nextcloud to start...
Waiting for Nextcloud to start...
Waiting for Nextcloud to start...
Waiting for Nextcloud to start...
[Sun Jan 21 20:25:38.713509 2024] [mpm_event:notice] [pid 58:tid 140406555687752] AH00489: Apache/2.4.58 (Unix) configured -- resuming normal operations
[Sun Jan 21 20:25:38.713557 2024] [core:notice] [pid 58:tid 140406555687752] AH00094: Command line: '/usr/local/apache2/bin/httpd -D FOREGROUND'
{"level":"info","ts":1705829138.718439,"msg":"using provided configuration","config_file":"/tmp/Caddyfile","config_adapter":""}
```
</details>
