### ISSUE TITLE
Invalid Nextcloud initial access credentials

### ISSUE THREAD

**Issue by lockness-Ko** [nextcloud/all-in-one#419]
### Steps to reproduce
1. start AIO with the following docker-compose.yml on a raspberry pi 4:
```yaml
version: "3"

services:
  nextcloud:
    image: nextcloud/all-in-one:latest-arm64
    restart: unless-stopped
    container_name: nextcloud-aio-mastercontainer
    volumes:
      - /srv/data/nextcloud_aio_mastercontainer:/mnt/docker-aio-config
      - /srv/data/data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 80:80
      - 8080:8080
      - 8443:8443
    privileged: true
```
2. go to :8080/containers
3. get the 'initial Nextcloud credentials'
4. Try to login on https://domain.com/login
5. says wrong user/pass
![image](https://user-images.githubusercontent.com/42625905/159834491-0b36ae86-6373-4135-a326-4b24eb93f80c.png)

### Host OS 
raspberry pi os 64-bit lite 
uname -a: Linux front 5.10.103-v8+ #1530 SMP PREEMPT Tue Mar 8 13:06:35 GMT 2022 aarch64 GNU/Linux

#### Nextcloud AIO version 
Beta v0.9.0

#### Other valuable info 
![image](https://user-images.githubusercontent.com/42625905/159834665-5f3d46c4-7b3c-476c-a5dd-0b062e31b885.png)
