### ISSUE TITLE
New preview images / thumbs (of large photos) are black & white only

### ISSUE THREAD

**Issue by kce68** [nextcloud/all-in-one#4239]
### Steps to reproduce
1. Make a fresh Install; but it happens also after updating: In my case from AiO 7.9.1 to 7.12.1
2. Open Photos-folder in Files
3. Take a Look at the standard "nextcloud group photo" / upload a new colored Photo 
4. Click on it: It's in B&W
5. Click the editing pencil: Photo becomes colored
6. Edit something and save it as new Photo: Previews und thumbnails ar generate in B&W

### Expected behavior 
Colored should be colored `:)`
As ist it works in all my installation with AiO 7.9.1

### Actual behavior 
Thumbnails and Previews are generated in B&W, when JPEG or PNGs have 12 megapixels
I found out that only smaller Photos seem to work. I checked PNG and JPEG.

Any ideas? Let me know if you need more information.

### Host OS 
KVM-VM in Proxmox with Ubuntu 22.4 LTS all updates as of today
has 6 GB RAM and 4 CPUs
Docker from the Docker apt-repositories
Deployed with docker compose via a Portainer EE
Behind a HAproxy

#### Nextcloud AIO version 
7.9.1 working and 7.12.1 not working
regardless of updating, fresh install with NC 27 or NC 28
with Containers:
 Apache ([Running]
 Database ([Running]
 Nextcloud ([Running]
 Notify Push ([Running]
 Redis ([Running]
 Collabora ([Running]
 Talk ([Running]
 Imaginary ([Running]
 Fulltextsearch ([Running]

#### Current channel 
Latest

#### Other valuable info 

My docker-compose:
```
version: "3.8"

volumes:
  nextcloud_aio_mastercontainer:
    name: nextcloud_aio_mastercontainer # This line is not allowed to be changed as otherwise the built-in backup solution will not work

services:
  nextcloud:
    image: nextcloud/all-in-one:latest
    restart: always
    container_name: nextcloud-aio-mastercontainer # This line is not allowed to be changed as otherwise AIO will not work correctly
    volumes:
      - nextcloud_aio_mastercontainer:/mnt/docker-aio-config # This line is not allowed to be changed as otherwise the built-in backup solution will not work
      - /var/run/docker.sock:/var/run/docker.sock:ro # May be changed on macOS, Windows or docker rootless. See the applicable documentation. If adjusting, don't forget to also set 'WATCHTOWER_DOCKER_SOCKET_PATH'!
    ports:
      - 8080:8080
    #  - 8443:8443 # Can be removed when running behind a web server or reverse proxy (like Apache, Nginx and else). See https://github.com/nextcloud/all-in-one/blob/main/reverse-proxy.md
    environment: # Is needed when using any of the options below
https://github.com/nextcloud/all-in-one#how-to-disable-collaboras-seccomp-feature
      - NEXTCLOUD_DATADIR=/smb/nxcdata # Allows to set the host directory for Nextcloud's datadir. See https://github.com/nextcloud/all-in-one#how-to-change-the-default-location-of-nextclouds-datadir
      - NEXTCLOUD_MOUNT=/mnt/ # Allows the Nextcloud container to access the chosen directory on the host. See https://github.com/nextcloud/all-in-one#how-to-allow-the-nextcloud-container-to-access-directories-on-the-host
      - NEXTCLOUD_UPLOAD_LIMIT=20G # Can be adjusted if you need more. See https://github.com/nextcloud/all-in-one#how-to-adjust-the-upload-limit-for-nextcloud
      - NEXTCLOUD_MAX_TIME=7200 # Can be adjusted if you need more. See https://github.com/nextcloud/all-in-one#how-to-adjust-the-max-execution-time-for-nextcloud
      - TALK_PORT=30678 # This allows to adjust the port that the talk container is using.
```

My haproxy.conf :
```
# Automaticaly generated, dont edit manually.
# Generated on: 2024-02-17 09:34
global
	maxconn			15000
	stats socket /tmp/haproxy.socket level admin  expose-fd listeners
	uid			80
	gid			80
	nbproc			1
	nbthread			1
	hard-stop-after		15m
	chroot				/tmp/haproxy_chroot
	daemon
	tune.ssl.default-dh-param	2048
	server-state-file /tmp/haproxy_server_state

listen HAProxyLocalStats
	bind 127.0.0.1:2200 name localstats
	mode http
	stats enable
	stats refresh 5
	stats admin if TRUE
	stats show-legends
	stats uri /haproxy/haproxy_stats.php?haproxystats=1
	timeout client 5000
	timeout connect 5000
	timeout server 5000

frontend Nextcloud-INGRES
	bind			136.243.179.76:443 name 136.243.179.76:443   ssl crt-list /var/etc/haproxy/Nextcloud-INGRES.crt_list  
	mode			http
	log			global
	option			http-keep-alive
	option			forwardfor
	acl https ssl_fc
	http-request set-header		X-Forwarded-Proto http if !https
	http-request set-header		X-Forwarded-Proto https if https
	maxconn			8000
	timeout client		30000
	acl			test-acl	var(txn.txnhost) -m sub -i nxctest.bindix
	acl			aclcrt_Nextcloud-INGRES	var(txn.txnhost) -m reg -i ^nxctest\.bindix\.de(:([0-9]){1,5})?$
	http-request set-var(txn.txnhost) hdr(host)
	use_backend nxc-test-BE_ipvANY  if  test-acl aclcrt_Nextcloud-INGRES

backend nxc-test-BE_ipvANY
	mode			http
	id			107
	log			global
	timeout connect		300000
	timeout server		300000
	retries			3
	option			httpchk OPTIONS / 
	server			NXC-test-Dienst 192.168.130.36:11000 id 101 check inter 1000
```

One of my Example Photo 2 reproduce :)

![IMG_9782](https://github.com/nextcloud/all-in-one/assets/77016734/02b3c4e0-bd3f-404a-9963-1cf83f93dbe8)
