### ISSUE TITLE
400 behind Traefik proxy

### ISSUE THREAD

**Issue by CryoByte33** [nextcloud/all-in-one#43]
When hosting this behind an existing Traefik reverse proxy with HTTPS redirect, the following error occurs when using 8080 as the load balancer port:

```
Bad Request

Your browser sent a request that this server could not understand.
Reason: You're speaking plain HTTP to an SSL-enabled server port.
Instead use the HTTPS scheme to access this URL, please.

Apache/2.4.51 (Debian) Server at 172.18.0.15 Port 8080
```

If I change the load balancer port to 8443, I get the following error:
```
Client sent an HTTP request to an HTTPS server.
```

If I change it to 80, I get an infinitely loading page.

The following is a snippet from my docker-compose.yml:
```
  # Nextcloud
  nextcloud:
    container_name: nextcloud
    image: nextcloud/all-in-one:latest
    restart: unless-stopped
    networks:
      - proxy
    environment:
      - PUID=${USER_ID}
      - PGID=${GROUP_ID}
      - TZ=${TIMEZONE}
    volumes:
      - /mnt/BigBox/docker-data/nextcloud:/mnt/docker-aio-config
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.nextcloud.entrypoints=https"
      - "traefik.http.services.nextcloud-web.loadbalancer.server.port=8080"
      # Middlewares:
      - "traefik.http.middlewares.nextcloud-redirect-tls.redirectscheme.scheme=https"
      - "traefik.http.middlewares.nextcloud-redirect-tls.redirectscheme.permanent=true"
      # HTTP:
      - "traefik.http.routers.nextcloud-web.rule=Host(`drive.example.com`)"
      - "traefik.http.routers.nextcloud-web.middlewares=nextcloud-redirect-tls"
      - "traefik.http.routers.nextcloud-web.entrypoints=http"
      # HTTPS:
      - "traefik.http.routers.nextcloud-web-secure.rule=Host(`drive.example.com`)"
      - "traefik.http.routers.nextcloud-web-secure.tls=true"
      - "traefik.http.routers.nextcloud-web-secure.entrypoints=https"
    depends_on:
      - traefik
```

I believe the issue is because all traffic is going over https between Traefik and Nextcloud, and I'm not aware of a way to turn it off without first going through the wizard. Unfortunately, I cannot get to the wizard until I'm past this issue.

If this is indeed the case, it might be useful to have an environment variable to disable HTTPS, or a combination of them to specify that you're using a reverse proxy.
