### ISSUE TITLE
App page broken

### ISSUE THREAD

**Issue by key262yek** [nextcloud/all-in-one#4301]
### Steps to reproduce
1. I don't know how to reproduce
2.
3.

### Expected behavior 
I can scroll down 'Apps' page.
I can click the enable, disable button

### Actual behavior 
Only when the cursor beside the "all apps are up-to-date" notification, I can scroll down the page.
Browser always think the cursor is on the last app in page (so I can't click other app)

remove cache, private windows, reboot the server, restart docker, fresh install all not works.

### Host OS 
Ubuntu 22.0.4

#### Nextcloud AIO version 
latest (7.13.0) Install Nextcloud 28

#### Other valuable info 
<img width="1315" alt="image" src="https://github.com/nextcloud/all-in-one/assets/28689807/9bd34f49-807d-4df6-aa04-806451f2a683">

My compose
``` yaml
nextcloud:
    image: nextcloud/all-in-one:latest
    init: true
    restart: unless-stopped
    container_name: nextcloud-aio-mastercontainer  # This line is not allowed to be changed as otherwise AIO will not work correctly
    volumes:
      - nextcloud_aio_mastercontainer:/mnt/docker-aio-config # This line is not allowed to be changed as otherwise the built-in backup solution will not work
      - /var/run/user/1000/docker.sock:/var/run/docker.sock:ro # May be changed on macOS, Windows or docker rootless. See the applicable documentation. If adjusting, don't forget to also set 'WATCHTOWER_DOCKER_SOCKET_PATH'!
    ports:
      - 8080:8080
    environment: # Is needed when using any of the options below
      - APACHE_PORT=16678 # Is needed when running behind a web server or reverse proxy (like Apache, Nginx, Cloudflare Tunnel and else). See https://github.com/nextcloud/all-in-one/blob/main/reverse-proxy.md
      - APACHE_IP_BINDING=127.0.0.1 # Should be set when running behind a web server or reverse proxy (like Apache, Nginx, Cloudflare Tunnel and else) that is running on the same host. See https://github.com/nextcloud/all-in-one/blob/main/reverse-proxy.md
      - NEXTCLOUD_DATADIR=/home/teahaven/docker/nextcloud/data # Allows to set the host directory for Nextcloud's datadir. ⚠️⚠️⚠️ Warning: do not set or adjust this value after the initial Nextcloud installation is done! See https://github.com/nextcloud/all-in-one#how-to-change-the-default-location-of-nextclouds-datadir
      - NEXTCLOUD_UPLOAD_LIMIT=40G # Can be adjusted if you need more. See https://github.com/nextcloud/all-in-one#how-to-adjust-the-upload-limit-for-nextcloud
      - NEXTCLOUD_STARTUP_APPS= deck calendar notes twofactor_totp # Allows to modify the Nextcloud apps that are installed on starting AIO the first time. See https://github.com/nextcloud/all-in-one#how-to-change-the-nextcloud-apps-that-are-installed-on-the-first-startup
      - NEXTCLOUD_ADDITIONAL_PHP_EXTENSIONS=imagick # This allows to add additional php extensions to the Nextcloud container permanently. Default is imagick but can be overwritten by modifying this value. See https://github.com/nextcloud/all-in-one#how-to-add-php-extensions-permanently-to-the-nextcloud-container
      - WATCHTOWER_DOCKER_SOCKET_PATH=/var/run/user/1000/docker.sock # Needs to be specified if the docker socket on the host is not located in the default '/var/run/docker.sock'. Otherwise mastercontainer updates will fail. For macos it needs to be '/var/run/docker.sock'
    networks: # Is needed when you want to create the nextcloud-aio network with ipv6-support using this file, see the network config at the bottom of the file
      - nextcloud-net # Is needed when you want to create the nextcloud-aio network with ipv6-support using this file, see the network config at the bottom of the file
```
