### ISSUE TITLE
LocalAI integegration does not work as expected.

### ISSUE THREAD

**Issue by DenuxPlays** [nextcloud/all-in-one#4354]
### Steps to reproduce
1. enable loca-ai community container
2. update your models.yml to this:
```yml
# Stable Diffusion in NCNN with c++, supported txt2img and img2img 
- url: github:go-skynet/model-gallery/stablediffusion.yaml

# Port of OpenAI's Whisper model in C/C++ 
- url: github:go-skynet/model-gallery/whisper-base.yaml
  name: whisper-1

# A commercially licensable model based on GPT-J and trained by Nomic AI on the v0 GPT4All dataset.
- url: github:go-skynet/model-gallery/gpt4all-j.yaml
  name: gpt4all-j
 ```
3. ask you nextcloud assistant to generate an image

### Expected behavior 

See a the generated photo

### Actual behavior 

Generation failed

### Host OS 

Fedora 39 Server

#### Nextcloud AIO version 

v8.0.0

#### Current channel 

Beta

#### Other valuable info 

Local-AI container:
![image](https://github.com/nextcloud/all-in-one/assets/83671398/f9fd91b2-0eea-4672-86ff-2f140b65857c)

Nextcloud logs:
![image](https://github.com/nextcloud/all-in-one/assets/83671398/584e655d-c43d-441c-b304-d80cc67b18ce)
