### ISSUE TITLE
Unable to log into Nextcloud even after full re-install

### ISSUE THREAD

**Issue by jnstockley** [nextcloud/all-in-one#4535]
### Steps to reproduce
1. Setup traefik proxy using docker
2. Install nextcloud-aio with rootless docker
3. Setup nextlcloud-aio and try to login with default credentials

### Expected behavior 
Be brought to the homepage for the default user

### Actual behavior 
Error message saying `ERR_CONNECTION_CLOSED`

### Host OS 
Debian 12.5

#### Nextcloud AIO version 
8.1.0

#### Current channel 
Latest
#### Other valuable info 
docker compose file
```services:
  nextcloud:
    image: "nextcloud/all-in-one:latest"
    restart: "unless-stopped"
    container_name: "nextcloud-aio-mastercontainer"
    volumes:
      - "nextcloud_aio_mastercontainer:/mnt/docker-aio-config"
      - "$XDG_RUNTIME_DIR/docker.sock:/var/run/docker.sock:ro"
    ports:
      - "8080:8080"
    networks:
      - nextcloud-aio
    environment:
      - APACHE_PORT=11000
      - APACHE_IP_BINDING=127.0.0.1
      - WATCHTOWER_DOCKER_SOCKET_PATH=$XDG_RUNTIME_DIR/docker.sock

volumes:
  nextcloud_aio_mastercontainer:
    name: "nextcloud_aio_mastercontainer"

networks:
  nextcloud-aio:
    external: true
    name: "nextcloud-aio"
```
traefik docker compose file
```
services:
  traefik:
    image: traefik:v2.11.1
    container_name: traefik
    ports:
      - 80:80
      - 443:443
    environment:
      - TZ=America/Chicago
    volumes:
      - $XDG_RUNTIME_DIR/docker.sock:/var/run/docker.sock:ro
      - ./config/traefik.yaml:/etc/traefik/traefik.yaml:ro
      - ./config/conf/:/etc/traefik/conf/
      - ./config/certs/:/etc/traefik/certs/
      - ./logs/:/var/log/traefik/
    networks:
      - nextcloud-aio
    restart: unless-stopped

networks:
  nextcloud-aio:
    external: true
    name: "nextcloud-aio"
```
nextcloud traefik config file
```
http:
  routers:
    nextcloud:
      rule: "Host(`nextcloud.jstockley.com`)"
      entrypoints:
        - "websecure"
      service: nextcloud
      middlewares:
        - nextcloud-chain
      tls:
        certresolver: "production"

  services:
    nextcloud:
      loadBalancer:
        servers:
          - url: "http://nextcloud-aio-apache:11000" # Use the host's IP address if Traefik runs outside the host network

  middlewares:
    nextcloud-secure-headers:
      headers:
        hostsProxyHeaders:
          - "X-Forwarded-Host"
        referrerPolicy: "same-origin"

    https-redirect:
      redirectscheme:
        scheme: https

    nextcloud-chain:
      chain:
        middlewares:
          # - ... (e.g. rate limiting middleware)
          - https-redirect
          - nextcloud-secure-headers
```

I checked the logs for traefik, nextcloud-aio-apche container, and nextcloud-aio-nextcloud container and there were no error messages.
