### ISSUE TITLE
Infinite loading with iOS Nextcloud App

### ISSUE THREAD

**Issue by RoSky7791** [nextcloud/all-in-one#4601]
### Steps to reproduce
1. I deployed Nextcloud AIO with the following docker-compose :

```
version: '2'

volumes:
  nextcloud:
  db:
  certificates:

services:
  db:
    image: mariadb:10.6
    restart: always
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=xx
      - MYSQL_PASSWORD=xx
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud

  app:
    image: nextcloud
    restart: always
    ports:
      - 8080:80
    links:
      - db
    volumes:
      - nextcloud:/var/www/html
      - certificates:/home/user/certificates
    environment:
      - MYSQL_PASSWORD=xx
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=db
      - NEXTCLOUD_TRUSTED_DOMAINS=nextcloud.home.local
      - NEXTCLOUD_OVERWRITEHOST=nextcloud.home.local
      - NEXTCLOUD_OVERWRITEPROTOCOL=https
      - NEXTCLOUD_OVERWRITECLI=--insecure
```

2. I have a DHCP & DNS server using pi-hole, and I added my nextcloud.home.local domain on my dns local server.

3. I also have a reverse proxy Nginx server, with this configuration :

```
server {
    listen 80;
    server_name nextcloud.wilmot.local;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name nextcloud.home.local;

    ssl_certificate /certificates/nextcloud.home.local.crt;
    ssl_certificate_key /certificates/nextcloud.home.local.key;

    location / {
        proxy_pass http://localhost:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
```

### Expected behavior 

When I want to user Nextcloud iOS app on a iPhone 12, i type my https://nextcloud.home.local dans I'm redirected to the logging page. I should be able to loggin.

### Actual behavior 

But, after typing my credentials, I have an infinite loading and I can't login. However, it's working on the web app (I'm using admin account for both)

### Host OS 
My nextcloud is running on Docker version 25.0.5, build 5dc9bcc, hosting in a Linux raspberrypi 6.6.20+rpt-rpi-v8 #1 SMP PREEMPT Debian 1:6.6.20-1+rpt1 (2024-03-07) aarch64 GNU/Linux

#### Nextcloud AIO version 
Nextcloud Hub 9 (29.0.0)

#### Current channel 
?

#### Other valuable info 

No

Thanks for the help !
