### ISSUE TITLE
AIO unable to start containers "Apache", "Nextcloud" & "Notify Push"

### ISSUE THREAD

**Issue by Wraaath** [nextcloud/all-in-one#4612]
### Steps to reproduce
1. Create a docker-compose.yml:
```
services:
  nextcloud-aio-mastercontainer:
    image: nextcloud/all-in-one:latest
    init: true
    restart: always
    container_name: nextcloud-aio-mastercontainer # This line is not allowed to be changed as otherwise AIO will not work correctly
    volumes:
      - nextcloud_aio_mastercontainer:/mnt/docker-aio-config # This line is not allowed to be changed as otherwise the built-in backup solution will not work
      - /var/run/docker.sock:/var/run/docker.sock:ro # May be changed on macOS, Windows or docker rootless. See the applicable documentation. If adjusting, don't forget to also set 'WATCHTOWER_DOCKER_SOCKET_PATH'!
    ports:
      #- 880:880 # Can be removed when running behind a web server or reverse proxy (like Apache, Nginx, Cloudflare Tunnel and else). See https://github.com/nextcloud/all-in-one/blob/main/reverse-proxy.md
      - 8080:8080
      #- 8443:8443 # Can be removed when running behind a web server or reverse proxy (like Apache, Nginx, Cloudflare Tunnel and else). See https://github.com/nextcloud/all-in-one/blob/main/reverse-proxy.md
    environment: # Is needed when using any of the options below
      - APACHE_PORT=11000 # Is needed when running behind a web server or reverse proxy (like Apache, Nginx, Cloudflare Tunnel and else). See https://github.com/nextcloud/all-in-one/blob/main/reverse-proxy.md
      - APACHE_IP_BINDING=0.0.0.0 # Should be set when running behind a web server or reverse proxy (like Apache, Nginx, Cloudflare Tunnel and else) that is running on the same host. See https://github.com/nextcloud/all-in-one/blob/main/reverse-proxy.md
      # - BORG_RETENTION_POLICY=--keep-within=7d --keep-weekly=4 --keep-monthly=6 # Allows to adjust borgs retention policy. See https://github.com/nextcloud/all-in-one#how-to-adjust-borgs-retention-policy
      - NEXTCLOUD_MOUNT=/mnt/truenas # Allows the Nextcloud container to access the chosen directory on the host. See https://github.com/nextcloud/all-in-one#how-to-allow-the-nextcloud-container-to-access-directories-on-the-host
      # - NEXTCLOUD_UPLOAD_LIMIT=10G # Can be adjusted if you need more. See https://github.com/nextcloud/all-in-one#how-to-adjust-the-upload-limit-for-nextcloud
      # - NEXTCLOUD_MAX_TIME=3600 # Can be adjusted if you need more. See https://github.com/nextcloud/all-in-one#how-to-adjust-the-max-execution-time-for-nextcloud
      # - NEXTCLOUD_STARTUP_APPS=deck twofactor_totp tasks calendar contacts notes # Allows to modify the Nextcloud apps that are installed on starting AIO the first time. See https://github.com/nextcloud/all-in-one#how-to-change-the-nextcloud-apps-that-are-installed-on-the-first-startup

volumes:
  nextcloud_aio_mastercontainer:
    name: nextcloud_aio_mastercontainer # This line is not allowed to be changed as otherwise the built-in backup solution will not work
```
2. Run `docker compose up -d`
3. Enter `https://192.168.0.201:8080/setup` and `https://192.168.0.201:8080/containers` afterwards

NOTE: 
Did try to switch Docker storage driver [like this](https://webdock.io/en/docs/how-guides/docker-guides/how-change-the-docker-storage-driver)
Did also reset the container-stack according to [your docs](https://github.com/nextcloud/all-in-one#how-to-properly-reset-the-instance)

### Expected behavior 
Containers "Apache", "Nextcloud" & "Notify Push" should be `Running` like the rest

### Actual behavior 
The containers are stuck on `Stopped`, even after stopping and starting containers.

### Host OS 
Ubuntu Privileged-LXC on Proxmox

#### Nextcloud AIO version 
v8.2.1
(also did select Nextcloud 29)
#### Current channel 
latest
#### Other valuable info 
My nextcloud-aio docker logs:
```
nextcloud-aio-mastercontainer  | Trying to fix docker.sock permissions internally...
nextcloud-aio-mastercontainer  | Creating docker group internally with id 118
nextcloud-aio-mastercontainer  |  Storage Driver: fuse-overlayfs
nextcloud-aio-mastercontainer  | Warning: It seems like the storage driver fuse-overlayfs is used. Please check if you can switch to overlay2 instead.
nextcloud-aio-mastercontainer  | .+...+++++++++++++++++++++++++++++++++++++++++++++*..+......+..+.......+......+.....+......+.+..+......+....+...........+.....................+.+.....+....+........+.+++++++++++++++++++++++++++++++++++++++++++++*...+.....+.......+.........+...............+..+.......+............+...+........+.........+...+.......+...+........+...............+.......+...+........+.........+......+....+..+...+...+....+..............+.........+.+......+.........+............+...+.....+......+++++
nextcloud-aio-mastercontainer  | .+........+...+.............+++++++++++++++++++++++++++++++++++++++++++++*...+......+..+.......+........+......+.......+..+...+.......+...+.....+...+++++++++++++++++++++++++++++++++++++++++++++*.+..+...+.......+.....................+..+.......+.....+.......+......+.........+...+..............................+..................+...............+...+..............+...+...+.......+...+.....+.+...............+......+..+......+.......+.....+..........+.................+.....................+.+...+.....+......+................+...............+...............+.....+.........+....+.......................+...+............+....+..............+.........+......+....+...............+......+..+...+......+.+...+..+.........+....+..+.......+........+.......+...+...............+...............+.....+..........+.....+.........+.+.........+.........+.....................+...+..+....+...........+.+.........+.....+...+...+.............+..+...+..........+.................+....+...+...+........+.+........+.............+.....+....+........+............+....+.............................+.......+...............+..............+.........+..........+........+...+.+......+..............+.+..+...+.......+......+.....+............+...+......+....+...............+......+...........+....+...+...+...+..+.......+............+...+.....+..................+...+.........+.+.....+.+......+.....+.......+...........+.......+..................+.................+...+.........+...+.......+......+.....+......+.........+......+.+..+..........+..................+.........+...+..+..........+.........+......+.....+.+...+..............+.+.....+......+................+............+...+............+..+....+.....+......................+.........+...............+.....+.+.....+.......+...+....................+.......+............+++++
nextcloud-aio-mastercontainer  | -----
nextcloud-aio-mastercontainer  | Initial startup of Nextcloud All-in-One complete!
nextcloud-aio-mastercontainer  | You should be able to open the Nextcloud AIO Interface now on port 8080 of this server!
nextcloud-aio-mastercontainer  | E.g. https://internal.ip.of.this.server:8080
nextcloud-aio-mastercontainer  | ⚠️ Important: do always use an ip-address if you access this port and not a domain as HSTS might block access to it later!
nextcloud-aio-mastercontainer  | 
nextcloud-aio-mastercontainer  | If your server has port 80 and 8443 open and you point a domain to your server, you can get a valid certificate automatically by opening the Nextcloud AIO Interface via:
nextcloud-aio-mastercontainer  | https://your-domain-that-points-to-this-server.tld:8443
nextcloud-aio-mastercontainer  | {"level":"info","ts":1714647193.0668151,"msg":"using provided configuration","config_file":"/Caddyfile","config_adapter":""}
nextcloud-aio-mastercontainer  | [02-May-2024 10:53:13] NOTICE: fpm is running, pid 156
nextcloud-aio-mastercontainer  | [02-May-2024 10:53:13] NOTICE: ready to handle connections
nextcloud-aio-mastercontainer  | [Thu May 02 10:53:13.105806 2024] [mpm_event:notice] [pid 146:tid 140119120472840] AH00489: Apache/2.4.59 (Unix) OpenSSL/3.1.4 configured -- resuming normal operations
nextcloud-aio-mastercontainer  | [Thu May 02 10:53:13.105851 2024] [core:notice] [pid 146:tid 140119120472840] AH00094: Command line: 'httpd -D FOREGROUND'
nextcloud-aio-mastercontainer  | NOTICE: PHP message: Slim Application Error
nextcloud-aio-mastercontainer  | Type: Exception
nextcloud-aio-mastercontainer  | Code: 0
nextcloud-aio-mastercontainer  | Message: Could not create container nextcloud-aio-nextcloud: Client error: `POST http://localhost/v1.41/containers/create?name=nextcloud-aio-nextcloud` resulted in a `400 Bad Request` response:
nextcloud-aio-mastercontainer  | {&quot;message&quot;:&quot;invalid mount config for type \&quot;bind\&quot;: bind source path does not exist: /mnt/truenas&quot;}
nextcloud-aio-mastercontainer  | File: /var/www/docker-aio/php/src/Docker/DockerActionManager.php
nextcloud-aio-mastercontainer  | Line: 590
nextcloud-aio-mastercontainer  | Trace: #0 /var/www/docker-aio/php/src/Controller/DockerController.php(65): AIO\Docker\DockerActionManager->CreateContainer(Object(AIO\Container\Container))
nextcloud-aio-mastercontainer  | #1 /var/www/docker-aio/php/src/Controller/DockerController.php(33): AIO\Controller\DockerController->PerformRecursiveContainerStart('nextcloud-aio-n...', true)
nextcloud-aio-mastercontainer  | #2 /var/www/docker-aio/php/src/Controller/DockerController.php(211): AIO\Controller\DockerController->PerformRecursiveContainerStart('nextcloud-aio-a...', true)
nextcloud-aio-mastercontainer  | #3 /var/www/docker-aio/php/src/Controller/DockerController.php(191): AIO\Controller\DockerController->startTopContainer(true)
nextcloud-aio-mastercontainer  | #4 /var/www/docker-aio/php/vendor/slim/slim/Slim/Handlers/Strategies/RequestResponse.php(38): AIO\Controller\DockerController->StartContainer(Object(GuzzleHttp\Psr7\ServerRequest), Object(GuzzleHttp\Psr7\Response), Array)
nextcloud-aio-mastercontainer  | #5 /var/www/docker-aio/php/vendor/slim/slim/Slim/Routing/Route.php(358): Slim\Handlers\Strategies\RequestResponse->__invoke(Array, Object(GuzzleHttp\Psr7\ServerRequest), Object(GuzzleHttp\Psr7\Response), Array)
nextcloud-aio-mastercontainer  | #6 /var/www/docker-aio/php/vendor/slim/slim/Slim/MiddlewareDispatcher.php(65): Slim\Routing\Route->handle(Object(GuzzleHttp\Psr7\ServerRequest))
nextcloud-aio-mastercontainer  | #7 /var/www/docker-aio/php/vendor/slim/slim/Slim/MiddlewareDispatcher.php(65): Slim\MiddlewareDispatcher->handle(Object(GuzzleHttp\Psr7\ServerRequest))
nextcloud-aio-mastercontainer  | #8 /var/www/docker-aio/php/vendor/slim/slim/Slim/Routing/Route.php(315): Slim\MiddlewareDispatcher->handle(Object(GuzzleHttp\Psr7\ServerRequest))
nextcloud-aio-mastercontainer  | #9 /var/www/docker-aio/php/vendor/slim/slim/Slim/Routing/RouteRunner.php(68): Slim\Routing\Route->run(Object(GuzzleHttp\Psr7\ServerRequest))
nextcloud-aio-mastercontainer  | #10 /var/www/docker-aio/php/vendor/slim/csrf/src/Guard.php(482): Slim\Routing\RouteRunner->handle(Object(GuzzleHttp\Psr7\ServerRequest))
nextcloud-aio-mastercontainer  | #11 /var/www/docker-aio/php/vendor/slim/slim/Slim/MiddlewareDispatcher.php(168): Slim\Csrf\Guard->process(Object(GuzzleHttp\Psr7\ServerRequest), Object(Slim\Routing\RouteRunner))
nextcloud-aio-mastercontainer  | #12 /var/www/docker-aio/php/vendor/slim/twig-view/src/TwigMiddleware.php(115): Psr\Http\Server\RequestHandlerInterface@anonymous->handle(Object(GuzzleHttp\Psr7\ServerRequest))
nextcloud-aio-mastercontainer  | #13 /var/www/docker-aio/php/vendor/slim/slim/Slim/MiddlewareDispatcher.php(121): Slim\Views\TwigMiddleware->process(Object(GuzzleHttp\Psr7\ServerRequest), Object(Psr\Http\Server\RequestHandlerInterface@anonymous))
nextcloud-aio-mastercontainer  | #14 /var/www/docker-aio/php/src/Middleware/AuthMiddleware.php(38): Psr\Http\Server\RequestHandlerInterface@anonymous->handle(Object(GuzzleHttp\Psr7\ServerRequest))
nextcloud-aio-mastercontainer  | #15 /var/www/docker-aio/php/vendor/slim/slim/Slim/MiddlewareDispatcher.php(269): AIO\Middleware\AuthMiddleware->__invoke(Object(GuzzleHttp\Psr7\ServerRequest), Object(Psr\Http\Server\RequestHandlerInterface@anonymous))
nextcloud-aio-mastercontainer  | #16 /var/www/docker-aio/php/vendor/slim/slim/Slim/Middleware/ErrorMiddleware.php(76): Psr\Http\Server\RequestHandlerInterface@anonymous->handle(Object(GuzzleHttp\Psr7\ServerRequest))
nextcloud-aio-mastercontainer  | #17 /var/www/docker-aio/php/vendor/slim/slim/Slim/MiddlewareDispatcher.php(121): Slim\Middleware\ErrorMiddleware->process(Object(GuzzleHttp\Psr7\ServerRequest), Object(Psr\Http\Server\RequestHandlerInterface@anonymous))
nextcloud-aio-mastercontainer  | #18 /var/www/docker-aio/php/vendor/slim/slim/Slim/MiddlewareDispatcher.php(65): Psr\Http\Server\RequestHandlerInterface@anonymous->handle(Object(GuzzleHttp\Psr7\ServerRequest))
nextcloud-aio-mastercontainer  | #19 /var/www/docker-aio/php/vendor/slim/slim/Slim/App.php(199): Slim\MiddlewareDispatcher->handle(Object(GuzzleHttp\Psr7\ServerRequest))
nextcloud-aio-mastercontainer  | #20 /var/www/docker-aio/php/vendor/slim/slim/Slim/App.php(183): Slim\App->handle(Object(GuzzleHttp\Psr7\ServerRequest))
nextcloud-aio-mastercontainer  | #21 /var/www/docker-aio/php/public/index.php(185): Slim\App->run()
nextcloud-aio-mastercontainer  | #22 {main}
nextcloud-aio-mastercontainer  | Tips: To display error details in HTTP response set "displayErrorDetails" to true in the ErrorHandler constructor.
nextcloud-aio-mastercontainer  | NOTICE: PHP message: Slim Application Error
nextcloud-aio-mastercontainer  | Type: Exception
nextcloud-aio-mastercontainer  | Code: 0
nextcloud-aio-mastercontainer  | Message: Could not create container nextcloud-aio-nextcloud: Client error: `POST http://localhost/v1.41/containers/create?name=nextcloud-aio-nextcloud` resulted in a `400 Bad Request` response:
nextcloud-aio-mastercontainer  | {&quot;message&quot;:&quot;invalid mount config for type \&quot;bind\&quot;: bind source path does not exist: /mnt/truenas&quot;}
nextcloud-aio-mastercontainer  | File: /var/www/docker-aio/php/src/Docker/DockerActionManager.php
nextcloud-aio-mastercontainer  | Line: 590
nextcloud-aio-mastercontainer  | Trace: #0 /var/www/docker-aio/php/src/Controller/DockerController.php(65): AIO\Docker\DockerActionManager->CreateContainer(Object(AIO\Container\Container))
nextcloud-aio-mastercontainer  | #1 /var/www/docker-aio/php/src/Controller/DockerController.php(33): AIO\Controller\DockerController->PerformRecursiveContainerStart('nextcloud-aio-n...', true)
nextcloud-aio-mastercontainer  | #2 /var/www/docker-aio/php/src/Controller/DockerController.php(211): AIO\Controller\DockerController->PerformRecursiveContainerStart('nextcloud-aio-a...', true)
nextcloud-aio-mastercontainer  | #3 /var/www/docker-aio/php/src/Controller/DockerController.php(191): AIO\Controller\DockerController->startTopContainer(true)
nextcloud-aio-mastercontainer  | #4 /var/www/docker-aio/php/vendor/slim/slim/Slim/Handlers/Strategies/RequestResponse.php(38): AIO\Controller\DockerController->StartContainer(Object(GuzzleHttp\Psr7\ServerRequest), Object(GuzzleHttp\Psr7\Response), Array)
nextcloud-aio-mastercontainer  | #5 /var/www/docker-aio/php/vendor/slim/slim/Slim/Routing/Route.php(358): Slim\Handlers\Strategies\RequestResponse->__invoke(Array, Object(GuzzleHttp\Psr7\ServerRequest), Object(GuzzleHttp\Psr7\Response), Array)
nextcloud-aio-mastercontainer  | #6 /var/www/docker-aio/php/vendor/slim/slim/Slim/MiddlewareDispatcher.php(65): Slim\Routing\Route->handle(Object(GuzzleHttp\Psr7\ServerRequest))
nextcloud-aio-mastercontainer  | #7 /var/www/docker-aio/php/vendor/slim/slim/Slim/MiddlewareDispatcher.php(65): Slim\MiddlewareDispatcher->handle(Object(GuzzleHttp\Psr7\ServerRequest))
nextcloud-aio-mastercontainer  | #8 /var/www/docker-aio/php/vendor/slim/slim/Slim/Routing/Route.php(315): Slim\MiddlewareDispatcher->handle(Object(GuzzleHttp\Psr7\ServerRequest))
nextcloud-aio-mastercontainer  | #9 /var/www/docker-aio/php/vendor/slim/slim/Slim/Routing/RouteRunner.php(68): Slim\Routing\Route->run(Object(GuzzleHttp\Psr7\ServerRequest))
nextcloud-aio-mastercontainer  | #10 /var/www/docker-aio/php/vendor/slim/csrf/src/Guard.php(482): Slim\Routing\RouteRunner->handle(Object(GuzzleHttp\Psr7\ServerRequest))
nextcloud-aio-mastercontainer  | #11 /var/www/docker-aio/php/vendor/slim/slim/Slim/MiddlewareDispatcher.php(168): Slim\Csrf\Guard->process(Object(GuzzleHttp\Psr7\ServerRequest), Object(Slim\Routing\RouteRunner))
nextcloud-aio-mastercontainer  | #12 /var/www/docker-aio/php/vendor/slim/twig-view/src/TwigMiddleware.php(115): Psr\Http\Server\RequestHandlerInterface@anonymous->handle(Object(GuzzleHttp\Psr7\ServerRequest))
nextcloud-aio-mastercontainer  | #13 /var/www/docker-aio/php/vendor/slim/slim/Slim/MiddlewareDispatcher.php(121): Slim\Views\TwigMiddleware->process(Object(GuzzleHttp\Psr7\ServerRequest), Object(Psr\Http\Server\RequestHandlerInterface@anonymous))
nextcloud-aio-mastercontainer  | #14 /var/www/docker-aio/php/src/Middleware/AuthMiddleware.php(38): Psr\Http\Server\RequestHandlerInterface@anonymous->handle(Object(GuzzleHttp\Psr7\ServerRequest))
nextcloud-aio-mastercontainer  | #15 /var/www/docker-aio/php/vendor/slim/slim/Slim/MiddlewareDispatcher.php(269): AIO\Middleware\AuthMiddleware->__invoke(Object(GuzzleHttp\Psr7\ServerRequest), Object(Psr\Http\Server\RequestHandlerInterface@anonymous))
nextcloud-aio-mastercontainer  | #16 /var/www/docker-aio/php/vendor/slim/slim/Slim/Middleware/ErrorMiddleware.php(76): Psr\Http\Server\RequestHandlerInterface@anonymous->handle(Object(GuzzleHttp\Psr7\ServerRequest))
nextcloud-aio-mastercontainer  | #17 /var/www/docker-aio/php/vendor/slim/slim/Slim/MiddlewareDispatcher.php(121): Slim\Middleware\ErrorMiddleware->process(Object(GuzzleHttp\Psr7\ServerRequest), Object(Psr\Http\Server\RequestHandlerInterface@anonymous))
nextcloud-aio-mastercontainer  | #18 /var/www/docker-aio/php/vendor/slim/slim/Slim/MiddlewareDispatcher.php(65): Psr\Http\Server\RequestHandlerInterface@anonymous->handle(Object(GuzzleHttp\Psr7\ServerRequest))
nextcloud-aio-mastercontainer  | #19 /var/www/docker-aio/php/vendor/slim/slim/Slim/App.php(199): Slim\MiddlewareDispatcher->handle(Object(GuzzleHttp\Psr7\ServerRequest))
nextcloud-aio-mastercontainer  | #20 /var/www/docker-aio/php/vendor/slim/slim/Slim/App.php(183): Slim\App->handle(Object(GuzzleHttp\Psr7\ServerRequest))
nextcloud-aio-mastercontainer  | #21 /var/www/docker-aio/php/public/index.php(185): Slim\App->run()
nextcloud-aio-mastercontainer  | #22 {main}
nextcloud-aio-mastercontainer  | Tips: To display error details in HTTP response set "displayErrorDetails" to true in the ErrorHandler constructor.
```
