### ISSUE TITLE
Redis Background Saving Error - Permission Denied

### ISSUE THREAD

**Issue by norimicry** [nextcloud/all-in-one#4791]
### Steps to reproduce
1. Install and setup AIO
2. Wait a couple minutes
3. Observe lockup and see permission errors in Redis container logs.

### Expected behavior 
Upon installation of a fresh AIO, all should work.

### Actual behavior 
Prior to any configuration of _anything_, installation locks up and throws permission errors in redis logs. Web page becomes unresponsive and CPU load gradually increases. The only observable errors are in the Redis container which are the attached background saving errors. The webpage times out and the CPU load begins to increase gradually. The only fix is restarting all containers.

```
76:C 07 Jun 2024 10:32:58.028 # Failed opening the temp RDB file temp-76.rdb (in server root dir /data) for saving: Permission denied

7:M 07 Jun 2024 10:32:58.128 # Background saving error

84:C 07 Jun 2024 10:33:04.041 # Failed opening the temp RDB file temp-84.rdb (in server root dir /data) for saving: Permission denied

7:M 07 Jun 2024 10:33:04.141 # Background saving error

85:C 07 Jun 2024 10:33:10.053 # Failed opening the temp RDB file temp-85.rdb (in server root dir /data) for saving: Permission denied

7:M 07 Jun 2024 10:33:10.153 # Background saving error

86:C 07 Jun 2024 10:33:16.065 # Failed opening the temp RDB file temp-86.rdb (in server root dir /data) for saving: Permission denied
```

### Host OS 
TrueNAS SCALE Debian Jail

#### Nextcloud AIO version 
V8.3.0

#### Current channel 
latest

#### Other valuable info 
```
networks:
  proxy:
    external: true
services:
  nextcloud-aio-mastercontainer:
    image: nextcloud/all-in-one:latest
    init: true
    restart: always
    networks:
      - proxy # To talk to Traefik container
    container_name: nextcloud-aio-mastercontainer
    volumes:
      - nextcloud_aio_mastercontainer:/mnt/docker-aio-config
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 8080:8080
    environment:
     APACHE_PORT: 11000
     APACHE_IP_BINDING: 0.0.0.0
     NEXTCLOUD_MOUNT: /nextcloud/backup # Bind on host with 770 www-data:www-data permissions 
     NEXTCLOUD_MEMORY_LIMIT: 1024M


volumes:
  nextcloud_aio_mastercontainer:
    name: nextcloud_aio_mastercontainer
```
