### ISSUE TITLE
Daily borg backup breaks the interaction of external disks

### ISSUE THREAD

**Issue by webstudiobond** [nextcloud/all-in-one#5198]
### Steps to reproduce
1. Mount an external disk in the system (owner www-data or other user, group www-data, folder permissions: 750, file permissions:640).
2. Connect the external disk in nextcloud and make sure everything is working (if the owner is www-data, with write, if different - read)
3. Stop the containers, then start the containers from the AIO interface and make sure everything works
4. Configure daily backup, set the nearest time. Check external disks in nextcloud interface
### Expected behavior 
The disks should display and work normally in nextcloud
### Actual behavior 
Disk connection error in nextcloud

### Other information
If you stop all containers and start them from the AIO interface, the disks show up normally again and everything works in nextcloud.
If you manually stop the nextcloud-aio-nextcloud container, everything starts working correctly too.
If you manually start backup creation from the AIO interface, everything works fine. The problem is only with scheduled backup.

**Comment by szaimen** [comment]
Hi, I fear I cannot reproduce the issue. So I need more information like logs, reproduction steps, etc.

**Comment by szaimen** [comment]
Also, please fill out the whole bug report template: https://raw.githubusercontent.com/nextcloud/all-in-one/main/.github/ISSUE_TEMPLATE/Bug_report.md

**Comment by webstudiobond** [comment]
### Other information
#### Host OS 
Ubuntu 22.04.4 LTS
#### Output of `sudo docker info`
```
Client: Docker Engine - Community
 Version:    27.2.0
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.16.2
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.29.2
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 61
  Running: 58
  Paused: 0
  Stopped: 3
 Images: 55
 Server Version: 27.2.0
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: runc io.containerd.runc.v2
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 472731909fa34bd7bc9c087e4c27943f9835f111
 runc version: v1.1.13-0-g58aa920
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 5.15.0-119-generic
 Operating System: Ubuntu 22.04.4 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 15.61GiB
 Name: redacted
 ID: redacted
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```
#### Docker run command or docker-compose file that you used
```
services:
  nextcloud-aio-mastercontainer:
    image: nextcloud/all-in-one:latest
    init: true
    restart: always
    # This line is not allowed to be changed as otherwise AIO will not work correctly
    container_name: nextcloud-aio-mastercontainer
    volumes:
      # This line is not allowed to be changed as otherwise the built-in backup solution will not work
      - nextcloud_aio_mastercontainer:/mnt/docker-aio-config
      - /var/run/docker.sock:/var/run/docker.sock:ro # May be changed on macOS, Windows or docker rootless. See the applicable documentation. If adjusting, don't forget to also set 'WATCHTOWER_DOCKER_SOCKET_PATH'!
    network_mode: bridge
    ports:
      - 127.0.0.1:14080:8080
    environment:
      # Setting this to true allows to hide the backup section in the AIO interface. See https://github.com/nextcloud/all-in-one#how-to-disable-the-backup-section
      AIO_DISABLE_BACKUP_SECTION: false
      # Is needed when running behind a web server or reverse proxy (like Apache, Nginx, Caddy, Cloudflare Tunnel and else). See https://github.com/nextcloud/all-in-one/blob/main/reverse-proxy.md
      APACHE_PORT: 11000
      # Should be set when running behind a web server or reverse proxy (like Apache, Nginx, Caddy, Cloudflare Tunnel and else) that is running on the same host. See https://github.com/nextcloud/all-in-one/blob/main/reverse-proxy.md
      APACHE_IP_BINDING: 127.0.0.1
      # Allows to adjust borgs retention policy. See https://github.com/nextcloud/all-in-one#how-to-adjust-borgs-retention-policy
      BORG_RETENTION_POLICY: --keep-within=7d --keep-weekly=4 --keep-monthly=6
      # Setting this to true allows to disable Collabora's Seccomp feature. See https://github.com/nextcloud/all-in-one#how-to-disable-collaboras-seccomp-feature
      COLLABORA_SECCOMP_DISABLED: false
      # Allows to set the host directory for Nextcloud's datadir. ⚠️⚠️⚠️ Warning: do not set or adjust this value after the initial Nextcloud installation is done! See https://github.com/nextcloud/all-in-one#how-to-change-the-default-location-of-nextclouds-datadir
      # NEXTCLOUD_DATADIR: /mnt/ncdata
      NEXTCLOUD_DATADIR: /mnt/ncdata
      # Allows the Nextcloud container to access the chosen directory on the host. See https://github.com/nextcloud/all-in-one#how-to-allow-the-nextcloud-container-to-access-directories-on-the-host
      NEXTCLOUD_MOUNT: /mnt
      # Can be adjusted if you need more. See https://github.com/nextcloud/all-in-one#how-to-adjust-the-upload-limit-for-nextcloud
      NEXTCLOUD_UPLOAD_LIMIT: 10G
      # Can be adjusted if you need more. See https://github.com/nextcloud/all-in-one#how-to-adjust-the-max-execution-time-for-nextcloud
      NEXTCLOUD_MAX_TIME: 3600
      # Can be adjusted if you need more. See https://github.com/nextcloud/all-in-one#how-to-adjust-the-php-memory-limit-for-nextcloud
      NEXTCLOUD_MEMORY_LIMIT: 512M
      # CA certificates in this directory will be trusted by the OS of the nexcloud container (Useful e.g. for LDAPS) See See https://github.com/nextcloud/all-in-one#how-to-trust-user-defined-certification-authorities-ca
      # NEXTCLOUD_TRUSTED_CACERTS_DIR: /path/to/my/cacerts
      # Allows to modify the Nextcloud apps that are installed on starting AIO the first time. See https://github.com/nextcloud/all-in-one#how-to-change-the-nextcloud-apps-that-are-installed-on-the-first-startup
      NEXTCLOUD_STARTUP_APPS: -deck twofactor_totp -tasks -calendar -contacts -notes 
      # This allows to add additional packages to the Nextcloud container permanently. Default is imagemagick but can be overwritten by modifying this value. See https://github.com/nextcloud/all-in-one#how-to-add-os-packages-permanently-to-the-nextcloud-container
      NEXTCLOUD_ADDITIONAL_APKS: imagemagick
      # This allows to add additional php extensions to the Nextcloud container permanently. Default is imagick but can be overwritten by modifying this value. See https://github.com/nextcloud/all-in-one#how-to-add-php-extensions-permanently-to-the-nextcloud-container
      NEXTCLOUD_ADDITIONAL_PHP_EXTENSIONS: imagick
      # This allows to enable the /dev/dri device in the Nextcloud container. ⚠️⚠️⚠️ Warning: this only works if the '/dev/dri' device is present on the host! If it should not exist on your host, don't set this to true as otherwise the Nextcloud container will fail to start! See https://github.com/nextcloud/all-in-one#how-to-enable-hardware-transcoding-for-nextcloud
      # NEXTCLOUD_ENABLE_DRI_DEVICE: false
      # Setting this to true will keep Nextcloud apps that are disabled in the AIO interface and not uninstall them if they should be installed. See https://github.com/nextcloud/all-in-one#how-to-keep-disabled-apps
      NEXTCLOUD_KEEP_DISABLED_APPS: false 
      # This allows to adjust the port that the talk container is using. See https://github.com/nextcloud/all-in-one#how-to-adjust-the-talk-port
      # TALK_PORT: 3478
      # Needs to be specified if the docker socket on the host is not located in the default '/var/run/docker.sock'. Otherwise mastercontainer updates will fail. For macos it needs to be '/var/run/docker.sock'
      WATCHTOWER_DOCKER_SOCKET_PATH: /var/run/docker.sock
      # https://github.com/nextcloud/all-in-one/tree/main/community-containers#how-to-use-this
      # AIO_COMMUNITY_CONTAINERS: libretranslate vaultwarden
    # Is needed when using SELinux
    # security_opt: ["label:disable"]

volumes:
  # If you want to store the data on a different drive, see https://github.com/nextcloud/all-in-one#how-to-store-the-filesinstallation-on-a-separate-drive
  nextcloud_aio_mastercontainer:
    # This line is not allowed to be changed as otherwise the built-in backup solution will not work
    name: nextcloud_aio_mastercontainer
```
#### Other valuable info 
External storage (all works)
![1](https://github.com/user-attachments/assets/6faf57ba-c6f4-4996-a621-981d055f5735)
![2](https://github.com/user-attachments/assets/11f80f86-ff20-451b-956f-bfaae4d3c388)
![3](https://github.com/user-attachments/assets/4f79355f-f49f-4013-8b6a-e7d5ec88003c)
![4](https://github.com/user-attachments/assets/cc0d75a1-a6d8-45c7-bf4f-480efe2c5c67)
![5](https://github.com/user-attachments/assets/836e1b4f-4f35-4039-b0ff-639a6c569291)

Rights, owner, group. View in container
```
docker exec -it nextcloud-aio-nextcloud /bin/bash

26f92dbe8f48:/var/www/html# ls -la /mnt
...
drwxr-x--- 1 www-data www-data    0 Sep  4 12:14 hetzner
drwxr-x--- 1     1038 www-data    0 Sep  4 12:07 imext
drwxr-x--- 1     1038 www-data    0 Sep  4 12:07 imlib
drwxr-x--- 6 www-data root     4096 Sep  4 12:15 ncdata
drwxr-x--- 1 www-data www-data    0 Sep  4 12:14 ncgdrive
```
Backup scheduled for 15:53 UTC
Scheduled backup in progress
![6](https://github.com/user-attachments/assets/e5b87ec7-2335-41a9-8f2e-c73d0ffd0578)
After the scheduled automatic backup is complete and all services are started
![7](https://github.com/user-attachments/assets/6d520e66-6eb2-41d9-a387-2035d8a015a4)
![8](https://github.com/user-attachments/assets/ede3703a-530d-4c8f-9724-bef7715d8a91)

```
[no app in context] Warning: Error while getting quota info, using root quota
	PROPFIND /remote.php/dav/files/sergei/
	from 10.10.1.4 by sergei at 4 сент. 2024 г., 18:57:01
```
![9](https://github.com/user-attachments/assets/6aa4ffd0-2e22-4b98-9740-d8da6c5bd5b1)
```
25a2079aa412:/var/www/html# ls -la /mnt
...
drwxr-xr-x 2 root     root        0 Sep  3 15:16 hetzner
drwxr-xr-x 2 root     root        0 Sep  3 15:16 imext
drwxr-xr-x 2 root     root        0 Sep  3 15:16 imlib
drwxr-x--- 6 www-data root     4096 Sep  4 18:55 ncdata
drwxr-xr-x 2 root     root        0 Sep  3 15:16 ncgdrive
```
Now manually stop and start the container nextcloud-aio-nextcloud
```
docker stop nextcloud-aio-nextcloud
docker start nextcloud-aio-nextcloud
```
After that, everything works again
![10](https://github.com/user-attachments/assets/fa500f6b-b5dd-405c-b588-6b0bde053e91)
```
25a2079aa412:/var/www/html# ls -la /mnt
...
drwxr-x--- 1 www-data www-data    0 Sep  4 18:56 hetzner
drwxr-x--- 1     1038 www-data    0 Sep  4 18:56 imext
drwxr-x--- 1     1038 www-data    0 Sep  4 18:56 imlib
drwxr-x--- 6 www-data root     4096 Sep  4 19:10 ncdata
drwxr-x--- 1 www-data www-data    0 Sep  4 18:56 ncgdrive
```
