### ISSUE TITLE
Issues using Talk App with differen STUN/TURN server

### ISSUE THREAD

**Issue by simon-77** [nextcloud/all-in-one#5346]
### Steps to reproduce
1. Setup a Nextcloud-AIO instance (server1) with _Nextcloud Talk_ as optional container
2. Setup a second Nextcloud-AIO instance (server2) without the _Nextcloud Talk_ container on another machine
3. Install the Talk App on server2 and set the STUN & TURN server address to server1 & disable the High-performance backend

Verify that configuration is working and Calls can be held

### Expected behavior 
After rebooting server2, the setup is still working.

### Actual behavior 
After rebooting server2 (or start/stop the containers through AIO interface), these steps have to be repeated every time:
a. The Talk App is no longer installed -> needs to be installed
b. When the Talk App is available, the "High-performance backend" will be set to server2 and must be deleted manually every reboot.

Note:
When also enabling the _Nextcloud Talk_ container on server2 & (step 3) configuring the STUN & TURN server address to server1, then (issue a) the Talk App is available after reboot and the STUN & TURN server address still point to server1, but (issue b) the "High-performance backend" setting will point to server2 and must be deleted manually.

#### Host OS 
openSUSE Leap 15.6

#### Output of `sudo docker info`
```
Client:
 Version:    26.1.5-ce
 Context:    default
 Debug Mode: false
 Plugins:
  compose: Docker Compose (Docker Inc.)
    Version:  2.29.7
    Path:     /usr/lib/docker/cli-plugins/docker-compose

Server:
 Containers: 12
  Running: 9
  Paused: 0
  Stopped: 3
 Images: 14
 Server Version: 26.1.5-ce
 Storage Driver: overlay2
  Backing Filesystem: btrfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 oci runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7f7fdf5fed64eb6a7caf99b3e12efcf9d60e311c
 runc version: v1.2.0-rc.3-0-g45471bc94557
 init version: 
 Security Options:
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 6.11.0-1-default
 Operating System: openSUSE MicroOS
 OSType: linux
 Architecture: x86_64
 CPUs: 1
 Total Memory: 3.274GiB
 Name: Paxomata
 ID: f4e47059-33eb-4377-8786-13dbf371cd1d
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

#### Docker run command or docker-compose file that you used
```
services:
  nextcloud:
    image: nextcloud/all-in-one:latest
    restart: unless-stopped
    container_name: nextcloud-aio-mastercontainer # This line is not allowed to be changed as otherwise AIO will not work correctly
    volumes:
      - nextcloud_aio_mastercontainer:/mnt/docker-aio-config # This line is not allowed to be changed as otherwise the built-in backup solution will not work
      - /var/run/docker.sock:/var/run/docker.sock:ro # May be changed on macOS, Windows or docker rootless. See the applicable documentation. If adjusting, don't forget to also set 'WATCHTOWER_DOCKER_SOCKET_PATH'!
    ports:
      - 8080:8080
    environment:
      - APACHE_PORT=11000 # Is needed when running behind a web server or reverse proxy (like Apache, Nginx and else). See https://github.com/nextcloud/all-in-one/blob/main/reverse-proxy.md
      - APACHE_IP_BINDING=0.0.0.0 # Should be set when running behind a web server or reverse proxy (like Apache, Nginx and else) that is running on the same host. See https://github.com/nextcloud/all-in-one/blob/main/reverse-proxy.md

      # - SKIP_DOMAIN_VALIDATION=true # use for setup behind reverse proxy
      - NEXTCLOUD_DATADIR=/srv/nextcloud/data # Allows to set the host directory for Nextcloud's datadir. See https://github.com/nextcloud/all-in-one#how-to-change-the-default-location-of-nextclouds-datadir

      ### Integraded BorgBackup
      # - AIO_DISABLE_BACKUP_SECTION=false # Setting this to true allows to hide the backup section in the AIO interface.
      - BORG_RETENTION_POLICY=--keep-within=7d --keep-weekly=4 --keep-monthly=6 # Allows to adjust borgs retention policy. See https://github.com/nextcloud/all-in-one#how-to-adjust-borgs-retention-policy

      ### Misc
      # - COLLABORA_SECCOMP_DISABLED=false # Setting this to true allows to disable Collabora's Seccomp feature. See https://github.com/nextcloud/all-in-one#how-to-disable-collaboras-seccomp-feature
      # - TALK_PORT=3478 # This allows to adjust the port that the talk container is using.

      ### Nextcloud limits
      # - NEXTCLOUD_MOUNT=/mnt/ # Allows the Nextcloud container to access the chosen directory on the host. See https://github.com/nextcloud/all-in-one#how-to-allow-the-nextcloud-container-to-access-directories-on-the-host
      # - NEXTCLOUD_UPLOAD_LIMIT=10G # Can be adjusted if you need more. See https://github.com/nextcloud/all-in-one#how-to-adjust-the-upload-limit-for-nextcloud
      # - NEXTCLOUD_MAX_TIME=3600 # Can be adjusted if you need more. See https://github.com/nextcloud/all-in-one#how-to-adjust-the-max-execution-time-for-nextcloud
      # - NEXTCLOUD_MEMORY_LIMIT=512M # Can be adjusted if you need more. See https://github.com/nextcloud/all-in-one#how-to-adjust-the-php-memory-limit-for-nextcloud
      
volumes:
  nextcloud_aio_mastercontainer:
    name: nextcloud_aio_mastercontainer # This line is not allowed to be changed as otherwise the built-in backup solution will not work 
```

#### Other valuable info 
![image](https://github.com/user-attachments/assets/25c93237-ade2-40c1-9dce-19a64b2c238d)

Note: yes I have replaced the real domain with <server2> before making the screenshot.
