### ISSUE TITLE
[Facerecognition] Illegal instruction (core dumped)

### ISSUE THREAD

**Issue by fliespl** [nextcloud/all-in-one#5402]
### Steps to reproduce
1. Install NC AIO (with nextcloud 30) AI

```
    environment: # Is needed when using any of the options below
      AIO_COMMUNITY_CONTAINERS: facerecognition
```

2. Start containers
3. Fail

### Expected behavior 
Working :)

### Actual behavior 

```
866ac89402d9   matiasdelellis/facerecognition-external-model:v1   "/bin/sh -c 'flask r…"   4 minutes ago   Up 1 second                   5000/tcp                                                                nextcloud-aio-facerecognition
```

```
flies@nextcloud:~$ docker logs 866ac89402d9
Illegal instruction (core dumped)
Illegal instruction (core dumped)
Illegal instruction (core dumped)
Illegal instruction (core dumped)
Illegal instruction (core dumped)
Illegal instruction (core dumped)
Illegal instruction (core dumped)
Illegal instruction (core dumped)
Illegal instruction (core dumped)
Illegal instruction (core dumped)
Illegal instruction (core dumped)
Illegal instruction (core dumped)
```

#### Host OS 
Ubuntu 24.04

#### Output of `sudo docker info`

```

Client: Docker Engine - Community
 Version:    27.3.1
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.17.1
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.29.7
    Path:     /usr/libexec/docker/cli-plugins/docker-compose
```

#### Docker run command or docker-compose file that you used

```
services:
  nextcloud-aio-mastercontainer:
    image: nextcloud/all-in-one:latest
    init: true
    restart: always
    container_name: nextcloud-aio-mastercontainer
    volumes:
      - nextcloud_aio_mastercontainer:/mnt/docker-aio-config
      - /var/run/docker.sock:/var/run/docker.sock:ro
    network_mode: bridge
    ports:
      - 8080:8080
    environment:
      AIO_COMMUNITY_CONTAINERS: facerecognition
      APACHE_PORT: 11000
      APACHE_IP_BINDING: 0.0.0.0

volumes:
  nextcloud_aio_mastercontainer:
    name: nextcloud_aio_mastercontainer # This line is not allowed to be changed as otherwise the built-in backup solution will not work

```
