### ISSUE TITLE
Can someone document how to use the aio-talk container on its own?

### ISSUE THREAD

**Issue by sbe-arg** [nextcloud/all-in-one#5512]
The possible scenarios are:

Setup HPB-talk along with a snap nextcloud, a aio setup non manual, and hybird setup where toy might have nextcloud running on bare metal.

Based on this https://github.com/nextcloud/all-in-one/tree/main/Containers/talk + https://github.com/nextcloud/all-in-one/tree/main/manual-install

Something like this should work if:

- inbound 3478 and STUN TURN servers are set in the talk admin settings
- inbound to port 8081 of the container/host

Yet no matter what I do I only get timeouts. 

```
  nc-talk:
    container_name: nc_talk
    image: nextcloud/aio-talk:latest
    init: true
    ports:
      - 3478:3478/tcp
      - 3478:3478/udp
      - 8081:8081/tcp
    environment:
      - NC_DOMAIN=cloud.domain.tld
      - TALK_HOST=signaling.domain2.tld
      - TURN_SECRET=secret
      - SIGNALING_SECRET=secret
      - TZ=time/zone
      - TALK_PORT=3478
      - INTERNAL_SECRET=secret
    restart: unless-stopped
    read_only: true
    tmpfs:
      - /var/log/supervisord
      - /var/run/supervisord
      - /opt/eturnal/run
      - /conf
      - /tmp
```

```
{
  "reqId": "3kepAUL4k2XiHWeTNuMf",
  "level": 3,
  "time": "2024-11-03T04:19:08+00:00",
  "remoteAddr": "",
  "user": "--",
  "app": "spreed",
  "method": "",
  "url": "--",
  "message": "Failed to send message to signaling server, giving up!",
  "userAgent": "--",
  "version": "30.0.1.2",
  "exception": {
    "Exception": "GuzzleHttp\\Exception\\ConnectException",
    "Message": "cURL error 7: Failed to connect to signaling.domain.tld2 port 443: Connection refused (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://signaling.domain.tld2/api/v1/room/dxfn7w45",
    "Code": 0,
    "Trace": [
      {
        "file": "/snap/nextcloud/44812/htdocs/3rdparty/guzzlehttp/guzzle/src/Handler/CurlFactory.php",
        "line": 158,
        "function": "createRejection",
        "class": "GuzzleHttp\\Handler\\CurlFactory",
        "type": "::",
        "args": [
          "*** sensitive parameters replaced ***"
        ]
      },
      {
        "file": "/snap/nextcloud/44812/htdocs/3rdparty/guzzlehttp/guzzle/src/Handler/CurlFactory.php",
        "line": 110,
        "function": "finishError",
        "class": "GuzzleHttp\\Handler\\CurlFactory",
        "type": "::"
      },
      {
        "file": "/snap/nextcloud/44812/htdocs/3rdparty/guzzlehttp/guzzle/src/Handler/CurlHandler.php",
        "line": 47,
        "function": "finish",
        "class": "GuzzleHttp\\Handler\\CurlFactory",
        "type": "::"
      },
      {
        "file": "/snap/nextcloud/44812/htdocs/3rdparty/guzzlehttp/guzzle/src/Middleware.php",
        "line": 142,
        "function": "__invoke",
        "class": "GuzzleHttp\\Handler\\CurlHandler",
        "type": "->"
      },
      {
        "file": "/snap/nextcloud/44812/htdocs/lib/private/Http/Client/DnsPinMiddleware.php",
        "line": 106,
        "function": "GuzzleHttp\\{closure}",
        "class": "GuzzleHttp\\Middleware",
        "type": "::",
        "args": [
          "*** sensitive parameters replaced ***"
        ]
      },
      {
        "file": "/snap/nextcloud/44812/htdocs/3rdparty/guzzlehttp/guzzle/src/PrepareBodyMiddleware.php",
        "line": 64,
        "function": "OC\\Http\\Client\\{closure}",
        "class": "OC\\Http\\Client\\DnsPinMiddleware",
        "type": "->",
        "args": [
          "*** sensitive parameters replaced ***"
        ]
      },
      {
        "file": "/snap/nextcloud/44812/htdocs/3rdparty/guzzlehttp/guzzle/src/Middleware.php",
        "line": 31,
        "function": "__invoke",
        "class": "GuzzleHttp\\PrepareBodyMiddleware",
        "type": "->"
      },
      {
        "file": "/snap/nextcloud/44812/htdocs/3rdparty/guzzlehttp/guzzle/src/RedirectMiddleware.php",
        "line": 71,
        "function": "GuzzleHttp\\{closure}",
        "class": "GuzzleHttp\\Middleware",
        "type": "::",
        "args": [
          "*** sensitive parameters replaced ***"
        ]
      },
      {
        "file": "/snap/nextcloud/44812/htdocs/3rdparty/guzzlehttp/guzzle/src/Middleware.php",
        "line": 66,
        "function": "__invoke",
        "class": "GuzzleHttp\\RedirectMiddleware",
        "type": "->"
      },
      {
        "file": "/snap/nextcloud/44812/htdocs/3rdparty/guzzlehttp/guzzle/src/HandlerStack.php",
        "line": 75,
        "function": "GuzzleHttp\\{closure}",
        "class": "GuzzleHttp\\Middleware",
        "type": "::",
        "args": [
          "*** sensitive parameters replaced ***"
        ]
      },
      {
        "file": "/snap/nextcloud/44812/htdocs/3rdparty/guzzlehttp/guzzle/src/Client.php",
        "line": 333,
        "function": "__invoke",
        "class": "GuzzleHttp\\HandlerStack",
        "type": "->"
      },
      {
        "file": "/snap/nextcloud/44812/htdocs/3rdparty/guzzlehttp/guzzle/src/Client.php",
        "line": 169,
        "function": "transfer",
        "class": "GuzzleHttp\\Client",
        "type": "->"
      },
      {
        "file": "/snap/nextcloud/44812/htdocs/3rdparty/guzzlehttp/guzzle/src/Client.php",
        "line": 189,
        "function": "requestAsync",
        "class": "GuzzleHttp\\Client",
        "type": "->",
        "args": [
          "*** sensitive parameters replaced ***"
        ]
      },
      {
        "file": "/snap/nextcloud/44812/htdocs/lib/private/Http/Client/Client.php",
        "line": 276,
        "function": "request",
        "class": "GuzzleHttp\\Client",
        "type": "->"
      },
      {
        "file": "/var/snap/nextcloud/44812/nextcloud/extra-apps/spreed/lib/Signaling/BackendNotifier.php",
        "line": 57,
        "function": "post",
        "class": "OC\\Http\\Client\\Client",
        "type": "->"
      },
      {
        "file": "/var/snap/nextcloud/44812/nextcloud/extra-apps/spreed/lib/Signaling/BackendNotifier.php",
        "line": 67,
        "function": "doRequest",
        "class": "OCA\\Talk\\Signaling\\BackendNotifier",
        "type": "->"
      },
      {
        "file": "/var/snap/nextcloud/44812/nextcloud/extra-apps/spreed/lib/Signaling/BackendNotifier.php",
        "line": 67,
        "function": "doRequest",
        "class": "OCA\\Talk\\Signaling\\BackendNotifier",
        "type": "->"
      },
      {
        "file": "/var/snap/nextcloud/44812/nextcloud/extra-apps/spreed/lib/Signaling/BackendNotifier.php",
        "line": 134,
        "function": "doRequest",
        "class": "OCA\\Talk\\Signaling\\BackendNotifier",
        "type": "->"
      },
      {
        "file": "/var/snap/nextcloud/44812/nextcloud/extra-apps/spreed/lib/Signaling/BackendNotifier.php",
        "line": 272,
        "function": "backendRequest",
        "class": "OCA\\Talk\\Signaling\\BackendNotifier",
        "type": "->"
      },
      {
        "file": "/var/snap/nextcloud/44812/nextcloud/extra-apps/spreed/lib/Signaling/Listener.php",
        "line": 219,
        "function": "roomDeleted",
        "class": "OCA\\Talk\\Signaling\\BackendNotifier",
        "type": "->"
      },
      {
        "file": "/var/snap/nextcloud/44812/nextcloud/extra-apps/spreed/lib/Signaling/Listener.php",
        "line": 130,
        "function": "notifyBeforeRoomDeleted",
        "class": "OCA\\Talk\\Signaling\\Listener",
        "type": "->"
      },
      {
        "file": "/var/snap/nextcloud/44812/nextcloud/extra-apps/spreed/lib/Signaling/Listener.php",
        "line": 81,
        "function": "handleExternalSignaling",
        "class": "OCA\\Talk\\Signaling\\Listener",
        "type": "->"
      },
      {
        "file": "/snap/nextcloud/44812/htdocs/lib/private/EventDispatcher/ServiceEventListener.php",
        "line": 68,
        "function": "handle",
        "class": "OCA\\Talk\\Signaling\\Listener",
        "type": "->"
      },
      {
        "file": "/snap/nextcloud/44812/htdocs/3rdparty/symfony/event-dispatcher/EventDispatcher.php",
        "line": 230,
        "function": "__invoke",
        "class": "OC\\EventDispatcher\\ServiceEventListener",
        "type": "->"
      },
      {
        "file": "/snap/nextcloud/44812/htdocs/3rdparty/symfony/event-dispatcher/EventDispatcher.php",
        "line": 59,
        "function": "callListeners",
        "class": "Symfony\\Component\\EventDispatcher\\EventDispatcher",
        "type": "->"
      },
      {
        "file": "/snap/nextcloud/44812/htdocs/lib/private/EventDispatcher/EventDispatcher.php",
        "line": 67,
        "function": "dispatch",
        "class": "Symfony\\Component\\EventDispatcher\\EventDispatcher",
        "type": "->"
      },
      {
        "file": "/snap/nextcloud/44812/htdocs/lib/private/EventDispatcher/EventDispatcher.php",
        "line": 79,
        "function": "dispatch",
        "class": "OC\\EventDispatcher\\EventDispatcher",
        "type": "->"
      },
      {
        "file": "/var/snap/nextcloud/44812/nextcloud/extra-apps/spreed/lib/Service/RoomService.php",
        "line": 1176,
        "function": "dispatchTyped",
        "class": "OC\\EventDispatcher\\EventDispatcher",
        "type": "->"
      },
      {
        "file": "/var/snap/nextcloud/44812/nextcloud/extra-apps/spreed/lib/BackgroundJob/RemoveEmptyRooms.php",
        "line": 103,
        "function": "deleteRoom",
        "class": "OCA\\Talk\\Service\\RoomService",
        "type": "->"
      },
      {
        "file": "/var/snap/nextcloud/44812/nextcloud/extra-apps/spreed/lib/BackgroundJob/RemoveEmptyRooms.php",
        "line": 84,
        "function": "doDeleteRoom",
        "class": "OCA\\Talk\\BackgroundJob\\RemoveEmptyRooms",
        "type": "->"
      },
      {
        "file": "/var/snap/nextcloud/44812/nextcloud/extra-apps/spreed/lib/BackgroundJob/RemoveEmptyRooms.php",
        "line": 63,
        "function": "deleteIfIsEmpty",
        "class": "OCA\\Talk\\BackgroundJob\\RemoveEmptyRooms",
        "type": "->"
      },
      {
        "file": "/var/snap/nextcloud/44812/nextcloud/extra-apps/spreed/lib/Manager.php",
        "line": 81,
        "function": "callback",
        "class": "OCA\\Talk\\BackgroundJob\\RemoveEmptyRooms",
        "type": "->"
      },
      {
        "file": "/var/snap/nextcloud/44812/nextcloud/extra-apps/spreed/lib/BackgroundJob/RemoveEmptyRooms.php",
        "line": 49,
        "function": "forAllRooms",
        "class": "OCA\\Talk\\Manager",
        "type": "->"
      },
      {
        "file": "/snap/nextcloud/44812/htdocs/lib/public/BackgroundJob/Job.php",
        "line": 61,
        "function": "run",
        "class": "OCA\\Talk\\BackgroundJob\\RemoveEmptyRooms",
        "type": "->"
      },
      {
        "file": "/snap/nextcloud/44812/htdocs/lib/public/BackgroundJob/TimedJob.php",
        "line": 83,
        "function": "start",
        "class": "OCP\\BackgroundJob\\Job",
        "type": "->"
      },
      {
        "file": "/snap/nextcloud/44812/htdocs/lib/public/BackgroundJob/TimedJob.php",
        "line": 73,
        "function": "start",
        "class": "OCP\\BackgroundJob\\TimedJob",
        "type": "->"
      },
      {
        "file": "/snap/nextcloud/44812/htdocs/cron.php",
        "line": 162,
        "function": "execute",
        "class": "OCP\\BackgroundJob\\TimedJob",
        "type": "->"
      }
    ],
    "File": "/snap/nextcloud/44812/htdocs/3rdparty/guzzlehttp/guzzle/src/Handler/CurlFactory.php",
    "Line": 210,
    "message": "Failed to send message to signaling server, giving up!",
    "exception": [],
    "CustomMessage": "Failed to send message to signaling server, giving up!"
  },
  "id": "6726fa3dade6d"
}
```

**Comment by sbe-arg** [comment]
Okay.

To use the aio-talk you have to use the turn only server setup by the aio-talk you cannot use the open relay turns.

I found a bit tricky to use https server endpoint vs wss endpoint specially behind a reverse proxy but it works.

Ill see if I can open a pr with proposed readme notes.

i use bunkerweb as my reverser proxy so might be a bit biased

**Comment by sbe-arg** [comment]
I use this successfully.

```
name: 'hpb'

services:

  nc-talk-2:
    container_name: nc_talk_2
    image: nextcloud/aio-talk:latest
    init: true
    ports:
      - 3479:3478/tcp
      - 3479:3478/udp
      - 8281:8081/tcp
    environment:
      - NC_DOMAIN=cloud.domain2.tld
      - TALK_HOST=signal2.somedomain.tld
      - TURN_SECRET=secret
      - SIGNALING_SECRET=secret
      - TZ=Pacific/Auckland
      - TALK_PORT=3478
      - INTERNAL_SECRET=secret
    restart: unless-stopped
    read_only: true
    tmpfs:
      - /var/log/supervisord
      - /var/run/supervisord
      - /opt/eturnal/run
      - /conf
      - /tmp

  nc-talk-1:
    container_name: nc_talk_1
    image: nextcloud/aio-talk:latest
    init: true
    ports:
      - 3478:3478/tcp
      - 3478:3478/udp
      - 8181:8081/tcp
    environment:
      - NC_DOMAIN=cloud.domain1.tld
      - TALK_HOST=signal1.somedomain.tld
      - TURN_SECRET=secret
      - SIGNALING_SECRET=secret
      - TZ=Pacific/Auckland
      - TALK_PORT=3478
      - INTERNAL_SECRET=secret
    restart: unless-stopped
    read_only: true
    tmpfs:
      - /var/log/supervisord
      - /var/run/supervisord
      - /opt/eturnal/run
      - /conf
      - /tmp
```

You can have as many signal services as you want without having to rebuild from source.

The caviats:

- Talk admin settings

hpb:
```
https://signal.somedomain.tld 
SIGNALING_SECRET
```

remove all turn servers:
```
add TURN-ONLY signal(1,2,3,etc).somedomain.tld:PORT(3478,3479,3480,etc) TURN_SECRET tcp-udp


Make sure your reverse proxy allows http WSS to the endpoints ip1:8181 ip2:8281

make sure you allow inbound bypass of 3478:ip1:3478  3479:ip2:3478
```
