### ISSUE TITLE
Unable to Save Documents in Collabora Online - WOPI Token Error

### ISSUE THREAD

**Issue by alexisdeviney** [nextcloud/all-in-one#5618]
### Steps to reproduce
1. Open a document in Collabora Online through Nextcloud
2. Make changes to the document
3. Click the save button OR wait for auto-save
4. Observe that the "Last saved" timestamp doesn't update

### Expected behavior 
- Document should save when the save button is clicked
- Auto-save should work periodically
- "Last saved" timestamp should update to reflect successful saves

### Actual behavior 
- Clicking save button appears to do nothing
- Auto-save does not appear to function
- "Last saved" timestamp remains stale (e.g., shows "4 hours ago" despite recent save attempts)
- No error message is shown to users despite save failure

#### Host OS 
Ubuntu 24.04 LTS

#### Output of `sudo docker info`
```
Client: Docker Engine - Community
 Version:    27.3.1
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.17.1
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.29.7
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 9
  Running: 8
  Paused: 0
  Stopped: 1
 Images: 9
 Server Version: 27.3.1
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 57f17b0a6295a39009d861b89e3b3b87b005ca27
 runc version: v1.1.14-0-g2c9f560
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 6.8.0-48-generic
 Operating System: Ubuntu 24.04 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 15.62GiB
 Name: dev-nextcloud2
 ID: b1272033-16a6-4940-83dd-78a68b54f4fd
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

#### Docker run command or docker-compose file that you used
```
services:
  caddy:
    image: caddy:alpine
    restart: unless-stopped
    container_name: caddy
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./certs:/certs
      - ./config:/config
      - ./data:/data
      - ./sites:/srv
    network_mode: "host"

  nextcloud:
    image: nextcloud/all-in-one:latest
    restart: unless-stopped
    container_name: nextcloud-aio-mastercontainer
    ports:
      - "8080:8080"
    environment:
      - APACHE_PORT=11000
      - SKIP_DOMAIN_VALIDATION=true
      - NEXTCLOUD_MEMORY_LIMIT=1024M
    volumes:
      - nextcloud_aio_mastercontainer:/mnt/docker-aio-config
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:
      - caddy
    deploy:
      resources:
        limits:
          memory: 16g

volumes:
  nextcloud_aio_mastercontainer:
    name: nextcloud_aio_mastercontainer
```

#### Other valuable info 

Error Logs:
```log
Error richdocuments
Time: Nov 19, 2024, 1:03:17 PM
UnknownTokenException Could not find token.
Failed to validate WOPI access during save

Request Details:
- Method: POST
- URL: /index.php/apps/richdocuments/wopi/files/1145_ocxnipeqsbfu/contents
- User Agent: COOLWSD HTTP Agent 24.04.9.1
- Version: 29.0.8.1
```
