### ISSUE TITLE
Can't login with 2-factor authentification code - only works with backup password

### ISSUE THREAD

**Issue by jm355** [nextcloud/all-in-one#5863]
### Steps to reproduce
1. Go to login screen
2. enter username and password of user with totp 2 factor authentification, login
3. Enter code from 2fa app, click submint

### Expected behavior 
Account should login

### Actual behavior 
Can't login, get "Error while validating your second factor"

#### Host OS 
Debian Bookworm
#### Output of `sudo docker info`
```
Client:
 Context:    default
 Debug Mode: false

Server:
 Containers: 20
  Running: 11
  Paused: 0
  Stopped: 9
 Images: 26
 Server Version: 20.10.24+dfsg1
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runtime.v1.linux runc io.containerd.runc.v2
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 1.6.20~ds1-1+b1
 runc version: 1.1.5+ds1-1+deb12u1
 init version: 
 Security Options:
  apparmor
  seccomp
   Profile: default
  cgroupns
 Kernel Version: 6.1.0-28-amd64
 Operating System: Debian GNU/Linux 12 (bookworm)
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 7.66GiB
 Name: jerry-server-host
 ID: 5MBI:Z4KT:J6F7:OCCQ:G4AW:K72J:DKGN:FE7T:XNAF:2CYQ:PYSC:ZJS2
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: true
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

#### Docker run command or docker-compose file that you used
compose.yaml
```
version: "3.6"

services:
  nextcloud-aio-mastercontainer:
    image: nextcloud/all-in-one:latest
    init: true
    restart: unless-stopped
    container_name: nextcloud-aio-mastercontainer # This line is not allowed to be changed as otherwise AIO will not work correctly
    hostname: nextcloud-aio-mastercontainer
    ports:
      - "8080:8080"
    volumes:
      - nextcloud_aio_mastercontainer:/mnt/docker-aio-config # This line is not allowed to be changed as otherwise the built-in backup solution will not work
      - /var/run/docker.sock:/var/run/docker.sock:ro # May be changed on macOS, Windows or docker rootless. See the applicable documentation. If adjusting, don't forget to also set 'WATCHTOWER_DOCKER_SOCKET_PATH'!
    environment:
      - APACHE_PORT=11000 # Is needed when running behind a web server or reverse proxy (like Apache, Nginx, Cloudflare Tunnel and else). See https://github.com/nextcloud/all-in-one/blob/main/reverse-proxy.md
      - APACHE_IP_BINDING=127.0.0.1 # Should be set when running behind a web server or reverse proxy (like Apache, Nginx, Cloudflare Tunnel and else) that is running on the same host. See https://github.com/nextcloud/all-in-one/blob/main/reverse-proxy.md
      - BORG_RETENTION_POLICY=--keep-within=7d --keep-monthly=6 --keep-yearly=4 
      - NEXTCLOUD_STARTUP_APPS=deck twofactor_totp tasks calendar contacts notes 
      - NEXTCLOUD_ENABLE_DRI_DEVICE=true # This allows to enable the /dev/dri device in the Nextcloud container. ⚠️⚠️⚠️ Warning: this only works if the '/dev/dri' device is present on the host! If it should not exist on your host, don't set this to true as otherwise the Nextcloud container will fail to start! See https://github.com/nextcloud/all-in-one#how-to-enable-hardware-transcoding-for-nextcloud
      - SKIP_DOMAIN_VALIDATION=true
    networks:
      - nextcloud-aio

  caddy:
    build: ./Caddy
    restart: unless-stopped
    container_name: caddy
    # ports:
    #   - "443:443"
    #   - "443:443/udp"
    volumes:
     - /server/caddy/Caddyfile:/etc/caddy/Caddyfile
     - /server/caddy/certs:/certs
     - /server/caddy/config:/config
     - /server/caddy/data:/data
     - /server/caddy/sites:/srv
     - /var/log/caddy:/logs
    network_mode: host

volumes: # If you want to store the data on a different drive, see https://github.com/nextcloud/all-in-one#how-to-store-the-filesinstallation-on-a-separate-drive
  nextcloud_aio_mastercontainer:
    name: nextcloud_aio_mastercontainer # This line is not allowed to be changed as otherwise the built-in backup solution will not work

# # Optional: If you need ipv6, follow step 1 and 2 of https://github.com/nextcloud/all-in-one/blob/main/docker-ipv6-support.md first and then uncomment the below config in order to activate ipv6 for the internal nextcloud-aio network.
# # Please make sure to uncomment also the networking lines of the mastercontainer above in order to actually create the network with docker-compose
networks:
  nextcloud-aio:
    name: nextcloud-aio # This line is not allowed to be changed as otherwise the created network will not be used by the other containers of AIO
    driver: bridge
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: fd5e:1153:cd4e:e12c:0a9e:3733:ad78:2589/64 # IPv6 subnet to use
```

#### Other valuable info 
It was working fine the other day, and backup codes seem to work
