### ISSUE TITLE
Nextcloud Office is force removed if Optional Container "Collabora" isn't enabled

### ISSUE THREAD

**Issue by ciaens** [nextcloud/all-in-one#6069]
### Steps to reproduce
1. Trigger a backup (a simple restart of the container stack (in the UI) didn't trigger it)
2. Have the Nextcloud Office extension installed
3. Have the optional Collabora container unchecked. 

EDIT: you can reproduce it by simply unchecking the Collabora container and restarting the stack. It will remove the Nextcloud Office extension.

### Expected behavior
The Nextcloud Office extension works as intended. In my case, I configured it to use an external Collabora server.

### Actual behavior
The Nextcloud Office extension is forcibly “removed” every day (I do my backups at night). I have to re-install it from the App Store every morning.
I don't want to run an unnecessary container on my host, as I already run Collabora on another server.

#### Output of `sudo docker info`
```
Client: Docker Engine - Community
 Version:    27.2.0
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.16.2
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.29.2
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 12
  Running: 9
  Paused: 0
  Stopped: 3
 Images: 12
 Server Version: 27.2.0
 Storage Driver: btrfs
  Btrfs:
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 472731909fa34bd7bc9c087e4c27943f9835f111
 runc version: v1.1.13-0-g58aa920
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 6.1.0-23-amd64
 Operating System: Debian GNU/Linux 12 (bookworm)
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 7.721GiB
 Name: nextcloud-prod
 ID: f8b8f86b-c1b8-4659-a221-5e5e1541573e
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

#### Docker run command or docker-compose file that you used
```
services:
  nextcloud:
    image: nextcloud/all-in-one:latest
    restart: always
    container_name: nextcloud-aio-mastercontainer
    volumes:
      - nextcloud_aio_mastercontainer:/mnt/docker-aio-config
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 192.168.10.67:8080:8080 
    environment:
      - APACHE_PORT=11000
      - APACHE_IP_BINDING=127.0.0.1
      - NEXTCLOUD_DATADIR=/data/current/nextcloud
      - NEXTCLOUD_UPLOAD_LIMIT=10G
      - NEXTCLOUD_MAX_TIME=3600
      - SKIP_DOMAIN_VALIDATION=true
      - BORG_RETENTION_POLICY=--keep-within=7d --keep-weekly=4 --keep-monthly=2
    extra_hosts:
     - redacted

volumes:
  nextcloud_aio_mastercontainer:
    name: nextcloud_aio_mastercontainer
```
