### ISSUE TITLE
OnlyOffice not working

### ISSUE THREAD

**Issue by chamabreu** [nextcloud/all-in-one#625]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Install a fresh Instance of Nextcloud-aio with caddy as reverse-proxy
2. Select in the container aio site OnlyOffice instead of Collabora
3. Run installation, log into nextcluod, create an Office file and open it
4. Get this error:
![image](https://user-images.githubusercontent.com/31648926/168255180-3d1fd417-09d0-4cfc-9525-c665b96f1cb8.png)

### Expected behavior 
Is obvious - Office files should work.

### Actual behavior 
Cant edit any office files.

### Host OS 
Linux server.

#### Nextcloud AIO version 
Nextcloud Hub II (23.0.4)

#### Current channel 
latest
Nextcloud AIO v1.1.0

#### Other valuable info 
Collabora has no problems.
Reaching `my-own-domain-name.de/onlyoffice/welcome/win.html` is successful.
I have no further configs set, not in Nextcloud or anywhere. Very simple plain installation.

See my docker-compose and Caddyfile here:

docker-compose.yaml
```
services:
  caddy:
    image: caddy:alpine
    restart: unless-stopped
    container_name: caddy
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./certs:/certs
      - ./config:/config
      - ./data:/data
      - ./sites:/srv
    network_mode: "host"

  nextcloud:
    image: nextcloud/all-in-one:latest
    restart: unless-stopped
    container_name: nextcloud-aio-mastercontainer
    ports:
      - "8080:8080"
    environment:
      - APACHE_PORT=11000
    volumes:
      - nextcloud_aio_mastercontainer:/mnt/docker-aio-config
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:
      - caddy

volumes:
  nextcloud_aio_mastercontainer:
```

Caddyfile
```
https://my-own-domain-name.de:443 {
    header Strict-Transport-Security max-age=31536000;
    reverse_proxy localhost:11000
}
```
