### ISSUE TITLE
Container exit with code 137 and 143 after running normally for hours

### ISSUE THREAD

**Issue by SaltySaltPie** [nextcloud/all-in-one#6284]
### Steps to reproduce
1.sudo docker compose up -d
2.app works as expected (for hours)
3.hours later, all containers (beside nextcloud aio) exited together

### Expected behavior 
All nextcloud container to be running for extended period of time
### Actual behavior 
containers seem to be terminated together
apache exited code 137
imaginary and notipush exited code 143

#### Host OS 
ubuntu 24.04 LTS
docker installed using app
ryzen 3400g and 64gb of ddr4
OS drive: 1TB ssd
nextcloud data drive: 8tb hdd
#### Output of `sudo docker info`
```
Client: Docker Engine - Community
 Version:    28.0.4
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.22.0
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.34.0
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 18
  Running: 8
  Paused: 0
  Stopped: 10
 Images: 34
 Server Version: 28.0.4
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: runc io.containerd.runc.v2 nvidia
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 05044ec0a9a75232cad458027ca83437aae3f4da
 runc version: v1.2.5-0-g59923ef
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 6.11.0-21-generic
 Operating System: Ubuntu 24.04.2 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 62.72GiB
 Name: jb-AB350-Gaming-3
 ID: 16ca021f-6777-4953-ad00-e64e1fe712a7
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  ::1/128
  127.0.0.0/8
 Live Restore Enabled: false
```
#### Docker run command or docker-compose file that you used
```
services:
  nextcloud-aio-mastercontainer:
    image: nextcloud/all-in-one:beta
    # image: nextcloud/all-in-one:latest
    init: true
    restart: always
    container_name: nextcloud-aio-mastercontainer # This line is not allowed to be changed as otherwise AIO will not work correctly
    volumes:
      - nextcloud_aio_mastercontainer:/mnt/docker-aio-config # This line is not allowed to be changed as otherwise the built-in backup solution will not work
      - /var/run/docker.sock:/var/run/docker.sock:ro # May be changed on macOS, Windows or docker rootless. See the applicable documentation. If adjusting, don't forget to also set 'WATCHTOWER_DOCKER_SOCKET_PATH'!
    network_mode: bridge # add to the same network as docker run would do
    ports:
      - 8080:8080
    environment: # Is needed when using any of the options below
      APACHE_PORT: 11000 # Is needed when running behind a web server or reverse proxy (like Apache, Nginx, Caddy, Cloudflare Tunnel and else). See https://github.com/nextcloud/all-in-one/blob/main/reverse-proxy.md
      APACHE_IP_BINDING: 127.0.0.1 # Should be set when running behind a web server or reverse proxy (like Apache, Nginx, Caddy, Cloudflare Tunnel and else) that is running on the same host. See https://github.com/nextcloud/all-in-one/blob/main/reverse-proxy.md
      NEXTCLOUD_DATADIR: /mnt/hdd_main/nextcloud/data # Allows to set the host directory for Nextcloud's datadir. ⚠️⚠️⚠️ Warning: do not set or adjust this value after the initial Nextcloud installation is done! See https://github.com/nextcloud/all-in-one#how-to-change-the-default-location-of-nextclouds-datadir
      TALK_PORT: 3478 # This allows to adjust the port that the talk container is using which is exposed on the host. See https://github.com/nextcloud/all-in-one#how-to-adjust-the-talk-port



volumes: # If you want to store the data on a different drive, see https://github.com/nextcloud/all-in-one#how-to-store-the-filesinstallation-on-a-separate-drive
  nextcloud_aio_mastercontainer:
    name: nextcloud_aio_mastercontainer # This line is not allowed to be changed as otherwise the built-in backup solution will not work

```
#### Other valuable info 
I have a caddy server running natively (not using docker): Caddyfile URL reacted:
```
https://nextcloud.xxx.xxx:443 {
    reverse_proxy localhost:11000
}
```
using portainer just to monitor the containers 
![Image](https://github.com/user-attachments/assets/5d32d5c8-5f19-42e9-8b20-53a285f1bfd5)

apache state:
```
   "State": {
        "Dead": false,
        "Error": "",
        "ExitCode": 137,
        "FinishedAt": "2025-04-12T04:04:47.463268273Z",
        "Health": {
            "FailingStreak": 0,
            "Log": [],
            "Status": "starting"
        },
        "OOMKilled": false,
        "Paused": false,
        "Pid": 0,
        "Restarting": false,
        "Running": false,
        "StartedAt": "2025-04-12T02:55:15.536755404Z",
        "Status": "exited"
    }
```
apache logs:
```
Waiting for Nextcloud to start...

Connection to nextcloud-aio-nextcloud (172.20.0.8) 9000 port [tcp/*] succeeded!

[Sat Apr 12 02:55:47.039377 2025] [mpm_event:notice] [pid 55:tid 55] AH00489: Apache/2.4.63 (Unix) configured -- resuming normal operations

[Sat Apr 12 02:55:47.039482 2025] [core:notice] [pid 55:tid 55] AH00094: Command line: '/usr/local/apache2/bin/httpd -D FOREGROUND'

INF ts=1744426547.0545526 msg=using config from file file=/tmp/Caddyfile

INF ts=1744426547.0565464 msg=adapted config to JSON adapter=caddyfile
```

imaginary logs:
```
Imaginary has started
```
notify push logs:
```
Waiting for Nextcloud to start...

Connection to nextcloud-aio-nextcloud (172.20.0.8) 9001 port [tcp/*] succeeded!

notify-push was started
```

I have searched wide and far and seem but couldn't find any solution
Please let me know if any other info is needed. Thanks
