### ISSUE TITLE
Odd error accessing NC AIO instance

### ISSUE THREAD

**Issue by alfre22** [nextcloud/all-in-one#6385]
Hi, I have my own NC AIO (Nextcloud Hub 9 30.0.10) installation running self-hosted in my homelab using docker compose and NGINX Proxy Manager running on the same host. This config has been valid for a while, but a while ago I noticed that the instance becomes unreachable until I open another tab pointing to https://IP_ADDRESS:11000. Then the original tab works again. I've noticed this behavior from a few versions back.

**Steps to reproduce**

1. Trying to access my own installation inside my LAN using https://nextcloud.mydomain.com
3. An ERR_SSL_UNRECOGNIZED_NAME_ALERT appears on the navigator.
4. This situation remains until I open _IP_ADDRESS:11000_ on a new tab, and the first tab now works.

**Expected behavior**

That error shouldn't happen

![Image](https://github.com/user-attachments/assets/6ca3c242-b7fa-4773-bb7e-e1d90c627175)

**Actual behavior**

Nextcloud can't be accessed until I open a different tab to IP_ADDRESS:11000.

![Image](https://github.com/user-attachments/assets/4c923c27-e853-48a2-848d-8caa3a1167e7)

Other information

**Host OS Debian 11 Bullseye**

**Output of `sudo docker info`**

Client: Docker Engine - Community
 Version:    28.1.1
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.23.0
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.35.1
    Path:     /usr/libexec/docker/cli-plugins/docker-compose
  scan: Docker Scan (Docker Inc.)
    Version:  v0.23.0
    Path:     /usr/libexec/docker/cli-plugins/docker-scan

Server:
 Containers: 60
  Running: 57
  Paused: 0
  Stopped: 3
 Images: 72
 Server Version: 28.1.1
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: true
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 05044ec0a9a75232cad458027ca83437aae3f4da
 runc version: v1.2.5-0-g59923ef
 init version: de40ad0
 Security Options:
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 6.8.12-9-pve
 Operating System: Debian GNU/Linux 11 (bullseye)
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 16GiB
 Name: portainer
 ID: ecb5b8d3-e129-43af-9ed5-9ba5251b053a
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  ::1/128
  127.0.0.0/8
 Live Restore Enabled: false
 Default Address Pools:
   Base: 172.16.0.0/12, Size: 20
   Base: 192.168.0.0/16, Size: 24

**Docker run command or docker-compose file that you used**

```
services:
  nextcloud:
    image: nextcloud/all-in-one:latest
    restart: always
    container_name: nextcloud-aio-mastercontainer # This line is not allowed to be changed as otherwise AIO will not work correctly
    volumes:
      - nextcloud_aio_mastercontainer:/mnt/docker-aio-config # This line is not allowed to be changed as otherwise the built-in backup solution will not work
      - /var/run/docker.sock:/var/run/docker.sock:ro # May be changed on macOS, Windows or docker rootless. See the applicable documentation. If adjusting, don>
    ports:
      - 8080:8080
    environment: # Is needed when using any of the options below
      - AIO_DISABLE_BACKUP_SECTION # Setting this to true allows to hide the backup section in the AIO interface.
      - APACHE_PORT # Is needed when running behind a web server or reverse proxy (like Apache, Nginx and else). See https://github.com/nextcloud/all-in-one/bl>
      - APACHE_IP_BINDING # Should be set when running behind a web server or reverse proxy (like Apache, Nginx and else) that is running on the same host. See>
#      - APACHE_ADDITIONAL_NETWORK # (Optional) Connect the apache container to an additional docker network. Needed when behind a web server or reverse proxy >
      - NEXTCLOUD_DATADIR # Allows to set the host directory for Nextcloud's datadir. See https://github.com/nextcloud/all-in-one#how-to-change-the-default-loc>
      - NEXTCLOUD_MOUNT # Allows the Nextcloud container to access the chosen directory on the host. See https://github.com/nextcloud/all-in-one#how-to-allow-t>
      - NEXTCLOUD_ADDITIONAL_APKS # This allows to add additional packages to the Nextcloud container permanently. Default is imagemagick but can be overwritte>
      - NEXTCLOUD_ADDITIONAL_PHP_EXTENSIONS # This allows to add additional php extensions to the Nextcloud container permanently. Default is imagick but can b>
      - NEXTCLOUD_ENABLE_DRI_DEVICE # This allows to enable the /dev/dri device in the Nextcloud container which is needed for hardware-transcoding. See https:>
      - SKIP_DOMAIN_VALIDATION
      - NEXTCLOUD_MEMORY_LIMIT
    # networks: # Is needed when you want to create the nextcloud-aio network with ipv6-support using this file, see the network config at the bottom of the fi>
      # - nextcloud-aio # Is needed when you want to create the nextcloud-aio network with ipv6-support using this file, see the network config at the bottom o>

volumes:
  nextcloud_aio_mastercontainer:
    name: nextcloud_aio_mastercontainer # This line is not allowed to be changed as otherwise the built-in backup solution will not work
```

**Other valuable info**

**Nextcloud-AIO Env file:**

```
AIO_DISABLE_BACKUP_SECTION=false
APACHE_PORT=11000
APACHE_IP_BINDING=0.0.0.0
NEXTCLOUD_DATADIR="/mnt/docs/NextCloud"
NEXTCLOUD_MOUNT="/mnt/docs"
NEXTCLOUD_ADDITIONAL_APKS=imagemagick
NEXTCLOUD_ADDITIONAL_PHP_EXTENSIONS=imagick
NEXTCLOUD_ENABLE_DRI_DEVICE=true
SKIP_DOMAIN_VALIDATION=false
NEXTCLOUD_MEMORY_LIMIT=2048M
```

**The NGINX-Proxy-Manager docker compose file, including the nextcloud-aio network:**
(_APACHE_ADDITIONAL_NETWORK_ env didn't work when I tried to use it in the past, so I tried a different approach connecting npm to the nextcloud-aio network)

```
services:
  npm-app:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: npm-app
    restart: always
    ports:
      - '80:80' # Public HTTP Port
      - '443:443' # Public HTTPS Port
      - '81:81' # Admin Web Port
      # Add any other Stream port you want to expose
      # - '21:21' # FTP
    environment:
      - TZ
      - DB_MYSQL_HOST
      - DB_MYSQL_PORT
      - DB_MYSQL_USER
      - DB_MYSQL_PASSWORD
      - DB_MYSQL_NAME
      # Uncomment the line below if IPv6 is not enabled on your host
      # - DISABLE_IPV6: 'true'
    volumes:
      - ./npm-data:/data
      - ./letsencrypt:/etc/letsencrypt
    depends_on:
      - npm-db
    networks:
      - npm-network
      - npm-internal
      - nextcloud-aio

  npm-db:
    image: 'mariadb:latest'
    container_name: npm-db
    restart: always
    environment:
      - TZ
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - npm-internal

networks:
  npm-internal:
  npm-network:
    external: true
  nextcloud-aio:
    external: true
```

Finally, I'm using a wildcard certificate on my reverse proxy:

![Image](https://github.com/user-attachments/assets/44aaa86c-d35d-4067-98af-d6f6674d0ff2)
