### ISSUE TITLE
### **Talk upload fails after AIO update to Hub 10 – WebDAV interface seems to be broken /  Your web server is not properly set up to resolve...**

### ISSUE THREAD

**Issue by youngabreu1** [nextcloud/all-in-one#6539]
### Steps to reproduce

- I run a Nextcloud instance using the AIO container with domain `nextcloud.******.com.br`.
- After an automatic update to **Hub 10 (Nextcloud 31.0.5)**, the **Talk app** can no longer upload files.
- The system was working correctly before the update.

### Expected behavior

Uploading files in Talk should work without issues.

### Actual behavior

When attempting to upload a file inside a Talk conversation, I get a popup with an error and the upload fails. In the Administration settings I see:

```
Your web server is not yet properly set up to allow file synchronization, because the WebDAV interface seems to be broken. To allow this check to run you have to make sure that your Web server can connect to itself. Therefore it must be able to resolve and connect to at least one of its `trusted_domains` or the `overwrite.cli.url`. This failure may be the result of a server-side DNS mismatch or outbound firewall rule.

Your web server is not properly set up to resolve `.well-known` URLs, failed on: `/.well-known/caldav` For more details see the [documentation ↗](https://docs.nextcloud.com/server/31/go.php?to=admin-setup-well-known-URL).

```

### Other information

Even with a valid user session, Talk seems unable to upload files.

### Troubleshooting steps taken

- Checked `trusted_domains` in `config.php` – it is correctly set and includes the domain.
- Verified HTTPS connection is valid via browser.
- The issue started **immediately after the upgrade**, which was performed automatically by AIO.

### Environment

- **Nextcloud version:** 31.0.5 (Hub 10)
- **Deployment method:** Docker via Nextcloud AIO
- **Host OS:** Ubuntu 22.04 LTS
- **Reverse Proxy:** Cloudflare Tunnel
- **Domain:** nextcloudplay.playlistsoftware.com.br

### Additional info

- I’ve already tried restarting the containers.
- No other parts of Nextcloud seem affected; only Talk uploads are broken.
- All internal DNS/resolution appears to be working fine.

#### Host OS 

Ubuntu 24.04.1 LTS (Noble)

#### Output of `sudo docker info`
```
Client: Docker Engine - Community
 Version:    27.4.0
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.19.2
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.31.0
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 26
  Running: 21
  Paused: 0
  Stopped: 5
 Images: 39
 Server Version: 27.4.0
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: active
  NodeID: 9g0wn8rkorvbxwa5blp1gahss
  Is Manager: true
  ClusterID: i9r1h2txmq9d41o8xzqxdh6fg
  Managers: 3
  Nodes: 5
  Default Address Pool: 10.0.0.0/8  
  SubnetSize: 24
  Data Path Port: 4789
  Orchestration:
   Task History Retention Limit: 5
  Raft:
   Snapshot Interval: 10000
   Number of Old Snapshots to Retain: 0
   Heartbeat Tick: 1
   Election Tick: 10
  Dispatcher:
   Heartbeat Period: 5 seconds
  CA Configuration:
   Expiry Duration: 3 months
   Force Rotate: 0
  Autolock Managers: false
  Root Rotation In Progress: false
  Node Address: 192.168.0.123
  Manager Addresses:
   192.168.0.123:2377
   192.168.0.74:2377
   192.168.0.81:2377
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 88bf19b2105c8b17560993bee28a01ddc2f97182
 runc version: v1.2.2-0-g7cb3632
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 6.8.0-59-generic
 Operating System: Ubuntu 24.04.1 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 6
 Total Memory: 15.53GiB
 Name: cluster02
 ID: 6dc03647-656f-4dc4-82c8-56a43b50f32e
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

```

#### Docker run command or docker-compose file that you used

```
version: '3.8'

services:
  nextcloud-aio-mastercontainer:
    image: nextcloud/all-in-one:latest
    container_name: nextcloud-aio-mastercontainer
    init: true
    restart: always
    ports:
      - "84:80"
      - "8084:8080"
      - "8449:8443"
    volumes:
      - nextcloud_aio_mastercontainer:/mnt/docker-aio-config
      - /var/run/docker.sock:/var/run/docker.sock:ro
    network_mode: bridge
    environment:
      - APACHE_PORT=11000
      - APACHE_IP_BINDING=0.0.0.0
      - SKIP_DOMAIN_VALIDATION=true
volumes:
  nextcloud_aio_mastercontainer:
    name: nextcloud_aio_mastercontainer
```

### Question

Is this a known issue with the latest Hub 10 update or something I can fix by reconfiguring certificates/trust manually within the container?

Thanks in advance!
