### ISSUE TITLE
Latest ghcr.io based image nextcloud php-fpm refuses connections even from curl http://localhost:9000/status

### ISSUE THREAD

**Issue by ACiDGRiM** [nextcloud/all-in-one#6547]
### Steps to reproduce
1. update docker-compose to use ghcr.io image path, and latest .env variables
2. Deploy to docker swarm 
3. check logs of nextcloud container and watch successful inplace upgrade
4. attempt to connect to domain, receive gateway timeout
5. attach apache container curl http://nextcloud-aio-nextcloud:9000/status "Connection reset by peer"
6. attach nextcloud container curl http://localhost:9000/status "Connection reset by peer"

### Expected behavior 
php-fpm port 9000 allows local and remote connections

### Actual behavior 
php-fpm closes connections

#### Host OS 
Rocky Linux 9 

#### Output of `sudo docker info`
```
docker info
Client: Docker Engine - Community
 Version:    28.2.2
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.24.0
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.36.2
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 135
  Running: 27
  Paused: 0
  Stopped: 108
 Images: 92
 Server Version: 28.2.2
 Storage Driver: overlay2
  Backing Filesystem: xfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: local
 Cgroup Driver: cgroupfs
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 CDI spec directories:
  /etc/cdi
  /var/run/cdi
 Swarm: active
  NodeID: zhs61pqvoyju1x9uwng80x5dz
  Is Manager: true
  ClusterID: jhn291n3k7rzlqif7aanvo4fg
  Managers: 3
  Nodes: 3
  Default Address Pool: 172.16.0.0/20
  SubnetSize: 24
  Data Path Port: 4789
  Orchestration:
   Task History Retention Limit: 5
  Raft:
   Snapshot Interval: 10000
   Number of Old Snapshots to Retain: 0
   Heartbeat Tick: 1
   Election Tick: 10
  Dispatcher:
   Heartbeat Period: 5 seconds
  CA Configuration:
   Expiry Duration: 3 months
   Force Rotate: 0
  Autolock Managers: false
  Root Rotation In Progress: false
  Node Address: 10.0.15.50
  Manager Addresses:
   10.0.15.50:2377
   10.0.15.51:2377
   10.0.15.52:2377
 Runtimes: io.containerd.runc.v2 nvidia runc
 Default Runtime: nvidia
 Init Binary: docker-init
 containerd version: 05044ec0a9a75232cad458027ca83437aae3f4da
 runc version: v1.2.5-0-g59923ef
 init version: de40ad0
 Security Options:
  seccomp
   Profile: builtin
  userns
  cgroupns
 Kernel Version: 6.14.9-1.el9.elrepo.x86_64
 Operating System: Rocky Linux 9.6 (Blue Onyx)
 OSType: linux
 Architecture: x86_64
 CPUs: 35
 Total Memory: 60.12GiB
 Name: sccs1dmz01.0xcbf.net
 ID: 7068cbea-c32b-46bf-b9fd-3c0c5e52d443
 Docker Root Dir: /data/165536.165536
 Debug Mode: false
 Username: 0xcbf
 Experimental: true
 Insecure Registries:
  ::1/128
  127.0.0.0/8
 Live Restore Enabled: false
```

#### Docker run command or docker-compose file that you used
```
cat docker-compose.yaml
services:
  apache:
    image: ghcr.io/nextcloud-releases/aio-apache:latest
    tty: true
    environment:
      - PROTOCOL=http
      - NC_DOMAIN
      - NEXTCLOUD_HOST=nextcloud-aio-nextcloud
      - APACHE_HOST=nextcloud-aio-apache
      - COLLABORA_HOST=nextcloud-aio-collabora
      - TALK_HOST=nextcloud-aio-talk
      - APACHE_PORT
      - ONLYOFFICE_HOST=nextcloud-aio-onlyoffice
      - TZ=${TIMEZONE}
      - APACHE_MAX_SIZE
      - APACHE_MAX_TIME=${NEXTCLOUD_MAX_TIME}
      - NOTIFY_PUSH_HOST=nextcloud-aio-notify-push
      - WHITEBOARD_HOST=nextcloud-aio-whiteboard
    volumes:
      - /volumes/nextcloud/persistent/nextcloud:/var/www/html:ro
      - /volumes/nextcloud/persistent/apache:/mnt/data:rw
      - type: tmpfs
        target: /var/run/supervisord
      - type: tmpfs
        target: /var/log/supervisord
      - type: tmpfs
        target: /tmp
      - type: tmpfs
        target: /home/www-data
      - type: tmpfs
        target: /usr/local/apache2/logs
    ports:
      - 8333:80
      - 8332:8000
    restart: always
    deploy:
      labels:
        - traefik.enable=true
        - traefik.docker.network=proxy
        - traefik.frontend.redirect.permanent=true
        - traefik.http.routers.nextcloud.entrypoints=websecure
        - traefik.http.routers.nextcloud.rule=Host(`cloud.0xcbf.net`)
        - traefik.http.routers.nextcloud.tls=true
        - traefik.http.routers.nextcloud.tls.certresolver=myhttpchallenge
        - traefik.http.routers.nextcloud.service=nextcloud
        - traefik.http.routers.nextcloud.middlewares=nextcloud-headers
          #,nextcloud-regex,nextcloud-regex2
        - traefik.http.services.nextcloud.loadbalancer.server.port=80
        - traefik.http.services.nextcloud.loadbalancer.server.scheme=http
        - traefik.http.middlewares.nextcloud-headers.headers.customFrameOptionsValue=SAMEORIGIN
        - traefik.http.middlewares.nextcloud-headers.headers.stsSeconds=15552000
          #- traefik.http.middlewares.nextcloud-regex.redirectregex.regex=https://(.*)/.well-known/(carddav|caldav)
          #- traefik.http.middlewares.nextcloud-regex.redirectregex.replacement=https://$${1}/remote.php/dav/
          #- traefik.http.middlewares.nextcloud-regex.redirectregex.permanent=true
          #- traefik.http.middlewares.nextcloud-regex2.redirectregex.regex=https://(.*)/.well-known/(.*)
          #- traefik.http.middlewares.nextcloud-regex2.redirectregex.replacement=https://$${1}/index.php/.well-known/$${2}
          #- traefik.http.middlewares.nextcloud-regex2.redirectregex.permanent=true
    networks:
      nextcloud-aio:
        aliases:
          - nextcloud-aio-apache
            #proxy:
    read_only: false

  database:
    image: ghcr.io/nextcloud-releases/aio-postgresql:latest
    tty: true
    expose:
      - "5432"
    volumes:
      - /volumes/nextcloud/persistent/database:/var/lib/postgresql/data:rw
      - /volumes/nextcloud/persistent/database_dump:/mnt/data:rw
      - type: tmpfs
        target: /var/run/postgresql
    healthcheck:
      start_period: 600s
    environment:
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=nextcloud_database
      - POSTGRES_USER=nextcloud
      - TZ=${TIMEZONE}
      - PGTZ=${TIMEZONE}
#    entrypoint:
#      - "pg_resetwal"
#      - "-f"
#      - "/var/lib/postgresql/data"
    stop_grace_period: 1800s
    restart: always
    shm_size: "268435456"
    networks:
      nextcloud-aio:
        aliases:
          - nextcloud-aio-database
    read_only: false

  nextcloud:
    hostname: nextcloud-aio-nextcloud
    image: ghcr.io/nextcloud-releases/aio-nextcloud:latest
    tty: true
    volumes:
      - /volumes/nextcloud/persistent/nextcloud:/var/www/html:rw
      - /volumes/nextcloud/persistent/data:/mnt/ncdata:rw
      - type: tmpfs
        target: /tmp
      #- ${NEXTCLOUD_TRUSTED_CACERTS_DIR}:/usr/local/share/ca-certificates:ro
    healthcheck:
      start_period: 600s
    environment:
      - NEXTCLOUD_HOST=nextcloud-aio-nextcloud
      - POSTGRES_HOST=nextcloud-aio-database
      - POSTGRES_PORT=5432
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=nextcloud_database
      - POSTGRES_USER=nextcloud
      - REDIS_HOST=nextcloud-aio-redis
      - REDIS_HOST_PASSWORD=${REDIS_PASSWORD}
      - APACHE_HOST=nextcloud-aio-apache
      - APACHE_PORT
      - NC_DOMAIN
      - ADMIN_USER=admin
      - ADMIN_PASSWORD=${NEXTCLOUD_PASSWORD}
      - NEXTCLOUD_DATA_DIR=/mnt/ncdata
      - OVERWRITEHOST=${NC_DOMAIN}
      - OVERWRITEPROTOCOL=https
      - TURN_SECRET
      - SIGNALING_SECRET
      - ONLYOFFICE_SECRET
      - NEXTCLOUD_MOUNT
      - CLAMAV_ENABLED
      - CLAMAV_HOST=nextcloud-aio-clamav
      - ONLYOFFICE_ENABLED
      - COLLABORA_ENABLED
      - COLLABORA_HOST=nextcloud-aio-collabora
      - TALK_ENABLED
      - ONLYOFFICE_HOST=nextcloud-aio-onlyoffice
      - UPDATE_NEXTCLOUD_APPS
      - TZ=${TIMEZONE}
      - TALK_PORT
      - IMAGINARY_ENABLED
      - IMAGINARY_HOST=nextcloud-aio-imaginary
      - CLAMAV_MAX_SIZE=${APACHE_MAX_SIZE}
      - PHP_UPLOAD_LIMIT=${NEXTCLOUD_UPLOAD_LIMIT}
      - PHP_MEMORY_LIMIT=${NEXTCLOUD_MEMORY_LIMIT}
      - FULLTEXTSEARCH_ENABLED
      - FULLTEXTSEARCH_HOST=nextcloud-aio-fulltextsearch
      - PHP_MAX_TIME=${NEXTCLOUD_MAX_TIME}
      - TRUSTED_CACERTS_DIR=${NEXTCLOUD_TRUSTED_CACERTS_DIR}
      - STARTUP_APPS=${NEXTCLOUD_STARTUP_APPS}
      - ADDITIONAL_APKS=${NEXTCLOUD_ADDITIONAL_APKS}
      - ADDITIONAL_PHP_EXTENSIONS=${NEXTCLOUD_ADDITIONAL_PHP_EXTENSIONS}
      - INSTALL_LATEST_MAJOR
      - TALK_RECORDING_ENABLED
      - RECORDING_SECRET
      - TALK_RECORDING_HOST=nextcloud-aio-talk-recording
      - FULLTEXTSEARCH_PASSWORD
      - REMOVE_DISABLED_APPS
      - IMAGINARY_SECRET
      - WHITEBOARD_SECRET
      - WHITEBOARD_ENABLED
    restart: always
    networks:
      nextcloud-aio:
        aliases:
          - nextcloud-aio-nextcloud

  notify-push:
    image: ghcr.io/nextcloud-releases/aio-notify-push:latest
    tty: true
    expose:
      - "7867"
    volumes:
      - /volumes/nextcloud/persistent/nextcloud:/nextcloud:ro
    environment:
      - NC_DOMAIN
      - NEXTCLOUD_HOST=nextcloud-aio-nextcloud
      - TZ=${TIMEZONE}
      - REDIS_HOST=nextcloud-aio-redis
      - REDIS_HOST_PASSWORD=${REDIS_PASSWORD}
      - POSTGRES_HOST=nextcloud-aio-database
      - POSTGRES_PORT=5432
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=nextcloud_database
      - POSTGRES_USER=nextcloud
    networks:
      nextcloud-aio:
        aliases:
          - nextcloud-aio-notify-push
    read_only: false

  redis:
    image: ghcr.io/nextcloud-releases/aio-redis:latest
    tty: true
    expose:
      - "6379"
    environment:
      - REDIS_HOST_PASSWORD=${REDIS_PASSWORD}
      - TZ=${TIMEZONE}
    volumes:
      - /volumes/nextcloud/persistent/redis:/data:rw
    restart: always
    networks:
      nextcloud-aio:
        aliases:
          - nextcloud-aio-redis
    read_only: false

  collabora:
    image: ghcr.io/nextcloud-releases/aio-collabora:latest
    tty: true
    expose:
      - "9980"
    environment:
      - aliasgroup1=https://${NC_DOMAIN}:443
      - extra_params=--o:ssl.enable=false --o:ssl.termination=true --o:mount_jail_tree=false --o:logging.level=warning --o:home_mode.enable=true --o:remote_font_config.url=https://${NC_DOMAIN}/apps/richdocuments/settings/fonts.json --o:net.post_allow.host[0]=.+
      - dictionaries=${COLLABORA_DICTIONARIES}
      - TZ=${TIMEZONE}
      - server_name=${NC_DOMAIN}
      - DONT_GEN_SSL_CERT=1
    restart: always
    networks:
      nextcloud-aio:
        aliases:
          - nextcloud-aio-collabora

  clamav:
    image: ghcr.io/nextcloud-releases/aio-clamav:latest
    tty: true
    expose:
      - "3310"
    environment:
      - TZ=${TIMEZONE}
      - MAX_SIZE=${APACHE_MAX_SIZE}
    volumes:
      - /volumes/nextcloud/persistent/clamav:/var/lib/clamav:rw
      - type: tmpfs
        target: /var/lock
      - type: tmpfs
        target: /var/log/clamav
      - type: tmpfs
        target: /tmp
      - type: tmpfs
        target: /var/log/supervisord
      - type: tmpfs
        target: /run
      - type: tmpfs
        target: /var/run/supervisord
      - type: tmpfs
        target: /run/clamav
    restart: always
    networks:
      nextcloud-aio:
        aliases:
          - nextcloud-aio-clamav
    read_only: false

  imaginary:
    image: ghcr.io/nextcloud-releases/aio-imaginary:latest
    tty: true
    expose:
      - "9000"
    environment:
      - TZ=${TIMEZONE}
      - IMAGINARY_SECRET
    volumes:
      - type: tmpfs
        target: /tmp
    networks:
      nextcloud-aio:
        aliases:
          - nextcloud-aio-imaginary
    read_only: false

  fulltextsearch:
    image: ghcr.io/nextcloud-releases/aio-fulltextsearch:latest
    tty: true
    expose:
      - "9200"
    environment:
      - TZ=${TIMEZONE}
      - ES_JAVA_OPTS=${FULLTEXTSEARCH_JAVA_OPTIONS}
      - bootstrap.memory_lock=true
      - cluster.name=nextcloud-aio
      - discovery.type=single-node
      - logger.org.elasticsearch.discovery=WARN
      - http.port=9200
      - xpack.license.self_generated.type=basic
      - xpack.security.enabled=false
      - FULLTEXTSEARCH_PASSWORD
    volumes:
      - /volumes/nextcloud/persistent/elasticsearch:/usr/share/elasticsearch/data:rw
    restart: always
    networks:
      nextcloud-aio:
        aliases:
          - nextcloud-aio-fulltextsearch

  #context-chat:
    #image: localhost:/nc-contextchat:latest
    #tty: true
    #environment:
    #  - TZ=${TIMEZONE}
    #  - CUDA_VISIBLE_DEVICES=0,1
    #volumes:
    #  - /volumes/nextcloud/persistent/context_chat/config.yaml
    #  - /volumes/nextcloud/persistent/context_chat/persistent
    #  - type: tmpfs
    #    target: /tmp
    #networks:
    #  - nextcloud-aio
    #read_only: false

# Inspired by https://github.com/mailcow/mailcow-dockerized/blob/master/docker-compose.yml
networks:
  nextcloud-aio:
  proxy:
    external: true
```

#### Other valuable info 
No logs are logged in /usr/local/var for php-fpm
