### ISSUE TITLE
Issue with data directory 

### ISSUE THREAD

**Issue by killmasta93** [nextcloud/all-in-one#658]
### Steps to reproduce
1. used docker compose to configure data directory in other location
2. created the directory mkdir -pv /data/ncdata
3. gave the permissions
```
sudo chown -R 33:0 /data/ncdata 
sudo chmod -R 750 /data/ncdata
```
then ran the docker compose but got this error

```

You've set NEXTCLOUD_DATADIR but not to an allowed value.

The string must start with '/' and must not be equal to '/'.

It is set to '"/data/ncdata/"'.

You've set NEXTCLOUD_DATADIR but not to an allowed value.

The string must start with '/' and must not be equal to '/'.

```

This is the docker compose im using

```

version: "3.8"

volumes:
  nextcloud_aio_mastercontainer:
    name: nextcloud_aio_mastercontainer

services:
  nextcloud:
    image: nextcloud/all-in-one:latest # Must be changed to 'nextcloud/all-in-one:latest-arm64' when used with an arm64 CPU
    restart: always
    container_name: nextcloud-aio-mastercontainer
    environment: # Is needed when using any of the options below
     - APACHE_PORT=11000 # Is needed when running behind a reverse proxy. See https://github.com/nextcloud/all-in-one/blob/main/reverse-proxy.md  
     - NEXTCLOUD_DATADIR="/data/ncdata" # Allows to set the host directory for Nextcloud's datadir. See https://github.com/nextcloud/all-in-one#how-to-change-the-default-location-of-nextclouds-datadir
     - NEXTCLOUD_MOUNT="/data/" # Allows the Nextcloud container to access the chosen directory on the host. See https://github.com/nextcloud/all-in-one#how-to-allow-the-nextcloud-container-to-access-directories-on-the-host
    volumes:
      - nextcloud_aio_mastercontainer:/mnt/docker-aio-config
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 8080:8080
```
      

### Host OS 
Ubuntu 20.04

Thank you
