### ISSUE TITLE
The server is not reachable on Port 443

### ISSUE THREAD

**Issue by farzadha2** [nextcloud/all-in-one#690]
Hi
Recently installed the version 1.2.0 and i get to the part where it says 

`The server is not reachable on Port 443.`

when i access my server  i see this

![image](https://user-images.githubusercontent.com/62571297/169668089-4a9a31f1-bca4-42e7-a175-16e41d6b1fec.png)

using nginx reverse proxy 

```

   server {

#        listen 80;
   listen 443 ssl;
         server_name nube.domain.com;

  ssl_certificate /etc/letsencrypt/live/nube.domain.com/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/nube.domain.com/privkey.pem;
        ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
       ssl_prefer_server_ciphers on;
        ssl_dhparam /etc/ssl/certs/dhparam.pem;
        ssl_ciphers 'EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH';
        ssl_session_timeout 1d;
        ssl_session_cache shared:SSL:50m;
        ssl_stapling on;
       ssl_stapling_verify on;

location ~ /.well-known {
        root /var/www/letsencrypt;
        allow all;
    }

location / {
        proxy_pass http://localhost:11000;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        client_max_body_size 0;

        # Websocket
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $connection_upgrade;
    }




        }
```

the docker compose
```

version: "3.8"

volumes:
  nextcloud_aio_mastercontainer:
    name: nextcloud_aio_mastercontainer

services:
  nextcloud:
    image: nextcloud/all-in-one:latest # Must be changed to 'nextcloud/all-in-one:latest-arm64' when used with an arm64 CPU
    restart: always
    container_name: nextcloud-aio-mastercontainer
    environment: # Is needed when using any of the options below
     - APACHE_PORT=11000 # Is needed when running behind a reverse proxy. See https://github.com/nextcloud/all-in-one/blob/main/reverse-proxy.md  
     - NEXTCLOUD_DATADIR=/data2/ncdata
     - NEXTCLOUD_MOUNT=/data2/
    volumes:
     - nextcloud_aio_mastercontainer:/mnt/docker-aio-config
     - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 8080:8080
```

thank you
